### ISSUE TITLE
Missing formula for maven 3.6.3

### ISSUE THREAD

**Issue by kszosze** [Homebrew/homebrew-core#79916] opened 2021-06-24 09:50 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
#brew gist-logs maven@3.6
Error: No available formula with the name "maven@3.6"
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

After a brew update, maven version bump to 3.8.1, the lates stable release, but company constrains, for now, doesn´t allow to use maven versions higher that 3.6.3. Trying to make a version downgrade wasn´t possible, since there is not such formula.

### What happened (include all command output)?

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and dart-lang/dart).
==> New Formulae
baidupcs-go                           fcp                                   pillow                                soapyrtlsdr
bosh-cli                              jello                                 plow                                  terminator
buildpulse-test-reporter              lima                                  pyflow                                wasmtime
==> Updated Formulae
Updated 228 formulae.
==> New Casks
asana                         burp-suite-professional       ears                          hyperkey                      radar
bit-fiddle                    castr                         goneovim                      keyboardholder                sqlight
==> Updated Casks
Updated 128 casks.

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "maven@3.6".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

### What did you expect to happen?

Formula for maven 3.6.3 be installed over latest maven version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install maven@3.6
```

**Comment by SMillerDev** [comment] 2021-06-24 10:04
This is not a bug, closing this.

**Closed by SMillerDev** 2021-06-24 10:04 UTC
Labels: bug
