### ISSUE TITLE
pgloader wrong version

### ISSUE THREAD

**Issue by yoghi** [Homebrew/homebrew-core#18101] opened 2017-09-15 10:27 UTC
```
$ brew info pgloader
pgloader: stable 3.4.1 (bottled), HEAD
Data loading tool for PostgreSQL
https://github.com/dimitri/pgloader
/usr/local/Cellar/pgloader/3.4.1 (7 files, 20.8MB) *
  Poured from bottle on 2017-09-15 at 12:03:00
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pgloader.rb
==> Dependencies
Build: buildapp ✘
Required: sbcl ✔, freetds ✔
==> Requirements
Recommended: postgresql ✔
==> Options
--without-postgresql
	Build without postgresql support
--HEAD
	Install HEAD version
```
```
$ /usr/local/Cellar/pgloader/3.4.1/bin/pgloader --version
pgloader version "3.3.2"
compiled with SBCL 1.3.19
```
Formula declare 3.4.1, install into 3.4.1 dir, but it was 3.3.2

**Comment by ilovezfs** [comment] 2017-09-17 09:58
Please file an issue upstream here: https://github.com/dimitri/pgloader/issues because the problem is not in the Homebrew formula.

**Comment by yoghi** [comment] 2017-09-18 15:10
Inside: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pgloader.rb
``
resource "pgloader" do
    url "https://beta.quicklisp.org/archive/pgloader/2016-12-04/pgloader-3.3.2.tgz"
    sha256 "1b0fd097932f980942c46ac7ec4211e2c4646577bc598a088b5f53b9a5393fe6"
end
``
Sure is a bug of pgloader?

**Comment by ilovezfs** [comment] 2017-09-19 10:29
@yoghi good catch. It should be fixed now.

**Closed by ilovezfs** 2017-09-19 10:29 UTC
