### ISSUE TITLE
python3: change gcc version after building or in post_install

### ISSUE THREAD

**Issue by curoky** [Homebrew/homebrew-core#91923] opened 2021-12-23 08:18 UTC
### Reason

1. Homebrew's bottled python@3.9 is built on ubuntu 16.04 with the used GCC version is 5. So all GCC config in 
  `/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/_sysconfigdata__linux_x86_64-linux-gnu.py` are GCC-5.
2. Pip uses GCC to compile the c/c++ extension, and get the compiler config from `_sysconfigdata__linux_x86_64-linux-gnu.py`.
3. When we use python@3.9's pip install thriftpy which need compile extension on ubuntu 20.04 ( or any release which not have gcc-5), it will fail.
4. We can't simply use `CC/CXX` environment to force pip or setuptools to use a special gcc version.

### Possible solution
1. replace gcc-n to gcc directly after building. https://github.com/Homebrew/homebrew-core/blob/master/Formula/python@3.9.rb#L229-L238  
2. replace gcc-n to gcc or gcc-n2 in post_install step.

### Logs

```
Installing collected packages: thriftpy2
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
    Running setup.py install for thriftpy2 ... error
    ERROR: Command errored out with exit status 1:
     command: /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/shm/curoky/cache/pip-install-d5lzeehn/thriftpy2_6aa184323ec84713879ddd5c0977ed9e/setup.py'"'"'; __file__='"'"'/shm/curoky/cache/pip-install-d5lzeehn/thriftpy2_6aa184323ec84713879ddd5c0977ed9e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /shm/curoky/cache/pip-record-f83n8g7l/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/include/python3.9/thriftpy2
         cwd: /shm/curoky/cache/pip-install-d5lzeehn/thriftpy2_6aa184323ec84713879ddd5c0977ed9e/
    Complete output (94 lines):
    running install
    /home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    ...
    running build_ext
    building 'thriftpy2.transport.cybase' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/thriftpy2
    creating build/temp.linux-x86_64-3.9/thriftpy2/transport
    gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/linuxbrew/.linuxbrew/opt/python@3.9/include/python3.9 -c thriftpy2/transport/cybase.c -o build/temp.linux-x86_64-3.9/thriftpy2/transport/cybase.o
    error: command 'gcc-5' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/shm/curoky/cache/pip-install-d5lzeehn/thriftpy2_6aa184323ec84713879ddd5c0977ed9e/setup.py'"'"'; __file__='"'"'/shm/curoky/cache/pip-install-d5lzeehn/thriftpy2_6aa184323ec84713879ddd5c0977ed9e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /shm/curoky/cache/pip-record-f83n8g7l/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/include/python3.9/thriftpy2 Check the logs for full command output.
```

**Comment by iMichka** [comment] 2021-12-23 08:50
Agreed that this definitively needs to be fixed. I noticed this too when using brew on ubuntu 20.04.
One workaround is to `brew install gcc@5`, that works too I think, but is not a good long term solution.

**Comment by XuehaiPan** [comment] 2021-12-31 12:39
You could set `CC` and `LDSHARED` in your shell profile:

```bash
export CC=gcc
export LDSHARED="${CC} -pthread -shared"
```

- See #91616

**Comment by curoky** [comment] 2022-01-05 03:48
> You could set `CC` and `LDSHARED` in your shell profile:
> 
> ```shell
> export CC=gcc
> export LDSHARED="${CC} -pthread -shared"
> ```
> 
> * See [Bottled Python causes the third-party CXX project to fail to build #91616](https://github.com/Homebrew/homebrew-core/issues/91616)

@XuehaiPan Thank you very much, I missed the `export LDSHARED` before, now it's ok.

**Comment by carlocab** [comment] 2022-01-05 06:22
Duplicate of #91616

**Comment by carlocab** [comment] 2022-01-05 06:22
Let me know if this is actually distinct from #91616 and we can discuss reopening this if needed.

**Closed by carlocab** 2022-01-05 06:22 UTC
Labels: bug
