### ISSUE TITLE
highlight CLI: Language syntax no longer detected automatically for some extensions

### ISSUE THREAD

**Issue by izhakjakov** [Homebrew/homebrew-core#74763] opened 2021-04-07 19:49 UTC
### `brew config` output

```shell
HOMEBREW_VERSION: 3.0.11-51-g1435018
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1435018e11ab5537c7df12cc8d2d261d88121b5b
Last commit: 52 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 760281826c541a3e49b6c4d2850e5f0a6a944580
Core tap last commit: 77 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.28
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Very recently, highlight stopped detecting shell scripts for me. It may have occurred when I upgraded to v4.0.
To get highlighting for shellscript, I have to explicitly use the -S shellscript parameter, then it works.
Detection is not completely broken for me, .md files are highlighted correctly.

I believe this issue is related [highlight's issue 181 on GitLab](https://gitlab.com/saalen/highlight/-/issues/181)

### What actually happened

Does NOT WORK when using:
```
$ highlight rln.sh
$ highlight rln.bash
```

WORKS when using:
```
$ highlight rln.shellscript
$ highlight -S shellscript rln.sh
$ highlight -S shellscript rln.bash
$ highlight -S shellscript rln
```

### What did you expect to happen?

Get highlighted syntax when using:
```
$ highlight rln.sh
$ highlight rln.bash
```

**Comment by carlocab** [comment] 2021-04-07 22:09
Based on the [upstream issue](https://gitlab.com/saalen/highlight/-/issues/181), it looks like a fix for this is to do
```
cd $(brew --prefix)/etc/highlight
mv filetypes.conf filetypes.conf.bak
mv filetypes.conf.default filetypes.conf
```
I guess the problem is that you actually want the new `filetypes.conf` file provided by upstream, but files installed into `$(brew --prefix)/etc` are never overwritten (because they often contain custom user configuration).

**Comment by carlocab** [comment] 2021-04-13 20:07
This is already tracked upstream, so I don't think there's a need to keep this open here.

**Closed by carlocab** 2021-04-13 20:07 UTC

**Comment by izhakjakov** [comment] 2021-04-16 14:26
Thank you!

**Comment by izhakjakov** [comment] 2021-04-16 14:34
> Based on the [upstream issue](https://gitlab.com/saalen/highlight/-/issues/181), it looks like a fix for this is to do
> 
> ```
> cd $(brew --prefix)/etc/highlight
> mv filetypes.conf filetypes.conf.bak
> mv filetypes.conf.default filetypes.conf
> ```
> 
> I guess the problem is that you actually want the new `filetypes.conf` file provided by upstream, but files installed into `$(brew --prefix)/etc` are never overwritten (because they often contain custom user configuration).

That's not a fix it is a workaround
`/usr/share/...` is not suppose to be user configuration path, `/Users/<user>/.local/share/...` should be used for that instead

**Comment by carlocab** [comment] 2021-04-16 14:47
Call it whatever you like.

`brew` doesn't install outside its prefix. Installing into `~/.local/share` would also require a similar fix/workaround/whatever-you-want-to-call-it.

**Comment by izhakjakov** [comment] 2021-04-16 14:53
For me, there was nothing in `$(brew --prefix)/etc/highlight` because I use the default settings.
So the system wide config path was used `/usr/local/highlight`
