### ISSUE TITLE
Bottled MPICH segfaults

### ISSUE THREAD

**Issue by mrzv** [Homebrew/homebrew-core#3975] opened 2016-08-17 14:59 UTC
The following example works fine on every MPI implementation I've tried, including `brew install --HEAD mpich`, but when compiled and run with the bottled MPICH (3.2_1), it segfaults.

```
// test-mpi.c

#include <mpi.h>

int main(int argc, char** argv)
{
    MPI_Init(&argc, &argv);

    MPI_Comm world = MPI_COMM_WORLD;

    int rank;
    MPI_Comm_rank(world, &rank);

    MPI_Comm local;
    MPI_Comm_split(world, rank, 0, &local);

    MPI_Finalize();
}
```

To compile and run:
```
mpicc test-mpi.c -o test-mpi
mpirun -n 2 ./test-mpi
```

**Comment by MikeMcQuaid** [comment] 2016-08-17 15:30
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by mrzv** [comment] 2016-08-17 15:37
The `gist-logs` are here https://gist.github.com/mrzv/dea48c710ff121fe0e9a2c0ffb6d5e0f

The `doctor` warnings are clearly unrelated.

**Comment by ilovezfs** [comment] 2016-08-19 09:22
This is reproducible, and, as @mrzv said, a HEAD build works fine. However, simply rebuilding the bottle doesn't help. Of course, not terribly surprisingly a build of the tag with gcc is fine and doesn't segfault.

**Comment by mrzv** [comment] 2016-08-19 14:40
@ilovezfs I have a tangentially related question. Is there a way for me to build 3.2 from source without uninstalling HEAD, only unlinking it? It used to be possible to say something like `brew install --build-from-source mpich@3.2_1` (I may be messing it up), but that doesn't seem to work anymore. Do I have to uninstall HEAD first? I want to test if it's an actual bug in MPICH 3.2, and I need to report it upstream.

**Comment by ilovezfs** [comment] 2016-08-19 14:45
@mrzv from IRC on 15 Aug:
>2:29 AM <Habbie> if i have a --HEAD formula installed, how do i also install the release version so i can switch between them with brew link?
5:36 AM <ilovezfs_> Habbie: 
5:36 AM <ilovezfs_> mv /usr/local/Cellar/hub{,.head}
5:36 AM <ilovezfs_>  brew install hub
5:36 AM <Habbie> unlink before mv i presume
5:36 AM <ilovezfs_> mv /usr/local/Cellar/hub{.head/*,}
5:37 AM <ilovezfs_> rmdir /usr/local/Cellar/hub.head
5:37 AM <ilovezfs_> then u can switch back and forth
5:37 AM <Habbie> ack
5:37 AM <Habbie> i was hoping for something cleaner ;)
5:37 AM <Habbie> thanks
5:37 AM <ilovezfs_> it does work with brew switch then
5:37 AM <Habbie> i have abandoned the whole project i needed it for by now
5:37 AM <Habbie> oh switch takes a version, that's useful
5:38 AM <ilovezfs_> right.
5:38 AM <ilovezfs_> Josephs-MacBook-Pro:~ joe$ brew switch hub 2.2.5
5:38 AM <ilovezfs_> Cleaning /usr/local/Cellar/hub/2.2.5
5:38 AM <ilovezfs_> Cleaning /usr/local/Cellar/hub/HEAD-ddd5b16
5:38 AM <ilovezfs_> 6 links created for /usr/local/Cellar/hub/2.2.5
5:39 AM <ilovezfs_> Josephs-MacBook-Pro:~ joe$ brew switch hub HEAD-ddd5b16
5:39 AM <ilovezfs_> Cleaning /usr/local/Cellar/hub/2.2.5
5:39 AM <ilovezfs_> Cleaning /usr/local/Cellar/hub/HEAD-ddd5b16
5:39 AM <ilovezfs_> 4 links created for /usr/local/Cellar/hub/HEAD-ddd5b16
5:39 AM <Habbie> :)
5:39 AM <ilovezfs_> it's just convincing it to install stable ...

**Comment by mrzv** [comment] 2016-08-19 14:49
@ilovezfs In other words, unlink, move out from the `Cellar`, install the desired version, move the other one back into the `Cellar`?

**Comment by ilovezfs** [comment] 2016-08-19 14:50
yep. Then `brew switch` will let you go back and forth between them.

**Comment by mrzv** [comment] 2016-08-19 14:50
Got you. Thanks.

**Comment by ilovezfs** [comment] 2016-08-19 14:52
You're welcome!

**Comment by mrzv** [comment] 2016-08-19 15:17
Ok, building 3.2 from source gives the same segfault. I think I'll report this upstream.

**Comment by ilovezfs** [comment] 2016-08-19 15:23
@mrzv Right that's what I saw too:
```
 However, simply rebuilding the bottle doesn't help
```

But since it doesn't happen in HEAD, your report needs to nag them for a new release tag as soon as possible.

Also, did you try building from source with gcc? That fixed it for me. `brew install gcc` and pass --cc=gcc-6, or add `fails_with :clang` to the formula.

**Comment by mrzv** [comment] 2016-08-19 15:27
I did not, but HEAD seems to work fine with the same compiler. Actually, now that I think about it, building both from source gave me a warning:
```
Warning: mpich dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```
But again, the build of HEAD didn't care.

**Comment by mrzv** [comment] 2016-08-19 21:16
Checked upstream. They know about the problem, meaning it will be fixed in the next bugfix release. Meanwhile, [alignment.patch](https://gist.github.com/mrzv/2abc82becd75ef7fe578cad27c6012d1) fixes the problem in the current release.

**Comment by ilovezfs** [comment] 2016-08-20 11:18
@mrzv the bottles should be fixed now!

**Closed** 2016-08-20 11:18 UTC
Labels: bug, in progress

**Comment by mrzv** [comment] 2016-08-20 18:04
Indeed, 3.2_2 works for me. Thanks!

**Comment by ilovezfs** [comment] 2016-08-20 18:05
@mrzv excellent. Thank you for following up and testing that it was indeed fixed!
