### ISSUE TITLE
Formulae should also handle exporting env vars like ${FORMULA}_HOME

### ISSUE THREAD

**Issue by alb-i986** [Homebrew/homebrew-core#889] opened 2016-05-06 01:17 UTC
Consider gradle. Part of its setup is to export the environment variable GRADLE_HOME.
If I use brew to install gradle, I'll need to add to my .bash_profile `export GRADLE_HOME=/usr/local/Cellar/gradle/2.13/libexec`. Then, when `brew update && brew upgrade` installs a new version of gradle, I'll need to (remember to!) manually update the export line in my `.bash_profile`.

As far as I understand, the best it is currently done is to add a caveat message saying something like "Please add #{lib exec} to your .bash_profile" (see e.g. https://github.com/Homebrew/homebrew-core/blob/master/Formula/wildfly-as.rb#L19)

How can we automate this?

One file, managed by brew, with all of the exports required by formulae.
With something like this in place, the final user would then only need to source this one file:

```
# .bash_profile

. /usr/local/Cellar/exports.sh
```

`exports.sh` may be actually sourcing other exports.sh files: each formula may have its own `exports.sh `, e.g. `/usr/local/Cellar/gradle/exports.sh `, which stores the actual export statements:

```
# /usr/local/Cellar/gradle/export.sh
export GRADLE_HOME=/usr/local/Cellar/gradle/2.13/libexec
```

Upon upgrade, a formula may completely overwrite the associated exports.sh file (as it may be easier than doing search&replace).

PS: Disclaimer: I'm just a brew user, so please bear with me, you may have better ideas for a concrete implementation

PPS: Sorry, maybe this should better go into the brew repo.

**Comment by ilovezfs** [comment] 2016-05-06 02:36
Not automating this is by design since users can have different shells and different desires for their environment. In really critical cases, a wrapper script is installed.

**Comment by DomT4** [comment] 2016-05-06 03:52
> One file, managed by brew, with all of the exports required by formulae.
With something like this in place, the final user would then only need to source this one file:

I don't want to go down this rabbit hole, personally.

We tend to handle this on a per-formula basis with env scripting. It's not uncommon, but doesn't work in 100% of cases. I don't think `GRADLE_HOME` has been mentioned to us, at least as so far as I remember, so that's possibly why discussion hasn't come up on this particular formula yet.

**Comment by DomT4** [comment] 2016-05-06 03:53
> Then, when brew update && brew upgrade installs a new version of gradle, I'll need to (remember to!) manually update the export line in my .bash_profile.

FYI, if you use for example `/usr/local/opt/gradle/libexec` you'll only need to add it the once and won't need to update it across every version.

**Comment by mikemcquaid** [comment] 2016-05-06 10:24
> We tend to handle this on a per-formula basis with env scripting. It's not uncommon, but doesn't work in 100% of cases. I don't think GRADLE_HOME has been mentioned to us, at least as so far as I remember, so that's possibly why discussion hasn't come up on this particular formula yet.

Agreed. Users shouldn't need to set these variables. We'd appreciate a PR to fix this for Gradle.

**Comment by mikemcquaid** [comment] 2016-05-06 10:24
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Closed by mikemcquaid** 2016-05-06 10:24 UTC

**Comment by alb-i986** [comment] 2016-05-09 08:54
@DomT4 

> FYI, if you use for example /usr/local/opt/gradle/libexec you'll only need to add it the once and won't need to update it across every version.

Thanks! Works for me.

> We tend to handle this on a per-formula basis with env scripting. It's not uncommon, but doesn't work in 100% of cases. 

What do you mean? Any example?

@mikemcquaid 

> Could you try and open a pull request? This document should help and I'm happy to walk you through anything else.

Do you mean for adding a caveat in gradle formula? Sure, will do.
Thanks

**Comment by mikemcquaid** [comment] 2016-05-09 08:57
> What do you mean? Any example?

https://github.com/Homebrew/homebrew-core/blob/12fe5cec8049243c02c7e742ddb198deccaf78ce/Formula/pig.rb#L21

> Do you mean for adding a caveat in gradle formula? Sure, will do.

Nope, add an env script so a caveat isn't needed. Thanks!

**Comment by alb-i986** [comment] 2016-05-10 14:17
> Nope, add an env script so a caveat isn't needed. Thanks!

I see.
Unfortunately I'm not too familiar with ruby, and I don't understand how I should call `write_env_script`.
Can you please help? What I need to write in the script is

    export GRADLE_HOME/usr/local/opt/gradle/libexec

Thanks

**Comment by mikemcquaid** [comment] 2016-05-12 19:23
@alb-i986 `(bin/"gradle").write_env_script libexec/"bin/gradle", Language::Java.java_home_env.merge(:GRADLE_HOME => libexec)` should do it!

**Comment by alb-i986** [comment] 2016-05-12 21:05
@mikemcquaid 
I'm not sure I can make it, I'm really a newbie here, maybe better if I let you handle it, or somebody else. I'll just open a new issue for now, is that ok?
Thanks anyways :)

**Comment by jasontedor** [comment] 2016-06-02 02:19
> Part of its setup is to export the environment variable GRADLE_HOME.

This is completely unnecessary as `/usr/local/bin` is already on the path and `gradle` there is a symbolic link there to the Homebrew-installed `gradle`.

> If I use brew to install gradle, I'll need to add to my .bash_profile `export GRADLE_HOME=/usr/local/Cellar/gradle/2.13/libexec`.

For running `gradle` from the command-line, you do not need to do this.

> Then, when `brew update && brew upgrade` installs a new version of gradle, I'll need to (remember to!) manually update the export line in my `.bash_profile`.

Again, this is completely unnecessary. You do not need to set `GRADLE_HOME` but if you must you can just point it to `/usr/local/opt/gradle`.

The problem with the change in #1543 is that now the `gradle` script no longer respects `JAVA_HOME` nor (the [purposeless](http://gradle.1045684.n5.nabble.com/retiring-GRADLE-HOME-td3325512.html) and [useless](https://github.com/gradle/gradle/search?q=GRADLE_HOME&type=Code&utf8=✓)) `GRADLE_HOME`.

I opened #1650.
