### ISSUE TITLE
Util-linux formulae do not build hardllink

### ISSUE THREAD

**Issue by eduardomozart** [Homebrew/homebrew-core#128904] opened 2023-04-20 18:48 UTC
Hello,
The Homebrew offers the ``hardlink`` package to create hard link to directories, but when attempting to install this formulae, it states that it's part of ``util-linux`` package, but on ``util-linux`` build formulae, the ``--enable-hardlink`` flag is missing, so the ``hardlink`` binary didn't seem to be build. I would like to recommend to remove the ``hardlink`` package from Homebrew if it's intended or add the ``--enable-hardlink`` flag on ``util-linux`` formulae.

### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
mac@MacBook-Pro-de-mac ~ % brew gist-logs util-linux
Error: No logs.
```

```shell
mac@MacBook-Pro-de-mac ~ % brew config
HOMEBREW_VERSION: 4.0.14-80-g72bdefb
ORIGIN: https://github.com/Homebrew/brew
HEAD: 72bdefb814083854830ceb2d8adad2c4983f49c8
Last commit: 8 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 43c6563b50a58a20b00f2ec1da91b03a00ee8d07
Core tap last commit: 3 hours ago
Core tap branch: master
Core tap JSON: 20 Apr 18:37 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.CVdzvy7fPi/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.5-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

```shell
mac@MacBook-Pro-de-mac ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libTitleGenerator.0.5.5.dylib
  /usr/local/lib/libVisio2Svg.0.5.5.dylib
  /usr/local/lib/libusb-0.1.4.dylib
  /usr/local/lib/libusbpp-0.1.4.dylib
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/usb.h
  /usr/local/include/usbpp.h
  /usr/local/include/visio2svg/TitleGenerator.h
  /usr/local/include/visio2svg/Visio2Svg.h
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libsane.la
  /usr/local/lib/libusb.la
  /usr/local/lib/libusbpp.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/libusb.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libusb.a
  /usr/local/lib/libusbpp.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  handbrake

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Installing the ``hardlink`` binary to create a hard link to a directory.

### What happened (include all command output)?

``util-linux`` formulae was installed but the ``hardlink`` binary is missing.

### What did you expect to happen?

``hardlink`` command should be available on Terminal, which is not.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install hardlink
brew install util-linux
```

**Comment by SMillerDev** [comment] 2023-04-20 19:15
https://docs.brew.sh/Updating-Software-in-Homebrew has the information you need. Closing this since it's not a bug

**Closed by SMillerDev** 2023-04-20 19:15 UTC
Labels: bug
