### ISSUE TITLE
swift: Build fails at doc generation due to "Can't open swift"

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew-core#5306] opened 2016-09-27 17:34 UTC
Relevant portion of the log below:

```
[478/665] Building CXX object stdlib/public/runtime/CMakeFiles/swiftRuntime-macosx-x86_64.dir/ErrorObject.mm.o
[479/665] Building CXX object stdlib/public/runtime/CMakeFiles/swiftRuntime-macosx-x86_64.dir/Reflection.mm.o
[480/665] Generating swift.1
FAILED: docs/tools/swift.1
cd /tmp/swift-20160927-9664-1i1t9yh/build/swift-macosx-x86_64/docs/tools && /usr/local/bin/pod2man --section 1 --center Swift\ Documentation --release --name swift --stderr /tmp/swift-20160927-9664-1i1t9yh/swift/docs/tools/swift.pod > /tmp/swift-20160927-9664-1i1t9yh/build/swift-macosx-x86_64/docs/tools/swift.1
Can't open swift: No such file or directory at /usr/local/bin/pod2man line 70.
[481/665] Building CXX object stdlib/public/runtime/CMakeFiles/swiftRuntime-macosx-x86_64.dir/Remangle.cpp.o
[482/665] Building CXX object stdlib/public/runtime/CMakeFiles/swiftRuntime-macosx-x86_64.dir/Metadata.cpp.o
[483/665] Building CXX object stdlib/public/runtime/CMakeFiles/swiftRuntime-macosx-x86_64.dir/Demangle.cpp.o
[484/665] Building CXX object lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/LoopTransforms/LoopRotate.cpp.o
[485/665] Building CXX object lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/LoopTransforms/ArrayBoundsCheckOpts.cpp.o
[486/665] Building CXX object lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/LoopTransforms/LoopUnroll.cpp.o
[487/665] Building CXX object lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/LoopTransforms/COWArrayOpt.cpp.o
ninja: build stopped: subcommand failed.
/private/tmp/swift-20160927-9664-1i1t9yh/swift-swift-2.2.1-RELEASE/utils/build-script: command terminated with a non-zero exit status 1, aborting
```

`pod2man` is present at `/usr/bin/pod2man`; not sure why swift is looking in `/usr/local/bin`. Easy fix is to add a `depends_on "pod2man" => :build`, but it's probably a better idea to figure out why Swift is looking in the wrong place

**Comment by aw1621107** [comment] 2016-09-27 18:04
Never mind about `depends_on "pod2man" => :build` being a fix; strangely enough, the build *still* fails with the following:

```
[523/665] Generating StdlibUnittest.swift from StdlibUnittest.swift.gyb with ptr size = 8
[524/665] Generating swift.1
FAILED: docs/tools/swift.1 
cd /tmp/swift-20160927-92695-14h9tie/build/swift-macosx-x86_64/docs/tools && /usr/local/opt/pod2man/bin/pod2man --section 1 --center Swift\ Documentation --release --name swift --stderr /tmp/swift-20160927-92695-14h9tie/swift/docs/tools/swift.pod > /tmp/swift-20160927-92695-14h9tie/build/swift-macosx-x86_64/docs/tools/swift.1
Can't open swift: No such file or directory at /usr/local/opt/pod2man/bin/pod2man line 74.
[525/665] Building CXX object stdlib/public/runtime/CMakeFiles/swiftRuntime-macosx-x86_64.dir/Metadata.cpp.o
[526/665] Building CXX object stdlib/public/runtime/CMakeFiles/swiftRuntime-macosx-x86_64.dir/Demangle.cpp.o
```

It's definitely there, so I'm not sure why it can't be opened.

**Comment by apjanke** [comment] 2016-10-26 19:05
```
Can't open swift: No such file or directory at /usr/local/opt/pod2man/bin/pod2man line 74.
```

That error message is being produced by `pod2man`. It's not the file `pod2man` that's failing to be opened, it's the file `swift`, and it's `pod2man` that's doing the complaining. Line 70 or 74 of `pod2man` is this:

```
    $parser->parse_from_file (@files);
```

Seems odd that it's complaining about plain `swift`, and not `swift.pod`, since that seems to be the input file on the command line.


> cd /tmp/swift-20160927-9664-1i1t9yh/build/swift-macosx-x86_64/docs/tools && /usr/local/bin/pod2man --section 1 --center Swift\ Documentation --release --name swift --stderr /tmp/swift-20160927-9664-1i1t9yh/swift/docs/tools/swift.pod > /tmp/swift-20160927-9664-1i1t9yh/build/swift-macosx-x86_64/docs/tools/swift.1

Here's the odd part of that command line:

```
--center Swift\ Documentation --release --name swift --stderr /tmp/swift-20160927-9664-1i1t9yh/swift/docs/tools/swift.pod
```

According to `man pod2man`, the `--release` option takes a string argument. But there's no argument there on the command line. So it looks like it'll consume `--name` as its argument, and the next token `swift` will look like a file name, instead of the argument to `--name`. I'm guessing this is a degenerate case where the value for `release` is ending up as an empty string, and the `pod2man` command line is not properly quoted.

Would you mind doing a `brew gist-logs swift` and posting the result, so we can see the full logs?

**Comment by aw1621107** [comment] 2016-10-26 19:52
[gist](https://gist.github.com/aw1621107/380b19acb85b382c3a3f3c5842382a47)

I have brew pointing to my fork of brew, so hopefully the suspicious origin warning isn't a big deal

**Comment by apjanke** [comment] 2016-10-26 19:57
Yeah, that's probably fine.

You've got a case-sensitive filesystem, which sometimes causes problems. But I don't think that's the issue here. I'm able to reproduce this failure on my own 10.11.6 box with a default case-insensitive filesystem, so I think this is an issue with the build script or formula, and not your configuration.

I'm doing a debug build now and will post details when it's finished.

**Comment by apjanke** [comment] 2016-10-27 00:06
Build logs from my failed build on 10.11.6: https://gist.github.com/4c2036f148cf5b30f1b1f23dbc9552ae

I get the same error with `pod2man`.

```
[665/665] Generating swift.1
FAILED: docs/tools/swift.1 
cd /tmp/swift-20161026-28784-jkqc2o/build/swift-macosx-x86_64/docs/tools && /usr/local/bin/pod2man --section 1 --center Swift\ Documentation --release --name swift --stderr /tmp/swift-20161026-28784-jkqc2o/swift/docs/tools/swift.pod > /tmp/swift-20161026-28784-jkqc2o/build/swift-macosx-x86_64/docs/tools/swift.1
Can't open swift: No such file or directory at /usr/local/bin/pod2man line 70.
ninja: build stopped: subcommand failed.
```

I think we can safely say it's not your configuration, and there's another problem going on here.

The `pod2man` reference is in `cmake/modules/SwiftManpage.cmake`. Here's the code where it calls `pod2man`.

```
  add_custom_command_target(
      unused_var
      COMMAND
        "${POD2MAN}" "--section" "${MP_MAN_SECTION}"
        "--center" "${MP_PAGE_HEADER}" "--release"
        "--name" "${MP_MAN_FILE_BASENAME}"
        "--stderr"
        "${MP_SOURCE}" > "${output_file_name}"
      OUTPUT "${output_file_name}"
      DEPENDS "${MP_SOURCE}"
      ALL)
```

So it's not a degenerate variable. The command is just written that way, with no argument to `--release`. My reading of `man pod2man` indicates an argument is required.

There's already an upstream commit that looks like it fixes this: https://github.com/apple/swift/commit/4e291f0b09d8bb86c91d608c1f52d741fd971527. Its comment says "This also fixes compatibility with newer versions of pod2man". So I'm guessing this build worked before when we had an older version of `pod2man`, and it was parsing its arguments differently.

I'll look at making a PR to pull in that patch to our `swift` formula.

**Comment by apjanke** [comment] 2016-10-27 00:45
Here's a PR to fix this by pulling in upstream's patch: https://github.com/Homebrew/homebrew-core/pull/6305.

**Comment by MikeMcQuaid** [comment] 2016-11-07 08:22
Should be fixed by https://github.com/Homebrew/homebrew-core/pull/6645

**Closed by MikeMcQuaid** 2016-11-07 08:22 UTC
Labels: upstream issue
