### ISSUE TITLE
nco: libgsl.19.dylib not loaded

### ISSUE THREAD

**Issue by ryofurue** [Homebrew/homebrew-core#15234] opened 2017-07-03 05:53 UTC
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I've installed nco via `brew install nco` and get this error:

    $ ncks -H -v ETOPO120X etopo120.cdf
    dyld: Library not loaded: /usr/local/opt/gsl/lib/libgsl.19.dylib
      Referenced from: /usr/local/bin/ncks
      Reason: image not found
    Abort trap: 6
    $ type ncks
    ncks is hashed (/usr/local/bin/ncks)
    $

`brew info` says `gsl` is installed (with a big green checkmark).

--- brew doctor ---
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
$

--- brew -------------
$ brew config
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 72126c105094790c3c02986edeaee8900efdfc82
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: N/A
X11: 2.7.11 => /opt/X11
$

**Comment by ilovezfs** [comment] 2017-07-03 06:13
@ryofurue nco is a homebrew/science formula, so this issue belongs in https://github.com/Homebrew/homebrew-science/ but it's actually a duplicate of

https://github.com/Homebrew/homebrew-science/pull/5887
https://github.com/Homebrew/homebrew-science/issues/5841

Thanks for reporting it, nonetheless.

**Closed by ilovezfs** 2017-07-03 06:13 UTC

**Comment by ryofurue** [comment] 2017-07-03 06:30
Thanks for your kind response.  I'm still not familiar with how these forums are organized.

For a record, I've just applied a "band-aid":

    $ cd /usr/local/opt/gsl/lib/
    $ ln -s libgsl.23.dylib libgsl.19.dylib

and `ncks` starts to work.

**Comment by ilovezfs** [comment] 2017-07-11 04:46
@ryofurue this is now fixed :)

**Comment by ryofurue** [comment] 2017-07-11 05:17
> this is now fixed :)

Thank you for letting me know!  I've just confirmed `ncks` works without the "band-aid" I described above.
