### ISSUE TITLE
'pip' not found

### ISSUE THREAD

**Issue by trusktr** [Homebrew/homebrew-core#24143] opened 2018-02-14 21:54 UTC
it's been a while since I've been on macOS, but seems like `brew install python` no longer adds the `python` or `pip` binaries to PATH. So, I ran `ln -s /usr/local/bin/python2 /usr/local/bin/python` and `ln -s /usr/local/bin/pip2 /usr/local/bin/pip` (and `/usr/loca/bin` is already in my PATH).

Why has this changed?

**Comment by Argon-** [comment] 2018-02-14 22:31
Did your postinstall fail?
Not entirely sure but I think this links pip. And for me the postinstall for both, `python` and `python3`, fails really frequently. Unfortunately, I have no idea why and can't reliably reproduce it in order to debug it. A failed postinstall also doesn't error out so I often don't notice it until I get some problems (e.g. stuff was not found, path related things) later on which can then be fixed by issuing postinstall by hand (which then always works).

**Comment by fxcoudert** [comment] 2018-02-14 22:53
```
  def caveats; <<~EOS
    This formula installs a python2 executable to #{HOMEBREW_PREFIX}/bin.
    If you wish to have this formula's python executable in your PATH then add
    the following to #{shell_profile}:
      export PATH="#{opt_libexec}/bin:$PATH"

    Pip and setuptools have been installed. To update them
      pip2 install --upgrade pip setuptools

    You can install Python packages with
      pip2 install <package>

    They will install into the site-package directory
      #{site_packages}

    See: https://docs.brew.sh/Homebrew-and-Python.html
    EOS
  end
```

The reasoning is explained here: https://github.com/Homebrew/homebrew-core/pull/14408

**Closed by fxcoudert** 2018-02-14 22:53 UTC
