### ISSUE TITLE
fontconfig 2.12.1 may cause performance degradation

### ISSUE THREAD

**Issue by edporras** [Homebrew/homebrew-core#4172] opened 2016-08-23 11:33 UTC
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

There seems to be a performance issue with the latest `fontconfig` ([2.12.1](https://github.com/Homebrew/homebrew-core/blob/7b38917c605172fc944f4331ea9d50087a8203ea/Formula/fontconfig.rb)) release affecting packages that depend on `poppler` or maybe just `freetype` - I'm not quite sure. I discovered it through my own Formula ([pdftoedn](https://github.com/Homebrew/homebrew-core/blob/7b38917c605172fc944f4331ea9d50087a8203ea/Formula/pdftoedn.rb)) which does not use `fontconfig` directly but depends on `poppler` which depends on `freetype` and `fontconfig`. 

What I'm seeing is my application takes much longer to process documents after upgrading to `fontconfig-2.12.1`. To be sure, I wiped brew from my system and started with a fresh brew that installed `2.12.1` from bottle and `fontconfig-2.11.1` from source after editing the formula:

```console
doppio:fontconfig_test admin$ brew info fontconfig
fontconfig: stable 2.12.1 (bottled)
XML-based font configuration API for X Windows
https://wiki.freedesktop.org/www/Software/fontconfig/
/usr/local/Cellar/fontconfig/2.11.1 (450 files, 2.9M)
  Built from source on 2016-08-23 at 12:08:32
/usr/local/Cellar/fontconfig/2.12.1 (468 files, 3M) *
  Poured from bottle on 2016-08-23 at 11:40:42
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/fontconfig.rb
==> Dependencies
Build: pkg-config ✔
Required: freetype ✔
==> Options
--universal
	Build a universal binary
```

I have the latest version of `pdftoedn` which shows the versions of the libraries it depends on:

```console
doppio:fontconfig_test admin$ pdftoedn -v
pdftoedn 0.34.1
Linked libraries: 
 poppler 0.47.0
 libpng 1.6.24
 boost 1.61
 freetype 2.6.5
 leptonica 1.73
 rapidjson 1.0.2
```

With `fontconfig-2.12.1` selected, processing a 14Kb 1-page PDF:

```console
doppio:fontconfig_test admin$ time pdftoedn -o 2.12.1.edn to_service4.pdf 

real	0m20.049s
user	0m19.630s
sys	0m0.414s
```

This seemed really odd as it's usually much faster than this. Switching to `fontconfig 2.11.1`:

```console
doppio:fontconfig_test admin$ brew switch fontconfig 2.11.1
Cleaning /usr/local/Cellar/fontconfig/2.11.1
Cleaning /usr/local/Cellar/fontconfig/2.12.1
215 links created for /usr/local/Cellar/fontconfig/2.11.1

doppio:fontconfig_test admin$ time pdftoedn -o 2.11.1.edn to_service4.pdf 

real	0m0.057s
user	0m0.025s
sys	0m0.011s
```

Make sure the output matches:

```console
doppio:fontconfig_test admin$ colordiff 2.11.1.edn 2.12.1.edn 
doppio:fontconfig_test admin$ 
```

Now, I realize whatever is causing this is not `homebrew`'s  to solve but you might have other people reporting issues as it is not just my app. I tested [`diff-pdf`](https://github.com/Homebrew/homebrew-core/blob/7b38917c605172fc944f4331ea9d50087a8203ea/Formula/diff-pdf.rb)  as well (which also just depends on `poppler`). First, with `fontconfig-2.11.1`:

```console
doppio:fontconfig_test admin$ time diff-pdf to_service4.pdf to_service4.pdf 

real	0m0.223s
user	0m0.110s
sys	0m0.063s
```

Then, with `fontconfig-2.12.1`:

```console
doppio:fontconfig_test admin$ brew switch fontconfig 2.12.1
Cleaning /usr/local/Cellar/fontconfig/2.11.1
Cleaning /usr/local/Cellar/fontconfig/2.12.1
222 links created for /usr/local/Cellar/fontconfig/2.12.1

doppio:fontconfig_test admin$ time diff-pdf to_service4.pdf to_service4.pdf 

real	0m22.901s
user	0m19.894s
sys	0m1.429s
```

To make sure this isn't a problem with the font cache, I uninstalled and reinstall `fontconfig-2.12.1` to force it to generate the cache:

```console
doppio:fontconfig_test admin$ brew uninstall fontconfig
Uninstalling /usr/local/Cellar/fontconfig/2.12.1... (468 files, 3M)
fontconfig 2.11.1 is still installed.
Remove them all with `brew uninstall --force fontconfig`.

doppio:fontconfig_test admin$ brew upgrade fontconfig
==> Upgrading 1 outdated package, with result:
fontconfig 2.12.1
==> Upgrading fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.12.1.el_capitan.bottle.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/fontconfig-2.12.1.el_capitan.bottle.tar.gz
==> Pouring fontconfig-2.12.1.el_capitan.bottle.tar.gz
==> Using the sandbox
==> Regenerating font cache, this may take a while
==> /usr/local/Cellar/fontconfig/2.12.1/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.12.1: 468 files, 3M
```

Then tested again:

```console
doppio:fontconfig_test admin$ time diff-pdf to_service4.pdf to_service4.pdf 

real	0m23.053s
user	0m19.796s
sys	0m1.581s

doppio:fontconfig_test admin$ brew switch fontconfig 2.11.1
Cleaning /usr/local/Cellar/fontconfig/2.11.1
Cleaning /usr/local/Cellar/fontconfig/2.12.1
215 links created for /usr/local/Cellar/fontconfig/2.11.1

doppio:fontconfig_test admin$ time diff-pdf to_service4.pdf to_service4.pdf 

real	0m0.218s
user	0m0.106s
sys	0m0.064s
```

I don't see any errors reported in the console but, when I first ran my app after the upgrade, I did see a `fontconfig` error (on standard error) complaining about a blank line in `fonts.conf`. Also, when I submitted a version of my Formula over the weekend, a [`fontconfig` error was reported](https://github.com/Homebrew/homebrew-core/pull/4071#issuecomment-241203363) that I had not seen before. 

I'm not sure where to begin to track this down - I'll bring it up on the poppler mailing list to see if they have any ideas. In the meantime, I'll update my project's README to advice folks to not update `fontconfig` to the latest version for now.

**Comment by MikeMcQuaid** [comment] 2016-08-23 11:41
Yeh, I'm afraid this sounds like an upstream issue unless you can't reproduce it when building from source. Closing this out but will reopen if we establish it's a Homebrew problem.

**Comment by zmwangx** [comment] 2016-08-25 02:26
I don't have to time to investigate this for now, but indeed, fc 2.12.1 seems to be having huge trouble with caching or cache validation, which is immediately obvious if you run `fc-cache -v` repeatedly, the subsequent runs of which should return immediately with a bunch of "existing cache is valid". Instead, the cache seems to be rebuilt each time. I'll look into the problem later when I have time.

**Comment by zmwangx** [comment] 2016-08-25 02:29
By the way, this issue is intrinsic to fontconfig as I demonstrated, so IMO it has nothing to do with freetype or poppler (I don't even have poppler installed). Maybe you could simplify the top post a bit.

**Comment by MikeMcQuaid** [comment] 2016-08-25 07:03
> Yeh, I'm afraid this sounds like an upstream issue unless you can't reproduce it when building from source.

Closing but will reopen if this isn't the case.

**Closed by MikeMcQuaid** 2016-08-25 07:03 UTC
Labels: upstream issue

**Comment by zmwangx** [comment] 2016-08-25 12:51
Upon closer look, fontconfig 2.12.1 has trouble caching `/System/Library/Fonts` (but not with `/Library/Fonts`). And it indeed appears to be an upstream issue.

**Comment by zmwangx** [comment] 2016-08-26 07:48
I tracked the issue down to https://cgit.freedesktop.org/fontconfig/commit/?id=7a4a5bd7897d216f0794ca9dbce0a4a5c9d14940 and reported to fontconfig@lists.freedesktop.org. [The archive](https://lists.freedesktop.org/archives/fontconfig/2016-August/thread.html) isn't up-to-date yet but expect it shortly.

**Comment by zmwangx** [comment] 2016-08-28 02:02
Actually my report never reached the list because I wasn't subscribed. I resent my report, and it's available here: https://lists.freedesktop.org/archives/fontconfig/2016-August/005811.html.

**Comment by edporras** [comment] 2016-08-31 08:27
I went ahead and filed a bug and linked to your post to the list, @zmwangx:

https://bugs.freedesktop.org/show_bug.cgi?id=97546

Thanks!
