### ISSUE TITLE
libtiff failed to build on 10.12.1 with --universal option

### ISSUE THREAD

**Issue by Saklad5** [Homebrew/homebrew-core#7537] opened 2016-12-04 20:11 UTC
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

The libtiff formula fails to build properly with the --universal option, saying that symbols are undefined for my architecture. It works if I run the same command without --universal.
https://gist.github.com/b0d0da430bac0091afa3ab2917b88949

**Comment by ilovezfs** [comment] 2016-12-04 20:36
```
  C compiler:                         /usr/bin/clang -O3 -march=native -flto -Wall -W
  C++ compiler:                       clang++ -O3 -march=native -flto
```
Where's that coming from?

**Comment by Saklad5** [comment] 2016-12-04 20:38
That’s from my environment variables. Using `--env=super` or deleting that from my .bash_profile removes those compiler flags, but does not fix the bug. As such, I am pretty sure that is unrelated.

**Comment by ilovezfs** [comment] 2016-12-04 20:41
I can't reproduce the problem so it's something in your configuration. Anything else out of the ordinary you can think of?

**Comment by Saklad5** [comment] 2016-12-04 20:41
I’ve racked my brain for anything that might cause it, but I’m coming up blank. `brew doctor --verbose` is also coming up blank.

**Comment by ilovezfs** [comment] 2016-12-04 20:42
mind creating a dummy user account and see if it goes away?

**Comment by Saklad5** [comment] 2016-12-04 20:43
That might take a while… I’ll see if I have time later, but I don’t think I will anytime soon.

**Comment by Saklad5** [comment] 2016-12-04 20:44
I’ll try renaming my bash_profile and running it.

**Comment by Saklad5** [comment] 2016-12-04 20:50
Nope, same issue.

**Comment by Saklad5** [comment] 2016-12-04 20:51
Well, after including files that it no longer had.

**Comment by ilovezfs** [comment] 2016-12-04 21:20
Looks like you're also setting the custom values in /usr/local/etc/config.site

**Comment by Saklad5** [comment] 2016-12-04 21:37
You are correct. Unfortunately, changing those didn’t help. Nice catch, though.

**Comment by ilovezfs** [comment] 2016-12-04 21:39
I still suspect it's related to the -flto since it mentions lto.o. Are you sure that's not being passed?

**Comment by Saklad5** [comment] 2016-12-04 22:22
Passing -no-flto _and_ deleting -flto seemed to fix it, but I’m not sure why. Verbose output didn’t change when I did so.

**Comment by ilovezfs** [comment] 2016-12-04 22:27
The verbose output is bogus. You have to look at the superenv log like https://gist.github.com/Saklad5/b0d0da430bac0091afa3ab2917b88949#file-02-make-cc to see what really is happening. It's in ~/Library/Logs/Homebrew/libtiff, and will be overwritten each time you build.

**Comment by ilovezfs** [comment] 2016-12-06 17:20
@Saklad5 any update here?

**Comment by Saklad5** [comment] 2016-12-06 17:23
Well, I got it working by passing `no-flto`, as I said. Is there anything else you would like me to look into?

**Comment by ilovezfs** [comment] 2016-12-06 17:24
@Saklad5 I'm happy if you're happy.

**Comment by Saklad5** [comment] 2016-12-06 17:26
Nevertheless, we still don't know why LTO is messing it up. I may have gotten what I wanted, but anyone else trying to install `libtiff` is going to have the same problem. I leave to you the question of whether or not this issue should be closed.

**Comment by ilovezfs** [comment] 2016-12-06 17:29
@Saklad5 I'll go ahead and close it since I can build successfully with universal, without using -no-flto, and if someone else hits this particular failure scenario, we'll know where to start the debugging again.

**Closed** 2016-12-06 17:29 UTC
