### ISSUE TITLE
opencv3 failed to build on 10.11.4

### ISSUE THREAD

**Issue by mazl123321** [Homebrew/homebrew-core#334] opened 2016-04-15 02:32 UTC
# I already follow the general troubleshooting steps first:

- [YES] Ran `brew update` and retried your prior step?
- [YES] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [YES] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

opencv3 build failure:

https://gist.github.com/9fce31be4edd5e4d8ab87b8db99bb7e9

Thanks!

**Comment by heinemml** [comment] 2016-04-15 07:49
Looks like the same problem reported in https://github.com/Homebrew/homebrew-science/issues/3371

@mazl123321 As this is a science package it should be reported at https://github.com/Homebrew/homebrew-science/issues

**Comment by dunn** [comment] 2016-04-16 15:53
Closing as a duplicate of Homebrew/homebrew-science#3371, then, but thank you for the report!

**Closed by dunn** 2016-04-16 15:53 UTC
