### ISSUE TITLE
cmake failed to build on 10.13

### ISSUE THREAD

**Issue by darnel** [Homebrew/homebrew-core#17250] opened 2017-08-25 21:03 UTC
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
> No, they are all warings "only", I fixed some issues that are no longer present in my [gist](https://gist.github.com/anonymous/67f0db121976a490221dae045e9e65d8). Please see details below.
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
> [https://gist.github.com/anonymous/67f0db121976a490221dae045e9e65d8](https://gist.github.com/anonymous/67f0db121976a490221dae045e9e65d8)
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I manually run `brew reinstall cmake`, because cmake (3.9.1) failed to build previously and repeatedly while installing as dependency of many packages
- What happened (include command output)
```
Last 15 lines from /Users/admin/Library/Logs/Homebrew/cmake/02.make:
[ 26%] Built target pseudonl_BC
Scanning dependencies of target pseudonl_purify
[ 26%] Building C object Tests/CMakeLib/PseudoMemcheck/NoLog/CMakeFiles/pseudonl_purify.dir/ret0.c.o
[ 26%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/x86.c.o
[ 26%] Linking C executable purify
Error: The core module cannot be found. Did you install Sphinx and its dependencies correctly?
make[2]: *** [Utilities/Sphinx/doc_format_man] Error 1
make[1]: *** [Utilities/Sphinx/CMakeFiles/documentation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 27%] Linking CXX executable testEncoding
[ 27%] Linking C static library libcmliblzma.a
[ 27%] Built target pseudonl_purify
[ 27%] Built target cmliblzma
[ 27%] Built target testEncoding
make: *** [all] Error 2
```
- What you expected to happen
I hoped `cmake` will build :)
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install cmake`

---

As I understand problem is with some `core` package of `sphinx`. I tried
```
brew reinstall sphinx
brew reinstall sphinx-doc
brew reinstall docutils
easy_install sphinx
```
All finished successfully, but has no effect to my issue.

I have some warnings in `brew doctor`, but I suppose it's not related.

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libusb-1.0.0.dylib
```
> It's mentioned in https://github.com/Homebrew/legacy-homebrew/issues/23333, I'm using DisplayLink drivers, which is working. I ignored this warning.

```
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php56
```
> I'm using `php56` and `php70`, and brew-linking/unlinking them as needed.

```
Warning: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```
> I know... 🙄
 
```
Warning: Ruby version 2.3.3 is unsupported on 10.13. Homebrew
is developed and tested on Ruby 2.0, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
```
> True (ruby 2.3.3p222), probably due to mac OS 10.13. No idea if this needs to be fixed somehow.

**Comment by DomT4** [comment] 2017-08-26 02:03
Might be an issue with the new CLT release. Can't reproduce this with Xcode 9 (9M214v).

**Comment by darnel** [comment] 2017-08-28 09:37
Tried Xcode 8.3 https://gist.github.com/anonymous/373b44f5d2e13196082472f8ecdfc812
and 9.0 https://gist.github.com/anonymous/36636a2f8f66677432cc7813cd969561 with no effect

**Comment by ilovezfs** [comment] 2017-08-28 10:34
Please try

```
HOMEBREW_MAKE_JOBS=1 brew install -dvs cmake
```

**Comment by darnel** [comment] 2017-08-28 12:14
It reaches 94% instead of ~27%
```
[ 94%] sphinx-build man: see Utilities/Sphinx/build-man.log
Error: The core module cannot be found. Did you install Sphinx and its dependencies correctly?
make[2]: *** [Utilities/Sphinx/doc_format_man] Error 1
make[1]: *** [Utilities/Sphinx/CMakeFiles/documentation.dir/all] Error 2
make: *** [all] Error 2
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:
```
When I choose ignore twice (for `make` and `make install`) it finished. Thanks.
Should I do backtrace for further research?

**Comment by ilovezfs** [comment] 2017-08-28 12:21
What's the output from
```
pip2 uninstall Sphinx
```

**Comment by darnel** [comment] 2017-08-28 12:24
```Cannot uninstall requirement Sphinx, not installed```.

Should I try to uninstall brew `sphinx` and/or `sphinx-doc`?

**Comment by ilovezfs** [comment] 2017-08-28 12:30
How about `pip3 uninstall Sphinx`?

**Comment by darnel** [comment] 2017-08-28 13:16
Same as previous.

I tried `pip uninstall ...` but there's command not found, I don't come pip3 in my mind...

**Comment by ilovezfs** [comment] 2017-08-28 13:18
Please try this:

```
mkdir ~/homebrew-20170828
sudo mv /usr/local/* ~/homebrew-20170828/
sudo mv /usr/local/.* ~/homebrew-20170828/
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install -dvs cmake
```

**Comment by DomT4** [comment] 2017-08-28 14:12
> Tried Xcode 8.3 https://gist.github.com/anonymous/373b44f5d2e13196082472f8ecdfc812
and 9.0 https://gist.github.com/anonymous/36636a2f8f66677432cc7813cd969561 with no effect

Just to check, did you switch your active developer path over from the CLT before trying `brew install cmake` again?

**Comment by darnel** [comment] 2017-08-28 20:47
This try works! Something is broken in my homebrew dirs...

**Comment by fxcoudert** [comment] 2017-09-03 19:39
Closing accordingly.

**Closed by fxcoudert** 2017-09-03 19:39 UTC
