### ISSUE TITLE
Imagemagick issue

### ISSUE THREAD

**Issue by farooq4** [Homebrew/homebrew-core#4931] opened 2016-09-17 21:15 UTC
wError: undefined method `downcase' for #<Pathname:imagemagick>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:349:in `core_path'
/usr/local/Library/Homebrew/formulary.rb:301:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:219:in `factory'
/usr/local/Library/Homebrew/utils.rb:637:in `rescue in rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:634:in `rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:631:in `block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:629:in `each'
/usr/local/Library/Homebrew/utils.rb:629:in `migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'
/ user$ brew update
Error: undefined method `downcase' for #<Pathname:imagemagick>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:349:in `core_path'
/usr/local/Library/Homebrew/formulary.rb:301:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:219:in `factory'
/usr/local/Library/Homebrew/utils.rb:637:in `rescue in rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:634:in `rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:631:in `block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:629:in `each'
/usr/local/Library/Homebrew/utils.rb:629:in `migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'
/ user$ brew doctor
Error: undefined method `downcase' for #<Pathname:imagemagick>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:349:in `core_path'
/usr/local/Library/Homebrew/formulary.rb:301:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:219:in `factory'
/usr/local/Library/Homebrew/utils.rb:637:in `rescue in rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:634:in `rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:631:in `block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:629:in `each'
/usr/local/Library/Homebrew/utils.rb:629:in `migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'

Go this error while trying to install imagemagick. 
Tried brew updates and brew doctor
get the same error every time.

**Comment by zmwangx** [comment] 2016-09-18 05:25
Sorry, this should be fixed once we ship https://github.com/Homebrew/brew/pull/1003 or something comparable. Could you please test the change in https://github.com/Homebrew/brew/pull/1003? Or if you're unsure about how to do that, just wait and we'll notify you.

**Comment by zmwangx** [comment] 2016-09-18 05:37
Actually this issue duplicates #4930, so please track the progress there. I will try to alert you here too when the issue is fixed, though.

**Closed by zmwangx** 2016-09-18 05:37 UTC

**Comment by ilovezfs** [comment] 2016-09-18 06:17
https://github.com/Homebrew/brew/pull/1003 has shipped. Please update, and this should be fixed.
