### ISSUE TITLE
Symbolic link from `man` to `gnuman`, etc. does not work

### ISSUE THREAD

**Issue by injust** [Homebrew/homebrew-core#176037] opened 2024-07-01 04:24 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 43eaeca50fe3b6c755f3fc9bc6f43669e0db1039
Last commit: 7 days ago
Core tap: N/A
Core cask tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.45.2 => /usr/local/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A

Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I want to install `coreutils`, follow the caveats, and:
1. Run GNU `ls` with `ls`
2. Read the GNU `ls` man page with `man ls`

### What happened (include all command output)?

1. `ls` runs GNU `ls`
2. `man -w ls` prints `/usr/share/man/man1/ls.1` and `man ls` displays the macOS `ls` man page instead of the GNU `ls` man page

### What did you expect to happen?

`man ls` should display the GNU `ls` man page.

In #35874, this caveat was removed:

> Additionally, you can access their man pages with normal names if you add
> the "gnuman" directory to your MANPATH from your bashrc as well:
>   MANPATH="#{opt_libexec}/gnuman:$MANPATH"

But `man ls` still displays the macOS `ls` man page, i.e. the changes in #35874 just don't work on my system. I'm not sure how the default manual path is constructed, but macOS man pages are being preferred over `coreutils` man pages, even if I prepend `/usr/local/opt/coreutils/libexec/gnubin` to `PATH`.

I had to prepend `/usr/local/opt/coreutils/libexec/gnuman` to `MANPATH` to get `man ls` working.

`coreutils` is just an example here. This also goes for other Homebrew formulae, e.g. `findutils`, `gnu-sed`, `grep`, and `uutils-coreutils`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# This should work according to #35874, but it doesn't
brew install coreutils
fish_add_path /usr/local/opt/coreutils/libexec/gnubin

# Prints /usr/share/man/man1/ls.1
man -w ls

# Prepending to MANPATH fixes it
set -gx MANPATH /usr/local/opt/coreutils/libexec/gnuman:

# Prints /usr/local/opt/coreutils/libexec/gnuman/man1/ls.1
man -w ls
```

**Comment by injust** [comment] 2024-07-01 04:25
cc @moonfruit

**Comment by gromgit** [comment] 2024-07-02 04:52
I'm not sure how #35874 managed to work. Perhaps macOS changed their MANPATH construction logic after that PR was committed, because the current `manpath` man page reads:

> The `manpath` utility constructs the manual path from two sources:
>      1.   From each component of the user's PATH for the first of:
>          -   `pathname/man`
>          -   `pathname/MAN`
>          -   If pathname ends with `/bin`: `pathname/../share/man` and `pathname/../man`

Since `/gnubin != /bin`, the corresponding `/man` would never be added.

I've confirmed this by reading the `man` and `manpath` sources (they're the same shell script).

**Comment by moonfruit** [comment] 2024-07-02 09:30
Yes, #35874 is not working properly now. I also create a PR #135272 to fix this. But this latter PR was not accepted and has been closed. So I had to add some scripts on my own computer to automate what was in this PR.

**Comment by gromgit** [comment] 2024-07-02 10:11
@Homebrew/maintainers, what was the rationale for using `libexec/gnu{bin,man}` instead of the conventional `libexec/{bin,man}` for Homebrew-wrapped binaries?

**Comment by cho-m** [comment] 2024-07-02 13:33
> @Homebrew/maintainers, what was the rationale for using `libexec/gnu{bin,man}` instead of the conventional `libexec/{bin,man}` for, say, Homebrew-wrapped binaries?

It looks like `gnubin` was copied from MacPorts. Ref: https://github.com/Homebrew/legacy-homebrew/commit/c53e35ed6560fe2074c0a5e9ca2ddbec11a7d155
```
 - libexec/gnubin directory contains symlinks to all the coreutils
   commands without its program-prefix "g". (Inspired by MacPorts'
   coreutils)
```

`gnuman` was probably created based on `gnubin` name (https://github.com/Homebrew/legacy-homebrew/commit/372c0d76849aaa18282e1841021588c74f2bf3a3). MacPorts instead used `libexec/gnubin/man/` (https://github.com/macports/macports-ports/blob/master/sysutils/coreutils/Portfile#L94).

**Comment by gromgit** [comment] 2024-07-02 15:19
> MacPorts instead used `libexec/gnubin/man/` (https://github.com/macports/macports-ports/blob/master/sysutils/coreutils/Portfile#L94).

Yeah, that would trigger the current macOS man path logic, so that's a third option, that's probably the least disruptive of all:

3. Move the `man` symlink created in #35874, from `libexec/man` to `libexec/gnubin/MAN` (to avoid confusion with the `man` command).

However, there's another issue: if `$MANPATH` is not empty (and `brew shellenv` ensures it's not), `man` only adds `$PATH`-derived man directories under the following circumstances:-

1. `$MANPATH == :*` --> _prepend_ derived directories
2. `$MANPATH == *:` --> _append_ derived directories
3. `$MANPATH == *::*` --> _insert_ derived directories between the two colons

Now, `brew shellenv` adds a trailing colon to MANPATH (case 2), so system man pages will _always_ shadow Homebrew pages of the same name, which I think defeats the whole purpose of deriving man dirs dynamically, particularly since people would logically _prepend_ `gnubin` directories to their PATH.

Ironically, having `brew shellenv` not set MANPATH at all (or simply prepending a colon if it's already been set) seems to be the Right Thing going forward.

Is there a flaw in my logic?

**Comment by moonfruit** [comment] 2024-07-03 01:43
> `gnuman` was probably created based on `gnubin` name ([Homebrew/legacy-homebrew@372c0d7](https://github.com/Homebrew/legacy-homebrew/commit/372c0d76849aaa18282e1841021588c74f2bf3a3)). MacPorts instead used `libexec/gnubin/man/` ([macports/macports-ports@`master`/sysutils/coreutils/Portfile#L94](https://github.com/macports/macports-ports/blob/master/sysutils/coreutils/Portfile?rgh-link-date=2024-07-02T13%3A33%3A44Z#L94)).

Yes, this is indeed a viable option. This solution gets around the problem of confusing directory names: `bin` vs `gnubin`. Just kind of breaks the regular Linux directory layout.

> Ironically, having `brew shellenv` not set MANPATH at all (or simply prepending a colon if it's already been set) seems to be the Right Thing going forward.

Couldn't agree more.

**Comment by MikeMcQuaid** [comment] 2024-07-03 11:54
> Ironically, having `brew shellenv` not set MANPATH at all (or simply prepending a colon if it's already been set) seems to be the Right Thing going forward.

Yes, agreed. Could you open a PR @gromgit? No worries if not.

> > MacPorts instead used `libexec/gnubin/man/` ([macports/macports-ports@`master`/sysutils/coreutils/Portfile#L94](https://github.com/macports/macports-ports/blob/master/sysutils/coreutils/Portfile?rgh-link-date=2024-07-02T15%3A19%3A32Z#L94)).
>
> Yeah, that would trigger the current macOS man path logic, so that's a third option, that's probably the least disruptive of all

This also seems like a good idea. I'd be in favour of doing both.

@homebrew/core any thoughts on the above?

**Comment by gromgit** [comment] 2024-07-04 08:10
> Yes, agreed. Could you open a PR @gromgit? No worries if not.

I'll take care of that in a few hours.

**Closed** 2024-07-08 07:42 UTC
Labels: bug

**Comment by injust** [comment] 2024-07-18 23:17
This isn't completely fixed until https://github.com/Homebrew/homebrew-core/pull/176589 is merged, and that seems to be stuck because of CI failures.

I don't seem to be able to reopen this issue though.

**Comment by ZhongRuoyu** [comment] 2024-07-18 23:47
It's merged now. CI failures were unrelated.

**Comment by injust** [comment] 2024-07-18 23:51
There's also https://github.com/Homebrew/homebrew-core/pull/176875, but that one's actually blocked because of https://github.com/Homebrew/brew/issues/16284.
