### ISSUE TITLE
gv issue

### ISSUE THREAD

**Issue by katelynallers** [Homebrew/homebrew-core#11084] opened 2017-03-14 18:20 UTC
So, gv recently decided to stop working for me.  I'm not sure if this coincided with the XQuartz update or not.  gv (and ghostscript) build with no errors or issues, but when I try to open gv I get the following error: 
Warning: translation table syntax error: Unknown event type :   EnterWindow
Warning: ... found while parsing '<EnterWindow>:        highlight()             '
Warning: String to TranslationTable conversion encountered errors
Warning: translation table syntax error: Unknown event type :   EnterWindow
Warning: ... found while parsing '<EnterWindow>:highlight()'
Warning: String to TranslationTable conversion encountered errors
Warning: translation table syntax error: Unknown modifier name:   Any
Warning: ... found while parsing 'Any<BtnDown>:set()PopupMenu()'
Warning: String to TranslationTable conversion encountered errors
Error: attempt to add non-widget child "fileButton" to parent "control" which supports only widgets
Any suggestions?

Here the output of brew config:
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 91ee3f689a2aaf2800104e36b7e6390b0a256bdf
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11

**Comment by dunn** [comment] 2017-03-15 02:43
If it's possible to build gv outside of Homebrew and see if this still occurs, that'd help us know if it's an issue with how we're compiling it, or an upstream bug.

**Comment by fxcoudert** [comment] 2017-03-17 13:07
Cannot reproduce this.

Maybe linked to the fact that you have an old version of X. Could you install the latest [XQuartz](https://www.xquartz.org) version, i.e. 2.7.11?

**Comment by MikeMcQuaid** [comment] 2017-03-19 16:33
And also paste your `brew doctor` output (as requested by the issue template).

**Comment by fxcoudert** [comment] 2017-03-30 09:56
Closing this for now, please reopen when you have the information requested.

**Closed by fxcoudert** 2017-03-30 09:56 UTC

**Comment by katelynallers** [comment] 2017-03-30 20:17
Hi all, sorry for the delay-classes started up again, so I was swamped with teaching.  I built gv outside of homebrew and was having the same issue.  So, I updated Xquartz (a security update also happened around that time), and this fixed the issue-thanks for the tip.   Of course, the update broke some other things (not homebrew related), which is always the frustration with updates!
