### ISSUE TITLE
Cannot tap caskroom/cask: invalid syntax in tap!

### ISSUE THREAD

**Issue by Moep90** [Homebrew/homebrew-core#6973] opened 2016-11-16 14:02 UTC
`brew cask list
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3530, done.
remote: Compressing objects: 100% (3515/3515), done.
remote: Total 3530 (delta 31), reused 166 (delta 11), pack-reused 0
Receiving objects: 100% (3530/3530), 1.14 MiB | 1.12 MiB/s, done.
Resolving deltas: 100% (31/31), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/metagrowler.rb
undefined method cask for Formulary::FormulaNamespace0a3fc67eb7f20792f6a4ee633903a783:Module
Error: Cannot tap caskroom/cask: invalid syntax in tap!
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:226:in install
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in process
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in <top (required)>
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in require
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in require
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in require?
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in <main>
`
`brew doctor
Your system is ready to brew.`

`brew config
HOMEBREW_VERSION: 1.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: edf042ee97f80955b077724119e717a51eb25e29
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cb504bc93e5502d742ec4a9cda899906b1ac788f
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 7.3.1.0.1.1461711523
X11: N/A
`

**Comment by MikeMcQuaid** [comment] 2016-11-16 14:19
> If this doesn’t fix the problem, please report this bug:
> https://github.com/caskroom/homebrew-cask#reporting-bugs

Please follow this in future. Closing as duplicate of https://github.com/caskroom/homebrew-cask/issues/26815

**Closed by MikeMcQuaid** 2016-11-16 14:19 UTC

**Comment by Moep90** [comment] 2016-11-16 15:07
Anyways the problem was resolved after updating to MacOS Sierra.
