### ISSUE TITLE
openmpi failed to build on 10.11.6 https://gist.github.com/fa7d5c53e18796619a8e3d38e099176c

### ISSUE THREAD

**Issue by ivanlupelli** [Homebrew/homebrew-core#4476] opened 2016-09-03 12:47 UTC
Hello, 

I'm trying to build openmpi on El Capitain:

brew install openmpi --default-fortran-flags --c++11 --with-mpi-thread-multiple --build-from-source

I'm using the following compilers (not the home-brew standard):

export HOMEBREW_CC=gcc-6
export HOMEBREW_CXX=g++-6
export HOMEBREW_CPP=cpp-6
export HOMEBREW_LD=gcc-6
export HOMEBREW_FC=gfortran-6

The procedure fails at the make test set:

Last 15 lines from /Users/ivan/Library/Logs/Homebrew/open-mpi/03.make:
# PASS:  8
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
# 

See test/class/test-suite.log
# Please report to http://www.open-mpi.org/community/help/

make[4]: **\* [test-suite.log] Error 1
make[3]: **\* [check-TESTS] Error 2
make[2]: **\* [check-am] Error 2
make[1]: **\* [check-recursive] Error 1
make: **\* [check-recursive] Error 1

Thank you for the help
Ivan

**Comment by MikeMcQuaid** [comment] 2016-09-03 12:52
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by ivanlupelli** [comment] 2016-09-03 13:09
https://gist.github.com/9bbe5704b4e04630deca73d829bc4732

Is ok now? It is not clear to me what it is missing....Sorry.

Thank you for the help
Ivan

**Comment by MikeMcQuaid** [comment] 2016-09-03 14:10
Thanks, those logs will help. I strongly suspect the issue is specifying a custom compiler (which we don't support).

**Comment by ilovezfs** [comment] 2016-09-03 14:52
I ran through all the environment variables.
```
export HOMEBREW_CC=gcc-6
```
is the culprit for whatever reason. @ivanlupelli Can you try again with all of your settings except that one. It seems to be fine then.
```
unset HOMEBREW_CC
```

**Comment by ivanlupelli** [comment] 2016-09-03 15:39
Thank you guys,  HOMEBREW_CC was the problem. Is this valid variable or it is better to remove it from my environment?

**Comment by ivanlupelli** [comment] 2016-09-03 15:42
Another question. Now mpicc -v gives me the 

Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

And obviously means that open-mpi is compiled with llvm.

**Comment by ilovezfs** [comment] 2016-09-03 15:42
The variable is totally valid. I think basically what's happening is when you unset that variable, it's just building with clang in this case. This failure is reproducible simply by passing --cc=gcc-6 or --cc=gcc-5 and also affects 2.0.1. I'd like to know if it affects Linux too but I'm sure we'll eventually get to the bottom of it. Until then, I'd advise building this with the stock configuration since it's the only one known to work at the moment.

**Comment by ilovezfs** [comment] 2016-09-03 15:42
@ivanlupelli yep, you're right. See my comment above.

**Comment by ivanlupelli** [comment] 2016-09-03 15:48
Thank you @ilovezfs. Unfortunately I can't mix the compilers with my code  :(.

**Comment by ilovezfs** [comment] 2016-09-03 17:03
@ivanlupelli you have a couple of choices here. You can comment out
```
    system "make", "check"
```
changing it to
```
    # system "make", "check"
```
(or just delete the line), and hope that nothing is so broken that it actually affects your project.

Or, if you don't need open-mpi 2.0.x, and 1.10.3 is sufficient, I was able to build 1.10.3 just now with gcc-6 without running into this issue. You can do this:
```
cd /usr/local/Library/Taps/homebrew/homebrew-core
git checkout 5b1858d2b2f95299831971f551ef01408e6f142b -- Formula/open-mpi.rb
HOMEBREW_NO_AUTO_UPDATE=1 brew install -dvs --cc=gcc-6 open-mpi
brew pin open-mpi
git checkout origin/master -- Formula/open-mpi
```

**Comment by iltommi** [comment] 2016-09-06 13:05
Sorry to interfere, I run into the same problem on my yosemite.

I have a problem: I need to use a custom compiler (gcc-6) because the apple provided clang doesn't support threads.

My point was: you need an openmp-compiler to compile a program supporting mpi-threads hence you need a recent gcc.

Thanks a lot

**Comment by centaure** [comment] 2016-09-10 04:23
@ilovezfs I tried your second suggestion above (i.e. 1.10.3 with gcc-6). However, I got the error below during the install. I am on El Capitan (v10.11.5).

    g++-6 -DHAVE_CONFIG_H -I. -I../..  -I../../otflib -I../../otflib -I../../otfauxlib -DINSIDE_OPENMPI -  DINSIDE_OPENMPI -I/private/tmp/open-mpi-20160909-25875-n1913v/openmpi-  1.10.3/ompi/include -I/private/tmp/open-mpi-20160909-25875-n1913v/openmpi-  1.10.3/ompi/contrib/vt/vt/../../../include -I/private/tmp/open-mpi-20160909-25875-  n1913v/openmpi-1.10.3/ompi/contrib/vt/vt/../../../include  -g -O2 -c -o Stats.o Stats.cpp
    /bin/sh ../../libtool  --tag=CXX   --mode=link g++-6  -g -O2  -L/private/tmp/open-mpi-20160909-25875-n1913v/openmpi-1.10.3/ompi/.libs -L/private/tmp/open-mpi-20160909-25875-n1913v/openmpi-1.10.3/ompi/contrib/vt/vt/../../../.libs -o otfaux otfaux.o Control.o Handler.o Stats.o  ../../otfauxlib/libotfaux.la ../../otflib/libopen-trace-format.la  
    libtool: link: g++-6 -g -O2 -o .libs/otfaux otfaux.o Control.o Handler.o Stats.o  -L/private/tmp/open-   mpi-20160909-25875-n1913v/openmpi-1.10.3/ompi/.libs -L/private/tmp/open-mpi-20160909-    25875-n1913v/openmpi-1.10.3/ompi/contrib/vt/vt/../../../.libs ../../otfauxlib/.libs/libotfaux.dylib     ../../otflib/.libs/libopen-trace-format.dylib -lz
    Undefined symbols for architecture x86_64:
      "operator delete(void*, unsigned long)", referenced from:
          _main in otfaux.o
          Control::~Control() [clone .isra.202] in Control.o
    ld: symbol(s) not found for architecture x86_64
    collect2: error: ld returned 1 exit status
    make[9]: *** [otfaux] Error 1
    make[8]: *** [all-recursive] Error 1
    make[7]: *** [all-recursive] Error 1
    make[6]: *** [all] Error 2
    make[5]: *** [all-recursive] Error 1
    make[4]: *** [all-recursive] Error 1
    make[3]: *** [all] Error 2
    make[2]: *** [all-recursive] Error 1
    make[1]: *** [all-recursive] Error 1
    make: *** [all-recursive] Error 1
    /usr/local/Library/Homebrew/debrew.rb:11:in `raise'
    BuildError: Failed executing: make all
    1. raise
    2. ignore
    3. backtrace
    4. irb
    5. shell
    Choose an action:

**Comment by iltommi** [comment] 2016-09-10 05:38
Hello, I have a maybe dummy question: What's the point of compiling openmpi with threads using a compiler who does not support threads?

Is there any mpi+threads application which can be built this way?

Thanks

**Comment by MikeMcQuaid** [comment] 2017-03-19 16:26
Closing as there's no work ongoing on this issue, sorry.

**Closed by MikeMcQuaid** 2017-03-19 16:26 UTC
