### ISSUE TITLE
Python3 certificates not installed

### ISSUE THREAD

**Issue by jorgecarleitao** [Homebrew/homebrew-core#42198] opened 2019-07-19 22:33 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Part of the installation of Python is to run a specific command to install ssh certificates. This is necessary to e.g. use https connections when accessing URL's programatically. Official Python installation recommends this on the README (see also https://bugs.python.org/issue29065)

However, it seems that `python3` formula is not doing so (upon `brew install python3`), which is causing the user to not have the certificates installed. This problem affects many users, as inferred by the number of votes on [this StackOverflow question](https://stackoverflow.com/q/44649449/931303).

Steps to reproduce:

```
brew install python3
python -c 'from urllib.request import urlretrieve; urlretrieve("https://google.com")'
```

**Comment by jorgecarleitao** [comment] 2019-07-19 22:37
I have not added the information required because I have the official Python installation and do not want brew to overwrite it and potentially break my working python. Please check the relevant StackOverflow question, that contains a lot of evidence that people are being affected by this.

**Comment by SMillerDev** [comment] 2019-07-20 10:15
It seems nobody has taken the time to fix it yet. Could you add a line to run the command and a test to verify it works in a pull request?

**Comment by jorgecarleitao** [comment] 2019-07-23 20:55
@SMillerDev, could this be re-opened then? I may give it a shot, but,  regardless, it is important for it to be on the list of open issues, for others to know it has been fielded and acknowledged.

**Comment by bradleysepos** [comment] 2019-08-26 11:43
This affects HandBrake users who have installed Python 3 using `brew`. Given the official Python 3 installer seems to work fine, this would seem to be a Homebrew issue.

**Comment by fxcoudert** [comment] 2019-09-05 09:14
I cannot reproduce this issue:

```
rmeur ~ $ brew install python
==> Downloading https://homebrew.bintray.com/bottles/python-3.7.4.mojave.bottle.tar.gz
Already downloaded: /Users/fx/Library/Caches/Homebrew/downloads/ffcfe300e2ad205387a2bdd27185d98d64621578d26d2f6ccbbcd091ff799fc8--python-3.7.4.mojave.bottle.tar.gz
==> Pouring python-3.7.4.mojave.bottle.tar.gz
==> /usr/local/Cellar/python/3.7.4/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/3
==> /usr/local/Cellar/python/3.7.4/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/3
==> /usr/local/Cellar/python/3.7.4/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/3
==> Caveats
[…]
==> Summary
🍺  /usr/local/Cellar/python/3.7.4: 3,865 files, 60MB
rmeur ~ $ python3                                                                               
Python 3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlretrieve
>>> urlretrieve("https://google.com")
('/var/folders/h8/9hx_fyj91053ksgdzb2w03vw0000gp/T/tmpyyg256m1', <http.client.HTTPMessage object at 0x102d429d0>)
>>> 
```

**Comment by fxcoudert** [comment] 2019-09-05 09:36
> it is important for it to be on the list of open issues

We can only keep it open if full information is provided (which is why we have issue templates that should be filled). Otherwise, we do not know what we are looking at.

> This problem affects many users, as inferred by the number of votes on this StackOverflow question

Homebrew's python has 390,000 installs per month, and this issue has not previously been reported here. The stackoverflow question is about python 3.6.1.

---

Looking more into it, I cannot reproduce the issue even when blasting my whole `/usr/local/lib/python3.7` directory, reinstalling a fresh Python, with no preinstalled `site-packages`. Also, there is evidence that `certifi` is indeed installed as part of the `brew install python` process:

```
$ find /usr/local -name 'certifi*'
/usr/local/lib/python3.7/site-packages/pip/_vendor/certifi
/usr/local/Cellar/python/3.7.4/libexec/pip/build/lib/pip/_vendor/certifi
/usr/local/Cellar/python/3.7.4/libexec/pip/src/pip/_vendor/certifi
```

**Comment by fxcoudert** [comment] 2019-09-05 09:46
I'm going to close this, we welcome a full report in a new issue, linking to this one.

**Closed by fxcoudert** 2019-09-05 09:46 UTC

**Comment by andrew-linc** [comment] 2019-10-21 15:08
I am getting this issue on Python 3.7. I am running MongoDB, here is the error message:
ERROR:main.src.app.db.product_faq:{'message': 'Unknown exception in getting object from mongodb', 'error': ServerSelectionTimeoutError('cortex-dev-shard-00-00-x3hjr.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056),cortex-dev-shard-00-02-x3hjr.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056),cortex-dev-shard-00-01-x3hjr.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'), 'params': ['product_reference', 'jeans', 265]}
Traceback (most recent call last):
  File "/Users/aweiss/git/kontext/main/src/app/db/product_faq.py", line 86, in get_object
    return ProductFaq.objects.get(level=level, franchise_id=franchise_id, value=value)
  File "/Library/Python/3.7/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/Library/Python/3.7/site-packages/mongoengine/document.py", line 198, in _get_collection
    db = cls._get_db()
  File "/Library/Python/3.7/site-packages/mongoengine/document.py", line 176, in _get_db
    return get_db(cls._meta.get('db_alias', DEFAULT_CONNECTION_NAME))
  File "/Library/Python/3.7/site-packages/mongoengine/connection.py", line 342, in get_db
    db.authenticate(conn_settings['username'], conn_settings['password'], **auth_kwargs)
  File "/Library/Python/3.7/site-packages/pymongo/database.py", line 1471, in authenticate
    connect=True)
  File "/Library/Python/3.7/site-packages/pymongo/mongo_client.py", line 751, in _cache_credentials
    writable_preferred_server_selector)
  File "/Library/Python/3.7/site-packages/pymongo/topology.py", line 231, in select_server
    address))
  File "/Library/Python/3.7/site-packages/pymongo/topology.py", line 189, in select_servers
    selector, server_timeout, address)
  File "/Library/Python/3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))

**Comment by andrew-linc** [comment] 2019-10-21 15:09
find /usr/local -name 'certifi*'
/usr/local/lib/python3.7/site-packages/pip/_vendor/certifi
/usr/local/lib/python3.7/site-packages/certifi-2019.9.11.dist-info
/usr/local/lib/python3.7/site-packages/certifi
/usr/local/Cellar/python/3.7.4_1/libexec/pip/build/lib/pip/_vendor/certifi
/usr/local/Cellar/python/3.7.4_1/libexec/pip/src/pip/_vendor/certifi

Also, I am using Mac Catalina, don't know if that makes any difference.

**Comment by numbermaniac** [comment] 2019-12-07 14:06
I'm getting the same error, even after `certifi` is installed. No idea how to fix it :(

**Comment by robo-corg** [comment] 2019-12-10 19:00
I don't have a full repro but I have a fix: `brew reinstall openssl`. Read on for the details as best as I found them....

`brew config`

```
HOMEBREW_VERSION: 2.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2fe99bd9823fadea1cf918b1ed8366de7f40d336
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 72e30491cf94d0e1ed9bcb4d99d30421bc3b6c11
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.1-x86_64
CLT: 1100.0.33.12
Xcode: 11.2.1
```
This problem is confusing because I think ssl support in python3 is fragmented. If your package uses requests and you have certfi you are probbaly fine. If it uses plain old ssl or urlib.requests you are probably hitting this.

The ssl package gets its certs from paths presumably configured by openssl. However the openssl brew installed initially on my machine a couple weeks ago failed to install anything in  /usr/local/etc/openssl@1.1.

You can see if you are affected by this by running `import ssl; ssl.create_default_context().get_ca_certs()` to see if you are affected by this.

You can see where it gets its paths from with `import _ssl; _ssl.get_default_verify_paths()`
For me that returns:
```python
('SSL_CERT_FILE',
 '/usr/local/etc/openssl@1.1/cert.pem',
 'SSL_CERT_DIR',
 '/usr/local/etc/openssl@1.1/certs')
```

So to fix this I reinstalled openssl via `brew reinstall openssl`. This seemed to populate the /usr/local/etc/openssl@1.1/ directory. Another fix might be to manually copy some other certificate bundle into these paths but that doesn't really make sense since it looks like the openssl homebrew package is setup to do this normally.

My guess this was a bug in the cert bundle bootstrapping process or something like that during my initial install?
