### ISSUE TITLE
Error: Failed to download resource "tomcat@6" - The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by Gogetter** [Homebrew/homebrew-core#31976] opened 2018-09-11 05:10 UTC
- What you were trying to do (and why)
Trying to install a specific version of tomcat - tomcat 6
- What happened (include command output)
Ran ``brew install tomcat@6``
- What you expected to happen
Installation to run through as usual
- Step-by-step reproduction instructions (by running `brew install` commands)
  First, ran ``brew update`` 
  Then, ran ``brew search tomcat`` to confirm tomcat formula exists
  Then, ran  ``brew install tomcat@6``

- [ ] ran `brew update` and can still reproduce the problem?
`Already up-to-date.`
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
`Your system is ready to brew.`
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
`Error: No logs.`
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
**brew config**
```
HOMEBREW_VERSION: 1.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 61ace27006a1cb444552c0be10087fcbc3051643
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8719cd1fc7fe514cf5a8e56ff73ac78c7d7f5e98
Core tap last commit: 76 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1, 1.8.0_162
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```
**brew doctor**
`Your system is ready to brew.`

**Comment by fxcoudert** [comment] 2018-09-11 09:52
Thanks for the report, the issue is fixed in https://github.com/Homebrew/homebrew-core/commit/5dada9896f0fab1f0b7cc1db42c65caea0c5cdf4

**Closed by fxcoudert** 2018-09-11 09:52 UTC
