### ISSUE TITLE
Homebrew urls for packages returns SSL errors

### ISSUE THREAD

**Issue by vongohren** [Homebrew/homebrew-core#72172] opened 2021-02-28 17:11 UTC
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae41186696329fa3c039d4c30f2d727998d0a98e
Core tap last commit: 26 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2-x86_64
CLT: 12.0.32.27
Xcode: 12.2

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your user.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/snorre/.pyenv/shims/python3.6m-config
  /Users/snorre/.pyenv/shims/python-config
  /Users/snorre/.pyenv/shims/python3-config
  /Users/snorre/.pyenv/shims/python3.6-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.5.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2
  osgeo-gdal
  nss
  gettext
  osgeo-qt-webkit
  python@3.9

Warning: Your Xcode (12.2) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.

Warning: Use osgeo/osgeo4mac/osgeo-gdal instead of deprecated gdal2

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Im just trying to install and upgrade packages on my mac.
I also try to open packages url directly: https://homebrew.bintray.com/bottles/openssl1.1-1.1.1j.big_sur.bottle.tar.gz

Sorry I lied about brew doctor, but il close this if this is not relevant to anyone.

**What happened (include all command output)?**

==> Upgrading 1 outdated package:
openssl@1.1 1.1.1i -> 1.1.1j
==> Upgrading openssl@1.1 1.1.1i -> 1.1.1j
==> Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "openssl@1.1"
Download failed: https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_sur.bottle.tar.gz

All other packages below
------------------------------------------------------------------------------------------------------------------------
==> Upgrading openldap 2.4.51 -> 2.4.57
==> Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "openssl@1.1"
Download failed: https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_sur.bottle.tar.gz
==> Upgrading libiconv 1.15 -> 1.16
==> Downloading https://homebrew.bintray.com/bottles/libiconv-1.16.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "libiconv"
Download failed: https://homebrew.bintray.com/bottles/libiconv-1.16.big_sur.bottle.tar.gz
==> Upgrading flex 2.6.4 -> 2.6.4_1
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.21.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "gettext"
Download failed: https://homebrew.bintray.com/bottles/gettext-0.21.big_sur.bottle.tar.gz
==> Upgrading openblas 0.3.4 -> 0.3.13
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.2.1.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "gmp"
Download failed: https://homebrew.bintray.com/bottles/gmp-6.2.1.big_sur.bottle.tar.gz
==> Upgrading curl 7.63.0 -> 7.75.0
==> Downloading https://homebrew.bintray.com/bottles/brotli-1.0.9.big_sur.bottle.tar.gz
#=#=#
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "brotli"
Download failed: https://homebrew.bintray.com/bottles/brotli-1.0.9.big_sur.bottle.tar.gz
==> Upgrading openssl@1.1 1.1.1i -> 1.1.1j
==> Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "openssl@1.1"
Download failed: https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_sur.bottle.tar.gz
==> Upgrading bison 3.2.3 -> 3.7.5
==> Downloading https://homebrew.bintray.com/bottles/bison-3.7.5.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "bison"
Download failed: https://homebrew.bintray.com/bottles/bison-3.7.5.big_sur.bottle.tar.gz
==> Upgrading icu4c 67.1 -> 68.2
==> Downloading https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "icu4c"
Download failed: https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
==> Upgrading ruby 2.7.1_2 -> 3.0.0_1
==> Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "openssl@1.1"
Download failed: https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_sur.bottle.tar.gz
==> Upgrading qt 5.12.0 -> 5.15.2
==> Downloading https://homebrew.bintray.com/bottles/qt-5.15.2.big_sur.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "qt"
Download failed: https://homebrew.bintray.com/bottles/qt-5.15.2.big_sur.bottle.tar.gz
==> Upgrading osgeo/osgeo4mac/osgeo-pyqt-webkit 5.10.1 -> 5.13.2_2
Error: No available formula with the name "osgeo-sip" (dependency of osgeo/osgeo4mac/osgeo-pyqt-webkit).

------------------------------------------------------------------------------------------------------------------------

<img width="1039" alt="Screen Shot 2021-02-28 at 18 10 10" src="https://user-images.githubusercontent.com/1012055/109426968-75c6b200-79f0-11eb-9122-7bf474d21eef.png">
<img width="1680" alt="Screen Shot 2021-02-28 at 18 10 17" src="https://user-images.githubusercontent.com/1012055/109426969-78290c00-79f0-11eb-88ed-dfd0cf986337.png">

**What did you expect to happen?**

Upgrade the package and packages.
Even able to download the tar from the browser.
It also happened on alot of differnt other packages.

**Step-by-step reproduction instructions (by running `brew` commands)**

brew upgrade something

**Comment by carlocab** [comment] 2021-02-28 17:15
Duplicate of https://github.com/Homebrew/brew/issues/10739.

See also https://github.com/Homebrew/discussions/discussions/962, https://github.com/Homebrew/discussions/discussions/961.

**Closed by carlocab** 2021-02-28 17:15 UTC
Labels: bug
