### ISSUE TITLE
ocaml-findlib: bottle does not install necessary findlib.conf (build from source does)

### ISSUE THREAD

**Issue by Amar1729** [Homebrew/homebrew-core#51698] opened 2020-03-13 18:02 UTC
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [n/a] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [n/a] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install and use `ocaml-findlib`.

When installing `ocaml-findlib` from the provided bottles, install succeeds but does NOT install a config file `/usr/local/etc/findlib.conf` required for ocamlfind to work. This can be verified by running:

```
$ brew install ocaml-findlib
$ brew test ocaml-findlib
```

The test command will fail (output below). However:

```
$ brew install --build-from-source ocaml-findlib
$ brew test ocaml-findlib
```

will work.

I would submit a PR, but I'm not sure how exactly to fix this. (does the formula have to create `prefix/"etc"` explicitly?)

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ brew test ocaml-findlib  # after installing from bottle:
Testing ocaml-findlib
==> /usr/local/Cellar/ocaml-findlib/1.8.1_2/bin/ocamlfind query findlib
ocamlfind: Config file not found - neither /usr/local/etc/findlib.conf nor the directory /usr/local/etc/findlib.conf.d
Error: ocaml-findlib: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<2>.
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:55:in `block in assert_block'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1636:in `_wrap_assertion'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:53:in `assert_block'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:240:in `assert_equal'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:12:in `shell_output'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ocaml-findlib.rb:34:in `block in <class:OcamlFindlib>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1775:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1774:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:865:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1773:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2018:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2017:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1767:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:32:in `<main>'

$ ocamlfind printconf  # after installing from bottle
Effective configuration:
ocamlfind: Config file not found - neither /usr/local/etc/findlib.conf nor the directory /usr/local/etc/findlib.conf.d
  </pre>
</details>

## What you expected to happen

This is the output printed when built from source:
```
$ ocamlfind printconf

Effective configuration:
Configuration file:
    /usr/local/etc/findlib.conf
Search path:
    /usr/local/lib/ocaml
Packages will be installed in/removed from:
    /usr/local/lib/ocaml
META files will be installed in/removed from:
    the corresponding package directories
The standard library is assumed to reside in:
    /usr/local/lib/ocaml
The ld.conf file can be found here:
    /usr/local/lib/ocaml/ld.conf
```

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
# working INSTALL from bottle, fails on use:
$ brew install ocaml-findlib
$ ocamlfind printconf


# working from source:
$ brew install --build-from-source ocaml-findlib
$ ocamlfind printconf
```

**Comment by Bo98** [comment] 2020-03-13 18:31
Thanks. I will build a new bottle.

The problem is because during the CI run, `ocaml-findlib` was installed when testing OCaml dependents, but since it was revision bumped in the same pull request, it was later uninstalled and rebuilt in order to generate a bottle. However, `etc` and `var` files are not purged on uninstall and as such the bottle generator did not detect that there was a new `findlib.conf` - the file was already there prior to `install --build-bottle`.

I'm not sure what the best way to prevent this in the future will be. I'll get this specific bottle fixed in the meantime however since it will need to be anyway.

**Closed** 2020-03-15 03:15 UTC
