### ISSUE TITLE
ansible: switching to virtualenv broke local tasks that require python modules

### ISSUE THREAD

**Issue by pwnall** [Homebrew/homebrew-core#9337] opened 2017-01-27 17:28 UTC
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

When using a local connection (executing commands on the local host), Ansible seems to be using the system Python and Python search path. However, Ansible's modules are installed in a virtualenv. This breaks the use of modules that need non-standard python modules, such as most cloud management modules (EC2, OpenStack, etc.)

A minimal reproduction requires writing the following contents to `import_shade.py` in the current directory (which can be a temporary dir).
```python
#!/usr/bin/python
# coding: utf-8 -*-
import json
import shade

def main():
    module = AnsibleModule(argument_spec = dict())
    module.exit_json(changed=False, msg="Successfully imported shade")

from ansible.module_utils.basic import AnsibleModule
if __name__ == '__main__':
    main()
```

and then running the following command (`-vvv` is for diagnostics, can be removed):
```bash
ansible -M . -i localhost, -c local -m import_shade -vvv localhost
```

Interestingly, adding the following code to the formula's `test do` block does _not_ cause the tests to fail. (I made sure by adding a failing command, and checking the output logs at `Library/Logs/Homebrew/ansible/test.03.ansible`)

```ruby
    # Ensure Ansible uses the virtualenv when doing local commands.
    (testpath/"import_shade.py").write <<-EOF.undent
      #!/usr/bin/python
      # coding: utf-8 -*-
      import json
      import shade

      def main():
        module = AnsibleModule(argument_spec = dict())
        module.exit_json(changed=False, msg="Successfully imported shade")

      from ansible.module_utils.basic import AnsibleModule
      if __name__ == '__main__':
        main()
    EOF
    system bin/"ansible", "-M", testpath, "-i", "localhost,", "-c", "local", "-m", "import_shade", "localhost"
```

I am fairly sure that the bug was introduced when switching to virtualenv in commit d0cdc62f927610b632d08202843f226e732d2000 because the following Ansible install fails the repro steps above:
```bash
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/d0cdc62f927610b632d08202843f226e732d2000/Formula/ansible.rb
```

whereas the following Ansible install passes the steps.
```bash
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f61e92830ed4d1828dd46f2a4fcce5202130351a/Formula/ansible.rb
```

The latter hash is the previous commit in [ansible.rb's history](https://github.com/Homebrew/homebrew-core/commits/5727b4ec2cee4b7a72c6591fb04ef967b4af8281/Formula/ansible.rb).

brew config output:
```
HOMEBREW_VERSION: 1.1.8-59-gad4fd014e1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ad4fd014e1e558207d4eecdafe8667ecba5a8f51
Last commit: 16 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7f4699219264398e66283d45a7a14fce665ff73d
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/pwnall/.rbenv/shims/ruby => /Users/pwnall/.rbenv/versions/2.3.3/bin/ruby
Java: 1.8.0_102, 1.8.0_92, 1.7.0_79
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```
brew doctor output:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  wireshark
```

The formula does not fail to build (or test), hence skipping `brew gist-logs`.

**Comment by pwnall** [comment] 2017-01-27 17:44
I forgot to mention, this is what failing output looks like:

```
pwnage:tmp pwnall$ ansible -M . -i localhost, -c local -m import_shade -vvv localhost
No config file found; using defaults
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pwnall
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1485538746.17-52769464916331 `" && echo ansible-tmp-1485538746.17-52769464916331="` echo $HOME/.ansible/tmp/ansible-tmp-1485538746.17-52769464916331 `" ) && sleep 0'
<localhost> PUT /var/folders/c1/cm9q0cy146d_6ghrxpd_n8km0000gn/T/tmpnPy2ht TO /Users/pwnall/.ansible/tmp/ansible-tmp-1485538746.17-52769464916331/import_shade
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/pwnall/.ansible/tmp/ansible-tmp-1485538746.17-52769464916331/import_shade; rm -rf "/Users/pwnall/.ansible/tmp/ansible-tmp-1485538746.17-52769464916331/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/c1/cm9q0cy146d_6ghrxpd_n8km0000gn/T/ansible_WfO7F8/ansible_module_import_shade.py", line 4, in <module>
    import shade
ImportError: No module named shade

localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "import_shade"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/c1/cm9q0cy146d_6ghrxpd_n8km0000gn/T/ansible_WfO7F8/ansible_module_import_shade.py\", line 4, in <module>\n    import shade\nImportError: No module named shade\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
```

and this is what passing output looks like

```
pwnage:tmp pwnall$ ansible -M . -i localhost, -c local -m import_shade -vvv localhost
No config file found; using defaults
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pwnall
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1485538212.86-31075087661669 `" && echo ansible-tmp-1485538212.86-31075087661669="` echo $HOME/.ansible/tmp/ansible-tmp-1485538212.86-31075087661669 `" ) && sleep 0'
<localhost> PUT /var/folders/c1/cm9q0cy146d_6ghrxpd_n8km0000gn/T/tmphH3Vt_ TO /Users/pwnall/.ansible/tmp/ansible-tmp-1485538212.86-31075087661669/import_shade
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/pwnall/.ansible/tmp/ansible-tmp-1485538212.86-31075087661669/import_shade; rm -rf "/Users/pwnall/.ansible/tmp/ansible-tmp-1485538212.86-31075087661669/" > /dev/null 2>&1 && sleep 0'
localhost | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_args": {}, 
        "module_name": "import_shade"
    }, 
    "msg": "Successfully imported shade"
}
```

I'd guess that the pre-virtualenv solution works because of the PYTHONPATH wrappers.

**Comment by ilovezfs** [comment] 2017-01-27 17:57
CC @tdsmith

**Comment by tdsmith** [comment] 2017-01-27 18:10
> Ansible seems to be using the system Python

That seems inadvisable; perhaps that's something you can configure? I don't know if Ansible respects the shebangs you're setting but you might try using `#!/usr/bin/env python` instead.

It's not immediately obvious to me why it wouldn't fail in the test environment.

**Comment by pwnall** [comment] 2017-01-27 18:19
@tdsmith Ansible modules use the `#!/usr/bin/python` shebang. The file I wrote above mimics existing modules. It's highly unlikely that I'd be able to convince Ansible to change the way they write their modules. See [their documentation](http://docs.ansible.com/ansible/dev_guide/developing_modules.html#module-checklist)

People generally have their Ansible playbooks and configuration checked into a repository, so having to do Homebrew-specific tweaks is rather brittle.

**Comment by pwnall** [comment] 2017-01-27 18:20
Also, thank you very much for looking into this issue so promptly!

**Comment by tdsmith** [comment] 2017-01-27 18:27
I mean just glancing at that, that appears to be a restriction for modules which are shipped with Ansible and it appears to be a magical string that allows some hack to work to insert the name of the real interpreter. I have no idea if that ansible internal hack works on the script you're running or not; it is possible that it is not being applied and that using the python in PATH is what you need to do. But I don't know!

Looking further at the ansible documentation, ansible_python_interpreter is a thing you can configure in your inventory file: https://docs.ansible.com/ansible/intro_inventory.html

I don't think Homebrew is doing anything that needs to change; just as a datum, ansible is a pretty popular package and nobody's reported this before. It might be helpful to speak to people in the ansible community.

**Comment by pwnall** [comment] 2017-01-27 20:06
@tdsmith Sorry for being unclear, I was trying to explain why it wouldn't help to change the shebang in the module I submitted for reproducing the issue.

I ran into this issue while using my playbooks that involve Ansible's modules for configuring OpenStack. I put together a minimal module that imports `shade`, which is used by OpenStack, so developers working on this don't need access to an OpenStack instance to verify the bug and the fix.

Regarding other people not complaining about this -- FWIW, I use Ansible to bring up OpenStack clusters about twice a year. I am reporting this issue now because it wasn't there last time I tried to use Ansible. I have the package installed, so I probably count in the popularity metrics.

Last, I respectfully disagree about Homebrew's formula not having to change. The formula is responsible for setting up Ansible in such a way that it works, without the user having to know about special tricks that Homebrew uses. Asking the users to configure Ansible seems wrong -- if I have to bother to understand how Homebrew installs Ansible in order to use it, I have lost the value that Homebrew provides. At that point, I'm ready to install Ansible from source.

The PYTHONPATH wrappers used to accomplish this. The virtualenv method seems to need additional configuration. That configuration should be done by Homebrew, so Ansible is usable in the same way as if it was installed by a package manager on a Linux distribution.

**Comment by tdsmith** [comment] 2017-01-27 22:00
As it happens, the virtualenv encapsulation for Homebrew was developed specifically to work around problems folks were encountering using python3 scripts with Ansible caused by the PYTHONPATH specification; reverting is not benign.

I agree Homebrew should mostly work like Linux but OS X is not quite Linux and Homebrew is not quite e.g. Debian and some of those differences are important. The point about "no other complaints" was intended to represent my prior belief (in a Bayesian sense) that for most people, most of the time, we are doing a good job of delivering an Ansible package that doesn't cause surprises.

I don't have the ansible-specific knowledge to understand why your configuration is different and while I'm not uncurious I don't have bandwidth to troubleshoot this. I'd like the package to be useful but if you install it from source you won't hurt my feelings. :)

**Comment by MikeMcQuaid** [comment] 2017-01-29 16:25
I trust and defer to @tdsmith's Python knowledge here. If Ansible works worse for you now than it did before then that's unfortunate but the number of issues we've had since moving to the virtualenv approach has dramatically reduced so I don't see us backtracking there, sorry.

**Closed by MikeMcQuaid** 2017-01-29 16:25 UTC
Labels: python

**Comment by pwnall** [comment] 2017-01-30 00:24
FWIW, I wasn't necessarily advocating for reverting to the previous implementation. I'm sorry I was unclear and I made it seem like that.

I pointed out a problem with the current implementation, and pointed to the commit that reverted it. In my book, that's a good bug report -- I'm grateful when we receive reports like this in Chromium. I don't think that stating you want to stick with virtualenv and accepting the loss of functionality documented here as a legitimate bug are incompatible statements.

**Comment by tdsmith** [comment] 2017-01-30 01:25
> I don't think that stating you want to stick with virtualenv and accepting the loss of functionality documented here as a legitimate bug are incompatible statements.

Sure.

That said: I don't know how to help you, so I don't think leaving this open is productive unless you can point to a way we can improve something; sorry.
