### ISSUE TITLE
brew extract method does not seem to work for installing OpenSSL v1.0.2t

### ISSUE THREAD

**Issue by kensoh** [Homebrew/homebrew-core#47368] opened 2019-12-01 18:42 UTC
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**brew config**
```
HOMEBREW_VERSION: 2.2.0-32-gfcfa80a
ORIGIN: https://github.com/Homebrew/brew
HEAD: fcfa80a63a43bb0a54d57e818044798029d338f5
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4151f1d1692482dff266a80e78c3e2629c984166
Core tap last commit: 48 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: N/A
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_232, 1.8.0_211
macOS: 10.15.1-x86_64
CLT: N/A
Xcode: N/A
```

---

**brew doctor**
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3-config

Warning: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install
```

## What you were trying to do (and why)
I want to install OpenSSL v1.0, it's a dependency of a software that I use (PhantomJS, which is no longer maintained and thus not going to migrate to v1.1)

## What happened (include command output)
It seems that the recommended way to install older versions of a Homebrew formula (https://github.com/Homebrew/homebrew-core/pull/46876) is not working.

When the recommended way using brew extract is used as follows -

```
brew uninstall openssl
brew tap-new $USER/old-openssl
brew extract --version=1.0.2t openssl $USER/old-openssl
brew install openssl@1.0.2t
```

I get the errors below, which seems to be issue with Homebrew's incorrect mapping to the download URL, though the correct download URLs are extracted to the file -
```
/usr/local/Homebrew/Library/Taps/$USER/homebrew-old-openssl/Formula/openssl@1.0.2t.rb
```

```
==> Installing openssl@1.0.2t from $USER/old-openssl
==> Downloading https://homebrew.bintray.com/bottles-old-openssl/openssl@1.0.2t-1.0.2t.catalina.bottle.tar.gz
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "openssl@1.0.2t"
Download failed: https://homebrew.bintray.com/bottles-old-openssl/openssl@1.0.2t-1.0.2t.catalina.bottle.tar.gz
```

---

However, by tracing the Homebrew commit history, trying to `brew install below_url` -

https://raw.githubusercontent.com/Homebrew/homebrew-core/827dd8b591367bce6c8d128cd3c164f6319be2cd/Formula/openssl.rb

.. will lead to SHA checksum not matching error.

---

A solution that I found to be working, is manually update the checksum from the file generated by the `brew extract` method into the file in the GitHub URL above. Thus the file must be hosted somewhere else. A working solution seems to be below command. There is 2 uninstall commands to make sure any OpenSSL v1.1 is removed, and any dead v1.0 is removed, before installing v1.0.

```
brew uninstall openssl; brew uninstall openssl; brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
```

<details>
  <summary>Command output</summary>
  <pre>
  Command output as above, by using the extract command to download v1.0.2t to a local tap, when installing that version, Homebrew seems to be downloading from an invalid URL -

  ```
  ==> Downloading https://homebrew.bintray.com/bottles-old-openssl/openssl@1.0.2t-1.0.2t.catalina.bottle.tar.gz
  ```
  </pre>
</details>

## What you expected to happen
Expected output like below, which is the working solution from above workaround. Manually tweaking the historical openssl.rb with updated checksums and host it somewhere.

```
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2t.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/c9/c9c5e017edabe41ae55ed10ba5b94b834ee494e7f362d7245fbb0b137c876810?__gda_
######################################################################## 100.0%
==> Pouring openssl-1.0.2t.catalina.bottle.tar.gz
```

## Step-by-step reproduction instructions (by running `brew install` commands)

As above. Issue first noticed and raised here - https://github.com/kelaberetiv/TagUI/issues/635

**Comment by Bo98** [comment] 2019-12-01 18:47
You'll be missing the bottles but it should go on and download the source and build from that. Could you post the full output?

**Comment by kensoh** [comment] 2019-12-01 19:02
Thanks Bo for your quick reply! Indeed after the download failed, I got an error similar to above output saying that xcode is not available. Below is the output when I rerun.

Is it the expected behaviour that user has to install Xcode command line tools and to build from source for this scenario? I'm so sorry for my noob question.

I'm weighing between using the workaround above that works by updating the checksums into the openssl.rb found from the commit history and then hosting it somewhere, and finding a solution that is recommended and supported by Homebrew Team. Because I'm not expecting the users for the project that I'm working on to be developer savvy to install additional dependencies such as Xcode.

```
brew tap-new $USER/old-openssl
brew extract --version=1.0.2t openssl $USER/old-openssl
brew install openssl@1.0.2t
==> Created kensoh/old-openssl
/usr/local/Homebrew/Library/Taps/kensoh/homebrew-old-openssl
Tebel:tagui-python kensoh$ brew extract --version=1.0.2t openssl $USER/old-openssl
==> Searching repository history
==> Writing formula for openssl from revision 8b9d6d6 to /usr/local/Homebrew/Library/Taps/kensoh/homebrew-old-openssl/Form
Tebel:tagui-python kensoh$ brew install openssl@1.0.2t
==> Installing openssl@1.0.2t from kensoh/old-openssl
==> Downloading https://homebrew.bintray.com/bottles-old-openssl/openssl@1.0.2t-1.0.2t.catalina.bottle.tar.gz
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "openssl@1.0.2t"
Download failed: https://homebrew.bintray.com/bottles-old-openssl/openssl@1.0.2t-1.0.2t.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
Error: The following formula
  openssl@1.0.2t
cannot be installed as binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install
```

**Comment by Bo98** [comment] 2019-12-01 19:22
> I'm weighing between using the workaround above that works by updating the checksums into the openssl.rb

The commit you picked isn't the latest - it's the one just before the bottle blocks were updated for 1.0.2t. Not sure if that's because of `brew extract` or what - I haven't checked. However it's probably best anyway to generate your own bottles - this can be done locally or even be done in various CIs available (an example for Azure Pipelines is included in the tap when you do `brew tap-new`).

> finding a solution that is recommended and supported by Homebrew Team

Maintaining your own tap as you were initially looking to do is indeed the recommended approach.

> Because I'm not expecting the users for the project that I'm working on to be developer savvy to install additional dependencies such as Xcode.

Xcode or the Command Line Tools are indeed required to build from source - compilers etc aren't shipped with macOS by default. However I fully understand that you don't expect users to do the same. You may create your own bottles for users to install. You may opt to add `root_url` to the `bottle` block if the default Bintray URL doesn't match where you want users to download the bottle from. Brewsci/homebrew-bio is an example tap that does this.

**Comment by kensoh** [comment] 2019-12-01 19:31
Thanks Bo for your guidance above! 😄 

Let me chew on your advice and see what I can do to minimise user friction.

**Comment by Bo98** [comment] 2019-12-01 19:32
No problem.

I'll close this for now as it's not a bug but feel free to follow up here since I'll receive notifications.

**Closed by Bo98** 2019-12-01 19:32 UTC

**Comment by kensoh** [comment] 2019-12-11 12:17
Hi Bo, after weighing through, I decided to use the following solution. May I run through with you if you can share any quick thoughts if the solution is robust and sound? Thank you very much!

1. Get a copy of openssl.rb from commit history -
https://raw.githubusercontent.com/Homebrew/homebrew-core/827dd8b591367bce6c8d128cd3c164f6319be2cd/Formula/openssl.rb

2. Use brew extract method to get a copy of openssl@1.0.2t.rb to get the SHA checksums, and update those checksums into the openssl.rb from step 1.

3. Host the modified openssl.rb somewhere to allow users to easy install from that formula -
```
brew uninstall openssl; brew uninstall openssl; brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
```
&ensp;
This solution does not need users to install and build using Xcode from using the brew extract method, it also allows the SHA failure error to be solved if trying to use step 1 directly. Trying these 3 steps out, I found that the correct OpenSSL v1.0 is installed and the open-source app that I'm maintaining works.

And users can install OpenSSL v1.0 by just running the commands in step 3. From trial and error I found brew uninstall twice in step 3 can help remove existing v1.1 and any dead v1.0 before installing, this helps to resolves any edge cases for users without them having to do their own troubleshooting.

**Comment by kensoh** [comment] 2019-12-18 06:22
Hi Bo, pinging @Bo98 just in case no tagging of userid does not result in notification.

**Comment by khun84** [comment] 2020-01-13 14:34
> Hi Bo, after weighing through, I decided to use the following solution. May I run through with you if you can share any quick thoughts if the solution is robust and sound? Thank you very much!
> 
>     1. Get a copy of openssl.rb from commit history -
>        https://raw.githubusercontent.com/Homebrew/homebrew-core/827dd8b591367bce6c8d128cd3c164f6319be2cd/Formula/openssl.rb
> 
>     2. Use brew extract method to get a copy of [openssl@1.0.2t.rb](mailto:openssl@1.0.2t.rb) to get the SHA checksums, and update those checksums into the openssl.rb from step 1.
> 
>     3. Host the modified openssl.rb somewhere to allow users to easy install from that formula -
> 
> 
> ```
> brew uninstall openssl; brew uninstall openssl; brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
> ```
> 
>  
> This solution does not need users to install and build using Xcode from using the brew extract method, it also allows the SHA failure error to be solved if trying to use step 1 directly. Trying these 3 steps out, I found that the correct OpenSSL v1.0 is installed and the open-source app that I'm maintaining works.
> 
> And users can install OpenSSL v1.0 by just running the commands in step 3. From trial and error I found brew uninstall twice in step 3 can help remove existing v1.1 and any dead v1.0 before installing, this helps to resolves any edge cases for users without them having to do their own troubleshooting.

@kensoh Can you elaborate more on step 2 & step 3?

I managed to download the `openssl.rb` from Step 1. 

Can you show me the full command to get the checksum of Step 2?

As for Step 3, which checksums are you referring to that I need to replace? Is it **Line 92** (line number is from `openssl.rb` from Step 1)

Thanks in advance.

**Comment by kensoh** [comment] 2020-01-13 21:24
Hi @khun84 I didn't save the exact commands used. [This is the Homebrew doc](https://docs.brew.sh/Manpage#extract-options-formula-tap) I used to run the extract command. I think it is create a personal tap then extract to that tap. I googled and found some answer from https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

```
brew tap-new username/repo-name
# extract with a version seems to run a grep under the hood
brew extract --version='4.4.23' bash username/repo-name
brew install bash@4.4.23
# Note this "fails" when trying to grab a bottle for the package and seems to have
# some odd doubling of the version in that output, but this isn't fatal.
```

The SHA I replaced are those below -
```
    sha256 "c4a762d719c2be74ac686f1aafabb32f3c5d5ff3a98935c4925a1ddb9c750ee1" => :mojave
    sha256 "b72b8d9e582713d909936d7236542b366f07d800f8ec0eaa2d487a95c4e93bd9" => :high_sierra
    sha256 "e556bbb8902700cd3cb896e0635ccb517feb4e1266911840c4b3c9e9cd044f7e" => :sierra
```
You can refer to the output of step 3 to compare - https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
