### ISSUE TITLE
Postgres with postgis upgrade missing symbol

### ISSUE THREAD

**Issue by TAKeanice** [Homebrew/homebrew-core#40607] opened 2019-06-02 12:45 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

HOMEBREW_VERSION: 2.1.4-33-g7bcd70b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 7bcd70b29b04b31aa74929866c6d9f2e3479b1b9
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e7fb557b8ef41767946d0c6e611ed0e5e26a67b8
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1, 10.0.1, 1.8.0_92
macOS: 10.14.5-x86_64
CLT: N/A
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11

To help us debug your issue please explain:

- What you were trying to do (and why)

Upgrading my posgtgres + postgis installation with `brew upgrade postgres` and subsequent `brew postgresql-upgrade-database`

- What happened (include command output)

Eventually, after each step, `Upgrading postgresql data from 10 to 11 failed!`

- What you expected to happen

Have everything upgraded and ready to go with postgres 11

- Step-by-step reproduction instructions (by running `brew install` commands)

I will try to describe all problems and every step taken to fix them. Please excuse minor oversights.

1. Old postgres version was some 10.X. `brew upgrade postgres` installed version 11.X and also upgraded postgis (although I missed which version was installed before. I am pretty sure it was an older 2.5.X version)
2. As advised by the postgres information, I ran `brew postgresql-upgrade-database`.
3. First issue was that my database creation user was different from my current user. I fixed it by adding `"-U", "dbcreationusername",` after line `safe_system "#{bin}/pg_upgrade"` in `brew-postgresql-upgrade-database.rb` on my local machine. This should be added an option for the script, instead of just assuming the current user.
4. Next time the `postgresql-upgrade-database` failed due to the missing postgis installation for `postgresql@10`, which is installed temporarily during the upgrade. I fixed this by manually installing `postgresql@10` and then linking all relevant files from my current postgis installation, as described here: https://gist.github.com/gopperman/18cb66078372d3261420829630230b80. There was the caveat though, that some symlinks are relative, so copying was not always appropriate. Instead I manually had to link some files.
5. Now postgresql@10 is running again, however, when executing the query `alter extension postgis update`, the issue `Symbol not found: _AllocSetContextCreateExtended` arises. This also now happens when running the database upgrade procedure. So there is some incompatibility between the postgis build and postgresql or the OS. The complete part of the log describing the issue is the following:
```
pg_dump: [archiver (db)] query failed: ERROR:  could not load library "/usr/local/Cellar/postgresql@10/10.8/lib/postgis-2.5.so": dlopen(/usr/local/Cellar/postgresql@10/10.8/lib/postgis-2.5.so, 10): Symbol not found: _AllocSetContextCreateExtended
  Referenced from: /usr/local/Cellar/postgresql@10/10.8/lib/postgis-2.5.so
  Expected in: /usr/local/Cellar/postgresql@10/10.8/bin/postgres
 in /usr/local/Cellar/postgresql@10/10.8/lib/postgis-2.5.so
```

Issues 3 and 4 were solved with my described hacks. The last issue persists and I do not know what to do against it.

For reference: A similar observations as in 5. was described in the following issue:
https://github.com/Homebrew/homebrew-core/issues/36129
The very same symbol was missing here:
https://github.com/lib/pq/issues/816
Another similar thing arised here (but has been solved and backported 17 months ago):
https://trac.osgeo.org/postgis/ticket/3946

I also tried several versions of postgis as described here:
https://discourse.brew.sh/t/upgrade-postgresql-10-to-11-with-postgis-2-5/3690

**Comment by TAKeanice** [comment] 2019-06-03 08:10
Although not relevant, here the `brew doctor` output

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libao.4.dylib
  /usr/local/lib/libaspell.15.1.4.dylib
  /usr/local/lib/libblkid.2.0.dylib
  /usr/local/lib/libcom_err.1.1.dylib
  /usr/local/lib/libe2p.2.1.dylib
  /usr/local/lib/libext2fs.2.1.dylib
  /usr/local/lib/liblwgeom-2.3.0.dylib
  /usr/local/lib/libpspell.15.1.4.dylib
  /usr/local/lib/libss.1.0.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib
  /usr/local/lib/libuuid.1.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

```
Unexpected header files:
  /usr/local/include/aspell.h
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/graphviz/textpara.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/pspell/pspell.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libfreetype.la
  /usr/local/lib/liblwgeom.la
  /usr/local/lib/libpspell.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a
```

**Comment by SMillerDev** [comment] 2019-06-03 08:30
> First issue was that my database creation user was different from my current user. I fixed it by adding "-U", "dbcreationusername", after line safe_system "#{bin}/pg_upgrade" in brew-postgresql-upgrade-database.rb on my local machine. This should be added an option for the script, instead of just assuming the current user.

Multi-user setups aren't that common on macOS but pull requests are welcome.

> Next time the postgresql-upgrade-database failed due to the missing postgis installation for postgresql@10, which is installed temporarily during the upgrade. I fixed this by manually installing postgresql@10 and then linking all relevant files from my current postgis installation, as described here: https://gist.github.com/gopperman/18cb66078372d3261420829630230b80. There was the caveat though, that some symlinks are relative, so copying was not always appropriate. Instead I manually had to link some files.
> Now postgresql@10 is running again, however, when executing the query alter extension postgis update, the issue Symbol not found: _AllocSetContextCreateExtended arises. This also now happens when running the database upgrade procedure. So there is some incompatibility between the postgis build and postgresql or the OS.

That's a pretty old gist. From what I can tell from the error here it seems like the version of postgis you're linking is build for a version with different symbols. I'd probably go with installing postgis without brew instead of symlinking the pg@11 version and see if that fixes things.

**Comment by TAKeanice** [comment] 2019-06-03 10:30
> That's a pretty old gist. From what I can tell from the error here it seems like the version of postgis you're linking is build for a version with different symbols. I'd probably go with installing postgis without brew instead of symlinking the pg@11 version and see if that fixes things.

Thanks for the advice. I will try installing postgis without brew and report. The gist, although it is old, helped me in that it listed all the places where postgis installation has to be symlinked, and linking itself works. But yes, since postgis is linking to wrong symbols it is not working afterwards.

**Comment by TAKeanice** [comment] 2019-06-03 11:21
So the manual compile and install for postgis just installs it to the current version of postgres (11.3) instead of my postgresql@10 keg. I had to unlink the current version of postgres and `brew link --force postgres@10`. Now at least the `postgresql@10` installation works again. I tried linking the old version previously with the brew installation of postgis, but it did not have the same effect.

**Comment by iMichka** [comment] 2019-11-25 18:22
@TAKeanice What is the status here? Can we close this? Is there any action on our side that needs to be handled.

**Comment by TAKeanice** [comment] 2019-11-26 21:15
I am not sure about the current status, because I haven´t tried upgrading again to not endanger my working environment for my thesis. I am not planning on repeating the procedure in near future. I am fine if you want to close it.

**Closed** 2019-11-26 21:26 UTC
Labels: needs response

**Comment by Bo98** [comment] 2019-11-26 21:30
Postgis upgrades are tricky to automate. Postgis 3.x improve this by excluding the minor version from their libraries. Unfortunately, there's still that upgrade to postgis 3.0 to deal with...

Slightly tempted to just provide an option to put you into a shell mid-upgrade to deal with Postgis. I'll need to think about it more - though the problem is probably not going to resurface upon the next postgis update.

**Comment by TAKeanice** [comment] 2019-11-27 06:58
The mid-update shell is a good idea I think, I recently installed several enterprise programs which do the same with a short warning before that the process should be followed through.
