### ISSUE TITLE
rust build-from-source failures

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#57305] opened 2020-07-02 16:21 UTC
10.15
```
 Error: 1 failed steps!
 brew install --build-from-source mgba
```

10.14
```
 Error: 1 failed steps!
 brew install --build-from-source mgba
```

10.13
```
 Error: 4 failed steps!
 brew install --build-from-source gjs
 brew install --build-from-source mgba
 brew install --build-from-source opencv@3
 brew install --build-from-source sonic
```

relates to #57118

**Comment by chenrui333** [comment] 2020-07-02 16:24
mgba 0.8.2 upgrade effort, #56319

**Comment by chenrui333** [comment] 2020-07-26 17:29
rust 1.14.5 PR: https://github.com/Homebrew/homebrew-core/pull/58166

failed on `mgba` and `minidlna`
brew install --build-from-source mgba
brew test --verbose minidlna

**Comment by bayandin** [comment] 2020-09-01 11:09
From `rust` 1.46.0 (https://github.com/Homebrew/homebrew-core/pull/60290):

- `brew install --build-from-source komposition`: looks similar to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968729, if so it requires to update `gi-pango` in upstream (I suppose)
```
GI/Pango/Objects/Font.hs:670:9: error:
    parse error on input ‘HarfBuzz.FeatureT.feature_t’
    |
670 |     Ptr HarfBuzz.FeatureT.feature_t ->      -- features : TCArray False (-1) 2 (TInterface (Name {namespace = "HarfBuzz", name = "feature_t"}))
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build gi-pango-1.0.22 (which is required by exe:komposition
from komposition-0.2.0 and exe:komposition-split from komposition-0.2.0). See
the build log above for details.
```
- `brew install --build-from-source visp`: one of the dependencies (`pcl`) doesn't support the latest `boost` (could be fixed with `pcl` update https://github.com/Homebrew/homebrew-core/pull/59146)
- `brew install --build-from-source opencv@3` (on 10.13 only): can't reproduce it locally yet, but the error already happen with previous rust updates https://github.com/Homebrew/homebrew-core/issues/57305#issue-650058492

**Comment by fxcoudert** [comment] 2020-10-06 11:04
Current status:
- `komposition` still problematic
- `opencv@3` is 10.13-only, and not reproducible
- `visp` was rebuilt on 2020-09-08, so apparently not a problem anymore
- `minidlna` fix was committed

**Comment by fxcoudert** [comment] 2020-10-13 06:40
Current rust build-from-source failures: https://github.com/Homebrew/homebrew-core/pull/62694

```
brew install --build-from-source findomain
brew install --build-from-source komposition
brew install --build-from-source mdbook
brew install --build-from-source spotifyd
```

```
==> Downloading https://github.com/Edu4rdSHL/findomain/archive/2.1.4.tar.gz
Error: SHA256 mismatch
Expected: e669e5297c3112ec4e256bef286028220dcb9d46cd8a31e6965cbbc3d2ae3199
  Actual: dd193f3b2d81b05769efbf2a2c7af7479395617204343c84fb5d7e1b0bec9d83
 Archive: /Users/brew/Library/Caches/Homebrew/downloads/b305afe0193306feb5636bdfcf789ee80af6826907d26baea5a8b7b26de0c570--Findomain-2.1.4.tar.gz
```

```
Unknown GIR element "docsection" when processing namespace "GLib", aborting.
CallStack (from HasCallStack):
  error, called at lib/Data/GI/CodeGen/API.hs:199:16 in hskll-g-0.23.1-5232f4d8:Data.GI.CodeGen.API
cabal: Failed to build gi-glib-2.0.23 (which is required by
exe:komposition-split from komposition-0.2.0 and exe:komposition from
komposition-0.2.0). See the build log above for details.
```

```
==> Downloading https://github.com/rust-lang/mdBook/archive/v0.4.3.tar.gz
Error: SHA256 mismatch
Expected: e1a60eb877a95c6cf8832cb158a8f09b2d641206fe853378905bcdb962902935
  Actual: 3a3c4da76ff47943dbd5d490567a3d283cf85889f16d4d96ae04328371c1a817
```

```
  thread 'main' panicked at 'unable to generate bindings: ()', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/coreaudio-sys-0.2.3/build.rs:100:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `spotifyd v0.2.24 (/private/tmp/spotifyd-20201012-73267-11hoo7e/spotifyd-0.2.24)`, intermediate artifacts can be found at `/private/tmp/spotifyd-20201012-73267-11hoo7e/spotifyd-0.2.24/target`
```

**Comment by fxcoudert** [comment] 2020-10-20 11:38
Latest status from https://github.com/Homebrew/homebrew-core/pull/62998 :

- `findomain`, `mdbook`, `nushell`: source checksum mismatch
- `komposition` failed to build gi-glib-2.0.23

**Comment by fxcoudert** [comment] 2020-11-24 17:20
Between Big Sur bottling, and the upcoming ARM bottling, we'll have plenty of opportunity to track these build-from-source failures. Keeping a separate tracking bug does not seem useful at the moment.

**Closed by fxcoudert** 2020-11-24 17:20 UTC
Labels: rust
