### ISSUE TITLE
git send-email fails with "out-of-date IO::Socket::SSL"

### ISSUE THREAD

**Issue by mephi42** [Homebrew/homebrew-core#24210] opened 2018-02-16 14:20 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/anonymous/bd4cb56c536c2d20d6e66397b82460b4

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I'm trying to use git send-email. In order to circumvent Net::SNMP::SSL issue I installed git with `--with-perl` flag, as indicated in https://github.com/Homebrew/homebrew-core/issues/12870

- What happened (include command output)
```
Not using SSL_VERIFY_PEER due to out-of-date IO::Socket::SSL.
To use SSL please install IO::Socket::SSL with version>=2.007 at /usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/Net/SMTP.pm line 270.
```
- What you expected to happen
It should have succeeded.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install git --with-perl
cd <any-git-repo> && git send-email --to=<yourself> HEAD^
```

**Comment by a3f** [comment] 2018-02-20 00:12
Did you try to update `IO::Socket::SSL`? `perl -MCPAN -e 'install "IO::Socket::SSL"'`

**Comment by mephi42** [comment] 2018-02-20 00:33
Thanks! I then got `Need MIME::Base64 and Authen::SASL todo auth at /usr/local/Cellar/git/2.16.1/libexec/git-core/git-send-email line 1455`, and fixed it the same way. The command now works.

The question is, shouldn't homebrew handle this out of the box?

**Comment by a3f** [comment] 2018-02-20 00:36
That I don't know. The Perl module name just caught my eye while creating a pull request ^^.

**Comment by ilovezfs** [comment] 2018-02-21 11:05
@DomT4 hmm is this a regression? I have déjà vu.

**Comment by DomT4** [comment] 2018-02-21 15:43
I can't reproduce it locally:

```
~> git send-email --to=myself@gmail.com HEAD^

/var/folders/qs/rg1v7kz56wv3v9z4qwgtv3g80000gn/T/c4MHzs1ATz/0001-cask-move_back-copy-delete.patch
/var/folders/qs/rg1v7kz56wv3v9z4qwgtv3g80000gn/T/c4MHzs1ATz/0002-backing-up.patch
(mbox) Adding cc: commitay <commitay@users.noreply.github.com> from line 'From: commitay <commitay@users.noreply.github.com>'

OK. Log says:
Sendmail: /usr/sbin/sendmail -i myself@gmail.com commitay@users.noreply.github.com
From: Dominyk Tiller <myself@gmail.com>
To: myself@gmail.com
Cc: commitay <commitay@users.noreply.github.com>
Subject: [PATCH 1/2] cask move_back: copy / delete
Date: Wed, 21 Feb 2018 15:39:18 +0000
Message-Id: <20180221153919.94507-1-myself@gmail.com>
X-Mailer: git-send-email 2.16.2

Result: OK
```

Truncated that a bit but essentially doesn't blow up with Perl errors. I build git with the following, FWIW:

```
--with-persistent-https --with-pcre2 --with-gettext --with-openssl --with-curl --with-perl
```

**Comment by ilovezfs** [comment] 2018-02-21 16:47
Closing this out since we cannot reproduce the problem.

**Closed by ilovezfs** 2018-02-21 16:47 UTC

**Comment by DomT4** [comment] 2018-02-21 17:03
I'll try and take a deeper look if multiple people can reproduce it, because it should work out of the box every time, but either way this wouldn't be a regression of the original issue.
