### ISSUE TITLE
Control-r (search command history) doesn't work in Python@3.11

### ISSUE THREAD

**Issue by kinghuang** [Homebrew/homebrew-core#118869] opened 2022-12-24 16:50 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

**brew config:**

```shell
HOMEBREW_VERSION: 3.6.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 740f9ddcc620d4812770a0f12854ddd79c643874
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7ffa9b10af106c4d45567c0d3a2eec853811564a
Core tap last commit: 28 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

**brew doctor:**

```
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I recently starting using `python@3.11` for my own projects. The Python 3.11 REPL (i.e., running `python3.11`) doesn't seem to work with control-r (`⌃r`) for searching history. The python installed with `python@3.10` and `python@3.9` do.

I see that the python@3.11 formula has an extra flag to use editline for readline (`--with-readline=editline`), while the previous formulas did not do this. I think this has something to do with it.

https://github.com/Homebrew/homebrew-core/blob/7ffa9b10af106c4d45567c0d3a2eec853811564a/Formula/python%403.11.rb#L134-L137

https://github.com/Homebrew/homebrew-core/blob/7ffa9b10af106c4d45567c0d3a2eec853811564a/Formula/python%403.10.rb#L146-L149

https://github.com/Homebrew/homebrew-core/blob/7ffa9b10af106c4d45567c0d3a2eec853811564a/Formula/python%403.9.rb#L122-L125

### What happened (include all command output)?

Pressing control-r in the Python 3.11 REPL doesn't do anything.

```
Python 3.11.0 (main, Oct 25 2022, 13:57:33) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

### What did you expect to happen?

Pressing control-r in the Python 3.10 or 3.9 REPLs starts a history search.

```
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(reverse-i-search)`': 
```

```
Python 3.9.16 (main, Dec  7 2022, 10:06:04) 
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(reverse-i-search)`': 
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install python@3.11
python
(press control-r)
```

**Comment by Bo98** [comment] 2022-12-24 18:14
Python 3.11 is now follows the same configuration what most other macOS tools use (including Apple's Python).

You might be missing a `bind "^R" em-inc-search-prev` from your `~/.editrc`.

**Comment by carlocab** [comment] 2022-12-25 07:20
I wonder if we can/should provide an `etc/"editrc"` that can replicate `readline` configuration using `libedit`.

**Comment by milosivanovic** [comment] 2022-12-26 01:49
What's the fix here? Adding `bind "^R" em-inc-search-prev` to my `~/.editrc` (which did not exist) did not revert to the 3.10 reverse-i-search behaviour.

**Comment by milosivanovic** [comment] 2022-12-26 01:54
Was there a reason this configure parameter was changed? It should favour readline if readline is installed.

**Comment by milosivanovic** [comment] 2022-12-26 02:26
For context, a primary use case I use brew for is to get as far away as possible from BSD/macOS utilities as I prefer a Linux command-line environment (I replace most tools with their GNU equivalents.) So unfortunately, this change directly conflicts with what I'm used to and what I've come to love brew for.

Given that brew's Python 3.11 doesn't fully link its executables (i.e. isn't the default python version in brew yet), it's likely that there are others who would feel the same way but aren't aware of this upcoming change as they are still using 3.10. Were there any reports of users who preferred the "same configuration that most other macOS tools use", or was this just a change to make Python more in-line with the default OS utilities?

I hope we can come to a resolution that allows users who prefer GNU readline to continue being able to use it as it has been the default for as long as I've been using brew.

**Comment by SMillerDev** [comment] 2022-12-26 15:08
> For context, my primary use case for brew is to help me get as far away as possible from BSD/macOS utilities as I prefer a Linux command-line environment (I replace most tools with their GNU equivalents.) So unfortunately, this change directly conflicts with what I'm used to and what I've come to love brew for.

Brew actually uses system versions of tools whenever possible to avoid unnecessary dependencies so your goals and brews are diagonally opposed here.

**Comment by milosivanovic** [comment] 2022-12-26 19:08
Was it not possible to use editline earlier? Why was this change made only now? There are still packages that depend on readline. Similarly, I am sure that brew's Python 3.8 could be built against the system LibreSSL and yet it still pulls in OpenSSL 1.1 (as do many other packages.)

My main gripe is that editline just doesn't seem to be working consistently across different programs that use it. With the previously-mentioned binding added to `~/.editrc`, when I run `/opt/homebrew/opt/python@3.11/libexec/bin/python3` and press `CTRL+R` to do a history search, I have to press `CTRL+C` three times to send a KeyboardInterrupt. When I do this same test with `/usr/bin/irb`, pressing `CTRL+C` in the middle of a history search ends the search the first time and correctly sends a ^C.

Additionally, when in any editline REPL, when I press `CTRL+R` to enter history mode and then use the arrow keys to move the cursor and edit the line, it inserts the control character for the arrow key that was pressed instead of actually moving the cursor.

Below is a screen recording showing these findings with keypresses shown in the bottom right.

https://user-images.githubusercontent.com/1274505/209576216-5632dc91-36b4-4b0e-9346-1090e25103fa.mov

If there's any way the brew team would consider reverting to use readline (since the cost of the dependency is minimal and is likely to already be installed since it is still a common dependency across brew packages), that would be greatly appreciated. I hope other brew users can chime in with their thoughts as well.

If the direction that brew is heading in really is to drop support of readline wherever possible (which I really hope is not the case), it would be extremely helpful to provide a way to replicate the readline configuration like @carlocab hinted earlier.

**Comment by kinghuang** [comment] 2022-12-27 05:04
I'm willing to adapt to editline, but I also cannot get it to work properly like @milosivanovic has described. With the homebrew Python 3.11 and the aforementioned editline config, I get weird characters inserted when I use the arrow keys and other anomalies.

Does the system zsh shell count as a macOS tool? It's where I use control-r the most, and it appears to use readline, not editline. It's not clear to me why editline is preferred here.

**Comment by cho-m** [comment] 2022-12-27 16:00
You can see the reasoning in the `python@3.11` PR https://github.com/Homebrew/homebrew-core/pull/113811#issue-1419568255.

> There are two areas of concern that I'm hoping to address:
> 
> 1. Parity with how Apple and Python themselves ship Python. Even MacPorts.
> 2. Legality of the effect of GPL dependencies on dependents, given how widespread our Python is now being used. Notably we can't exactly legally ship anything that might have been using readline or gdbm with something that uses GPL-2.0-only or OpenSSL 1.1.

**Comment by MikeMcQuaid** [comment] 2022-12-27 21:06
Paging @Bo98 to help out here when he gets the chance 🙇🏻

**Comment by dtrodrigues** [comment] 2022-12-29 22:35
Given that this is the same behavior that Apple's and CPython's (https://www.python.org/downloads/macos/) python exhibits since they're also use editline, I'd suggest reporting this to  CPython: https://github.com/python/cpython/issues/new/choose.

**Comment by milosivanovic** [comment] 2022-12-29 23:48
As I've mentioned before, there are many packages in brew that still use readline. The [PR that removed readline](https://github.com/Homebrew/homebrew-core/pull/113811#issue-1419568255) even suggested that there are bugs/incompatibilities with editline and that removing readline is not critical. An alternative was suggested which was to look at other ways to audit the potential licensing issues, meaning that building against GNU readline might not be an issue if enough time is spent to figure that out. I'd be happy to help with this if the team is, as evidently shown in the PR, open to going down that path.

macOS's super old bash that they still ship with has readline, just that [it's statically linked](https://superuser.com/a/1450272):

```
milos@pro:~$ which bash
/opt/homebrew/bin/bash
milos@pro:~$ echo $BASH_VERSION
5.2.15(1)-release
milos@pro:~$ /bin/bash
milos@pro:~$ echo $BASH_VERSION
3.2.57(1)-release
[press CTRL+R]
(reverse-i-search)`':
```

If macOS is able to statically link an older readline to seemingly avoid licensing issues, could we do the same here?

**Comment by Bo98** [comment] 2022-12-30 02:28
(Expect respones to be a little slow and probably a bit briefer/blunter because of the holiday period - sorry!)

> I wonder if we can/should provide an `etc/"editrc"` that can replicate `readline` configuration using `libedit`.

Will require patching for this to work.

> Python 3.8 could be built against the system LibreSSL

No it can't. There are no headers offered to link against system LibreSSL. The only system SSL library Apple allow is their own, which we use in curl etc that support it.

> My main gripe is that editline just doesn't seem to be working consistently across different programs that use it. With the previously-mentioned binding added to `~/.editrc`, when I run `/opt/homebrew/opt/python@3.11/libexec/bin/python3` and press `CTRL+R` to do a history search, I have to press `CTRL+C` three times to send a KeyboardInterrupt. When I do this same test with `/usr/bin/irb`, pressing `CTRL+C` in the middle of a history search ends the search the first time and correctly sends a ^C.

This does seem like a Python-specific inconsistency with signal handling - thanks for the upstream report about that. But do note that the standard way to exit search mode (ESC key) works fine so this is a `Ctrl+C` specific issue.

> Additionally, when in any editline REPL, when I press CTRL+R to enter history mode and then use the arrow keys to move the cursor and edit the line, it inserts the control character for the arrow key that was pressed instead of actually moving the cursor.

Again, the documented exit command key (ESC) works. I do sympathise that's perhaps confusing in this particular case. Given this one doesn't appear Python-specific, I'll check if it's Apple specific or if it exists with upstream `libedit` too.

> The https://github.com/Homebrew/homebrew-core/pull/113811#issue-1419568255 suggested that there are bugs/incompatibilities with editline

Bugs and incompatibilities are not the same thing - and there's no mention of bugs there. The incompatibilities were actually largely caused by us using readline unlike everyone else. If you use a readline-based Python your history will become corrupt if you later run Apple's or upstream Python. This has routinely happened to me over the years. This problem doesn't happen if we use editline.

I'm monitoring to see if there's any issues when we convert packages to use Python 3.11. In the two months so far, only one has been identified in emacs but the issue is on emacs' side and I'll have a patch out for that very soon.

> The given alternative was to look at other ways to audit the potential licensing issues, meaning that building against GNU readline might not be an issue if enough time is spent to figure that out.

Making sure every single package that uses Python is GPL-compliant and deleting everything that isn't seems a massive effort just for slightly different REPL behaviour?

I appreciate that the sudden change in behaviour is not ideal (shipping readline in the past was perhaps a mistake in hindsight) and I tried alternatives to begin with. The compromise I offered was to not backport this change to any earlier version of Python so that any transition is not forced if you want to stick with 3.10 for a bit (note that we do allow you to pick your own `python3` now).

I disagree that libedit is "broken". I agree it perhaps behaves less intuitively in the case of arrow keys and the default binds, but there's nothing that's been demonstrated to me yet that's serious enough that means we need to start doing extreme things like shipping ancient versions or dropping OpenSSL support or dropping GPL-incompatible packages from Homebrew.

> macOS's super old bash that they still ship with has readline, just that [it's statically linked](https://superuser.com/a/1450272):

I don't agree that Apple's model of sticking with aging software is something people should be following.

If the differing keybinds are unbearable to work with, it does seem installing `gnureadline` on a per-user basis seems best. After the change was merged I very closely followed for any user reports about any issues. - it has taken 2 months for the first report of this to come through. During this time, our Python 3.11 has been installed ~670,000 times with at least ~35,000 of that being an explicit `brew install python@3.11` on the command line (as opposed to it being pulled in by some dependency or mass install). The only thing else I recall is one email asking for details about `.editrc` and that user is happy with how the REPL is working once they sorted out the bind command.

**Comment by SMillerDev** [comment] 2022-12-30 07:57
> But I would like to focus this discussion on the removal of readline and what it would take to get it back.

Only a significant amount of issue reports and a change in packaging by upstream and Apple would get us to change this.

**Comment by milosivanovic** [comment] 2022-12-30 09:27
@Bo98 thanks a lot for your detailed response and for covering all my questions. I do understand the reason for wishing to move to editline, and I appreciate your sympathetic tone since this change will likely cause a few bumps for some.

> Again, the documented exit command key (ESC) works. I do sympathise that's perhaps confusing in this particular case. Given this one doesn't appear Python-specific, I'll check if it's Apple specific or if it exists with upstream libedit too.

While using the escape key to first exit editline's history mode might "work", arrow key control characters showing instead of the cursor moving definitely feels like a bug to me. (When I mentioned bugs/incompatibilities, I conflated the bugs I found with the incompatibilities you listed.) This particular bug is likely an editline issue, so I could report that to them and hear their rationale and/or if they would be willing to adapt that to work similarly to the way readline did.

Other weird bugs include what happens after pressing enter: In the Python REPL with readline, it would execute the line immediately. In the Python REPL with editline, pressing enter just exits history mode and now you have to press enter again if you want to actually run the command. On the other hand, `/usr/bin/irb` executes the line immediately after pressing enter even with editline. Do you think this is another Python-specific bug that I should report? (I'm worried how many other bugs like this exist...)

I'm already seeing another bug which I'm not sure how to reproduce reliably, but this is what happened several times after trying to execute a REPL line with a syntax error (or other error):
```
>>> [something from editline history with a syntax error]
object address  : 0x102a6b2e0
object refcount : 2
object type     : 0x1030d5b28
object type name: SyntaxError
object repr     : SyntaxError('multiple statements found while compiling a single statement', ('<stdin>', 1, 125, "...", 1, 125))
lost sys.stderr
```

Python says it `lost sys.stderr` and so the output of the Python error is some internal output instead of the expected one. All of this was discovered with extremely minimal, basic usage of editline in Python 3.11. I haven't even tried using this as a "daily driver" yet because I keep running into deterrants like this.

@SMillerDev Respectfully, that seems like a hard stance to take given [the PR](https://github.com/Homebrew/homebrew-core/pull/113811) says...
> I'm opening this to discuss changes that I've proposed to be made to Python 3.11. These don't have to happen if people disagree.

...and ends with...

> We don't have to do these changes

I am doing my best to be flexible by working with this new proposal/change, reporting issues to Python and now possibly editline as well, so I would appreciate flexibility from your side as this issue develops so that we can find the best possible solution, which may include reintroducing readline in some form. If there is no flexibility, then I am confused with the wording in the aforementioned PR.

> During this time, our Python 3.11 has been installed ~680,000 times with at least ~35,000 of that being an explicit brew install python@3.11 on the command line (as opposed to it being pulled in by some dependency or mass install).

Since Python 3.11 is not default in brew right now, people end up using Python 3.10 even if they installed 3.11, since they discover a few of their projects' dependencies still don't work with 3.11 (that was the case for me.) It will therefore take more time for people to notice bugs or comment on changes relating to Python 3.11.

> If the differing keybinds are unbearable to work with, it does seem installing gnureadline from PyPI on a per-user basis seems best.

I have already [reported the build issue](https://github.com/ludwigschwardt/python-gnureadline/issues/62) to the `gnureadline` maintainer who now has this on their radar and will try to get `gnureadline` working for 3.11. It looks like a promising solution for those who want to keep using readline.

I definitely understand the reason for moving to editline, but it does seem like the road will be a bumpy one. Personally, I'm at the very least least hoping to find a way to get CTRL+R to work as similarly as before, and without the random bugs I mentioned above. That being said, this is certainly not just about what I think so I am looking forward to seeing further comments from the community and how they feel about the changes once the adoption increases.

**Comment by SMillerDev** [comment] 2022-12-30 09:50
> Respectfully, that seems like a hard stance to take given https://github.com/Homebrew/homebrew-core/pull/113811 says...

I realise what it says, but the changes did happen and moving back and forth is only going to make matters worse for everyone. I realise you don't like the change, but the bugs you encounter are essentially the state all python installs are in since we were the only one using a different dependency for this. Reporting bugs upstream is a good solution, reverting Homebrew to be the only macOS build that does things differently from upstreams defaults is not.

**Comment by jamesjames1122** [comment] 2023-01-11 04:03
command

**Comment by milosivanovic** [comment] 2023-02-02 00:03
Commenting to keep this issue open.

**Comment by MikeMcQuaid** [comment] 2023-02-02 10:21
We'll review PRs to improve this but am not planning on fixing it.

**Closed by MikeMcQuaid** 2023-02-02 10:21 UTC
Labels: upstream issue, user configuration
