### ISSUE TITLE
Python or GTK crash after upgrade to Sierra

### ISSUE THREAD

**Issue by brechtm** [Homebrew/homebrew-core#8022] opened 2016-12-19 15:17 UTC
I was using a brew-installed Python 2.7 and PyGTK to run [Zim](http://zim-wiki.org). Something broke after upgrading macOS to Sierra. I'm not sure how to debug this, but I'll provide as much information as I can.

To make sure nothing stayed behind that linked to El Capitan libs, I uninstalled and reinstalled python, gtk, pygtk etc. I also did a `brew upgrade`.

Running zim (`/usr/local/bin/python zim.py`) pops up a dialog:

> **Python quit unexpectedly.**
> Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple.

With the buttons *Ignore*, *Report...* and *Reopen*

Here is the report: [report.txt](https://github.com/Homebrew/homebrew-core/files/661377/report.txt)

Running `/usr/local/bin/python -m trace --trace zim.p` stops at (displaying the dialog):

```
...
socket.py(202):             setattr(self, method, dummy)
socket.py(201):         for method in _delegate_methods:
socket.py(202):             setattr(self, method, dummy)
socket.py(201):         for method in _delegate_methods:
socket.py(202):             setattr(self, method, dummy)
socket.py(201):         for method in _delegate_methods:
connection.py(323):     return conn
connection.py(171):     if authkey is not None and not isinstance(authkey, bytes):
connection.py(174):     if authkey is not None:
connection.py(178):     return c
ipc.py(764): 			conn.send(msg)
ipc.py(765): 			if not msg.async:
ipc.py(766): 				re = conn.recv()
```

At this point I can Ctrl-C, and the python interpreter seems to continue and process the KeyboardInterrupt exception.

[brew_doctor.txt](https://github.com/Homebrew/homebrew-core/files/661384/brew_doctor.txt)
[brew_config.txt](https://github.com/Homebrew/homebrew-core/files/661382/brew_config.txt)

**Comment by MikeMcQuaid** [comment] 2016-12-25 20:37
@tdsmith Any ideas/help debugging this would be 🙇

**Comment by tdsmith** [comment] 2016-12-26 04:55
The crash is in glib; no special insight. It looks like 2.7.12 is linked but 2.7.13 is being executed; maybe try `brew unlink python && brew link --overwrite python && brew switch python 2.7.13`?

**Comment by brechtm** [comment] 2016-12-26 08:48
`brew unlink python && brew link --overwrite python && brew switch python 2.7.13` does not solve the problem.

Could this have something to do with a pyenv-installed python being active while building brew packages? I ran into trouble because of that before. That's why I uninstalled python, gtk, pygtk etc., making sure the python was the Homebrew-provided one. But perhaps I missed some?

brew should perhaps check that the python in the PATH is the Homebrew-provided one and abort or at least warn?

**Comment by tdsmith** [comment] 2016-12-27 21:37
It shouldn't; that should be supported.

I'll close this because I don't think we can help and it's not obvious to me that it's a Homebrew bug. If you collect any more information I'd be happy to take a look.

**Closed by tdsmith** 2016-12-27 21:37 UTC
Labels: python

**Comment by brechtm** [comment] 2017-02-10 13:03
I tried `brew upgrade`, but it didn't help

I can see the Zim window popping up very briefly, before the Python crash dialog appears.

Any pointers as to how I can start to debug this?

**Comment by brechtm** [comment] 2017-02-10 13:31
Running `python zim.py --standalone` seems to work. I'll ask the Zim developer to shine his light on this.

**Comment by Kreisleriana** [comment] 2017-02-17 11:07
I can confirm that the --standalone flag solved the issue that brechtm described. 
Python no longer crashes when starting Zim after updating macOS to Sierra. 
In addition to that I also had to fix the locale on two Macs, which appear to have been damaged in the course of the update.
