### ISSUE TITLE
Irssi

### ISSUE THREAD

**Issue by angaron** [Homebrew/homebrew-core#29835] opened 2018-07-07 07:38 UTC
When building Irssi from source (macOS 10.14 and 10.13) it doesn't support Perl scripting so no plugin will work, this do not occur when installing from keg (macOS 10.13).

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran `brew update` and can still reproduce the problem?
Yes.
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 10.14.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Ruby version 2.3.7 is unsupported on 10.14. Homebrew
is developed and tested on Ruby 2.3.3, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
```
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
`Error: No logs.`

To help us debug your issue please explain:
- What you were trying to do (and why)

Install irssi with perl support.

- What happened (include command output)

Building from source doesn't have perl support.

- What you expected to happen

To have perl support like in keg.

- Step-by-step reproduction instructions (by running `brew install` commands)

I'm doing only brew install irssi.

Brew Config:

```
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 07928a16f14b94d2574553eec82c6fa7b5a2f387
Core tap last commit: 23 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_INSECURE_REDIRECT: 1
HOMEBREW_VISUAL: vim
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1530455945
CLT headers: 10.0.0.0.1.1530455945
Xcode: 10.0 => /Applications/Xcode-beta.app/Contents/Developer
XQuartz: N/A
```

**Comment by ilovezfs** [comment] 2018-07-07 07:40
brew config? brew doctor? brew gist-logs irssi?

Also, what are commands to test the perl support?

**Comment by angaron** [comment] 2018-07-07 08:46
I've updated my comment. To see if Perl support is in Irssi you need to open it and write /load perl it will show you that there is no Perl module loaded. In fact homebrew version of irssi doesn't have any modules...

```
Irssi: Error loading module perl/core:      dlopen(/usr/local/Cellar/irssi/1.1.1/lib/irssi/modules/libperl_core.so, 10): image not found
```

**Comment by angaron** [comment] 2018-07-07 08:57
Probably this is the problem: 

```ruby
    if build.with? "perl"
      args << "--with-perl=yes"
      args << "--with-perl-lib=#{lib}/perl5/site_perl"
    else
      args << "--with-perl=no"
    end
```

There is an option to build without Perl support   `option "without-perl", "Build without perl support"
`, but I'm not using it, just plain old `brew install irssi`. Because of using unsupported macOS 10.14 everything is build from source and this is where the problem shows up.

**Comment by DomT4** [comment] 2018-07-07 17:53
IIRC there are some issues with Perl on 10.14 currently.

**Comment by angaron** [comment] 2018-07-07 18:29
Same issue is when building with `--HEAD` on High Sierra.

**Comment by DomT4** [comment] 2018-07-07 19:52
```
checking for library containing setupterm... -lncurses
checking for working Perl support... error linking with perl libraries, building without Perl
...

Building with Perl support ....... : NO!
 - Error linking with perl libraries: -fstack-protector -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl: conftest.c:1:10: fatal error: 'EXTERN.h' file not found
#include <EXTERN.h>
         ^~~~~~~~~~
1 error generated.
```

That's the error on 10.14. Interestingly that file does indeed not exist at that location on 10.14 but does currently exist in the CLT in the expected place: `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/EXTERN.h`.

**Comment by DomT4** [comment] 2018-07-07 19:54
> I have same issue when building with --HEAD on High Sierra.

Can't reproduce this one though.

**Comment by angaron** [comment] 2018-07-07 20:39
Maybe on High Sierra it's a bug associated with Xcode beta? Either way it works fine. I will try to test it further and report with more details. :)

**Comment by ilovezfs** [comment] 2018-07-09 09:44
Closing as this is a 10.14 issue, which we don't support yet.

**Closed by ilovezfs** 2018-07-09 09:44 UTC
