### ISSUE TITLE
Error: unknown version :x86_64_linux during install 

### ISSUE THREAD

**Issue by gcamp** [Homebrew/homebrew-core#33541] opened 2018-10-31 04:15 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

=======

Installation of lp_solve (from brewsci) fails at the moment. Issue is in this repo because the recipe didn't change for months but other issues (like https://github.com/Homebrew/homebrew-core/issues/33304) seems to point out that changes to core might have caused this. 

Logs during installation : 
```
==> Installing lp_solve from brewsci/science
Error: unknown version :x86_64_linux
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:23:in `block in from_symbol'
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:22:in `fetch'
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:22:in `from_symbol'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:60:in `block in find_older_compatible_tag'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `find'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `find_older_compatible_tag'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:31:in `find_matching_tag'
/usr/local/Homebrew/Library/Homebrew/utils/bottles.rb:94:in `fetch_checksum_for'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:381:in `checksum_for'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:368:in `tag?'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:96:in `bottled?'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `bottled?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:92:in `pour_bottle?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:469:in `expand_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:381:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:142:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:135:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:324:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:256:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

brew config : https://gist.github.com/gcamp/41831105a1b60bdea484c95fbe91d3be
brew doctor : https://gist.github.com/gcamp/f70f39fe041b38cb859234ce480a093b
recipe file : https://github.com/brewsci/homebrew-science/blob/master/Formula/lp_solve.rb

**Comment by MikeMcQuaid** [comment] 2018-10-31 09:34
Duplicate of https://github.com/Homebrew/homebrew-core/issues/33304.

**Closed by MikeMcQuaid** 2018-10-31 09:34 UTC

**Comment by MikeMcQuaid** [comment] 2018-10-31 09:41
This is now fixed, please `brew update`.
