### ISSUE TITLE
Broken Bash completion for *poetry*

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#113711] opened 2022-10-21 15:35 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

Output of `brew config`
```shell
HOMEBREW_VERSION: >=2.5.0 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: (none)
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open -a Firefox.app
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.jAXNwUkjFX/org.xquartz:0
HOMEBREW_EDITOR: mate_wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.38.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: 13.4.1
Rosetta 2: false
```

Output of `brew doctor`
```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  subliminal

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/alex/.cargo/bin/cargo-install-update-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/BandedSmithWaterman.h
  /usr/local/include/BedReader.h
  /usr/local/include/Fasta.h
  /usr/local/include/IndelAllele.h
  /usr/local/include/IntervalTree.h
  /usr/local/include/LargeFileSupport.h
  /usr/local/include/LeftAlign.h
  /usr/local/include/Mosaik.h
  /usr/local/include/Region.h
  /usr/local/include/Repeats.h
  /usr/local/include/SmithWatermanGotoh.h
  /usr/local/include/Variant.h
  /usr/local/include/disorder.h
  /usr/local/include/filevercmp.h
  /usr/local/include/join.h
  /usr/local/include/makeUnique.h
  /usr/local/include/mt19937ar.h
  /usr/local/include/multichoose.h
  /usr/local/include/multipermute.h
  /usr/local/include/vec128int.h
  /usr/local/include/veclib_types.h
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem. (Actually no, but warnings are unavoidable and clearly not relevant to issue!)

### What were you trying to do (and why)?

Use tab-completion for Poetry (installed as part of formula).

### What happened (include all command output)?

Open new Bash shell. The following is output.
```shell
-bash: /opt/homebrew/etc/bash_completion.d/poetry: line 40: syntax error near unexpected token `clear'
-bash: /opt/homebrew/etc/bash_completion.d/poetry: line 40: `            (cache clear)'
```

### What did you expect to happen?

No error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install poetry
# Then just open a new Bash shell and observe the error message, per above.
```

**Comment by bayandin** [comment] 2022-10-21 15:57
Duplicate of #111924

**Closed by bayandin** 2022-10-21 15:57 UTC
Labels: bug
