### ISSUE TITLE
zsh 5.4.2 aborting on some commands

### ISSUE THREAD

**Issue by justinkim** [Homebrew/homebrew-core#18400] opened 2017-09-21 20:35 UTC
- [x] `brew update` up to date
- [x] `brew doctor` clean
- [x] `brew gist-logs zsh` [gist](https://gist.github.com/anonymous/65afabe3c8b2adb63ac758a1e4fe34c7)

---

Earlier today, the zsh formula was updated to 5.4.2. ([commit](https://github.com/Homebrew/homebrew-core/commit/121d1eda94edbda8e083dc998db503312f6108f8), [bottles](https://github.com/Homebrew/homebrew-core/commit/c16aefd128e137f4b3d1d6d9c6126c67e9745353))

After a `brew update` and `brew upgrade` today, my `zsh` was exiting immediately on startup. I tracked the problem down to [a line in oh-my-zsh's gitfast plugin](https://github.com/robbyrussell/oh-my-zsh/blob/d848c94804918138375041a9f800f401bec12068/plugins/gitfast/git-prompt.sh#L99).

Running the command above manually with `zsh -x`, I get the following ([gist](https://gist.github.com/justinkim/b5ddb92ba575ee0a599165aa58e3ced9)):

```
$ printf -v __git_printf_supports_v -- '%s'
<snip>
+zsh:2> printf -v __git_printf_supports_v -- %s
dyld: lazy symbol binding failed: Symbol not found: _open_memstream
  Referenced from: /usr/local/bin/zsh
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _open_memstream
  Referenced from: /usr/local/bin/zsh
  Expected in: /usr/lib/libSystem.B.dylib

[1]    63774 abort      zsh -x
```

I'm on the latest Command Line Tools for Xcode (9.0) and Xcode (9.0). This occurs whether zsh is poured or built from source.

---

Steps to reproduce:
* `brew install zsh` (version 5.4.2)
* `zsh`
* `printf -v -- ''` or `printf -v bupkis -- '%s'`
* zsh aborts

---

If I can provide any additional info, please let me know.

**Comment by jballanc** [comment] 2017-09-22 13:41
Just want to echo that I've seen identical behavior, but in my case it was caused by `source`ing the `git-prompt.sh` bash completion script (which also contains a number of calls to `printf -v ...`).

**Comment by ilovezfs** [comment] 2017-09-22 14:12
This should be fixed by https://github.com/Homebrew/homebrew-core/pull/18426.

**Closed** 2017-09-22 14:25 UTC
Labels: open_memstream

**Comment by justinkim** [comment] 2017-09-22 14:26
Thanks very much for the quick fix! Really appreciate it.

**Comment by ilovezfs** [comment] 2017-09-22 14:46
@justinkim you're welcome!
