### ISSUE TITLE
Go 1.7rc5 and 10.12

### ISSUE THREAD

**Issue by okket** [Homebrew/homebrew-core#3665] opened 2016-08-06 08:02 UTC
Many thanks for the Go bootstrap rewrite that makes it easy to install 1.7rc5 with `brew install go --devel`. But all formulas that depend on Go (docker, syncthing...) still require stable and fail to install like this:

```
→ brew install syncthing
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
go: This formula either does not compile or function as expected on OS X
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

Even when Go 1.7rc5 is successfully installed. 

I can understand that this is minor edge case that will soon fix itself when stable versions are released, so this should probably not get fixed. ~~I am perfectly ok to live with my quick, stupid hack to make things work on 10.12: Switch "stable" and "devel" labels in the `go.rb` formula.~~ (better solution further down)

To illustrate how stupid this hack is, why nobody in their right mind should ever do this or run beta software at all: "godep" complained on one 10.12 machine about not finding dependencies, but worked nicely on another, under exact the same circumstances/versions/etc. Reinstalling godep fixed this problem.

**Comment by ilovezfs** [comment] 2016-08-06 10:31
>Error: An unsatisfied requirement failed this build.

Since the devel spec does not specify that requirement, I think this may be a general `brew` bug having nothing to do with `go` or 10.12 per se. Likely the requirement checking code needs to be consulting the "tab" (i.e., INSTALL_RECEIPT.json) to check if the requirement actually applies to the installed version or not.

**Comment by ilovezfs** [comment] 2016-08-06 10:55
@okket a fairly awful workaround is to pass `--ignore-dependencies --std=env` after the other dependencies besides go are already installed.

**Comment by okket** [comment] 2016-08-06 11:08
Thanks, worked with`---ignore-dependencies --env=std` 👍

**Comment by ilovezfs** [comment] 2016-08-06 12:10
@okket you can try this diff if you'd like:
```
diff --git a/Library/Homebrew/requirement.rb b/Library/Homebrew/requirement.rb
index 7a40d41..b22f177 100644
--- a/Library/Homebrew/requirement.rb
+++ b/Library/Homebrew/requirement.rb
@@ -198,7 +198,20 @@ class Requirement
       formulae.unshift(dependent)
 
       formulae.each do |f|
-        f.requirements.each do |req|
+        if f.installed? && f.installed_version.version > f.version
+          spec = Tab.for_keg(f.installed_prefix).spec
+          puts "#{f} is über qualified: #{spec}"
+          spec_requirements =  if spec == :devel
+            f.devel.requirements
+          elsif spec == :head
+            f.head.requirements
+          else
+            f.requirements
+          end
+        else
+          spec_requirements = f.requirements
+        end
+        spec_requirements.each do |req|
           if prune?(f, req, &block)
             next
           else
```

**Comment by okket** [comment] 2016-08-06 12:27
Seems to work,  freshly ```brew install go --devel``` and then just ```brew install docker``` with applied patch. Some additional output:

```
→ brew install docker
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
go is über qualified: devel
go is über qualified: devel
go is über qualified: devel
==> Cloning https://github.com/docker/docker.git
[...]
🍺  /usr/local/Cellar/docker/1.12.0: 10 files, 10.7M, built in 18 seconds
```

**Comment by ilovezfs** [comment] 2016-08-06 12:37
@okket cool. It's definitely not perfect for several reasons, the most important one being that it's still expanding the dependencies and requirements based on the stable spec's list of dependencies not the devel spec's, but it should be sufficient for this particular use case.

**Comment by DomT4** [comment] 2016-08-06 14:07
>  But all formulas that depend on Go (docker, syncthing...) still require stable and fail to install like this:

Yeah, this is a bug. `--devel` should satisfy other formulae just fine. I'm almost sure this _used_ to work, unless my memory is failing me.

**Comment by ilovezfs** [comment] 2016-08-06 14:17
@DomT4 should this be reopened as an issue in https://github.com/Homebrew/brew/issues/ since it actually has nothing to do specifically with `go` or `:sierra` or `homebrew/core`?

**Comment by DomT4** [comment] 2016-08-06 14:19
Yeah, probably. It's not something specific to `go`or this repo. If we're seeing it here theoretically it'll be something that's knocking around the whole ecosystem.

I am almost certain we didn't have this issue last year.

**Comment by ilovezfs** [comment] 2016-08-06 14:22
@DomT4 Yeah, it would be pretty :cry: if this is now considered "works as designed"/"won't fix"

**Comment by ilovezfs** [comment] 2016-08-08 12:35
Closing this since it's works-as-designed.

**Closed by ilovezfs** 2016-08-08 12:35 UTC
Labels: bug
