### ISSUE TITLE
Error: undefined method `exist?' for nil:NilClass

### ISSUE THREAD

**Issue by ahmetcetin** [Homebrew/homebrew-core#9391] opened 2017-01-28 21:06 UTC
Tried to install python. apparently i had already 2.7.13 installed, brew have warning that python-2.7.13 already installed. and the following error output:

Error: undefined method `exist?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/tab.rb:338:in `write'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:104:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:104:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by MikeMcQuaid** [comment] 2017-01-29 16:57
> http://docs.brew.sh/Troubleshooting.html

Please read this.

**Comment by alexch** [comment] 2017-02-03 13:51
I am getting the same error when doing `brew install coreutils` (which happens to break `rvm install 2.3`, but it happens when running `brew install` on its own too.)

@MikeMcQuaid What part of Troubleshooting.html are you referring to? I read it and performed all the troubleshooting steps and am still getting that bug. 

Bug started happening on El Capitan, survived the upgrade to Sierra (10.12.3).

```
$ brew install coreutils 
Error: undefined method `exist?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/tab.rb:338:in `write'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:104:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:104:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

The line of code in question is 
```
    Formula.clear_installed_formulae_cache unless tabfile.exist?
```
which has nothing to do with a particular formula; instead the `tabfile` var is nil. 

Frustratingly, even if I comment that line out, brew replaces it on the fly ("`Updating Homebrew...`") then (un)helpfully tells me 

```
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
```
which doesn't survive since `brew install` immediately re-un-restores the changes.


```
$ brew config
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d22470fe6bd34f6bde024b028bc1ee224b3fecc8
Core tap last commit: 46 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.4.6 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/alex/.rvm/rubies/ruby-2.2.4/bin/ruby
Java: 1.7.0_55
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: N/A
X11: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment] 2017-02-03 15:01
> @MikeMcQuaid What part of Troubleshooting.html are you referring to?

I needed `brew config` and `brew doctor` output, thanks.

Thanks for the backtrace, I'll take a look at this (or @alyssais could beat me to it).

**Comment by alyssais** [comment] 2017-02-03 15:22
> I'll take a look at this (or @alyssais could beat me to it).

Always up for a challenge ;)

I've had a quick look into it, and it looks like the install receipt isn't being created for some reason (which later causes errors when Homebrew assumes that it exists).

**Comment by alyssais** [comment] 2017-02-03 15:30
My guess to the cause is that there are existing installs that are just very old, so they don't have install receipts.

Here's a quick reproduce:

1. `brew install hello`
2. `rm $(brew --prefix hello)/INSTALL_RECEIPT.json`
3. `brew install hello`

And [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/install.rb#L188-L194) is the problematic code.

**Comment by alyssais** [comment] 2017-02-03 15:34
@MikeMcQuaid I guess it's up to you how you want to handle this. I think you have two options:

- Create a stripped-down install receipt when running `brew install` on a formula that was already installed but lacked an install receipt. We couldn't create a full receipt because build options, etc. have been lost in the sands of time, but you could just store the `installed_on_request` etc. values.

  I'd be hesitant to do this, though, because having incomplete install receipts floating around seems like it could cause all sorts of problems.

- Don't attempt to store `installed_on_request` etc for kegs that are so old they don't have install receipts.

  This would be much easier, and this case will diminish over time as installs are upgraded and install receipts are created for them.

**Comment by alexch** [comment] 2017-02-03 18:36
Awesome! Now that I understand the issue, I found a workaround:

```
brew uninstall coreutils
brew install coreutils
```

@ahmetcetin try `brew uninstall python; brew install python` and see how that goes.

**Comment by MikeMcQuaid** [comment] 2017-02-10 15:11
> Don't attempt to store installed_on_request etc for kegs that are so old they don't have install receipts.
> 
> This would be much easier, and this case will diminish over time as installs are upgraded and install receipts are created for them.

This is the right approach I think 👍

**Comment by ilovezfs** [comment] 2017-02-19 10:16
Closing since this is not actually a homebrew/core issue.

@alyssais is there a corresponding brew issue/PR for this yet?

**Closed by ilovezfs** 2017-02-19 10:16 UTC

**Comment by alyssais** [comment] 2017-02-19 12:35
@ilovezfs Don't think so.

**Comment by nimbusLiQuid** [comment] 2017-03-06 01:38
Thank you, brew uninstall hello; brew install hello;  that is exactly the perfect solution.
