### ISSUE TITLE
sqlite in python is not available on apple m1

### ISSUE THREAD

**Issue by Cat7373** [Homebrew/homebrew-core#68281] opened 2021-01-04 08:18 UTC
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Use sqlite3 in python.

## What happened (include command output)
```
cat73@Cats-MacBook-Pro ~> /opt/homebrew/opt/python@3.9/bin/python3.9
Python 3.9.1 (default, Jan  5 2021, 09:10:27) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
>>> exit()
```

## What you expected to happen
```
cat73@Cats-MacBook-Pro ~> /usr/bin/python3
Python 3.8.2 (default, Nov  4 2020, 21:23:28) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> exit()
```

## Step-by-step reproduction instructions (by running `brew` commands)
```
brew install -s python@3.9
/opt/homebrew/opt/python@3.9/bin/python3.9
import sqlite3
```

## Output of `brew config` and `brew doctor` commands
<pre>
cat73@Cats-MacBook-Pro ~> brew config
HOMEBREW_VERSION: 2.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdb71a5cb3029da2ef74d7e09c40575bbfb4ec72
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ad6fd898d478d011330946a97cda8ff335e44ae6
Core tap last commit: 9 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.271.09, 1.8.0_271
macOS: 11.2-arm64
CLT: N/A
Xcode: 12.3
Rosetta 2: false
cat73@Cats-MacBook-Pro ~> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libecpg.6.dylib
  /usr/local/lib/libecpg_compat.3.dylib
  /usr/local/lib/libpgtypes.3.dylib
  /usr/local/lib/libpq.5.dylib
</pre>

**Comment by carlocab** [comment] 2021-01-05 01:17
One of these might be causing your problem:
```
macOS: 11.2-arm64
CLT: N/A
```
Does `brew test python@3.9` also produce errors?

**Comment by Cat7373** [comment] 2021-01-05 01:18
> One of these might be causing your problem:
> 
> ```
> macOS: 11.2-arm64
> CLT: N/A
> ```
> 
> Does `brew test python@3.9` also produce errors?

```
cat73@Cats-MacBook-Pro ~> brew test python@3.9
==> Testing python@3.9
==> /opt/homebrew/Cellar/python@3.9/3.9.1_4/bin/python3.9 -c import sqlite3
Last 15 lines from /Users/cat73/Library/Logs/Homebrew/python@3.9/test.01.python3.9:
2021-01-05 09:18:11 +0800

/opt/homebrew/Cellar/python@3.9/3.9.1_4/bin/python3.9
-c
import sqlite3

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
Error: python@3.9: failed
An exception occurred within a child process:
  BuildError: Failed executing: /opt/homebrew/Cellar/python@3.9/3.9.1_4/bin/python3.9 -c import\ sqlite3
/opt/homebrew/Library/Homebrew/formula.rb:2096:in `block in system'
/opt/homebrew/Library/Homebrew/formula.rb:2032:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:2032:in `system'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.9.rb:386:in `block in <class:PythonAT39>'
/opt/homebrew/Library/Homebrew/formula.rb:1900:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/utils.rb:530:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1899:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:904:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1898:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2145:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:1892:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:42:in `<main>'
```

**Comment by carlocab** [comment] 2021-01-05 01:19
What does `brew info sqlite` say?

**Comment by Cat7373** [comment] 2021-01-05 01:20
I have been using XCode to develop apps

I thought the Command line tool was already installed

Wait a minute, I will try to install it

**Comment by Cat7373** [comment] 2021-01-05 01:21
> brew info sqlite

```
cat73@Cats-MacBook-Pro ~> brew info sqlite
sqlite: stable 3.34.0 (bottled) [keg-only]
Command-line interface for SQLite
https://sqlite.org/
/opt/homebrew/Cellar/sqlite/3.34.0 (11 files, 4.2MB)
  Poured from bottle on 2020-12-08 at 19:52:23
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/sqlite.rb
License: blessing
==> Dependencies
Required: readline ✔
==> Caveats
sqlite is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have sqlite first in your PATH run:
  echo 'set -g fish_user_paths "/opt/homebrew/opt/sqlite/bin" $fish_user_paths' >> ~/.config/fish/config.fish

For compilers to find sqlite you may need to set:
  set -gx LDFLAGS "-L/opt/homebrew/opt/sqlite/lib"
  set -gx CPPFLAGS "-I/opt/homebrew/opt/sqlite/include"

For pkg-config to find sqlite you may need to set:
  set -gx PKG_CONFIG_PATH "/opt/homebrew/opt/sqlite/lib/pkgconfig"

==> Analytics
install: 614,521 (30 days), 1,426,796 (90 days), 5,693,214 (365 days)
install-on-request: 72,180 (30 days), 126,622 (90 days), 420,352 (365 days)
build-error: 0 (30 days)
```

**Comment by carlocab** [comment] 2021-01-05 01:22
>Wait a minute, I will try to install it

Yes, it's different from the one provided by Xcode. Once you've installed the CLT, reinstall python.

**Comment by Cat7373** [comment] 2021-01-05 01:41
Doesn't seem to work.
```
cat73@Cats-MacBook-Pro ~> brew install python@3.9
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.1_4.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/b79adb7fbf9c8b99647257cb3d74f77a7af19f18b69c5bd4d8004a427398c232?response-content-disposition=attachment%3Bfilename%3D%22python%403.9-3.9.1_4.arm
######################################################################## 100.0%
==> Pouring python@3.9-3.9.1_4.arm64_big_sur.bottle.tar.gz
==> /opt/homebrew/Cellar/python@3.9/3.9.1_4/bin/python3 -m ensurepip
==> /opt/homebrew/Cellar/python@3.9/3.9.1_4/bin/pip3 install -v --global-option=--no-user-cfg --install-option=--force --install-option=--single-version-externally-managed --install-option=--record=instal
==> Caveats
Python has been installed as
  /opt/homebrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /opt/homebrew/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /opt/homebrew/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /opt/homebrew/Cellar/python@3.9/3.9.1_4: 3,934 files, 65MB
cat73@Cats-MacBook-Pro ~> python3
Python 3.9.1 (default, Dec 29 2020, 02:24:05) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sqlite'
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/opt/homebrew/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_sqlite3.cpython-39-darwin.so, 2): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /opt/homebrew/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_sqlite3.cpython-39-darwin.so
  Expected in: /usr/lib/libsqlite3.dylib
 in /opt/homebrew/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_sqlite3.cpython-39-darwin.so
>>> 
```

**Comment by carlocab** [comment] 2021-01-05 01:44
What do `brew config` and `brew doctor` say now?

I suspect the problem is that you're running a beta version of Big Sur. Try building `sqlite` from source, then reinstalling `python@3.9`, also from source.

**Comment by Cat7373** [comment] 2021-01-05 01:45
Wait a minute, I try to build from source

```
cat73@Cats-MacBook-Pro ~ [1]> brew config
HOMEBREW_VERSION: 2.7.1-125-gd820c9a
ORIGIN: https://github.com/Homebrew/brew
HEAD: d820c9a91952934ac6ca68b0ef0c8b6aeec285bd
Last commit: 62 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ad6fd898d478d011330946a97cda8ff335e44ae6
Core tap last commit: 42 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.271.09, 1.8.0_271
macOS: 11.2-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
Rosetta 2: false
cat73@Cats-MacBook-Pro ~> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  lua@5.1

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libecpg.6.dylib
  /usr/local/lib/libecpg_compat.3.dylib
  /usr/local/lib/libpgtypes.3.dylib
  /usr/local/lib/libpq.5.dylib
```

**Comment by Cat7373** [comment] 2021-01-05 01:58
Okay, it seems that it may really be a Beta issue.

```
cat73@Cats-MacBook-Pro ~> brew uninstall --ignore-dependencies python@3.9 sqlite
Uninstalling /opt/homebrew/Cellar/python@3.9/3.9.1_4... (3,937 files, 65MB)
Uninstalling /opt/homebrew/Cellar/sqlite/3.34.0... (11 files, 4.2MB)
cat73@Cats-MacBook-Pro ~> brew install -s sqlite python@3.9
==> Downloading https://www.sqlite.org/2020/sqlite-autoconf-3340000.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/opt/homebrew/Cellar/sqlite/3.34.0 --enable-dynamic-extensions --enable-readline --disable-editline --enable-session
==> make install
==> Caveats
sqlite is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have sqlite first in your PATH run:
  echo 'set -g fish_user_paths "/opt/homebrew/opt/sqlite/bin" $fish_user_paths' >> ~/.config/fish/config.fish

For compilers to find sqlite you may need to set:
  set -gx LDFLAGS "-L/opt/homebrew/opt/sqlite/lib"
  set -gx CPPFLAGS "-I/opt/homebrew/opt/sqlite/include"

For pkg-config to find sqlite you may need to set:
  set -gx PKG_CONFIG_PATH "/opt/homebrew/opt/sqlite/lib/pkgconfig"

==> Summary
🍺  /opt/homebrew/Cellar/sqlite/3.34.0: 11 files, 4.2MB, built in 37 seconds
==> Downloading https://files.pythonhosted.org/packages/94/23/e9e3d96500c063129a19feb854efbb01e6ffe7d913f1da8176692418ab8e/setuptools-51.1.1.tar.gz
Already downloaded: /Users/cat73/Library/Caches/Homebrew/downloads/dfd0f93bf21fd28ac8eb7b31b8c29e4ceee4eaf1026de0be1933c133d13f4100--setuptools-51.1.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ca/1e/d91d7aae44d00cd5001957a1473e4e4b7d1d0f072d1af7c34b5899c9ccdf/pip-20.3.3.tar.gz
Already downloaded: /Users/cat73/Library/Caches/Homebrew/downloads/20a3d55b9c92b83b2c00924c174145efd31ccbe94b8f91f40cffc61441e7b6f2--pip-20.3.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ed/46/e298a50dde405e1c202e316fa6a3015ff9288423661d7ea5e8f22f589071/wheel-0.36.2.tar.gz
Already downloaded: /Users/cat73/Library/Caches/Homebrew/downloads/2628149c388cda23d833947d9d838f27eba9442101b2958948fbe661e96b689b--wheel-0.36.2.tar.gz
==> Downloading https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
Already downloaded: /Users/cat73/Library/Caches/Homebrew/downloads/4f82a87872361431c1ff89331abe8b4474053a6310159862948c4e0f35bdaca5--Python-3.9.1.tar.xz
==> ./configure --prefix=/opt/homebrew/Cellar/python@3.9/3.9.1_4 --enable-ipv6 --datarootdir=/opt/homebrew/Cellar/python@3.9/3.9.1_4/share --datadir=/opt/homebrew/Cellar/python@3.9/3.9.1_4/share --enable-
==> make
==> make install PYTHONAPPSDIR=/opt/homebrew/Cellar/python@3.9/3.9.1_4
==> make frameworkinstallextras PYTHONAPPSDIR=/opt/homebrew/Cellar/python@3.9/3.9.1_4/share/python@3.9
==> /opt/homebrew/Cellar/python@3.9/3.9.1_4/bin/python3 -m ensurepip
==> /opt/homebrew/Cellar/python@3.9/3.9.1_4/bin/pip3 install -v --global-option=--no-user-cfg --install-option=--force --install-option=--single-version-externally-managed --install-option=--record=instal
==> Caveats
Python has been installed as
  /opt/homebrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /opt/homebrew/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /opt/homebrew/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /opt/homebrew/Cellar/python@3.9/3.9.1_4: 8,666 files, 129.4MB, built in 2 minutes 54 seconds
==> Caveats
==> sqlite
sqlite is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have sqlite first in your PATH run:
  echo 'set -g fish_user_paths "/opt/homebrew/opt/sqlite/bin" $fish_user_paths' >> ~/.config/fish/config.fish

For compilers to find sqlite you may need to set:
  set -gx LDFLAGS "-L/opt/homebrew/opt/sqlite/lib"
  set -gx CPPFLAGS "-I/opt/homebrew/opt/sqlite/include"

For pkg-config to find sqlite you may need to set:
  set -gx PKG_CONFIG_PATH "/opt/homebrew/opt/sqlite/lib/pkgconfig"

==> python@3.9
Python has been installed as
  /opt/homebrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /opt/homebrew/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /opt/homebrew/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
cat73@Cats-MacBook-Pro ~> which python3
/opt/homebrew/bin/python3
cat73@Cats-MacBook-Pro ~> /opt/homebrew/bin/python3
Python 3.9.1 (default, Jan  5 2021, 09:50:07) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
```

**Comment by carlocab** [comment] 2021-01-05 02:02
Yep, looks like it. Not much we can do to help you, I think, so I'm closing this issue.

**Closed by carlocab** 2021-01-05 02:02 UTC
