### ISSUE TITLE
Recent updates to libspatialite crashing processes

### ISSUE THREAD

**Issue by bricelam** [Homebrew/homebrew-core#43203] opened 2019-08-16 15:44 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Recent updates by @fxcoudert to the libspatialite package are crashing processes using .NET Core and Entity Framework Core to access SpatiaLite databases. (Originally filed by @garfbradaz as aspnet/EntityFrameworkCore#16667)

### Steps to reproduce

0. Download and install the [.NET Core 2.2 SDK](https://dotnet.microsoft.com/download)
1. `git clone` https://github.com/StratumFive/EFCore.SQLite.SpatialCrash.
2. `brew install libspatialite`
3. Change directory to the root solution.
4. `dotnet test xunit`
5. Receive error message: The active test run was aborted. Reason: Test host process crashed.

The *dotnet* executable crashes and I will receive a [crash dump report](https://gist.github.com/garfbradaz/3ea71037bc625eaf30d397c7f016d6e0).

Operating system: Mac Mojave 10.14.5

### Workaround

Using the previous version works as expected.

``` sh
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/835ae521c065524abdf66578e68032fa24bce514/Formula/libspatialite.rb
```

### Wild Speculation

It may or may not be related to the fact that our native SQLite library is named libe_sqlite3.dylib and not libsqlite3.dylib.

**Comment by pond** [comment] 2019-08-20 05:31
Success. By carefully unpicking all newer versions and installing specific versions of the runtime and related libraries, I have the test suite running on SQLite that used to crash. Notably, the version of `libspatialite` is _not_ in my case responsible. Using the most recent Homebrew build works fine. It's other dependencies that seem to be the issue - at least in my case.

It's quite an ugly process. I imagine that most of these carefully chosen versions are _not_ necessary, so I'll edit and update this answer as I narrow things down, until I run out of time for it anyway.

First:

* Uninstall any DotNetCore versions you don't want: https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos
* Get DotNetCore SDK version 2.2.300: https://dotnet.microsoft.com/download/dotnet-core/2.2
* Important! Clean any relevant builds; `dotnet clean` or equivalent
  Next, remove a few Homebrew packages: 
```
brew uninstall postgis
brew uninstall gdal
brew uninstall libspatialite 
brew uninstall libgeotiff
brew uninstall proj
brew uninstall sqlite
```

...resolving dependencies (or ignoring them) with further `uninstall` commands if need be, taking note of them all for reinstallation later. Then, we cherry-pick versions that happen to work on my machine.

SQLite 3.28.0
``` brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/4fa421cfc34548eb48bc236460584c9f4fa16b22/Formula/sqlite.rb
```
 Proj 6.1.0
``` brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ca19c245aae7d6fa8c0d9d7314a4964a3a3b18c8/Formula/proj.rb
``` 
Libgeotiff seems unrelated, so just install the most recent. For this and further calls, Homebrew doesn't seem to recognise the from-SHA installations of dependencies so halts; you have to install with `--ignore-dependencies`. Rather unhelpfully, Homebrew will then warn you that this is an unsupported flag you're not supposed to use, but it's not as if there's any choice.
```
brew install --ignore-dependencies libgeotiff
```

Gdal 2.4.1_1
``` brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/37ce68573be9fe921ef65d421da4657e2f6d0270/Formula/gdal.rb
```

Libspatialite 4.3.0a_7 (the most recent version at the time of writing, but locking to SHA for safety here)
``` brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/1bbba12ca10e05e7194a6233d4bf5bf56677939f/Formula/libspatialite.rb
```
 Postgis 2.5.2_2 (the most recent version at the time of writing, but locking to SHA for safety here)
``` brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/0a2e72798e72e3accead7e793d6cccf4ff89dd70/Formula/postgis.rb
```

**Comment by SMillerDev** [comment] 2019-08-20 06:41
This seems a lot like a bug in dotnet. If it can't handle recent libspatialite libraries it should just break before that.

**Comment by fxcoudert** [comment] 2019-08-20 14:50
Agreed. There is not much indication that the problem lies in `libspatialite`, especially since we haven't really changed our build for it (just triggered a re-build due to `proj` being updated).

One thing that could help decide what is going wrong: does the problem persist if you `brew reinstall -s libspatialite` (i.e. reinstall the latest version, but from source)?

**Comment by bricelam** [comment] 2019-08-20 15:42
I doubt it's related to .NET; that's just our means of invoking native calls like this:
``` c
sqlite3 *db;
sqlite3_open(":memory:", &db);
sqlite3_enable_load_extension(db, 1);
sqlite3_exec(db, "SELECT load_extension('mod_spatialite');", 0, 0, 0);
```
Let me see if it repros with `brew reinstall -s`...

**Comment by bricelam** [comment] 2019-08-20 15:48
Also worth noting: the same code passes on Ubuntu using their latest libsqlite3-mod-spatialite package.

**Comment by SMillerDev** [comment] 2019-08-20 15:48
Does it pass on arch Linux? Cause Ubuntu isn't really a cutting edge distro

**Comment by bricelam** [comment] 2019-08-20 15:56
There was one report of a crash on Debian in Docker, but it's unclear if it's related.

**Comment by bricelam** [comment] 2019-08-20 16:01
[Still segfaulting](https://dev.azure.com/dnceng/public/_build/results?buildId=316669) with `-s`.

**Comment by bricelam** [comment] 2019-08-20 17:26
Hmm, renaming the library to libsqlite3.dylib didn't help either...

Were you able to repro using the C code above?

**Comment by bricelam** [comment] 2019-08-20 18:23
This might be a problem with PROJ. It looks like it's linked to libsqlite3-0

**Comment by bricelam** [comment] 2019-08-20 18:40
Following up [on the SpatiaLite mailing list](https://groups.google.com/forum/#!topic/spatialite-users/71jnc6QVN-A).

**Comment by bricelam** [comment] 2019-08-20 18:49
Any chance of reverting to PROJ v5?

**Comment by garfbradaz** [comment] 2019-08-20 18:54
> There was one report of a crash on Debian in Docker, but it's unclear if it's related.

I can confirm when running in Docker Debian I experienced the same. Had to use Alpine instead.

**Comment by pond** [comment] 2019-08-20 20:22
@bricelam 5.2.0 available via https://github.com/aspnet/EntityFrameworkCore/issues/16667#issuecomment-523179141

**Comment by fxcoudert** [comment] 2019-08-23 07:45
> I doubt it's related to .NET

If you have a crash without .NET, on the minimal code you posted (or another one), that would be fine. But we have many other formulas that depend, directly or indirectly, on libspatialite… and no bugs reported there. Which is why I think it might be .NET specific (in the way it links libraries, or something else).

Closing for now, there is no indication that this is a Homebrew-specific issue. Happy to reconsider if this is debugged further.

**Closed by fxcoudert** 2019-08-23 07:45 UTC

**Comment by bricelam** [comment] 2019-08-23 15:17
I believe recent updates in PROJ v6 have broken mod_spatialite for certain scenarios. This issue is external to the Homebrew formula. Thanks for helping me dig deeper into the issue.
