### ISSUE TITLE
brew doctor is throwing errors

### ISSUE THREAD

**Issue by sim4life** [Homebrew/homebrew-core#46306] opened 2019-11-05 07:23 UTC
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [Y] ran `brew update` and can still reproduce the problem?
- [N] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [N] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [Y] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I ran:
`$ brew doctor`

## What happened (include command output)

`brew doctor` is throwing errors:

<details>
  <summary>Command output</summary>
  <pre>

  Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
Error: formulae require at least a URL
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:247:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:198:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:263:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:355:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:331:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:721:in `block in check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:720:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:720:in `check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:60:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:52:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:52:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

  </pre>
</details>

## What you expected to happen

I expect `brew doctor` to run successfully

## Step-by-step reproduction instructions (by running `brew install` commands)

Just run `brew doctor` after 30-days of inactivity.

**Comment by alebcay** [comment] 2019-11-14 16:53
Duplicate of #46305. Let's continue discussion and troubleshooting there, please.

**Closed by alebcay** 2019-11-14 16:53 UTC
