### ISSUE TITLE
R doesn't compile (--with open-blas)

### ISSUE THREAD

**Issue by ReneMalenfant** [Homebrew/homebrew-core#15982] opened 2017-07-24 12:20 UTC
R no longer launches because of a change to open-blas.  The error message is:
```
dyld: Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.2.19.dylib
  Referenced from: /usr/local/Cellar/r/3.4.1_1/R.framework/Versions/3.4/Resources/lib/libR.dylib
```

When I try `brew reinstall R`, it dies with an error related to X. But to my knowledge, XQuartz is installed fine, and I've had no problems installing formulas that depended on it before.
```
Last 15 lines from /Users/rene/Library/Logs/Homebrew/r/02.make:
            ^
1 error generated.
clang -I../../../../include -DNDEBUG -I../../../include -I../../../../src/include -DHAVE_CONFIG_H -I/usr/local/include -I/usr/local/include -I/usr/X11/include  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include   -fPIC  -g -O2  -c tcltk.c -o tcltk.o
make[4]: *** [tcltk.d] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from tcltk.c:668:
/usr/local/include/tk.h:71:13: fatal error: 'X11/Xlib.h' file not found
#   include <X11/Xlib.h>
            ^
1 error generated.
make[4]: *** [tcltk.o] Error 1
make[3]: *** [all] Error 1
make[2]: *** [R] Error 1
make[1]: *** [R] Error 1
make: *** [R] Error 1

READ THIS: http://docs.brew.sh/Troubleshooting.html
```

The gist log is here:
https://gist.github.com/ReneMalenfant/4a8d9c1beade3d4e5824ca31897be5da

**Comment by ilovezfs** [comment] 2017-07-24 12:29
I cannot reproduce this issue: https://gist.github.com/ilovezfs/0ed5a3fa057544993110b4965783d9a9

**Comment by fxcoudert** [comment] 2017-07-24 12:31
Can you try `brew reinstall openblas`?

**Comment by ReneMalenfant** [comment] 2017-07-24 12:43
`brew uninstall R` then `brew reinstall openblas` then `brew install --with-openblas r` results in the same error message.  (But it installs and runs fine when poured from the bottle.)

Again, the problem doesn't seem to be openblas itself, it's that it's reaching out to X11 during compilation.  There used to be a `--with-x11` option for R when it was under homebrew/science.  I'm not sure where that's gone, since it's not there anymore.

`brew doctor` results are in the gist log (00.doctor.out).

**Comment by fxcoudert** [comment] 2017-07-24 12:49
Not sure why it's trying to pull in X11 when it was explicitly told to configure `--without-x` in the new formula. (The X11 option was purposefully removed when it was moved to core: https://github.com/Homebrew/homebrew-core/pull/14416)

**Comment by ReneMalenfant** [comment] 2017-07-24 12:54
To me, based on the output I posted above, it looks as though compilation dies when trying to compile the tcltk R package, which presumably requires X, which no longer works because `--with-x11` is not an option?

**Comment by ilovezfs** [comment] 2017-07-24 12:56
where is your /usr/local/lib/tkConfig.sh from?

**Comment by ReneMalenfant** [comment] 2017-07-24 12:58
Don't know what installed it, but I've attached it.
[tkConfig.sh.txt](https://github.com/Homebrew/homebrew-core/files/1169858/tkConfig.sh.txt)

**Comment by ilovezfs** [comment] 2017-07-24 12:59
It looks like this issue is the result of the things `brew doctor` identified in https://gist.githubusercontent.com/ReneMalenfant/4a8d9c1beade3d4e5824ca31897be5da/raw/e3eebc22aa5bbf83c3b3af2efadafb8812f1e27c/00.doctor.out

Can you please try resolving those issues (i.e., removing those files), and then try the build again?

**Comment by ReneMalenfant** [comment] 2017-07-24 13:23
Yeah, sorry.  Not going to move a bunch of files just to have that subtly break something else I need a few months from now and not be able to figure out why that's not working.

The R formula seemed to be working fine until `--with-x11` and other options were removed.

**Comment by ilovezfs** [comment] 2017-07-24 13:24
OK.

**Comment by fxcoudert** [comment] 2017-07-24 13:25
You have files, installed there, from another package manager or software. They include fortran compiler, gnu scientific library, and a X11-enabled tcl-tk. This is incompatible with the Homebrew setup.

**Closed by ilovezfs** 2017-07-24 13:24 UTC
Labels: user configuration

**Comment by Eunoia** [comment] 2017-09-29 02:29
I had this issue as well. 

I chose to move those files. If anythings breaks, I'll report it back in this thread.
