### ISSUE TITLE
pijul 0.12.0_1: mojave bottle not found (404)

### ISSUE THREAD

**Issue by spl** [Homebrew/homebrew-core#44041] opened 2019-09-09 08:59 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software.
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**What you were trying to do (and why)**

Upgrading `pijul` preferably from a bottle.

**What happened (include command output)**

```
$ brew upgrade pijul
==> Upgrading 1 outdated package:
pijul 0.12.0 -> 0.12.0_1
==> Upgrading pijul 
==> Downloading https://homebrew.bintray.com/bottles/pijul-0.12.0_1.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pijul"
Download failed: https://homebrew.bintray.com/bottles/pijul-0.12.0_1.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

**What you expected to happen**

`pijul-0.12.0_1.mojave.bottle.tar.gz` is found and installed.

**Step-by-step reproduction instructions (by running `brew install` commands)**

```
$ brew upgrade pijul
```

**Comment by fxcoudert** [comment] 2019-09-09 09:55
And build from source is currently failing with:

```
error[E0308]: mismatched types
   --> pijul/src/commands/record.rs:347:38
    |
347 |             patch.save(&patches_dir, key.keys.get_mut(0))?
    |                                      ^^^^^^^^^^^^^^^^^^^ expected struct `sequoia_openpgp::crypto::asymmetric::KeyPair`, found struct `sequoia_openpgp::crypto::KeyPair`
    |
    = note: expected type `std::option::Option<&mut sequoia_openpgp::crypto::asymmetric::KeyPair>`
               found type `std::option::Option<&mut sequoia_openpgp::crypto::KeyPair>`
note: Perhaps two different versions of crate `sequoia_openpgp` are being used?
   --> pijul/src/commands/record.rs:347:38
    |
347 |             patch.save(&patches_dir, key.keys.get_mut(0))?
    |                                      ^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> pijul/src/commands/rollback.rs:167:34
    |
167 |         patch.save(&patches_dir, key.keys.get_mut(0))?
    |                                  ^^^^^^^^^^^^^^^^^^^ expected struct `sequoia_openpgp::crypto::asymmetric::KeyPair`, found struct `sequoia_openpgp::crypto::KeyPair`
    |
    = note: expected type `std::option::Option<&mut sequoia_openpgp::crypto::asymmetric::KeyPair>`
               found type `std::option::Option<&mut sequoia_openpgp::crypto::KeyPair>`
note: Perhaps two different versions of crate `sequoia_openpgp` are being used?
   --> pijul/src/commands/rollback.rs:167:34
    |
167 |         patch.save(&patches_dir, key.keys.get_mut(0))?
    |                                  ^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> pijul/src/commands/tag.rs:129:34
    |
129 |         patch.save(&patches_dir, key.keys.get_mut(0))?
    |                                  ^^^^^^^^^^^^^^^^^^^ expected struct `sequoia_openpgp::crypto::asymmetric::KeyPair`, found struct `sequoia_openpgp::crypto::KeyPair`
    |
    = note: expected type `std::option::Option<&mut sequoia_openpgp::crypto::asymmetric::KeyPair>`
               found type `std::option::Option<&mut sequoia_openpgp::crypto::KeyPair>`
note: Perhaps two different versions of crate `sequoia_openpgp` are being used?
   --> pijul/src/commands/tag.rs:129:34
    |
129 |         patch.save(&patches_dir, key.keys.get_mut(0))?
    |                                  ^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors
```

**Comment by fxcoudert** [comment] 2019-09-09 09:57
I can't report the bug because I don't have an account with them, can you please report the bug?

**Comment by spl** [comment] 2019-09-09 10:36
> And build from source is currently failing with:

Oh, I didn't let the process go that far.

> I can't report the bug because I don't have an account with them, can you please report the bug?

Sure. I think I have an account. I bet the problem is due to a recently released [`sequoia-openpgp-0.10.0`](https://crates.io/crates/sequoia-openpgp/0.10.0).

**Comment by spl** [comment] 2019-09-09 10:46
Reference: [pijul_org/pijul#430](https://nest.pijul.com/pijul_org/pijul/discussions/430)

**Comment by spl** [comment] 2019-09-16 08:29
@alebcay Thanks for the note!

Sorry, I didn't see the issue you posted at [pijul_org/pijul#425](https://nest.pijul.com/pijul_org/pijul/discussions/425) before this. You're probably right that updating the released tarballs would fix this.

As an aside, I can no longer log into <https://nest.pijul.com> to comment on any of these issues.

It seems like the upstream Pijul developers have been quiet for a while, so it might be some time before those releases will be made.

In the meantime, is there anything that can be done on the Homebrew side to remedy the current situation? What about patching the the 0.12.0 `Cargo.toml` to fix the build-from-source route?

**Comment by fxcoudert** [comment] 2019-09-16 09:15
> What about patching the the 0.12.0 Cargo.toml to fix the build-from-source route?

We'll consider a PR if there is not other way to make it work :(

**Comment by samford** [comment] 2019-10-29 01:21
As in #45839, `brew --build-from-source` is failing for pijul because the `cargo install` command isn't using the `--locked` flag (which forces `cargo install` to use the dependency versions in the `Cargo.lock` file, leading to a reproducible build).  By default, `cargo install` builds using the latest dependency versions, which will fail if there are breaking changes in a dependency (as seen above).

To test this, I added the `--locked` flag to the pijul formula and building from source worked as expected.

```
$ brew install --build-from-source pijul
==> Installing pijul
==> Downloading https://pijul.org/releases/pijul-0.12.0.tar.gz
######################################################################## 100.0%
==> cargo install --locked --root /usr/local/Cellar/pijul/0.12.0_1 --path .
🍺  /usr/local/Cellar/pijul/0.12.0_1: 6 files, 11.8MB, built in 12 minutes 32 seconds

$ brew test pijul
Testing pijul
==> /usr/local/Cellar/pijul/0.12.0_1/bin/pijul init
==> /usr/local/Cellar/pijul/0.12.0_1/bin/pijul add haunted house
==> /usr/local/Cellar/pijul/0.12.0_1/bin/pijul record --all --message='Initial P
==> /usr/local/Cellar/pijul/0.12.0_1/bin/pijul ls
```

There's ongoing discussion in the aforementioned pull request about how to proceed with rolling out the `--locked` flag to Rust formulae, so I'll hold off on creating a PR to fix building from source for pijul for the moment, as it will likely be taken care of as part of that process.

**Comment by fxcoudert** [comment] 2019-10-29 12:58
A separate `pijul` PR would be great, since it fixes the build on Catalina

**Comment by samford** [comment] 2019-11-01 21:14
By request, I created a pull request to add the `--locked` flag to the `cargo install` command, which fixes building from source for the version of Pijul in the current formula (0.12.0).  The PR is now merged and the bottles were updated in the process, so you may want to give this another try now if you were having issues before.

**Closed** 2019-11-02 01:15 UTC
Labels: rust
