### ISSUE TITLE
Updating python3 fails at latest HEAD

### ISSUE THREAD

**Issue by achanda** [Homebrew/homebrew-core#10771] opened 2017-03-08 12:11 UTC
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew?
### Bug reports:
I had python3 installed on my system (macOS 10.12.3) which worked fine. Today I ran `brew update && brew upgrade` and python3 failed to update
```
==> Using the sandbox
==> /usr/local/Cellar/python3/3.6.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.6.0_1/bin --install-lib=/usr/local/lib/python3.6/site-packages --single-version-externally
Last 15 lines from /Users/Abhishek/Library/Logs/Homebrew/python3/post_install.01.python3:
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python3/3.6.0_1/libexec/setuptools/setuptools/command/install_egg_info.py", line 34, in run
    self.run_command('egg_info')
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python3/3.6.0_1/libexec/setuptools/setuptools/command/egg_info.py", line 271, in run
    writer = ep.resolve()
  File "/usr/local/Cellar/python3/3.6.0_1/libexec/setuptools/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'setuptools_version_command'
```
https://gist.github.com/achanda/3ab4eb259ada48f792645ca9c96e5065

### `brew config`
```
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 35 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f594f7ae846b9ded69fdfbddd77de87a132f2ada
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by tdsmith** [comment] 2017-03-13 23:57
Thanks for opening an issue. Sorry to say I can't reproduce & don't have any insight. :/

**Comment by MikeMcQuaid** [comment] 2017-03-19 16:32
Closing as @tdsmith can't reproduce.

**Closed by MikeMcQuaid** 2017-03-19 16:32 UTC
