### ISSUE TITLE
The Homebrew version of get_iplayer version 3.14 fails to download requested BBC program

### ISSUE THREAD

**Issue by RobinE** [Homebrew/homebrew-core#27707] opened 2018-05-10 16:15 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?... No logs reported
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? reorted
HOMEBREW_VERSION: 1.6.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: d14d0c25d6bd5a15f3fbca4cb402f0f2245c4631
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bc968312ad956c3d23d417a16c32a4b69a7dffa8
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_101, 1.6.0_65-b14-468
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: 2.7.11 => /opt/X11

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

The Homebrew version of get_iplayer version 3.14 fails to download requested BBC program. on Mac OS high Sierra 10.13 (and latest) I can give you terminal output if necessary.
Rolling back to version 3.12 works fine (I was able to do this by setting up a link to the version saved in Cellar).
get_iplayer support says that this is due to homebrew incorrectly handling the latest release of get_iplayet, and that I should report problem on this forum.

MikeMcQuaid on Homebrew Forums asked me to report this problem here.

**Comment by SMillerDev** [comment] 2018-05-11 07:05
Thanks for the report, this is however a duplicate of https://github.com/Homebrew/homebrew-core/issues/27706

**Closed** 2018-05-11 07:09 UTC
