### ISSUE TITLE
Error: unknown option `config` on install

### ISSUE THREAD

**Issue by phylaxis** [Homebrew/homebrew-core#702] opened 2016-04-29 22:06 UTC
When attempting to install Homebrew on an older Mac (can only run OS X 10.6.8) I get the following error:

```
==> Tapping homebrew/core
error: unknown option `config'
usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <branch>
                          use <branch> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --separate-git-dir <gitdir>
                          separate git dir from working tree

Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-core /usr/local/Library/Taps/homebrew/homebrew-core --config core.autocrlf=false --depth=1
Failed during: /usr/local/bin/brew tap homebrew/core
```

I originally did have a copy of Homebrew installed on this machine, but when I attempted a `brew update` I got the same error, so I was attempting an uninstall (which did work) and then reinstall, but this issue persists.

Any help would be appreciated. Thanks.

**Comment by DomT4** [comment] 2016-04-29 23:41
What does `which git` and `git --version` return?

**Comment by phylaxis** [comment] 2016-04-30 07:07
`which git` is `/usr/bin/git`

and `git --version` is `git version 1.7.5.4`

**Comment by ilovezfs** [comment] 2016-04-30 11:12
You can
```
curl -OL https://raw.githubusercontent.com/Homebrew/install/master/install
perl -p -i -e 's/system "#{HOMEBREW_PREFIX}\/bin\/brew", "tap", "homebrew\/core"//' install 
chmod +x install
./install
perl -p -i -e 's/ --config core.autocrlf=false//' /usr/local/Library/Homebrew/tap.rb
brew tap homebrew/core
brew install git
cd /usr/local
git checkout -- /usr/local/Library/Homebrew/tap.rb
rm -rf Library/Taps/Homebrew/homebrew-core
brew tap homebrew/core
brew update
```

**Comment by phylaxis** [comment] 2016-04-30 15:26
@ilovezfs Thanks, I appreciate the help. In looking at this I assume my issue is the location of my executables and that's likely due to my system running an older version of OS X? A couple things I don't understand about the code. Why do I need to run standard commands like curl, perl, and rm using the full `/bin/` path? Also why remove `Library/Taps/Homebrew/homebrew-core`?

**Comment by ilovezfs** [comment] 2016-04-30 15:31
Those are great questions.

1. The issue is not location, just that your git is old.
2. I used absolute paths in those cases because that's best practice when you don't know exactly what might be lurking in someone's PATH. Feel free to use the simple names as you see fit.
3. I remove it with rm because it cannot be untapped via `brew untap`. It's immediately re-tapped in the penultimate step, but with the new git installed from brew so that you won't have a problem when it tries to set the config value the second time. That will also confirm everything was successful since it follows the `git checkout -- Library/Homebrew/tap.rb`

**Comment by phylaxis** [comment] 2016-04-30 17:03
Awesome thanks again for the help and the education

**Comment by ilovezfs** [comment] 2016-05-01 09:45
Incidentally, I don't think that there's any reason `brew tap` has to use the newish `--config` option as opposed to setting it the old fashioned way, especially given that it is called from the install script before the user even has a chance to install brew's version of git. @mistydemeo I guess this will come up if/when tigerbrew splits brew and homebrew-core and the tiger brew install script is updated accordingly.

**Comment by UniqMartin** [comment] 2016-05-01 10:58
> Incidentally, I don't think that there's any reason `brew tap` has to use the newish `--config` option as opposed to setting it the old fashioned way, especially given that it is called from the install script before the user even has a chance to install brew's version of git.

The reason for passing it like that is that the option will already have an effect on `git clone`. If it is set afterwards, the checkout might already be borked by the user's configuration. Of course this can be also fixed afterwards by doing `git reset --hard`, but that doesn't feel particularly elegant. (Nonetheless, maybe it's the way to go if we don't want to stop supporting ancient Git versions.)

**Comment by ilovezfs** [comment] 2016-05-01 13:03
@UniqMartin maybe the solution is https://github.com/Homebrew/brew/pull/36 ?

**Comment by UniqMartin** [comment] 2016-05-01 13:09
@ilovezfs Yes, some form of Homebrew/brew#36 should also be able to resolve this issue.

**Comment by vanderhoorn** [comment] 2016-05-26 16:19
I was running into the same issue, so many thanks to those who replied in this thread!

I ran into the following though, while executing the list of commands that @ilovezfs mentioned:

```
...
$ brew install git
Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
==> Installing dependencies for git: xz
==> Installing git dependency: xz
Error: uninitialized constant Class::Xcode
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/extend/os/mac/development_tools.rb:25:in `default_compiler'
/usr/local/Library/Homebrew/compilers.rb:92:in `compilers'
/usr/local/Library/Homebrew/compilers.rb:87:in `select_for'
/usr/local/Library/Homebrew/extend/ENV/shared.rb:165:in `compiler'
/usr/local/Library/Homebrew/extend/ENV/super.rb:45:in `setup_build_environment'
/usr/local/Library/Homebrew/build.rb:86:in `install'
/usr/local/Library/Homebrew/build.rb:178
```

I did install Xcode 4.2 for Snow Leopard (which comes with git 1.7.5.4), but maybe something is configured in a wrong way. Any clue?

Thanks in advance.

**Comment by UniqMartin** [comment] 2016-05-26 16:38
@vanderhoorn I'm currently looking into this. Can you please post the output of running

```
echo 'puts DevelopmentTools.locate("cc")' | brew irb
```

on your system? That would help confirm my suspicion.

**Comment by vanderhoorn** [comment] 2016-05-26 16:47
This doesn't look good...

```
$ echo 'puts DevelopmentTools.locate("cc")' | brew irb
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
Error: can't dup NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb.rb:278:in `dup'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb.rb:278:in `prompt'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb.rb:130:in `eval_input'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb/ruby-lex.rb:207:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb/ruby-lex.rb:207:in `prompt'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb/ruby-lex.rb:221:in `initialize_input'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb/ruby-lex.rb:228:in `each_top_level_statement'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb.rb:154:in `eval_input'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb.rb:71:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb.rb:70:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb.rb:70:in `start'
/usr/local/Library/Homebrew/cmd/irb.rb:31:in `irb'
/usr/local/Library/brew.rb:87:in `send'
/usr/local/Library/brew.rb:87
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb.rb:84:in `throw': uncaught throw `IRB_EXIT' (NameError)
	from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb.rb:84:in `irb_exit'
	from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb/context.rb:226:in `exit'
	from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb/extend-command.rb:24:in `exit'
	from /usr/local/Library/brew.rb:149
```

**Comment by UniqMartin** [comment] 2016-05-26 16:48
Do you have a `.irbrc` in your home directory? If so, can you temporarily move it aside and retry?

**Comment by UniqMartin** [comment] 2016-05-26 16:50
Or alternatively just run `brew irb`, execute `puts DevelopmentTools.locate("cc")` in there, and then exit by typing `exit` …

**Comment by vanderhoorn** [comment] 2016-05-26 16:58
```
$ brew irb
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
1.8.7-p358 :001 > puts DevelopmentTools.locate("cc")
/usr/bin/cc
 => nil 
1.8.7-p358 :002 > 
```

**Comment by UniqMartin** [comment] 2016-05-26 17:06
@vanderhoorn Should be fixed by Homebrew/brew@aa747b915a080633e626cd741fa8f74ae6c5c9d8. Can you `brew update` and then try again?

**Comment by vanderhoorn** [comment] 2016-05-26 18:07
Yes, works, awesome! Thanks a lot!

**Comment by phylaxis** [comment] 2016-05-28 18:58
@ilovezfs So I finally have had time to attempt your solution and everything went fine until I tried to do `git checkout -- Library/Homebrew/tap.rb`.

Then I got this error
`git checkout -- Library/Homebrew/tap.rb
fatal: Not a git repository (or any of the parent directories): .git
`

**Comment by ilovezfs** [comment] 2016-05-28 19:02
You have to be in `cd /usr/local`

**Comment by phylaxis** [comment] 2016-05-28 19:19
@ilovezfs Thanks. I was in that directory, but must have made some other error when I was copying and pasting the commands. I repeated the steps and all worked great. Thanks again you're a life saver.

**Comment by ilovezfs** [comment] 2016-05-28 20:01
@phylaxis You're welcome. I'm glad it worked out. Be sure to follow up by running `brew install curl` as well, which is known to be problematic on older OSs.

**Comment by MikeMcQuaid** [comment] 2016-08-10 09:41
Sounds like this is working now.

**Closed by MikeMcQuaid** 2016-08-10 09:41 UTC
Labels: 10.6
