### ISSUE TITLE
Unsuitable OpenJDK dependency for `sonar-scanner`

### ISSUE THREAD

**Issue by kapfab** [Homebrew/homebrew-core#78468] opened 2021-06-01 14:12 UTC
```shell
HOMEBREW_VERSION: 3.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76cfe88b7628a8010bf98115627f6aced4ff8870
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e5faf791fdb1df83c30e45d3d85a5ab48a700f25
Core tap last commit: 41 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: (redacted)
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: 12.5
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `sonar-scanner` on our iOS projects.

### What happened (include all command output)?

Until a few days ago, `sonar-scanner` used to run fine on our iOS projects, but it started to fail after our latest `brew update` with the following error:
```
...
Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6968c1d6
...
```

### What did you expect to happen?

After investigation, this fails because the formula depends on the latest `openjdk`, which just passed from `15.0.2` to `16.0.1` (and `16.0.1` now denies by default the illegal reflective access `sonar-scanner` relies on).

There are 3 options to solve this issue:
- The formula could be changed to depend on `openjdk@11` (`sonar-scanner` actually expects Java 11), but I understand Brew tries to limit the number of JDK versions to be installed via dependencies and to therefore uses as much as possible the latest one.
- Illegal reflective access can be re-allowed with the `--illegal-access=permit` command-line option, but this is not very clean nor handy (most of iOS CI use `fastlane`’s `sonar` plugin and not directly the `sonar-scanner` CLI), so it would be better to directly set this option in the `sonar-scanner` wrapper.
- The same option could be set globally with an environment variable, so the following advice could be written at the end of the formula install log: `export SONAR_SCANNER_OPTS="--illegal-access=permit"`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install sonar-scanner

cd /path/of/ios_project
fastlane lane_that_runs_scan_slather_lizard_etc

fastlane lane_that_runs_sonar
(Fails)

export SONAR_SCANNER_OPTS="--illegal-access=permit"
fastlane lane_that_runs_sonar
(Works)
```

**Comment by cho-m** [comment] 2021-06-01 20:16
Using `--illegal-access=permit` would be a short-term fix as JDK17 (release planned Sept 2021) will make the option have no effect with **JEP 403** (https://openjdk.java.net/jeps/403).

Explicitly providing `--add-opens` and/or `--add-exports` (preferably done by upstream) would be better workaround to illegal access issues.

We can downgrade to `openjdk@11` if that ends up being simplest and/or easiest to maintain approach, and switch back to latest `openjdk` in future update.

---

On side note, if we had a better test case, we might have been able to catch this during the OpenJDK 16 PR. The test using `sonar-scanner --version` is probably exiting before hitting any meaningful code.

**Comment by Moisan** [comment] 2021-06-01 22:48
To run `sonar-scanner` one needs to have `sonarqube` server running. I wonder if we should make it a runtime dependency, I suspect users install both together anyway. This would allow us to test `sonar-scanner` on some codebase, such as Homebrew itself maybe.

**Comment by SMillerDev** [comment] 2021-06-02 06:00
I suspect most people would have the server somewhere in a cloud. But we can use it for the test.

**Comment by kapfab** [comment] 2021-06-02 10:10
Indeed, in CI configurations, the Sonar server is usually on another machine (cloud or on-premise) than the CI worker.
Pulling and running a SonarQube server just for testing would be a bit of a stretch.

@cho-m, `--add-opens java.base/java.lang=ALL-UNNAMED` is indeed more future-proof.
Could it be added directly to the formula? I am not sure such a fix would be accepted on the SonarSource side as it is more of a dependency issue on the Brew side.

**Comment by SMillerDev** [comment] 2021-06-02 10:18
>  Pulling and running a SonarQube server just for testing would be a bit of a stretch.

It's not that heavy really in a brew CI context.

> I am not sure such a fix would be accepted on the SonarSource side as it is more of a dependency issue on the Brew side.

It's going to be a requirement for running Sonarqube scanner on the next LTS. At some point they will have to do this regardless.

**Comment by kapfab** [comment] 2021-06-02 11:01
> > I am not sure such a fix would be accepted on the SonarSource side as it is more of a dependency issue on the Brew side.
> 
> It's going to be a requirement for running Sonarqube scanner on the next LTS. At some point they will have to do this regardless.

Not sure to understand… Next LTS will not stick to Java 11 anymore?

**Comment by SMillerDev** [comment] 2021-06-02 11:28
> Not sure to understand… Next LTS will not stick to Java 11 anymore?

Right, I was mixing terms there. Java 17 will be an LTS version and I expect Sonarqube will want to support that. So it's also in their interest to fix this.

**Comment by cho-m** [comment] 2021-06-02 16:48
Off the top of my head, here are ways that 2 different formulae have dealt with JDK16+ requirement
1. `google-java-format` - since they provide a JAR file, they pushed adding `--add-exports` to the end-user. (See: https://github.com/google/google-java-format/releases/tag/v1.10.0)
2. `jmeter` - since they provide a wrapper script around JAR, they added all the `--add-opens` necessary to run (See: https://github.com/apache/jmeter/commit/e0e978704745080b2c516d0d33f951d51c571448)

It seems like a better choice for `sonar-scanner` to do something like the latter upstream for a future release.

---

In the meantime, we should fix the current formula issue.

If you are interested in contributing, you can open a PR with any of fixes in this thread; otherwise, someone on Homebrew side will probably look into this.

The main options being:
- add `SONAR_SCANNER_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED"` as part of environment for the `bin.env_script_all_files` line
- downgrade to JDK11 by modifying dependency to `openjdk@11` and changing `JAVA_HOME` to match.

**Comment by andrewclaus** [comment] 2021-06-02 23:54
This just started failing for us also. We install sonar-scanner through homebrew in our Azure DevOps pipeline jobs on our iOS projects. We see a different error, but we have narrowed it down to the same issue, java 15 works fine, but java 16 fails.

The different error is probably caused by running a different sonarqube server version (or plugin version).

**Comment by kapfab** [comment] 2021-06-03 18:06
> In the meantime, we should fix the current formula issue.
> 
> If you are interested in contributing, you can open a PR with any of fixes in this thread; otherwise, someone on Homebrew side will probably look into this.
> 
> The main options being:
> 
> * add `SONAR_SCANNER_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED"` as part of environment for the `bin.env_script_all_files` line... **EDIT:** may want to actually append onto existing environment variable to allow users to still add extra opts.
> * downgrade to JDK11 by modifying dependency to `openjdk@11` and changing `JAVA_HOME` to match.

I wanted to open a PR with the first option in mind to avoid pulling an additional JDK, as the single `--add-opens java.base/java.lang=ALL-UNNAMED` seems to do the trick for us, but I have no clue whether this is enough to cover all use cases.
So unless someone has more insight on this, I would rather go for the JDK downgrade…

**Comment by andrewclaus** [comment] 2021-06-03 23:56
As a side note, the extra parameter mentioned above did get our builds working:
SONAR_SCANNER_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED"

**Comment by Moisan** [comment] 2021-06-04 15:43
Closing since the Formula has been downgraded to `openjdk@11`.

**Closed by Moisan** 2021-06-04 15:43 UTC
Labels: bug
