### ISSUE TITLE
Error: The bottle for readline has an invalid build provenance attestation.

### ISSUE THREAD

**Issue by ianhu92** [Homebrew/homebrew-core#191583] opened 2024-09-23 11:53 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.24-5-gbd3c7f8
ORIGIN: https://github.com/Homebrew/brew
HEAD: bd3c7f80530d21e791ccc01b02234b299941dd29
Last commit: 4 hours ago
Core tap HEAD: 51788b5f5ac6df5625ef91e33472b988f8af4f22
Core tap last commit: 67 minutes ago
Core tap JSON: 23 Sep 11:34 UTC
Core cask tap HEAD: b6cb08f8119ad5798faf7b007e45aab4a8053601
Core cask tap last commit: 21 minutes ago
Core cask tap JSON: 23 Sep 11:34 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 16.0.0 build 1600
Git: 2.44.0 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7-x86_64
CLT: 16.0.0.0.1.1724870825
Xcode: N/A

Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew upgrade

### What happened (include all command output)?

ianhu@Ianhu-MacBook-Pro ~ % brew upgrade readline
==> Upgrading 1 outdated package:
readline 8.2.10 -> 8.2.13
==> Downloading https://ghcr.io/v2/homebrew/core/readline/manifests/8.2.13
Already downloaded: /Users/ianhu/Library/Caches/Homebrew/downloads/aa1afa38997a2866d91c81fdda8b36d436cd4ea7a82aed07d13c83c56eb3460e--readline-8.2.13.bottle_manifest.json
==> Fetching readline
==> Downloading https://ghcr.io/v2/homebrew/core/readline/blobs/sha256:0cf2cae0b9bb71bee1f9f9b3ab1e5dfc27b32f474db7f2d38b8b2dffd02da
Already downloaded: /Users/ianhu/Library/Caches/Homebrew/downloads/446fbf00927bacd971f43f42c3605e00929b283700936241ad8044fe469ccb25--readline--8.2.13.sonoma.bottle.tar.gz
==> Upgrading readline
  8.2.10 -> 8.2.13 
==> Verifying attestation for readline
Error: The bottle for readline has an invalid build provenance attestation.

This may indicate that the bottle was not produced by the expected
tap, or was maliciously inserted into the expected tap's bottle
storage.

Additional context:

attestation verification failed: Failure while executing; `/usr/bin/env GH_TOKEN=****** GH_HOST=github.com /usr/local/bin/gh attestation verify /Users/ianhu/Library/Caches/Homebrew/downloads/446fbf00927bacd971f43f42c3605e00929b283700936241ad8044fe469ccb25--readline--8.2.13.sonoma.bottle.tar.gz --repo Homebrew/homebrew-core --format json` exited with 1. Here's the output:
Failed to verify the artifact: failed to fetch attestations for subject: sha256:0cf2cae0b9bb71bee1f9f9b3ab1e5dfc27b32f474db7f2d38b8b2dffd02da5ff

### What did you expect to happen?

Should update version without errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
run `brew upgrade` or `brew upgrade readline`.
```

**Comment by SMillerDev** [comment] 2024-09-24 09:36
Duplicate of pinned https://github.com/Homebrew/homebrew-core/issues/177384

**Closed by SMillerDev** 2024-09-24 09:36 UTC
Labels: bug
