### ISSUE TITLE
ftp.pcre.org's expired SSL certs cause "brew install git" to fail

### ISSUE THREAD

**Issue by neokio** [Homebrew/homebrew-core#86251] opened 2021-10-01 15:34 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
| => brew config
HOMEBREW_VERSION: 3.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e6919b73444e9f9e02ad81d8afc4bbd97533567
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f77f713831a4dfcf550613d354e8192e8503a47c
Core tap last commit: 20 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.56hnZUKJZh/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/subl
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 10.0.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
________________________________________________________________________________
| ~
| => brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Applications/MAMP/bin/php/php7.4.2/bin/php-config

Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install git`

### What happened (include all command output)?

```
==> Downloading https://ftp.pcre.org/pub/pcre/pcre2-10.37.tar.bz2

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
Error: git: Failed to download resource "pcre2"
Download failed: https://ftp.pcre.org/pub/pcre/pcre2-10.37.tar.bz2
```

### What did you expect to happen?

`git` installed :)

I recognize that this is on macOS 10.13, which is no longer supported. But if it's as simple as updating a single link, I'm sure a number of us would appreciate the fix.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install git`
```

**Comment by carlocab** [comment] 2021-10-01 15:37
Duplicate of Homebrew/brew#12161

**Closed by carlocab** 2021-10-01 15:37 UTC
Labels: bug

**Comment by neokio** [comment] 2021-10-02 18:35
For anyone else experiencing this exact problem, the workaround ()thanks to @carlocab's link above) is ...

```
export HOMEBREW_FORCE_BREWED_CURL=1
brew install git
```
