### ISSUE TITLE
`sleepwatcher` installs config in `/Users/brew/...` instead of `$HOME`

### ISSUE THREAD

**Issue by henrik242** [Homebrew/homebrew-core#126336] opened 2023-03-22 12:31 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
🐤 brew gist-logs sleepwatcher
Error: No logs.
🐤 brew config
HOMEBREW_VERSION: 4.0.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 584588afb4ab557bcc0536f2794b4d043c333bb9
Last commit: 2 days ago
Core tap JSON: 22 Mar 12:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.osgq5rg0pu/org.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
🐤 brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Getting sleepwatcher to run its `$HOME/.wakeup` and `$HOME/.sleep` scripts.

### What happened (include all command output)?

`$HOME/.wakeup` and `$HOME/.sleep` aren't run on sleep & wakeup.

### What did you expect to happen?

`$HOME/.wakeup` and `$HOME/.sleep` being run on sleep & wakeup.

### Step-by-step reproduction instructions (by running `brew` commands)

sleepwatcher is running with wrong `-w` and `-s`:
```shell
🐤 ps ax | grep sleepw
41316   ??  S      0:00.08 /opt/homebrew/opt/sleepwatcher/sbin/sleepwatcher -V -s /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/home/.sleep -w /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/home/.wakeup
```
That's from here:
```
🐤 cat /opt/homebrew//Cellar/sleepwatcher/2.2.1/.brew/sleepwatcher.rb 
...

  service do
    run [opt_sbin/"sleepwatcher", "-V", "-s", "#{Dir.home}/.sleep", "-w", "#{Dir.home}/.wakeup"]
    run_type :immediate
    keep_alive true
  end
...
```
So it seems `#{Dir.home}` doesn't resolve correctly.

**Comment by SMillerDev** [comment] 2023-03-22 12:45
Duplicate of https://github.com/Homebrew/brew/issues/14925

**Closed by SMillerDev** 2023-03-22 12:45 UTC
Labels: bug
