### ISSUE TITLE
openjpeg 2.3.0 fails to build on Sierra 10.12.6 and Xcode 9.0 (9A235)

### ISSUE THREAD

**Issue by Ranutso** [Homebrew/homebrew-core#19344] opened 2017-10-11 19:08 UTC
- [✓] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [✓] Ran `brew update` and retried your prior step? Yes, twice.
- [✓] Ran `brew doctor`, fixed all issues and retried your prior step? I'm building this from source. I hope I am giving you a hand on these least popular formulas.
- [✓] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? Included at the end.
- [✓] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade openjpeg to the latest version.

- What happened (include command output)
```$ brew upgrade openjpeg
==> Upgrading 1 outdated package, with result:
openjpeg 2.3.0
==> Upgrading openjpeg 
==> Downloading https://github.com/uclouvain/openjpeg/archive/v2.3.0.tar.gz
Already downloaded: /Users/rash/Library/Caches/Homebrew/openjpeg-2.3.0.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/openjpeg/2.3.0 -DCMAKE_BUILD_TYPE=Re
==> make install
Last 15 lines from /Users/rash/Library/Logs/Homebrew/openjpeg/02.make:
cd /tmp/openjpeg-20171011-39388-1l4dwcx/openjpeg-2.3.0/src/lib/openjp2 && /usr/local/Cellar/cmake/3.9.4/bin/cmake -E cmake_link_script CMakeFiles/openjp2.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 7.0.0 -current_version 2.3.0 -o ../../../bin/libopenjp2.2.3.0.dylib -install_name @rpath/libopenjp2.7.dylib CMakeFiles/openjp2.dir/thread.c.o CMakeFiles/openjp2.dir/bio.c.o CMakeFiles/openjp2.dir/cio.c.o CMakeFiles/openjp2.dir/dwt.c.o CMakeFiles/openjp2.dir/event.c.o CMakeFiles/openjp2.dir/image.c.o CMakeFiles/openjp2.dir/invert.c.o CMakeFiles/openjp2.dir/j2k.c.o CMakeFiles/openjp2.dir/jp2.c.o CMakeFiles/openjp2.dir/mct.c.o CMakeFiles/openjp2.dir/mqc.c.o CMakeFiles/openjp2.dir/openjpeg.c.o CMakeFiles/openjp2.dir/opj_clock.c.o CMakeFiles/openjp2.dir/pi.c.o CMakeFiles/openjp2.dir/t1.c.o CMakeFiles/openjp2.dir/t2.c.o CMakeFiles/openjp2.dir/tcd.c.o CMakeFiles/openjp2.dir/tgt.c.o CMakeFiles/openjp2.dir/function_list.c.o CMakeFiles/openjp2.dir/opj_malloc.c.o CMakeFiles/openjp2.dir/sparse_array.c.o -lm 
cd /tmp/openjpeg-20171011-39388-1l4dwcx/openjpeg-2.3.0/src/lib/openjp2 && /usr/local/Cellar/cmake/3.9.4/bin/cmake -E cmake_symlink_library ../../../bin/libopenjp2.2.3.0.dylib ../../../bin/libopenjp2.7.dylib ../../../bin/libopenjp2.dylib
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.4/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.4/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

make[2]: *** [bin/libopenjp2.dylib] Abort trap: 6
make[2]: *** Deleting file `bin/libopenjp2.dylib'
make[1]: *** [src/lib/openjp2/CMakeFiles/openjp2.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

- What you expected to happen
Expected openjpeg to compile successfully.

- Step-by-step reproduction instructions (by running `brew install` commands)
Run `brew update`
Run `brew upgrade openjpeg`
or
Run `brew install openjpeg`

Here is the gist-logs files: https://gist.github.com/anonymous/54fe2600d438863eb994574753f21d8a

**Comment by dunn** [comment] 2017-10-12 04:36
I can't reproduce; the only difference I notice in our configurations is that I also have the CLT installed.

**Comment by ilovezfs** [comment] 2017-10-12 04:37
@dunn are you testing on 10.12 or 10.13?

**Comment by dunn** [comment] 2017-10-12 04:41
10.12.6

**Comment by ilovezfs** [comment] 2017-10-12 04:42
@Ranutso did you build cmake from source?

**Comment by dunn** [comment] 2017-10-12 05:04
Probably.  From doctor:
```
Warning: You have HOMEBREW_BUILD_FROM_SOURCE set. This environment variable is
intended for use by Homebrew developers. If you are encountering errors,
please try unsetting this. Please do not file issues if you encounter
errors when using this environment variable.

**Comment by ilovezfs** [comment] 2017-10-12 05:06
Yeah that's why. This is fixed in the next version of CMake, but until then we've enabled an or_later bottle. @Ranutso please unset `HOMEBREW_BUILD_FROM_SOURCE` and reinstall cmake from the bottle.

**Closed by ilovezfs** 2017-10-12 05:06 UTC

**Comment by Ranutso** [comment] 2017-10-12 17:36
Thank you for answering the questions, Dunn. That's all correct. Everything build from source and on 10.12.6.

Got it, guys! Thanks for the support.
