### ISSUE TITLE
unfs3 is broken

### ISSUE THREAD

**Issue by royger** [Homebrew/homebrew-core#7213] opened 2016-11-24 12:39 UTC
Hello,

unfs3 doesn't seem to work on OS X at all, I've tried several options (-d, -s) and although the destination can mount the share, the data seems to be completely unavailable, and I have to end up force-unmounting it (umount -f) because proceeses trying to access it just hung. I've tried dtracing the unfsd process, but I don't seem to spot anything obviously wrong. I'm using 10.12.1, maybe this was working on previous OS X versions? If not it should be removed IMHO.

Thanks, Roger.

**Comment by MikeMcQuaid** [comment] 2016-11-24 14:28
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

Also, you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by royger** [comment] 2016-12-05 12:00
Hello,

Sorry, I completely forgot about this.

 - What you were trying to do (and why):

I'm trying to run a NFS server from user-space using unfs3. This should allow me to share folders from OS X to any other OS with NFS support (mostly UNIX ones). I'm doing this because the current nfsd shipped with OS X (10.12.1) crashes the kernel (this is already reported and acknowledged by Apple).

- What happened:

I've created a sample exports file, used it with unfs and mounted it from a FreeBSD box, the result is that when trying to access a folder or subfolder of that share the client gets stuck.

- What you expected to happen:

The client should be able to access the share.

- Step-by-step reproduction instructions (with as minimal input data as possible):

1. Create a sample exports file (in my case I'm using /Users/royger/exports), and it contains the following line:

/Users/royger/src    nuc(rw,anonuid=501,anongid=20,all_squash)

I'm exporting folder ~/src, and all accesses should be mapped to the id of my user (501) and the group id of staff (20).

2. Start unfsd:

$ sudo /usr/local/sbin/unfsd -e /Users/royger/exports -d

3. Mount the share from another box:

$ mount mac:/Users/royger/src src

4. Try to access the share:

$ ls src/foo

5. ls gets stuck.

I've done what the Troubleshooting guide describes, but AFAICT this is not a homewbrew issue, it's just that unfs3 simply doesn't work on OS X[0] so it should be removed from homebrew.

Roger.

[0] https://sourceforge.net/p/unfs3/mailman/message/131177/

**Comment by MikeMcQuaid** [comment] 2016-12-08 10:09
Thanks for the report. This will be removed from Homebrew in https://github.com/Homebrew/homebrew-core/issues/7667.

**Comment by woodruffw** [comment] 2017-01-02 06:35
Closing since the boneyarding went through.

**Closed by woodruffw** 2017-01-02 06:35 UTC
