### ISSUE TITLE
Error: undefined method `non_apple_gcc_version' for DevelopmentTools:Class

### ISSUE THREAD

**Issue by schultzm** [Homebrew/homebrew-core#1028] opened 2016-05-10 01:41 UTC
```
Error: undefined method `non_apple_gcc_version' for DevelopmentTools:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/compilers.rb:138:in `compiler_version'
/usr/local/Library/Homebrew/compilers.rb:121:in `block (2 levels) in find_compiler'
/usr/local/Library/Homebrew/compilers.rb:119:in `reverse_each'
/usr/local/Library/Homebrew/compilers.rb:119:in `block in find_compiler'
/usr/local/Library/Homebrew/compilers.rb:116:in `each'
/usr/local/Library/Homebrew/compilers.rb:116:in `find_compiler'
/usr/local/Library/Homebrew/compilers.rb:109:in `compiler'
/usr/local/Library/Homebrew/compilers.rb:92:in `select_for'
/usr/local/Library/Homebrew/extend/ENV/shared.rb:165:in `compiler'
/usr/local/Library/Homebrew/extend/ENV/super.rb:45:in `setup_build_environment'
/usr/local/Library/Homebrew/build.rb:86:in `install'
/usr/local/Library/Homebrew/build.rb:178:in `<main>'
```

**Comment by UniqMartin** [comment] 2016-05-10 01:50
To help us debug this issue, can you please explain:

- What you were trying to do (and why)
- ~~What happened~~ 👉 *Alright, I can see that from your original message.*
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by mattadav** [comment] 2016-05-10 01:56
Hello,
I see the same problem.  Notes for Debug:
* Trying to install the kraken package from homebrew-science with:
  -> brew install kraken
* Recently upgraded to El Capitan from Yosemite
* Ran xcode-select --install 
* brew update at the latest (run several times)
* brew doctor clean except for warnings about tcl libs in /usr/local

**Comment by schultzm** [comment] 2016-05-10 02:01
Hi,

Thanks for the response.  I was running 
`brew install gubbins`

Instructions here: [https://github.com/sanger-pathogens/gubbins/blob/master/INSTALL.md#osx---mavericks-109--yosemite-1010--el-capitan-1011](url)
### OSX - Mavericks (10.9) & Yosemite (10.10) & El Capitan (10.11)

Install HomeBrew. It requires a minimum of Xcode 5.1.1 (xcodebuild -version). Then run:

```
brew tap homebrew/science
brew install gubbins

```

**Comment by UniqMartin** [comment] 2016-05-10 02:20
Thanks! That's sufficient information to reproduce the issue! It's caused by some refactoring we've done recently. Sorry that this is causing some problems. I won't be able to fix this myself (it's way too late where I am), but I'll try to leave enough information for some other maintainer to pick this up:

- The method `non_apple_gcc_version` lives in `OS::Mac`, but is accessed via `@versions == DevelopmentTools` in [`CompilerSelector#compiler_version` (in `compilers.rb`)](https://github.com/Homebrew/brew/blob/500f9eada854c1939bf9a0caf94085214c9399b0/Library/Homebrew/compilers.rb#L135-L142). This needs to be addressed somehow.

- The method [`clear_version_cache` in `os/mac.rb`](https://github.com/Homebrew/brew/blob/500f9eada854c1939bf9a0caf94085214c9399b0/Library/Homebrew/os/mac.rb#L121-L125) also needs some attention. It clears caches that are mostly somewhere else now and thus the method no longer works as intended.

cc @mikemcquaid

**Comment by nomoon** [comment] 2016-05-10 04:21
This appears to break Imagemagick compilation too.

**Comment by nomoon** [comment] 2016-05-10 04:31
Is there a way to rollback to a functional version of Homebrew?

**Comment by ilovezfs** [comment] 2016-05-10 14:46
@nomoon cd /usr/local ; git reset --hard @{2.days.ago} (or whatever the minimum that is required) and add HOMEBREW_NO_AUTO_UPDATE=1 to your profile temporarily.

**Comment by UniqMartin** [comment] 2016-05-10 14:52
Everyone: The bug should have been fixed by https://github.com/Homebrew/brew/commit/5c1f463ac0f1ac8b3dffc5d235071f9759aa5633. Please `brew update` and try again. Closing as resolved, but happy to reopen if there's still an issue. Thanks!

**Closed by UniqMartin** 2016-05-10 14:52 UTC
Labels: bug

**Comment by UniqMartin** [comment] 2016-05-10 14:56
> […] and add HOMEBREW_NO_AUTO_UPDATE=1 to your profile temporarily.

@ilovezfs This shouldn't be necessary. The auto-update code isn't yet switched on by default.

**Comment by ilovezfs** [comment] 2016-05-10 14:59
@UniqMartin Ah, so the apocalypse hasn't started yet then.

**Comment by mikemcquaid** [comment] 2016-05-10 15:01
@ilovezfs Currently the only person it is annoying is me (and I wrote it).
