### ISSUE TITLE
Error: undefined method `ohai_stdout_or_stderr' on OS X 11.2 (Big sur)

### ISSUE THREAD

**Issue by thobson** [Homebrew/homebrew-core#70512] opened 2021-02-05 15:24 UTC
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

https://gist.github.com/thobson/7c033bff85844af109c8dab9e00bfb8f

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Run brew upgrade

**What happened (include all command output)?**

Error: undefined method `ohai_stdout_or_stderr' for #<ReporterHub:0x00007fc48cb92208>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:505:in `dump'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:148:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

**What did you expect to happen?**

Successful update / upgrade

**Step-by-step reproduction instructions (by running `brew` commands)**

$ brew upgrade

**Comment by carlocab** [comment] 2021-02-05 15:26
Duplicate of https://github.com/Homebrew/brew/issues/10536.

**Closed by carlocab** 2021-02-05 15:26 UTC
Labels: bug
