### ISSUE TITLE
Cannot upgrade node

### ISSUE THREAD

**Issue by Zearin** [Homebrew/homebrew-core#28423] opened 2018-05-29 13:47 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Upgrade node.  (I like to keep it up to date.)

- What happened (include command output)

```
 brew upgrade node
==> Upgrading 1 outdated package, with result:
node 10.1.0 -> 10.2.1
Error: node contains conflicting version recursive dependencies:
  openssl@1.1, openssl
View these with `brew deps --tree node`.
```

So, I did just that.

```
  brew deps --tree node
node
└── icu4c
```

I’ve seen this `icu4c` formula many times, but I didn’t remember what it was for.  So I looked into it.

```
  brew info icu4c
icu4c: stable 61.1 (bottled), HEAD [keg-only]
C/C++ and Java libraries for Unicode and globalization
http://site.icu-project.org/
/usr/local/Cellar/icu4c/61.1 (249 files, 67.2MB)
  Poured from bottle on 2018-03-29 at 12:58:59
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/icu4c.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig
```

- What you expected to happen

Upgrades usually complete without any problem.

- Step-by-step reproduction instructions (by running `brew install` commands)

Same as above. ☹ 

```
  brew install node
Error: node contains conflicting version recursive dependencies:
  openssl@1.1, openssl
View these with `brew deps --tree node`.
```

## `brew config` output

```
  brew config
HOMEBREW_VERSION: 1.6.6-24-g315ccf6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 315ccf604fc69f119aa40cc6a37d3fc6c29f7af3
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe3c4060826048d4fa765e576be2840077ab96a4
Core tap last commit: 20 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: mate --wait 
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.1
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3.1
XQuartz: 2.7.11 => /opt/X11
```

## `brew dr` output

```
  brew dr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /usr/local/opt/pkg-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```

I’m not sure how `/usr/local/opt/pkg-config` got there.  Almost all open source software on my system is installed via Homebrew. (Exceptions for `npm` or `pip3` packages, which keep to themselves—except for a few edge cases, which I’m 99.9% certain are not responsible for putting `pkg-config` into `/usr/local/opt`.)

I have installed Inkscape (but _not_ with `brew cask`) and MacTeX (_with_ `brew cask`, version 2018.0417—which, I believe, plays nice with Homebrew these days). 

## `brew gist-logs node` output

```
 brew gist-logs node
Error: No logs.
```

**Comment by ilovezfs** [comment] 2018-05-30 05:17
Can you `brew upgrade` now that node `10.3.0` is out?

**Comment by Zearin** [comment] 2018-05-30 16:09
Nope. :( 


```
 brew upgrade node && brew cleanup
==> Upgrading 1 outdated package, with result:
node 10.1.0 -> 10.3.0
Error: node contains conflicting version recursive dependencies:
  openssl@1.1, openssl
View these with `brew deps --tree node`.
```

**Comment by Zearin** [comment] 2018-06-02 14:46
Still getting this error.

Just remembered I can share the following:

```
 brew uses --installed openssl
casperjs                     ffmpeg                       libssh                       pipenv                       rtmpdump
csvkit                       gobject-introspection        node                         python                       ruby
csvtomd                      libevent                     phantomjs                    python@2                     tmux

 brew uses --installed openssl@1.1
node
```

Can I uninstall and reinstall node without losing my globally installed npm packages?  (If it might fix this?)

**Comment by Zearin** [comment] 2018-06-05 13:38
Uninstalling and reinstalling solved my problem.  

Since `node` has the option `--with-openssl@1.1`, I guess I must have done that at some point (although I don’t remember it).  

If Homebrew is going to offer this installation option, perhaps someone could investigate why installing `node --with-openssl@1.1` prevents upgrading to future versions of `node`.

**Comment by anvil008** [comment] 2018-06-12 13:51
Facing the same issue, however in my case uninstalling and reinstalling does not fix the issue. Thou I am on macOS 10.14 Beta so 🤔

**Comment by anvil008** [comment] 2018-06-23 13:12
Tried on High Sierra, and everything is fine, I believe it's related to the Beta Xcode Command Line Tools in macOS 10.14.

**Comment by T-Jedsada** [comment] 2018-06-25 19:44
Try install by file.pkg

https://nodejs.org/en/download/

**Comment by ckizer** [comment] 2018-07-05 10:06
Any fix for 10.14?

**Comment by ilovezfs** [comment] 2018-07-05 12:28
@ckizer did you install /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by wilomgfx** [comment] 2018-07-07 19:14
@ilovezfs i did and still does not work

**Comment by FradSer** [comment] 2018-07-09 03:22
@ilovezfs so do I. Installed but does not work.

**Comment by pistantan** [comment] 2018-07-09 13:12
Hi guys,

If in your error trace you happen to see a zlib related problem, then this below did it for me:

https://stackoverflow.com/a/51050640/8658008

```
brew install zlib
brew link zlib --force

#python 3
brew (re)install python3
brew postinstall python3
brew link python3 #just in case...

#python 2
brew (re)install python2
brew link python2 #just in case...
```

Seems the problem is the linking of the zlib.

**Comment by wilomgfx** [comment] 2018-07-11 15:33
I was able to make it install node by doing

`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
`
followed by
`brew reinstall python@2`

took about 5 mins to complete on my late 2016 15 inch MBP with touchbar

**Comment by ilovezfs** [comment] 2018-07-11 15:49
Closing since the original issue is resolved and has nothing to do with the ongoing conversations about 10.14

**Closed by ilovezfs** 2018-07-11 15:49 UTC
