### ISSUE TITLE
Problem with get_iplayer 3.14

### ISSUE THREAD

**Issue by therealmarcuslynch** [Homebrew/homebrew-core#27742] opened 2018-05-11 07:00 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [y ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ y] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ y] ran `brew update` and can still reproduce the problem?
- [ y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [y ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Run get_iplayer 3.14 after upgrade
- What happened (include command output)
Unable to read metadata (as with get_iplayer 3.13 via Homebrew)
Unable to download programs (unlike get_iplayer 3.13 via Homebrew)
- What you expected to happen
Read metadata and download programs
- Step-by-step reproduction instructions (by running `brew install` commands)
Dinky on get_iplayer forums says, “However, this is a Homebrew problem, so you need to tell them. They apparently didn't read the release notes and released a broken v3.14 package. As you can see in the logs, their v3.13 package was partially broken as well. The fact it (mostly) worked was a happy accident. It is up to them to fix it.” and “The underlying problem is broken HTTPS support. A couple of users have already reported it in Homebrew issue tracker.” I am another reporting it to you.

Many thanks.

**Comment by SMillerDev** [comment] 2018-05-11 07:05
Thanks for the report, this is however a duplicate of https://github.com/Homebrew/homebrew-core/issues/27706

**Comment by therealmarcuslynch** [comment] 2018-05-11 07:08
Thanks

**Closed** 2018-05-11 07:09 UTC
