### ISSUE TITLE
Install bottle from URL fails cask load, then is treated as a formula

### ISSUE THREAD

**Issue by wathenj** [Homebrew/homebrew-core#78279] opened 2021-05-28 22:05 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.1.9-58-g7ae9cc3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7ae9cc346788ab7a022f033df08943df52e60273
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 125b1393f65b09b80a1705205519ead555d1e550
Core tap last commit: 29 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 10.0.1 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 11.3.1.


Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  nscli

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/jame6972/.pyenv/shims/python2-config
  /Users/jame6972/.pyenv/shims/python3.7-config
  /Users/jame6972/.pyenv/shims/python2.7-config
  /Users/jame6972/.pyenv/shims/python3.7m-config
  /Users/jame6972/.pyenv/shims/python3.9-config
  /Users/jame6972/.pyenv/shims/python-config
  /Users/jame6972/.pyenv/shims/python3-config
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install or upgrade a brew-managed package, given a bottle URL. I was originally troubleshooting an internal package that is not publicly available, but I've reproduced it with wget. 

### What happened (include all command output)?

$ brew install https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Downloading https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/ae4e6f1dc4ecaf2bbed7700e8d64cdc671bf9d6c085ba335f119861fd15956fe?response-
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
Already downloaded: /Users/jame6972/Library/Caches/Homebrew/downloads/0c68c13b926cbe838d8f6b127b2ad51cb631bd0bf01b19dd0717104ac780b3f9--wget-1.21.1.mojave.bottle.tar.gz
==> Pouring the cached bottle
==> Downloading https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
######################################################################## 100.0%
Error: Failed to load cask: https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
Cask 'wget-1.21.1.mojave.bottle.tar.gz' is unreadable: /Users/jame6972/Library/Caches/Homebrew/Cask/wget-1.21.1.mojave.bottle.tar.gz:1: Invalid char `\x1F' in expression
/Users/jame6972/Library/Caches/Homebrew/Cask/wget-1.21.1.mojave.bottle.tar.gz:1: invalid multibyte char (UTF-8)
Warning: Treating https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz as a formula.
🍺  /usr/local/Cellar/wget/1.21.1: 88 files, 4MB

$ brew upgrade --force-bottle https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 3 formulae.

==> Downloading https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
Already downloaded: /Users/jame6972/Library/Caches/Homebrew/downloads/0c68c13b926cbe838d8f6b127b2ad51cb631bd0bf01b19dd0717104ac780b3f9--wget-1.21.1.mojave.bottle.tar.gz
==> Pouring the cached bottle
==> Downloading https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
Already downloaded: /Users/jame6972/Library/Caches/Homebrew/downloads/0c68c13b926cbe838d8f6b127b2ad51cb631bd0bf01b19dd0717104ac780b3f9--wget-1.21.1.mojave.bottle.tar.gz
==> Pouring the cached bottle
==> Downloading https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
######################################################################## 100.0%
Error: Failed to load cask: https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
Cask 'wget-1.21.1.mojave.bottle.tar.gz' is unreadable: /Users/jame6972/Library/Caches/Homebrew/Cask/wget-1.21.1.mojave.bottle.tar.gz:1: Invalid char `\x1F' in expression
/Users/jame6972/Library/Caches/Homebrew/Cask/wget-1.21.1.mojave.bottle.tar.gz:1: invalid multibyte char (UTF-8)
Warning: Treating https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz as a formula.
Warning: wget 1.21.1 already installed

### What did you expect to happen?

To successfully install/upgrade from bottle without fallback to formula. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
or
brew upgrade --force-bottle https://homebrew.bintray.com/bottles/wget-1.21.1.mojave.bottle.tar.gz
```

**Comment by nandahkrishna** [comment] 2021-05-28 23:09
Formulae cannot be installed from URLs (https://github.com/Homebrew/brew/pull/7660), whereas Casks can. That's why you're seeing the Cask-related error. If you want to install from a bottle, you can download it locally and use (example):
```
brew install ./ant--1.10.10.all.bottle.tar.gz
```
(The filename differs because I downloaded the bottle from GitHub Packages instead.)

**Comment by wathenj** [comment] 2021-05-28 23:46
Thanks for the info. I'm still trying to fully learn and understand homebrew features. So a bottle would be considered a formula in this regard? We noticed our process was working until somewhere around the 3.0 release and a colleague made a separate issue in Sept. ([Homebrew/brew#8743](https://github.com/Homebrew/brew/issues/8743)) where we had a different problem, but which used the same process.

Could there have been another change after that time where this could have been affected? Or perhaps bottles were incorrectly identified as casks? Just trying to think of ideas. 

Otherwise, not a big deal, we can support having an additional step to download the bottle first, but I'd like to keep installation steps as simple as possible for our users.

**Comment by MikeMcQuaid** [comment] 2021-05-31 11:28
Closing as not a bug.

> Otherwise, not a big deal, we can support having an additional step to download the bottle first, but I'd like to keep installation steps as simple as possible for our users.

@wathenj why not let Homebrew download (and checksum) the bottle for you? What are you trying to do here?

**Closed** 2021-05-31 11:28 UTC
Labels: bug

**Comment by wathenj** [comment] 2021-05-31 16:16
We just have an internal tool that we distribute/install through brew. I believe we also have an internal tap set up, but we moved away from using this due to some complication that I'm honestly not familiar with. So the preferred method was to install using the URL of the internally hosted bottle. If this is no longer allowed, it sounds like our solutions are to either download the bottle locally and install from the local file, or re-investigate if whether all of our users can use the tap.

**Comment by SMillerDev** [comment] 2021-05-31 16:20
Seeing how taps are really just directories with some folders I'm not entirely sure how that could be more complicated than using bottle urls.

**Comment by wathenj** [comment] 2021-05-31 16:58
I still have a lot to learn so I'm not familiar with what it takes to create a tap. If I recall correctly, I think it was more permission related as the tap exists as a repo within our internal github and only certain organizations within the company are allowed to even access our github. So it became a challenge to apply appropriate permissions to the people that needed it. Because of that, we simply bottled the tool and hosted it for people to reference the URL when installing or upgrading.

**Comment by MikeMcQuaid** [comment] 2021-06-01 13:08
Yes, the way you're trying to use bottles are not supported or recommended, sorry.

**Comment by MikeMcQuaid** [comment] 2021-06-01 13:08
You're also entirely bypassing the checksumming security which seems like a bad idea.

**Comment by wathenj** [comment] 2021-06-01 14:59
Alright, understood. Thank you very much for the help! We'll modify how we're implementing this.
