### ISSUE TITLE
bash-completion@2 errors on login and completion of paths with cd etc

### ISSUE THREAD

**Issue by gramtech** [Homebrew/homebrew-core#25370] opened 2018-03-16 15:34 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
The issue is with bash-completion@2
After installing bash-completion@2 and added the entry it suggests into my .bash_profile I get an error each time a new terminal is opened and when doing tab completion 
for example -  cd somedir<tab> 

- What happened (include command output)
After starting the a new terminal session I see the following error:

```
Last login: Fri Mar 16 15:07:52 on ttys003
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
MacBook-Pro:~ me$
```
when "cd myd tab" i get the following error

```
example command as done below 'cd myd<tab>'

MacBook-Pro:~ me$ mkdir mydir
MacBook-Pro:~ me$ cd myd-bash: printf: `words[0]': not a valid identifier
-bash: printf: `words[1]': not a valid identifier
-bash: compopt: command not found

```

- What you expected to happen
To not get errors on each new terminal session / login
for the above example for the folder name to complete

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install bash
brew install bash-completion@2
```
Then added the following to ~/.bash_profile

```
if [ -f /usr/local/share/bash-completion/bash_completion ]; then
    . /usr/local/share/bash-completion/bash_completion
fi
```
I then get the errors described above. Removing the above lines from my .bash_profile stops the errors and this is currently the only thing in my bash_profile.

Output of some brew commands requested above:

brew update
```
MacBook-Pro:~ me$ brew update
Updated 1 tap (caskroom/cask).
No changes to formulae.
MacBook-Pro:~ me$
```

brew doctor
```
MacBook-Pro:~ me$ brew doctor
Your system is ready to brew.
MacBook-Pro:~ me$
```

brew gist-logs bash-completion@2
```
MacBook-Pro:~ me$ brew gist-logs bash-completion@2
Error: No logs.
MacBook-Pro:~ me$
```

Please let me know if you need any more information

**Comment by fxcoudert** [comment] 2018-03-16 16:50
I can't reproduce this… are you sure you're using Homebrew's bash, and not macOS bash?

**Comment by gramtech** [comment] 2018-03-16 17:05
I am using ( or at least should be) bash from brew 

I've been looking more on the net since posting this and from what it looks like, the install of bash from brew is not changing the users shell, bash is correctly in $PATH however.

I have just discovered I can "fix" the issue by doing the following:
```
# Add the new shell to the list of allowed shells
sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
# Change to the new shell
chsh -s /usr/local/bin/bash 
```

I got this from https://github.com/mathiasbynens/dotfiles/issues/536 which also links to http://clubmate.fi/upgrade-to-bash-4-in-mac-os-x/

Is this not something that can or should be done as part of the bash install (I realise root will be needed which is generally avoided with brew installs) ?

**Comment by gramtech** [comment] 2018-03-16 17:09
Further details,  I have tried this on two different machine (both High Sierra)

As well as with the MacOS default terminal and iTerm

**Comment by fxcoudert** [comment] 2018-03-17 13:48
`brew info bash` and `brew install bash` both say:

```
==> Caveats
In order to use this build of bash as your login shell,
it must be added to /etc/shells.
```

We could possibly amend `bash-completion@2`'s caveat to say:

```
Add the following to your ~/.bash_profile:
  if [ "${BASH_VERSINFO}" -ge 4 ] && [ -f /usr/local/share/bash-completion/bash_completion ]; then
    . /usr/local/share/bash-completion/bash_completion
  fi
```

**Comment by apjanke** [comment] 2018-03-18 05:14
@gramtech: That "fix" with modifying `/etc/shells` and doing `chsh` is the normal way of using the Homebrewed `bash` by default instead of the system `bash`. (When I say "by default", I mean what gets launched when you open a new terminal.) Its presence on `$PATH` is *not* sufficient to make it the default shell used when your terminal starts up; `$PATH` only affects what happens when you explicitly type `bash` at a command line in a shell that's already running. The "login" shell selection does not care about `$PATH`.

You can also configure your terminal program to use a specific shell instead of the default login shell. This is done in "profiles" in Terminal.app and iTerm.

It's unfortunate that this is not a smoother installation experience. Sorry.

Maybe the `brew info bash` caveats should be expanded to mention `chsh` as well as modifying `/etc/shells`? Or point you to a web page that explains how to configure multi-version `bash` with Homebrew? Because you really need to do that too if you want to use the brewed `bash` by default; changing `/etc/shells` alone is not sufficient. *On the other hand*, that can lead to some frustrating breakage scenarios if you don't have advanced sys configuration skills. (E.g. if you change your shell and then blow away Homebrew or uninstall the brewed `bash`, basically all your terminals will break in ways that are annoying to fix, and we can't guard against that. And Homebrew tries hard to make sure none of its stuff breaks your base system.) That plus the need for root access is a good reason to not make it the default, IMHO. Again, it's unfortunate that this isn't smoother, but there are Reasons. But we could probably explain it better.

@fxcoudert: Adding that guard code sounds like a good idea to me.

This (along with notes on `zsh` and `fish` configuration) seems maybe worthy of its own doco page under https://github.com/Homebrew/brew/tree/master/docs.

**Comment by ilovezfs** [comment] 2018-03-18 05:26
The description of the formula is "Programmable completion for Bash 4.1+". Not printing the caveat just because the user hasn't already set up bash 4.1 seems pretty weird to me. At that point we might as well block installation since it's not going to work without the caveat.

In any case closing, as this is a local configuration issue which is now solved.

**Closed by ilovezfs** 2018-03-18 05:26 UTC
