### ISSUE TITLE
lsof has moved to GitHub and has a new release

### ISSUE THREAD

**Issue by lrosenman** [Homebrew/homebrew-core#39572] opened 2019-05-07 16:49 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
   Upgrade lsof to 4.93.1 (from https://github.com/lsof-org)
- What happened (include command output)
   current release in homebrew is 4.91
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I'm not comfortable enough with updating this formula since we'd be changing the origin, etc.

**Comment by SMillerDev** [comment] 2019-05-07 17:30
docs.brew.sh is there to help. We won't merge your pull request if it's wrong so you got nothing to lose. Except this issue, that's gonna be closed cause it's not according to the rules.

**Comment by fxcoudert** [comment] 2019-05-08 11:13
The problem is that it's not clear that the github repo you link to (https://github.com/lsof-org/lsof) is the official continuation of the project. It is described as:

> lsof-org at GitHub team takes over the maintainership of lsof originally maintained by Vic Abell

and darwin (macOS) is listed as “not maintained”. So I don't know who is behind that fork, but it's not clear we want to switch to it (and it does not appear to be popular either).

**Comment by fxcoudert** [comment] 2019-05-09 11:57
That's good to know, sorry for misunderstanding the situation here. We're happy to get more information for our records, can you point to a mailing-list post that clarifies the current situation?

**Comment by lrosenman** [comment] 2019-05-09 12:10
the github repo is the *OFFICIAL* webpage now.

lsof.itap.purdue.edu (the former home) has been shutdown.

**Comment by lrosenman** [comment] 2019-05-09 12:18
from: https://lists.purdue.edu/mailman/private/lsof-l/2018-June/000437.html

SInce the archives are closed:
Jan Rybar jrybar at redhat.com 
Mon Jun 11 13:14:24 EDT 2018
Previous message: [LSOF-L] Move lsof to github
Next message: [LSOF-L] Move lsof to github
Messages sorted by: [ date ] [ thread ] [ subject ] [ author ]
I can represent Fedora Linux and Red Hat Linux.

As for Github repository, it seems that a repository can be 
administrated by a group as an entity.
E.g. logrotate (https://github.com/logrotate), i.e. a group of 
administrators as representatives with same privileges.
Hence no actual responsibility on an individual (if that is satisfactory 
approach).

Jan

On 06/11/2018 04:29 PM, Victor Abell wrote:
> I have initiated a contact with the Purdue Research Foundation to
> discover who can discuss the release of lsof to GitHub.
> 
> I need to know who should be involved in the discussion.  Please
> let me know who will take responsibility for the GitHub archive.
> 
> Vic
> 
> -----Original Message-----
> From: lsof-l-bounces at lists.purdue.edu [mailto:lsof-l-bounces at lists.purdue.edu] On Behalf Of Jan Rybar
> Sent: Monday, June 11, 2018 6:01 AM
> To: lsof-l at lists.purdue.edu
> Subject: Re: [LSOF-L] Move lsof to github
> 
> Hello,
> 
> knowing about Masatake's repository, I didn't know it could be considered 'official', and as far as I know (and I may be mistaking) it's only linux-oriented.
> 
> Turning back to our previous discussion, you mentioned the following:
> "While lsof is free software,
> It does have a copyright that is owned by the Purdue University Research Foundation.
> There will obviously have to be negotiations with that office..."
> 
> I believed the Purdue's consent is required to move lsof officially to an open CVS so the community from all platforms can continue contributing to the project.
> 
> Can a discussion with someone from Purdue concerned be arranged? Or probably can be added to CC to this thread?
> 
> Thanks.
> 
> Jan Rybar
> 
> On 06/10/2018 04:41 PM, Victor Abell wrote:
>> Jan,
>>
>> I thought Masatake YAMATO might answer your query before I returned
>> home.  He <masatake at gmail.com> and Peter Schiffer
>> <pschiffe at redhat.com>  have established a GitHub account with the name
>> lsof-org.
>>
>> Contact one of them for more information.
>>
>> Vic
>>
>> -----Original Message-----
>> From: lsof-l-bounces at lists.purdue.edu
>> [mailto:lsof-l-bounces at lists.purdue.edu] On Behalf Of Jan Rybar
>> Sent: Thursday, June 07, 2018 9:19 AM
>> To: lsof-l at lists.purdue.edu
>> Subject: Re: [LSOF-L] Move lsof to github
>>
>> Is it possible to provide some specific contacts to people from Purdue with whom it is possible to discuss the future of lsof and moving it to online VCS service (Github/Gitlab)?
>> Since it is copyrighted and Vic is planning to end his work on general lsof revision releases, some actions should be taken to keep the community around lsof live and agile.
>>
>> Please correct me if I'm wrong.
>>
>> Jan Rybar
>>
>> ----- Original Message -----
>> From: "Steve Bonds" <rxzk33rm3q at snkmail.com>
>> To: lsof-l at lists.purdue.edu
>> Sent: Monday, February 12, 2018 4:24:59 PM
>> Subject: Re: [LSOF-L] Move lsof to github
>>
>> It would be great for Vic and/or Purdue to give a GitHub location their official support, especially if Vic will be taking on a lesser role. I know in the past I've had to whip up unofficial patches to get lsof working on some of the more obscure platforms. They didn't always make it back to the mainstream since often these were "make it work for this specific problem" fixes. However, a place like GitHub makes it much simpler to report problems and suggest fixes-- often a specific one-off fix can make for a great example of how to do a better, more general fix.
>>
>> -- Steve Bonds
>>
>> On Mon, Feb 12, 2018 at 5:07 AM, Jan Rybar jrybar-at-redhat.com |lsof-l 20100415/ ***************** | < tbsyusteft at sneakemail.com > wrote:
>>
>>
>> Hello Vic,
>>
>> Thanks for reply, my comments are below.
>>
>> On 02/08/2018 09:42 PM, Victor Abell wrote:
>>
>>
>> Jan,
>>
>> Rather than forwarding your posting to lsof-l, since it contains comments directed to me, I will try to answer it directly.
>>
>> You write:
>>
>>
>>
>> I noticed that the last release of lsof took place back in 2015 and the process to download the archives can sometimes be > cumbersome due to timeouts and inaccessibility of servers at Purdue University.
>>
>> There are two comments there. First, you are partly correct that the last lsof revision release was 2015, but there have been 17 lsof 4.90 pre-releases for FreeBSD. Why so many pre-releases?
>> That's because the FreeBSD lsof packager has made FreeBSD tests systems available to me at three different system releases and he has readily made packages with which FreeBSD users can access the pre-releases.
>>
>> I think this is one of many advantages a public git repository offers. All the changes are visible to all and can be pulled, compiled and tested right away. For any platform.
>>
>>
>>
>>
>> I have absolutely no Linux test systems and have not had any since mid-2015. (But see my later comment about my current temporary test system access.) The disappearance of a Linux test system prevented the planned release of lsof revision 4.90 in 2016. Since then I have made only the FreeBSD pre-releases.
>>
>> Again, all changes can be tested in pre-release rolling-release-based Linux distributions, e.g. Arch or Fedora Rawhide which, in my opinion, exists for this purpose.
>>
>>
>>
>>
>> Second, no FreeBSD community member has noted any problem obtaining the pre-releases from the lsof.itap.purdue.edu ftp server. Because that system has come under continuous and extensive root attack via SSH, it has been armored to resist attacks. In particular, specific IP addresses have been diverted Solaris calls blackhole routes. It is possible that the timeouts and inaccessible instances you report have come from those blocked addresses.
>>
>>
>> Github/Gitlab (whatever) is an online project that is used by dozens of huge and important projects and offers great yet protected accessibility, not speaking about decentralized approach of git.
>>
>>
>>
>>
>>
>> I believe it might be time to make lsof more open in terms of moving the source code to a git repository available online, >so any contributor can send pull requests that would be tracked.
>> Also preparing releases for download, e.g. at SourceForge or elsewhere would become much easier and the process could >become more automated.
>>
>> I'm sorry, but I don't agree. I am very close to making the last lsof revision release. I will reach 80 years of age later this year and I think it's time for me to end my work on general lsof revision releases. I will probably continue with the FreeBSD pre-releases as long as I can, because that system's package maintainer has been so helpful. In any case it makes no sense for me to develop new distribution methods.
>>
>> There is almost nothing you need to do. The technical side of things consists of loading the current source code to git, which can be done by anybody (I would be honored to do it myself).
>>
>>
>>
>>
>>
>>
>> I started about this because of bugfixes I would like to contribute with and it took me quite some time to verify whether >they're already fixed in latest release which I wasn't able to download from official upstream page.
>>
>> Well you certainly could have contacted me via e-mail and asked about the bugs. Over the years many contributors have done so. The last lsof revision will contain a significant contribution to Linux lsof from a Japanese user who has arranged with Peter Schiffer of redhat.com for a temporary test system which I am currently using to test the contribution.
>>
>> I took the mailing list way because I believe the maintainers for other platforms/distributions might be interested as well. Why not to use mailing list since it still exists.
>>
>>
>>
>>
>>
>>
>> Thank you a lot and I'm looking forward to your replies/ideas.
>>
>> I hope I have given you a sense of where my efforts and attention to lsof reside. I do not know what will happen to lsof after I no longer look after it. While lsof is free software, It does have a copyright that is owned by the Purdue University Research Foundation.
>> There will obviously have to be negotiations with that office were someone other than a Purdue person to take over lsof maintenance and development.
>>
>> Thank you for your answers. I appreciate that.
>> To the legal part, I believe copyright should not be a problem. GitHub seems to support BSD-licensed sources.
>> Please correct me if I'm wrong.
>> Can you please propose a contact to someone with whom the negotiations should be lead?
>>
>> If you plan to divert your attention away from lsof code, I think it would be nice if the community took care of your legacy.
>> Thank you very much.
>>
>>
>>
>>
>>
>> Regards,
>>
>> Vic Abell
>>
>> _______________________________________________
>> LSOF-L mailing list
>> LSOF-L at lists.purdue.edu
>> https://lists.purdue.edu/mailman/listinfo/lsof-l
>>
>> _______________________________________________
>> LSOF-L mailing list
>> LSOF-L at lists.purdue.edu
>> https://lists.purdue.edu/mailman/listinfo/lsof-l
>>
>>
>> _______________________________________________
>> LSOF-L mailing list
>> LSOF-L at lists.purdue.edu
>> https://lists.purdue.edu/mailman/listinfo/lsof-l
>> _______________________________________________
>> LSOF-L mailing list
>> LSOF-L at lists.purdue.edu
>> https://lists.purdue.edu/mailman/listinfo/lsof-l
>>
>> _______________________________________________
>> LSOF-L mailing list
>> LSOF-L at lists.purdue.edu
>> https://lists.purdue.edu/mailman/listinfo/lsof-l
>>
> _______________________________________________
> LSOF-L mailing list
> LSOF-L at lists.purdue.edu
> https://lists.purdue.edu/mailman/listinfo/lsof-l
> 
Previous message: [LSOF-L] Move lsof to github
Next message: [LSOF-L] Move lsof to github
Messages sorted by: [ date ] [ thread ] [ subject ] [ author ]
More information about the LSOF-L mailing list

**Comment by zbeekman** [comment] 2019-05-15 21:52
We should make the homebrew version keg_only, either way as mojave ships with `/usr/sbin/lsof`. I just signed up for the mailing list to confirm.

**Comment by zbeekman** [comment] 2019-05-15 21:54
also the level of patching in 4.91 is not great. @lrosenman Do you know if this is fixed in later versions from the GH repo?

**Comment by lrosenman** [comment] 2019-05-15 23:41
4.93.2 is current.  I'd pull/play with it as is from the repo.

**Comment by lrosenman** [comment] 2019-05-15 23:43
the mojave version is 4.89.  That is *ANCIENT*.  So we shouldn't restrict it to keg_only, IMO.

**Comment by zbeekman** [comment] 2019-05-16 13:26
Our general policy is not to shadow stuff provided by apple, no matter how
ancient, AFAIK. You can always force link it.

**Comment by fxcoudert** [comment] 2019-06-03 10:27
We welcome a pull request to move to a more recent version. Closing this here.

**Closed by fxcoudert** 2019-06-03 10:27 UTC
