### ISSUE TITLE
pipx 1.2.0 does not launch

### ISSUE THREAD

**Issue by homocomputeris** [Homebrew/homebrew-core#151710] opened 2023-10-18 20:26 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs pipx
Error: No logs.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install and use pipx.

### What happened (include all command output)?

pipx

Traceback (most recent call last):
  File "/usr/local/bin/pipx", line 5, in <module>
    from pipx.main import cli
  File "/usr/local/Cellar/pipx/1.2.0/libexec/lib/python3.12/site-packages/pipx/main.py", line 19, in <module>
    from packaging.requirements import InvalidRequirement, Requirement
ModuleNotFoundError: No module named 'packaging'

### What did you expect to happen?

Launch pipx.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install pipx
==> Downloading https://ghcr.io/v2/homebrew/core/pipx/manifests/1.2.0-4
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/0ee9adeb897df47be556d2dcff23aa914dba2b436f241bee1350f0d8d17d0d75--pipx-1.2.0-4.bottle_manifest.json
==> Fetching pipx
==> Downloading https://ghcr.io/v2/homebrew/core/pipx/blobs/sha256:ab7bc10484f1acebdda35d32b0c682f25
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/0bcf0babf7d42163ef4c9e9e46b4a2e42dbe4df9861a9af5f3740fe4491ef1f5--pipx--1.2.0.sonoma.bottle.4.tar.gz
==> Pouring pipx--1.2.0.sonoma.bottle.4.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/pipx/1.2.0: 92 files, 591.2KB
==> Running `brew cleanup pipx`...

pipx
Traceback (most recent call last):
  File "/usr/local/bin/pipx", line 5, in <module>
    from pipx.main import cli
  File "/usr/local/Cellar/pipx/1.2.0/libexec/lib/python3.12/site-packages/pipx/main.py", line 19, in <module>
    from packaging.requirements import InvalidRequirement, Requirement
ModuleNotFoundError: No module named 'packaging'
```

**Comment by henryiii** [comment] 2023-10-18 20:59
Same basic issue with `cookiecutter`, but with `pyyaml`. I was able to fix it by running `brew reinstall pyyaml`, which gave me the missing Python 3.12 parts. I think you might be able to fix this with `brew reinstall python-packaging`. Not sure why those parts are missing, though, that seems like a brew bug.

**Comment by henryiii** [comment] 2023-10-18 21:03
I think this is due to https://github.com/Homebrew/homebrew-core/issues/151248, which looks like there's ongoing work to fix.

**Comment by cho-m** [comment] 2023-10-19 18:06
Probably meant issue #151657 with PR #151697 to force upgrade. Root cause is same so going to close this as duplicate. You can track issue/PR or use workaround of reinstalling.

**Closed by cho-m** 2023-10-19 18:06 UTC
Labels: bug
