### ISSUE TITLE
parallel --csv option does not work: "Can't locate object method "new" via package "Text::CSV""

### ISSUE THREAD

**Issue by slhck** [Homebrew/homebrew-core#94775] opened 2022-02-09 11:56 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config.


HOMEBREW_VERSION: 3.3.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a787e45ff45583fb245030757296548f82c1cbd
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e120c6936cdc59811733a73321378e48408cda21
Core tap last commit: 39 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.35.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: false
```

brew doctor:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/werner/.pyenv/shims/pythran-config
  /Users/werner/.pyenv/shims/python3.10-config
  /Users/werner/.pyenv/shims/python3.9-config
  /Users/werner/.pyenv/shims/python-config
  /Users/werner/.pyenv/shims/python3-config
  /Users/werner/.pyenv/shims/pre-commit-validate-config
  /Users/werner/.pyenv/shims/python3.8-config
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run the CSV example from GNU parallel's manpage:

```bash
echo '"1 big, 2 small","2""x4"" plank",12.34' | parallel --csv echo {1} of {2} at {3}
```

### What happened (include all command output)?

```
Can't locate object method "new" via package "Text::CSV" (perhaps you forgot to load "Text::CSV"?) at /opt/homebrew/bin/parallel line 1902.
```

### What did you expect to happen?

I expected to get the correct output.

When I run:

```bash
perl -MCPAN -e'install Text::CSV'
```

the example works.

Since it's missing a library, but the documentation does not mention that one would have to install this, I could think of the following solutions:

- the Text::CSV module should be installed by default (but it seems that parallel does not depend on Homebrew perl, so this is unlikely), or
- there should be a caveat that full functionality is only possible with this module (including instructions on how to install it)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install perl
brew install parallel
echo '"1 big, 2 small","2""x4"" plank",12.34' | parallel --csv echo {1} of {2} at {3}
```
```

**Comment by carlocab** [comment] 2022-02-09 12:02
Duplicate of https://github.com/Homebrew/homebrew-core/issues/76163

**Comment by carlocab** [comment] 2022-02-09 12:03
See also https://github.com/Homebrew/homebrew-core/pull/76365

**Comment by slhck** [comment] 2022-02-09 12:40
Oh, I mistakenly did not search in the closed issues for this.

**Comment by slhck** [comment] 2022-02-09 12:42
Would you be leaning towards accepting a PR that adds this to the caveats?

**Comment by carlocab** [comment] 2022-02-09 13:17
Not opposed to it, yea.

**Comment by slhck** [comment] 2022-02-12 17:43
Addressed in https://github.com/Homebrew/homebrew-core/pull/95018

**Closed** 2022-02-12 17:47 UTC
Labels: bug
