### ISSUE TITLE
tcl-tk failing to install

### ISSUE THREAD

**Issue by webdeck** [Homebrew/homebrew-core#141981] opened 2023-09-11 14:29 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
homebrew@home ~ % brew config
HOMEBREW_VERSION: 4.1.10-31-g96e61c5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96e61c5ba5f53b807dab4f36827176344ad9a662
Last commit: 43 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b8451b4f285e1fc30aae4af206938331cbfdc248
Core tap last commit: 33 minutes ago
Core tap branch: master
Core tap JSON: 11 Sep 14:20 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/emacs
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: N/A
Xcode: 14.3.1
Rosetta 2: false
homebrew@home ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Initially was trying to update tcl-tk and got this error.  I tried removing and reinstalling, and got the same error on install.

### What happened (include all command output)?

```shell
homebrew@home ~ % brew install tcl-tk
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Downloading https://ghcr.io/v2/homebrew/core/tcl-tk/manifests/8.6.13_5
Already downloaded: /Users/homebrew/Library/Caches/Homebrew/downloads/37d4c98d33cbcc1d4c78fd424a96623554b669eca5da2698a376d9b993fd1a86--tcl-tk-8.6.13_5.bottle_manifest.json
==> Fetching tcl-tk
==> Downloading https://ghcr.io/v2/homebrew/core/tcl-tk/blobs/sha256:9954fa13ce6
Already downloaded: /Users/homebrew/Library/Caches/Homebrew/downloads/42d94eaae47354f1774b5f2a759c9d3bf6fb31aa0c23e15862aec70abed7f3f0--tcl-tk--8.6.13_5.arm64_ventura.bottle.tar.gz
==> Pouring tcl-tk--8.6.13_5.arm64_ventura.bottle.tar.gz
Error: Parameter 'old': Expected type Pathname, got type String with value "@@HOMEBREW_PREFIX@@/opt/openssl@3/lib"
Caller: /opt/homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:41
Definition: /opt/homebrew/Library/Homebrew/os/mac/keg.rb:40
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:187:in `report_error'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:116:in `block in validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:201:in `each_args_value_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:41:in `block (3 levels) in relocate_dynamic_linkage'
/opt/homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:138:in `each'
/opt/homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:138:in `each_linkage_for'
/opt/homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:39:in `block (2 levels) in relocate_dynamic_linkage'
/opt/homebrew/Library/Homebrew/extend/pathname.rb:337:in `ensure_writable'
/opt/homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:23:in `block in relocate_dynamic_linkage'
/opt/homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:22:in `each'
/opt/homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:22:in `relocate_dynamic_linkage'
/opt/homebrew/Library/Homebrew/keg_relocate.rb:130:in `replace_placeholders_with_locations'
/opt/homebrew/Library/Homebrew/formula_installer.rb:1287:in `pour'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/formula_installer.rb:437:in `install'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/upgrade.rb:218:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:358:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:303:in `block in install_formulae'
/opt/homebrew/Library/Homebrew/install.rb:302:in `each'
/opt/homebrew/Library/Homebrew/install.rb:302:in `install_formulae'
/opt/homebrew/Library/Homebrew/cmd/install.rb:295:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

tcl-tk installs successfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install tcl-tk
```

**Comment by SMillerDev** [comment] 2023-09-11 14:39
Duplicate of https://github.com/Homebrew/brew/issues/15990

**Closed by SMillerDev** 2023-09-11 14:39 UTC
Labels: bug
