### ISSUE TITLE
docker-credential-helpers: pass variant

### ISSUE THREAD

**Issue by glensc** [Homebrew/homebrew-core#39517] opened 2019-05-04 15:14 UTC
so, [docker/docker-credential-helpers](https://github.com/docker/docker-credential-helpers#available-programs) has also `pass` variant.

how to package this? to existing formula?
1. https://github.com/Homebrew/homebrew-core/blob/9b37cb405386ed11af4cb68130d56ceb5335d413/Formula/docker-credential-helper.rb
2. create new formula: `docker-credential-helper-pass`?

as would be accurate to also install the `pass` dependency that `pass` requires...

**Comment by glensc** [comment] 2019-05-04 15:43
i think separate formula is way to go, because also need to link and overwrite if installing docker-for-mac. and without link doesn't get any program from the formula, not just conflicting ones

```
...
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/docker-credential-osxkeychain
Target /usr/local/bin/docker-credential-osxkeychain
already exists. You may want to remove it:
  rm '/usr/local/bin/docker-credential-osxkeychain'

To force the link and overwrite all conflicting files:
  brew link --overwrite docker-credential-helper

To list all files that would be deleted:
  brew link --overwrite --dry-run docker-credential-helper

Possible conflicting files are:
/usr/local/bin/docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
==> Summary
```

**Comment by zbeekman** [comment] 2019-05-15 20:40
@glensc: Can docker-crednetial-helper be built against both osx-keychain and pass at the same time? Or does it require a different formula?

Also, I saw [your issue on their repo]() that they do not currently support using pass on macOS. If they don't support using pass on macOS, then I'm going to close this as "won't fix" and we can revisit it once docker-credential-helpers supports pass on macOS.

**Comment by glensc** [comment] 2019-05-16 09:54
@zbeekman yes, it can be built two variants from same formula. and to make build need to copy (or rename) two files:
- https://github.com/docker/docker-credential-helpers/issues/146#issuecomment-489337920

however, I think it should be separate formula due to usability issues:
- https://github.com/Homebrew/homebrew-core/issues/39517#issuecomment-489338068

**Comment by Fremont2** [comment] 2019-06-30 03:31
nn

**Comment by Fremont2** [comment] 2019-06-30 03:31
#41468 @girtsf

**Comment by Fremont2** [comment] 2019-06-30 03:33
Duplicate of # @

- [ ] 

- [ ] 

- 

> ### ### 

> _[](url)_

**Comment by Fremont2** [comment] 2019-06-30 03:34
> Duplicate of # @
> 
> * [ ]
> * [ ]
> 
> > 
> 
> > __

:(

**Closed** 2019-09-16 11:57 UTC
