### ISSUE TITLE
Error: podman-desktop: Unexpected run command: 

### ISSUE THREAD

**Issue by stevekennedyuk** [Homebrew/homebrew-core#131287] opened 2023-05-18 10:47 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0dc84b117f54f6b18e0528b95477c54e409ebdd
Last commit: 5 days ago
Core tap JSON: 18 May 10:40 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.167RgrQQuq/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.40.1 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  llvm@11

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pygments
  python-typing-extensions
  gnupg
  protobuf

Warning: You have an unnecessary local Cask tap.
This can cause problems installing up-to-date casks.
Please remove it by running:
  brew untap homebrew/cask
Error: Unexpected run command: 
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:149:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:711:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:684:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:717:in `block in check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:716:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:716:in `check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:60:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew upgrade

### What happened (include all command output)?

podman-deskop doesn't upgrade

### What did you expect to happen?

clean upgrade

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade
```

**Comment by SMillerDev** [comment] 2023-05-18 10:52
Duplicate of literally the latest issue: https://github.com/Homebrew/homebrew-core/issues/131284

**Closed** 2023-05-18 10:52 UTC
Labels: bug
