### ISSUE TITLE
watch: UTF-8 support broken

### ISSUE THREAD

**Issue by zeha** [Homebrew/homebrew-core#7178] opened 2016-11-23 09:17 UTC
### Bug reports:

The watch binary from the watch formula on Sierra fails to display non-ASCII characters (i.e. UTF-8 umlauts, etc.). As this works on Linux, I'd say this is a build environment issue.

Installed from watch-3.3.12.sierra.bottle.tar.gz, also happens when installing with `brew install --HEAD watch`.

### Repro:

```
cat > ~/test.sh <<EOT
echo "höllö!" 
EOT

watch -n2 bash ~/test.sh
```

Notice that the displayed string is either "hllo!" or "h  ll  o!" depending on your Terminal.app settings, but never the expected "höllö!".

**Comment by MikeMcQuaid** [comment] 2016-11-23 12:46
Does it work when built from source outside of Homebrew on macOS?

**Comment by apjanke** [comment] 2016-11-28 00:26
Doesn't work for me when built outside Homebrew either.

I think the issue is that its `configure` logic doesn't recognize macOS's `ncurses` library as providing wide character support, even though it does, and assumes a separate `ncursesw` library is required.

There's an `--enable-watch8bit` configure option which looks like it enables wide character support.

E.g., in `watch.c`:

```
#ifdef WITH_WATCH8BIT
# define _XOPEN_SOURCE_EXTENDED 1
# include <wchar.h>
# include <wctype.h>
#endif	/* WITH_WATCH8BIT */
```

However, when using that switch, configure fails. Looks like it's looking for a separate `ncursesw` library.

```
[~/tmp/procps-ng/procps on ⇄ master]
$ ./configure --prefix=/tmp/test-watch --enable-watch8bit
...
checking for NCURSES... no
checking for initscr in -lncurses... yes
checking for curses.h... yes
checking for ncurses.h... yes
checking for term.h... yes
checking for NCURSESW... no
checking for addwstr in -lncursesw... no
configure: error: Cannot find ncurses wide library ncursesw with --enable-watch8bit
```

Seems like basically the same upstream issue as https://github.com/hishamhm/htop/issues/301.

If I modify the `watch` formula to have `depends_on "homebrew/dupes/ncurses"` (which does have a separate `libncursesw`) and add the `--enable-watch8bit`, then it builds, and UTF-8 display using OP's test code works for me.

Sounds like this should be reported upstream as an incompatibility with macOS's ncurses library.

**Comment by apjanke** [comment] 2016-11-28 00:35
Reported upstream: https://gitlab.com/procps-ng/procps/issues/47

**Comment by MikeMcQuaid** [comment] 2016-11-28 08:25
> I can reproduce zeha's issue. Doesn't work for me when built outside Homebrew either.

Thanks @apjanke. Closing as not a Homebrew issue.

**Closed by MikeMcQuaid** 2016-11-28 08:25 UTC
Labels: upstream issue
