### ISSUE TITLE
swagger-codegen throws java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by fedormatantsev** [Homebrew/homebrew-core#81466] opened 2021-07-18 20:04 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config

HOMEBREW_VERSION: 3.2.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d37d09709b6fbd5b89b468eb0b4438ffa0fb81c
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cf82db6c42f47ecd34dc06d2e2a0e1d4cc017261
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: N/A

% brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I've run the following command with [this api spec](https://raw.githubusercontent.com/TinkoffCreditSystems/invest-openapi/master/src/docs/swagger-ui/swagger.yaml).

`swagger-codegen generate -i $(INTERMEDIATE_DIR)/tinkoff_investing.yaml -l python -o $(INTERMEDIATE_DIR)/tinkoff_investing_client`

### What happened (include all command output)?

```
swagger-codegen generate -i .intermediate/tinkoff_investing.yaml -l python -o .intermediate/tinkoff_investing_client
22:57:47.710 [Thread-0] INFO  i.s.c.v.i.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "Thread-0" java.lang.NoSuchMethodError: 'boolean com.fasterxml.jackson.databind.SerializationConfig.hasExplicitTimeZone()'
        at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.formatValue(InstantSerializerBase.java:144)
        at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.serialize(InstantSerializerBase.java:103)
        at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.serialize(InstantSerializerBase.java:43)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:35)
        at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:786)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:677)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:637)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:35)
        at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1516)
        at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1217)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1086)
        at io.swagger.v3.core.util.Json.pretty(Json.java:24)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromModel(DefaultCodegenConfig.java:1339)
        at io.swagger.codegen.v3.generators.python.PythonClientCodegen.fromModel(PythonClientCodegen.java:241)
        at io.swagger.codegen.v3.DefaultGenerator.processModels(DefaultGenerator.java:1011)
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:375)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:779)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:378)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Google says similar problems may appear because of dependencies version mismatch

### What did you expect to happen?

Well, no exceptions :)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install swagger-codegen
swagger-codegen generate -i tinkoff_investing.yaml -l python -o tinkoff_investing_client
```

**Comment by carlocab** [comment] 2021-07-19 00:30
Can you reproduce the problem with a non-Homebrew version of swagger-codegen? If you can, the problem is upstream, and needs to be reported and fixed there. If not, then we should find out where the formula differs from a non-Homebrew install so we can fix it.

**Comment by fedormatantsev** [comment] 2021-07-19 00:40
> Can you reproduce the problem with a non-Homebrew version of swagger-codegen? If you can, the problem is upstream, and needs to be reported and fixed there. If not, then we should find out where the formula differs from a non-Homebrew install so we can fix it.

Could I get binaries for non-Homebrew release somehow? I found only source code distribution so far. If not, I'll try to build it from source this week; I'm not a java guy, so it would take some time to figure out how to build swagger-codegen properly.

**Comment by gromgit** [comment] 2021-07-19 00:59
It's an upstream issue: https://github.com/swagger-api/swagger-codegen/issues/11040

The fix was incorporated in 3.0.27, but the version bump was abandoned due to what appears to be upstream packaging issues: https://github.com/Homebrew/homebrew-core/pull/80220

**Comment by fedormatantsev** [comment] 2021-07-19 01:14
Oh, thanks for the information. Looking forward for the updates then :)

**Comment by fryette** [comment] 2021-08-11 11:31
@gromgit What about releasing a new version to Homebrew? Any updates here?

**Comment by carlocab** [comment] 2021-08-11 12:29
@fryette There's no new information that can't be found by searching the repo. If you'd like the formula to be updated, you're welcome to open a pull request that does this.

**Comment by mmihalev** [comment] 2021-08-12 07:43
.. Same issue here. Basically swagger-codegen is completely unusable. We need the latest version.

**Comment by SMillerDev** [comment] 2021-08-12 08:27
Then go complain here: https://github.com/swagger-api/swagger-codegen, their latest release have been broken. There is nothing Homebrew can do so I'm closing this issue.

**Closed by SMillerDev** 2021-08-12 08:27 UTC
Labels: bug, upstream issue
