### ISSUE TITLE
brew install/reinstall mapserver --with-php dies at 85%

### ISSUE THREAD

**Issue by JillAusVet** [Homebrew/homebrew-core#9320] opened 2017-01-27 06:53 UTC
Have run brew doctor and deleted everything so it now says 'you are ready to brew' and brew update says 'you are up to date' but still it crashes at 85% - see gistlog https://gist.github.com/anonymous/7cbe2961950e4744902a5f8fa4506868.

Also tried to run without python as that seems to be where it's crashing but still same output:
```
brew reinstall mapserver --with-php --without-python
==> Reinstalling mapserver --with-php
==> Using the sandbox
==> Downloading http://download.osgeo.org/mapserver/mapserver-6.4.3.tar.gz
Already downloaded: /Users/jill/Library/Caches/Homebrew/mapserver-6.4.3.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make install
Last 15 lines from /Users/jill/Library/Logs/Homebrew/mapserver/02.make:
/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/swiginc/../swiginc/map.i:72: Warning 740: Whitespace indentation is inconsistent compared to earlier lines (line 2 of %feature("shadow"))
/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/swiginc/../swiginc/map.i:72: Warning 740: Whitespace indentation is inconsistent compared to earlier lines (line 3 of %feature("shadow"))
/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/swiginc/../swiginc/map.i:72: Warning 740: Whitespace indentation is inconsistent compared to earlier lines (line 4 of %feature("shadow"))
cd /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3 /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/python /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build/mapscript/python /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/DependInfo.cmake --color=
Scanning dependencies of target _pythonmapscript
/Library/Developer/CommandLineTools/usr/bin/make -f mapscript/python/CMakeFiles/_pythonmapscript.dir/build.make mapscript/python/CMakeFiles/_pythonmapscript.dir/build
[ 83%] Building C object mapscript/python/CMakeFiles/_pythonmapscript.dir/pygdioctx/pygdioctx.c.o
[ 84%] Building C object mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c.o
cd /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build/mapscript/python && /usr/local/Homebrew/Library/Homebrew/shims/super/clang  -D_pythonmapscript_EXPORTS -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/renderers/agg/include -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/local/opt/libxml2/include/libxml2 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/swiginc -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/python  -DNDEBUG -fPIC   -o CMakeFiles/_pythonmapscript.dir/pygdioctx/pygdioctx.c.o   -c /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/python/pygdioctx/pygdioctx.c
cd /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build/mapscript/python && /usr/local/Homebrew/Library/Homebrew/shims/super/clang  -D_pythonmapscript_EXPORTS -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/renderers/agg/include -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/local/opt/libxml2/include/libxml2 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/swiginc -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript -I/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/python  -DNDEBUG -fPIC   -o CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c.o   -c /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build/mapscript/python/mapscriptPYTHON_wrap.c
[ 85%] Linking C shared module _mapscript.so
cd /tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/build/mapscript/python && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_link_script CMakeFiles/_pythonmapscript.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang   -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o _mapscript.so CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c.o CMakeFiles/_pythonmapscript.dir/pygdioctx/pygdioctx.c.o -Wl,-undefined,dynamic_lookup ../../libmapserver.6.4.3.dylib /usr/local/lib/libpng.dylib /usr/lib/libz.dylib /usr/local/lib/libjpeg.dylib /usr/local/lib/libfreetype.dylib /usr/local/lib/libproj.dylib /usr/lib/libiconv.dylib /usr/local/lib/libgdal.dylib /usr/local/opt/libxml2/lib/libxml2.dylib /usr/local/lib/libgif.dylib -lm 
[ 85%] Built target _pythonmapscript
make: *** [all] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html
```

**Comment by dunn** [comment] 2017-02-08 19:23
Here's the errors:
```
/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/php/error.c:71:8: error: called object type 'php_error_object *' (aka 'struct _php_error_object *') is not a function or function pointer
  else IF_GET_STRING("routine", php_error->error->routine)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/php/php_mapscript_util.h:186:9: note: expanded from macro 'IF_GET_STRING'
        RETVAL_STRING( (value ? value:"") , 1);    \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/php56/5.6.29_5/include/php/Zend/zend_API.h:627:39: note: expanded from macro 'RETVAL_STRING'
#define RETVAL_STRING(s, duplicate)             ZVAL_STRING(return_value, s, duplicate)
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/php56/5.6.29_5/include/php/Zend/zend_API.h:583:14: note: expanded from macro 'ZVAL_STRING'
                        zend_error(E_ERROR, "String size overflow"); \
                        ~~~~~~~~~~^
/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/php/error.c:72:10: error: called object type 'php_error_object *' (aka 'struct _php_error_object *') is not a function or function pointer
    else IF_GET_STRING("message", php_error->error->message)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/mapserver-20170127-47582-e1rb1n/mapserver-6.4.3/mapscript/php/php_mapscript_util.h:186:9: note: expanded from macro 'IF_GET_STRING'
        RETVAL_STRING( (value ? value:"") , 1);    \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/php56/5.6.29_5/include/php/Zend/zend_API.h:627:39: note: expanded from macro 'RETVAL_STRING'
#define RETVAL_STRING(s, duplicate)             ZVAL_STRING(return_value, s, duplicate)
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/php56/5.6.29_5/include/php/Zend/zend_API.h:583:14: note: expanded from macro 'ZVAL_STRING'
                        zend_error(E_ERROR, "String size overflow"); \
                        ~~~~~~~~~~^
2 errors generated.
``` 
Can you try building outside of Homebrew, or check upstream to see if this is a known issue?

**Comment by ilovezfs** [comment] 2017-02-19 10:38
@DomT4 do you mind taking a look at this? Seems to be reproducible.

**Comment by DomT4** [comment] 2017-02-19 17:16
Will take a look at it. First thoughts are that we're not using the latest release which is now the 7.x branch, and we're not even using the latest release on the older 6.x branch (which is still supported).

Obviously this build is using a custom PHP because `cmake` does whatever `cmake` wants with deps, but on a clean system it uses the system PHP which as of the current Sierra release is the same version as OPs, and the system PHP blows up in the same way.

```
PHP 5.6.29 (cli) (built: Jan 29 2017 23:38:52)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by ilovezfs** [comment] 2017-02-19 17:50
@DomT4 thanks!

**Comment by DomT4** [comment] 2017-02-19 18:07
https://github.com/Homebrew/homebrew-core/pull/10140

**Comment by ilovezfs** [comment] 2017-02-19 18:44
Fixed via https://github.com/Homebrew/homebrew-core/pull/10140 thanks to Mr. T

**Closed by ilovezfs** 2017-02-19 18:44 UTC
