### ISSUE TITLE
gcc...Again no Availability.h being added to include-fixed

### ISSUE THREAD

**Issue by BJWiley233** [Homebrew/homebrew-core#92689] opened 2022-01-07 07:37 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
FYI I have older Xcode because Intel's new oneapi icc/icpc doesn't config with Xcode 13.  

Well... maybe it does now, I am updating to Xcode 13 now!
https://www.intel.com/content/www/us/en/developer/articles/reference-implementation/intel-compilers-compatibility-with-microsoft-visual-studio-and-xcode.html


% brew config
HOMEBREW_VERSION: 3.3.9-154-g13c45f4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 13c45f4f3efeb01e6e67e2865886f0ab8e62d6a6
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d73605261b0b165638aa00fecd19acd51e29500d
Core tap last commit: 36 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.wQpSqdFHiO/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.1-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
```

```
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  docker-machine
  docker2aci
  isl@0.18

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/brian/anaconda3/bin/icu-config
  /Users/brian/anaconda3/bin/krb5-config
  /Users/brian/anaconda3/bin/freetype-config
  /Users/brian/anaconda3/bin/xslt-config
  /Users/brian/anaconda3/bin/libpng16-config
  /Users/brian/anaconda3/bin/libpng-config
  /Users/brian/anaconda3/bin/xml2-config
  /Users/brian/anaconda3/bin/python3-config
  /Users/brian/anaconda3/bin/curl-config
  /Users/brian/anaconda3/bin/ncursesw6-config
  /Users/brian/anaconda3/bin/pybind11-config
  /Users/brian/anaconda3/bin/pcre-config
  /Users/brian/anaconda3/bin/nspr-config
  /Users/brian/anaconda3/bin/ncurses6-config
  /Users/brian/anaconda3/bin/gts-config
  /Users/brian/anaconda3/bin/python3.8-config
  /Users/brian/anaconda3/bin/nss-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libfftw3.3.dylib
  /usr/local/lib/libfftw3_omp.3.dylib
  /usr/local/lib/libfftw3_threads.3.dylib
  /usr/local/lib/libhts.1.11.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/fftw3.h
  /usr/local/include/htslib/bgzf.h
  /usr/local/include/htslib/cram.h
  /usr/local/include/htslib/faidx.h
  /usr/local/include/htslib/hfile.h
  /usr/local/include/htslib/hts.h
  /usr/local/include/htslib/hts_defs.h
  /usr/local/include/htslib/hts_endian.h
  /usr/local/include/htslib/hts_log.h
  /usr/local/include/htslib/hts_os.h
  /usr/local/include/htslib/kbitset.h
  /usr/local/include/htslib/kfunc.h
  /usr/local/include/htslib/khash.h
  /usr/local/include/htslib/khash_str2int.h
  /usr/local/include/htslib/klist.h
  /usr/local/include/htslib/knetfile.h
  /usr/local/include/htslib/kroundup.h
  /usr/local/include/htslib/kseq.h
  /usr/local/include/htslib/ksort.h
  /usr/local/include/htslib/kstring.h
  /usr/local/include/htslib/regidx.h
  /usr/local/include/htslib/sam.h
  /usr/local/include/htslib/synced_bcf_reader.h
  /usr/local/include/htslib/tbx.h
  /usr/local/include/htslib/thread_pool.h
  /usr/local/include/htslib/vcf.h
  /usr/local/include/htslib/vcf_sweep.h
  /usr/local/include/htslib/vcfutils.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libfftw3.la
  /usr/local/lib/libfftw3_omp.la
  /usr/local/lib/libfftw3_threads.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/fftw3.pc
  /usr/local/lib/pkgconfig/htslib.pc
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libfftw3.a
  /usr/local/lib/libfftw3_omp.a
  /usr/local/lib/libfftw3_threads.a
  /usr/local/lib/libhts.a
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  htslib
  awscli
  hadoop
  samtools

Warning: Your Xcode (12.5.1) is outdated.
Please update to Xcode 13.1 (or delete it).
Xcode can be updated from the App Store.


Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/c++-5
  /usr/local/bin/cpp-5
  /usr/local/bin/g++-5
  /usr/local/bin/gcc-5
  /usr/local/bin/gcc-ar-5
  /usr/local/bin/gcc-nm-5
  /usr/local/bin/gcc-ranlib-5
  /usr/local/bin/gcov-5
  /usr/local/bin/gcov-dump-5
  /usr/local/bin/gcov-tool-5
  /usr/local/bin/gfortran-5
  /usr/local/bin/x86_64-apple-darwin17.7.0-c++-5
  /usr/local/bin/x86_64-apple-darwin17.7.0-g++-5
  /usr/local/bin/x86_64-apple-darwin17.7.0-gcc-5
  /usr/local/bin/x86_64-apple-darwin17.7.0-gcc-5.5.0
  /usr/local/bin/x86_64-apple-darwin17.7.0-gcc-ar-5
  /usr/local/bin/x86_64-apple-darwin17.7.0-gcc-nm-5
  /usr/local/bin/x86_64-apple-darwin17.7.0-gcc-ranlib-5
  /usr/local/bin/x86_64-apple-darwin17.7.0-gfortran-5
  /usr/local/include/c++/5.5.0
  /usr/local/lib/gcc/5
  /usr/local/share/gcc-5.5.0
  /usr/local/share/man/man1/cpp-5.1
  /usr/local/share/man/man1/g++-5.1
  /usr/local/share/man/man1/gcc-5.1
  /usr/local/share/man/man1/gcov-5.1
  /usr/local/share/man/man1/gcov-dump-5.1
  /usr/local/share/man/man1/gcov-tool-5.1
  /usr/local/share/man/man1/gfortran-5.1
  /usr/local/share/man/man5/package-locks.5
  /usr/local/share/man/man5/shrinkwrap-json.5
  /usr/local/share/man/man7/fsf-funding-5.7
  /usr/local/share/man/man7/gfdl-5.7
  /usr/local/share/man/man7/gpl-5.7
```
```


### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install gcc 11.2.0_3 on bigSur.

### What happened (include all command output)?

brew reinstall gcc

### What did you expect to happen?

according to @fxcoudert [here](https://github.com/Homebrew/homebrew-core/issues/44579) there should be an `include-fixed/Availability.h` header file.  Very weird but one of the times I tried to reinstall gcc I saw this header and then it disappeared!!

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
brew info gcc
brew install gcc
brew cleanup
```

**Comment by carlocab** [comment] 2022-01-07 09:11
Can you give a minimal example of code that fails to compile because of the absence of `Availability.h`?

**Comment by BJWiley233** [comment] 2022-01-09 05:17
Yes I will.  Actually need to see if we can compile the program with SuiteSparse so I will do this Monday.

**Comment by fxcoudert** [comment] 2022-01-11 15:11
It seems you have a very old version of gcc lying around, not properly linked. This might be the issue?

**Comment by carlocab** [comment] 2022-01-11 15:21
I'm not even really sure what the issue is, which is why I asked for an MRE. I think `Availability.h` just isn't there anymore. There is, however, an `AvailabilityInternal.h`.
```
❯ fd 'Availability\.h'
❯ fd 'availability'
lib/gcc/11/gcc/x86_64-apple-darwin21/11/include-fixed/AvailabilityInternal.h
```
I am running Monterey, however, so, to be sure, I checked the Big Sur bottles too. The same is true:
```
❯ fd 'availability'
gcc/11.2.0_3/lib/gcc/11/gcc/x86_64-apple-darwin20/11/include-fixed/AvailabilityInternal.h
❯ fd 'availability'
gcc/11.2.0_3/lib/gcc/11/gcc/aarch64-apple-darwin21/11/include-fixed/AvailabilityInternal.h
```
Any issues @BJWiley233 is experiencing is likely to not be due to a missing `Availability.h`, or else we'd have already seen problems in CI by now.

My guess is that this is most probably due to an outdated CLT. However, it's hard to say for sure since I don't know what fails to compile.

**Comment by carlocab** [comment] 2022-01-11 15:22
Closing for now, since I don't see what the issue is here. We can reopen this if we have a minimum reproducible example of code the doesn't compile due to the absence of this header.

**Closed by carlocab** 2022-01-11 15:21 UTC
Labels: bug
