### ISSUE TITLE
Making newest version of gcc versioned formula alias to gcc formula causes ``brew install gcc@ver`` to fail

### ISSUE THREAD

**Issue by gdevenyi** [Homebrew/homebrew-core#41045] opened 2019-06-17 14:58 UTC
- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)
``brew install gcc@9`` for use in an automated Travis-CI environment on OSX xcode10.2 environment.
- What happened (include command output)
```
Error: gcc 8.3.0 is already installed
To upgrade to 9.1.0, run `brew upgrade gcc`.
```
- What you expected to happen
gcc9 was installed
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install gcc@9

**Comment by gdevenyi** [comment] 2019-06-17 15:02
This is not a bug per-se in a specific version of the formula, but rather an issue with the decision to alias gcc@9 to the gcc formula.

For all other versions of gcc, I can do ``brew install gcc@5`` for example, and things work as expected, however since the ``gcc`` formula is already installed, and the alias exists, install fails and tells me to run ``brew upgrade`` instead.

Additionally, this is an issue with reproducibility.
Currently, I can get around this problem in my travis config by doing the upgrade instead, but if/when gcc@10 arrives, suddenly upgrade becomes a different version.

I would like to request instead that the gcc@9 be a proper formula instead of an alias to gcc.

**Comment by chrmoritz** [comment] 2019-06-17 16:34
I think your issue is caused by the fact, that the gcc 8.3.0 on the travis image was not installed through `gcc@8`, but through the normal unversioned `gcc` formula (which the `gcc@9` Alias currently points too) at a time where the unversioned `gcc` formula did still install version 8.3.0 (prior to the 9.1.0 upgrade in https://github.com/Homebrew/homebrew-core/commit/763ca1f3c6291f24c1f69ffaf2d156fee3bdef67).

If you call `brew install gcc` or (`gcc@9` which is equivalent) than brew looks at the metadata of the current installed `gcc` and just sees that you try to install a newer version of the unversioned formula over a currently installed (and very outdated) old version and suggest the upgrade.

But `brew reinstall gcc@9` should work fine for you use case, shouldn't it?

**Comment by gdevenyi** [comment] 2019-06-17 17:19
Thanks @chrmoritz I realize that this is mostly an issue of me not having full control of the homebrew state prior to doing the install, and there's a couple of workarounds, currently using (brew install gcc@9 || brew upgrade gcc).

What I'm looking at is a way to write generically "I want gcc version X" in a reproducible way, without knowing the current homebrew state. I'm looking to avoid special-casing for versions. Right now, ``gcc@8`` and ``gcc@9`` need special casing, ``gcc@8`` probably because 8 is already installed as ``gcc`` unversioned and ``gcc@9`` because its aliased to ``gcc``.

Would ``(brew install gcc@N || brew reinstall gcc@N)`` be a generic way to install a specific version, regardless of the state?

**Comment by chrmoritz** [comment] 2019-06-17 17:27
Yeah, I think `brew reinstall gcc@N` would work fine for that use case and you don't even need the `brew install gcc@N ||` part, because `reinstall` doesn't complain about the formula not being installed.

**Comment by gdevenyi** [comment] 2019-06-18 13:37
``brew reinstall gcc@N`` does solve my issue in a generic way, thanks for the suggestion.

I still think the aliasing choice is the wrong way to go in terms of versioning so I'll leave this open. Feel free to close this with WONTFIX if you disagree.

**Comment by chrmoritz** [comment] 2019-06-18 13:58
I don't think the the alias is the real issue here, because it only makes it possible to refer to the latest unversioned formula as `gcc@9` instead of having to omit the version prefix for the latest version.

The real issue is that there is no way to migrate the `gcc` 8.3.0 (installed at a time were is was the latest unversioned version) to the new versioned `gcc@8` (after it got added during the `gcc` 9 upgrade). But unfortunately there is no reliable way to tell if a user wants to upgrade to the new major version or stay within the current major version (which as of now requires to reinstall the newly created versioned formula).

Also `brew install` always fails if the formula is already installed, regardless it's major version. So you would have to handle the case that one versioned formula line of `gcc` is already installed anyway. 
It's likely that travis will upgrade to a preinstalled `gcc` 9.x in the near future and than you would have to special case this too by not doing a `brew install gcc@9` there (and maybe having not the latest minor version) or you could keep using `brew reinstall gcc@N` to always have the latest minor version for a given major line.

**Comment by gdevenyi** [comment] 2019-06-18 14:19
Okay, I see there's some additional complications. From my perspective, ``brew reinstall gcc@N`` works regardless of what version is installed so I'm happy with that solution. If you want to adjust the title of this to track the issue you're describing feel free, otherwise, my issue is solved.

Thanks very much for your help!

**Comment by fxcoudert** [comment] 2019-09-05 09:59
I think we will close as WONTFIX. This is how we handle versions for now, and although we might change it in the future, it would be a major `brew` change.

**Closed by fxcoudert** 2019-09-05 09:59 UTC
