### ISSUE TITLE
Brew install openssl location doesn't exist

### ISSUE THREAD

**Issue by fbuibish** [Homebrew/homebrew-core#49304] opened 2020-01-22 21:00 UTC
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/fbuibish/d8cbe8a42c9f77989b1b5c535edae261

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I started getting this error running a python script that was making a call to retrieve some data over https.

```
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
```

So I do some digging and see that when I run ```openssl version -a``` I see that my ```OPENSSLDIR``` is set to this location

```
OpenSSL 1.1.1d  10 Sep 2019
built on: Thu Sep 19 13:36:19 2019 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(int) des(int) idea(int) blowfish(ptr) 
compiler: clang -fPIC -arch x86_64 -O2 -g -arch x86_64 -fno-common -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DNDEBUG -DNDEBUG -arch x86_64
OPENSSLDIR: "/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/ssl"
ENGINESDIR: "/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/lib/engines-1.1"
Seeding source: os-specific
```

Thing is, this location does not exist on my computer.  I have another computer and it's location when i run openssl is the expected location and it runs this script perfectly fine.

## What happened (include command output)

This is the output of when I run build from source install on openssl.

<details>
  <summary>Command output</summary>
  <pre>

   brew install -s openssl
==> Downloading https://www.openssl.org/source/openssl-1.1.1d.tar.gz
######################################################################## 100.0%
==> perl ./Configure --prefix=/usr/local/Cellar/openssl@1.1/1.1.1d --openssldir=/usr/local/etc/openssl@1.1 no-ssl3 no-ssl3-method no-zlib darwin64-
==> make
==> make test
==> make install MANDIR=/usr/local/Cellar/openssl@1.1/1.1.1d/share/man MANSUFFIX=ssl
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1d: 7,976 files, 17.9MB, built in 6 minutes 16 seconds

  </pre>
</details>

## What you expected to happen

I expect the openssl directory for certs to be located in a similar location to ```/usr/local/etc/openssl@1.1/certs``` instead of ```/Volumes/hd2/...```

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew uninstall openssl --ignore-dependencies
brew install -s openssl
openssl version -a
```

**Comment by SMillerDev** [comment] 2020-01-23 00:24
How did you install homebrew on this new PC? and why would you build openssl from source?

**Comment by fbuibish** [comment] 2020-01-23 01:16
Not a new PC and I don't remember how I installed homebrew.  If this would be helpful I can try to locate the instructions I used but i'm not entirely sure.

So I tried the normal ```brew install openssl``` and it wasn't working so I was looking into setting that directly in the config line...long story short I tried this after a bunch of attempts with a normal install and when i saw this showing ```--openssldir=/usr/local/opt/openssl/certs``` in the output of ```brew install -s openssl``` then I knew this was something that I probably would need assistance with, because in the build from source install it's setting the location correctly with that parameter.

**Comment by SMillerDev** [comment] 2020-01-23 01:28
What isn't working about the normal install?

**Comment by fbuibish** [comment] 2020-01-23 05:00
Normal install was not solving the problem either.  Basically the build from source was a last resort.

So the reason I think that the ```OPENSSLDIR``` value is causing problems is because when I attempted to run some python code as referenced on some article:

```
>>> import _ssl;
>>> _ssl.get_default_verify_paths();
('SSL_CERT_FILE', '/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/ssl/cert.pem', 'SSL_CERT_DIR', '/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/ssl/certs')
```
I did this because running a python script to install certifi similar to the 'Install Certificates.command' script yielded an error that the script could not find the my certs at that location.

brew config output

```
HOMEBREW_VERSION: 2.2.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: d014d5a982bc3712179af59faae33fe777d49aef
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 07fcb96b558b7ad18f36a9ba9a90752822fe988e
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_112
macOS: 10.15.2-x86_64
CLT: N/A
Xcode: 11.3
XQuartz: 2.7.11 => /opt/X11
```

**Comment by puxlit** [comment] 2020-01-23 18:14
This bears some resemblance to #43495. However, this formula is keg-only by default. What do you get when you run `/usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl version -a`?

**Comment by fbuibish** [comment] 2020-01-23 18:32
Yes the reason I opened the issue was I saw the similar problem but the issue was closed without solution.
When I run that command I get a similar output.
```
OpenSSL 1.1.1d  10 Sep 2019
built on: Thu Sep 19 13:36:19 2019 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(int) des(int) idea(int) blowfish(ptr) 
compiler: clang -fPIC -arch x86_64 -O2 -g -arch x86_64 -fno-common -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DNDEBUG -DNDEBUG -arch x86_64
OPENSSLDIR: "/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/ssl"
ENGINESDIR: "/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/lib/engines-1.1"
Seeding source: os-specific
```

**Comment by puxlit** [comment] 2020-01-23 23:35
Could you run `otool -L /usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl` and `cat /usr/local/Cellar/openssl@1.1/1.1.1d/lib/pkgconfig/libcrypto.pc` please?

**Comment by fbuibish** [comment] 2020-01-24 04:53
```otool -L /usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl``` output:
```
/usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl:
	/usr/local/Cellar/openssl@1.1/1.1.1d/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/Cellar/openssl@1.1/1.1.1d/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

```/usr/local/Cellar/openssl@1.1/1.1.1d/lib/pkgconfig/libcrypto.pc``` output:
```
prefix=/usr/local/Cellar/openssl@1.1/1.1.1d
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
enginesdir=${libdir}/engines-1.1

Name: OpenSSL-libcrypto
Description: OpenSSL cryptography library
Version: 1.1.1d
Libs: -L${libdir} -lcrypto
Libs.private:  
Cflags: -I${includedir}
```

then I ran ```openssl version -a``` output:
```
LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"
```
Should I try to install now because it looks like something changed?

**Comment by puxlit** [comment] 2020-01-24 07:09
I believe LibreSSL 2.8.3 is supplied by Catalina.

After a bit of sleuthing, I'm able to reproduce this under very specific conditions, where the OpenSSL libraries bundled with MySQL 8.0.18 are forcibly loaded.

```
puxlit@kiara:~$ pushd "$(mktemp -d)"
/var/folders/rp/vrkcvkms15g29ttpn2zt38t00000gn/T/tmp.yCJIXbr1 ~
puxlit@kiara:/var/folders/rp/vrkcvkms15g29ttpn2zt38t00000gn/T/tmp.yCJIXbr1$ curl -sLO 'https://downloads.mysql.com/archives/get/p/23/file/mysql-8.0.18-macos10.14-x86_64.tar.gz'
puxlit@kiara:/var/folders/rp/vrkcvkms15g29ttpn2zt38t00000gn/T/tmp.yCJIXbr1$ md5sum -c <<'EOF'
> 5deda97d03db45374e77e35d7f3a5f56  mysql-8.0.18-macos10.14-x86_64.tar.gz
> EOF
mysql-8.0.18-macos10.14-x86_64.tar.gz: OK
puxlit@kiara:/var/folders/rp/vrkcvkms15g29ttpn2zt38t00000gn/T/tmp.yCJIXbr1$ tar -xvf mysql-8.0.18-macos10.14-x86_64.tar.gz mysql-8.0.18-macos10.14-x86_64/lib/libcrypto.1.1.dylib mysql-8.0.18-macos10.14-x86_64/lib/libssl.1.1.dylib
x mysql-8.0.18-macos10.14-x86_64/lib/libcrypto.1.1.dylib
x mysql-8.0.18-macos10.14-x86_64/lib/libssl.1.1.dylib
puxlit@kiara:/var/folders/rp/vrkcvkms15g29ttpn2zt38t00000gn/T/tmp.yCJIXbr1$ DYLD_INSERT_LIBRARIES=mysql-8.0.18-macos10.14-x86_64/lib/libcrypto.1.1.dylib:mysql-8.0.18-macos10.14-x86_64/lib/libssl.1.1.dylib DYLD_FORCE_FLAT_NAMESPACE=1 /usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl version -a
OpenSSL 1.1.1d  10 Sep 2019
built on: Thu Sep 19 13:36:19 2019 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(int) des(int) idea(int) blowfish(ptr) 
compiler: clang -fPIC -arch x86_64 -O2 -g -arch x86_64 -fno-common -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DNDEBUG -DNDEBUG -arch x86_64
OPENSSLDIR: "/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/ssl"
ENGINESDIR: "/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/lib/engines-1.1"
Seeding source: os-specific
```

Do you have MySQL 8.0.18 installed? If so, was it installed via brew or through <https://downloads.mysql.com/>? If you're still able to reproduce this problem when directly running `/usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl version -a`, could you run `which -a openssl` and `echo $DYLD_INSERT_LIBRARIES`?

**Comment by fxcoudert** [comment] 2020-01-26 20:43
Paths under `/Volumes/hd2/pb2` are not related to Homebrew at all. Google hints that they are used by mysql binary builds, from mysql (which do include some openssl). I think your Python script is somehow loading an openssl which is not from homebrew, but from your mysql install.

You appear to also have a lot of stuff installed in `/opt` and that might be a problem too.

I'm closing this, as apparently the problem is not in Homebrew itself but in the loading of shared libraries that do not originate in Homebrew. (It doesn't mean we won't help you debug further, just that we don't think it's an issue that needs fixing within homebrew)

**Closed by fxcoudert** 2020-01-26 20:43 UTC
Labels: user configuration

**Comment by fbuibish** [comment] 2020-02-03 16:38
Ok thanks for your time in helping me.

I think I installed mysql from their site, and this makes sense because I installed that right before the script stopped working.

Here's what those commands yield:
`which -a openssl`: `/usr/bin/openssl`
`echo $DYD_INSERT_LIBRARIES`: -nothing-
`DYLD_PRINT_LIBRARIES=/usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl version -a`: `-bash: version: command not found`

**Comment by fbuibish** [comment] 2020-02-03 19:06
So I tried a couple things, but the workaround for me is that I set these two values as referenced [here](https://stackoverflow.com/a/55856969)

`
export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem
export REQUESTS_CA_BUNDLE=/usr/local/etc/openssl/cert.pem
`

but in my case I set them to
`
export SSL_CERT_FILE=/usr/local/etc/openssl@1.1/cert.pem
export REQUESTS_CA_BUNDLE=/usr/local/etc/openssl@1.1/cert.pem
`
not sure if this fixes the actual problem I'm having but I can now run my script.

**Comment by puxlit** [comment] 2020-02-03 21:33
I suspect the underlying problem remains. Could you please retry running the command `DYLD_PRINT_LIBRARIES= /usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl version -a`? Note that there is a space between `DYLD_PRINT_LIBRARIES=` and the path to the `openssl` binary.

**Comment by fbuibish** [comment] 2020-02-03 21:36
Oh yes my fault.  Here is the output:
`
dyld: loaded: <55DC151C-28AF-384E-87D7-3CB20B3386D2> /usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl
dyld: loaded: <4A5C9662-D204-3998-A472-A3071888C6A3> /usr/local/mysql/lib/libssl.1.1.dylib
dyld: loaded: <C149CF60-F73F-36E8-8839-021062716277> /usr/local/mysql/lib/libcrypto.1.1.dylib
dyld: loaded: <2F6BCFD9-A5F9-30FE-BF5A-5C53D3CBAB4D> /usr/lib/libSystem.B.dylib
dyld: loaded: <AD7479C0-73FA-3B2E-9544-D566DFFAB4C6> /usr/lib/system/libcache.dylib
dyld: loaded: <F7B65873-FAC8-3EB5-8912-34109EFC74B5> /usr/lib/system/libcommonCrypto.dylib
dyld: loaded: <51107CAA-0727-370D-8287-940D40D09AC1> /usr/lib/system/libcompiler_rt.dylib
dyld: loaded: <6454A046-88E5-32D6-898C-FB0D30D28637> /usr/lib/system/libcopyfile.dylib
dyld: loaded: <8090C446-35C8-31B4-8B1E-AF6D0EF3524B> /usr/lib/system/libcorecrypto.dylib
dyld: loaded: <A9EDFE95-31BA-3BEF-89CA-60DE153237FA> /usr/lib/system/libdispatch.dylib
dyld: loaded: <8E2D3DED-0756-37A0-9D55-B9264CA020B4> /usr/lib/system/libdyld.dylib
dyld: loaded: <0B9A3AF7-086E-3E7A-A52E-3DAF2E52CF86> /usr/lib/system/libkeymgr.dylib
dyld: loaded: <A061D971-A337-3528-8B78-FFAD2B0B5CC6> /usr/lib/system/liblaunch.dylib
dyld: loaded: <9831715F-ED86-3A9D-88CD-152C888B784B> /usr/lib/system/libmacho.dylib
dyld: loaded: <58CE8913-EC7B-376B-BC80-69763993A1E4> /usr/lib/system/libquarantine.dylib
dyld: loaded: <4E1AD797-3993-3E05-BB9B-B4E3038CE09C> /usr/lib/system/libremovefile.dylib
dyld: loaded: <2CD6CABE-F8D7-3CCA-A930-08F8AC356D30> /usr/lib/system/libsystem_asl.dylib
dyld: loaded: <71A75F21-83AD-382F-95E4-4D6B77B4B9FE> /usr/lib/system/libsystem_blocks.dylib
dyld: loaded: <ECA8CD0D-0B55-3151-B389-8109DAEC85B1> /usr/lib/system/libsystem_c.dylib
dyld: loaded: <CE186284-4923-35DE-9141-7B6B89523668> /usr/lib/system/libsystem_configuration.dylib
dyld: loaded: <FBE4483A-7B6E-30CF-AECE-828AFFACDC15> /usr/lib/system/libsystem_coreservices.dylib
dyld: loaded: <9AC37996-630C-3B1E-8285-CFC77B684359> /usr/lib/system/libsystem_darwin.dylib
dyld: loaded: <7F0DF910-F4AC-3CED-9494-295B5E45549C> /usr/lib/system/libsystem_dnssd.dylib
dyld: loaded: <985005B7-C0B3-3DCA-B064-6D34A0687212> /usr/lib/system/libsystem_featureflags.dylib
dyld: loaded: <D9805FBC-1BBD-3825-AB62-83C3ABB4191F> /usr/lib/system/libsystem_info.dylib
dyld: loaded: <92F1FF45-BD1C-32FE-A9A9-D12AF02C8212> /usr/lib/system/libsystem_m.dylib
dyld: loaded: <51472F42-71BE-348F-B42E-4EDD3040B690> /usr/lib/system/libsystem_malloc.dylib
dyld: loaded: <846C06C0-A705-38AE-8A29-3FA4153252B3> /usr/lib/system/libsystem_networkextension.dylib
dyld: loaded: <7CB7DE46-5877-3CAD-8526-CACEA22F3AD5> /usr/lib/system/libsystem_notify.dylib
dyld: loaded: <AA2E4441-A517-3921-AF0E-AA8158D2A6D9> /usr/lib/system/libsystem_sandbox.dylib
dyld: loaded: <129C187A-E580-3F00-A0C3-E96A633364F1> /usr/lib/system/libsystem_secinit.dylib
dyld: loaded: <90F8650F-D3A9-38B3-BB8C-B5D3686393BC> /usr/lib/system/libsystem_kernel.dylib
dyld: loaded: <AC9560A9-CCE8-3158-BCC8-8FF47929397A> /usr/lib/system/libsystem_platform.dylib
dyld: loaded: <9D14694F-F3FE-385D-9B23-6A87844D5CBF> /usr/lib/system/libsystem_pthread.dylib
dyld: loaded: <5540DEA3-9C3A-3991-8C3A-7B375A5410C7> /usr/lib/system/libsystem_symptoms.dylib
dyld: loaded: <EF6BD746-85CD-3490-92E6-7C7EDA0B703B> /usr/lib/system/libsystem_trace.dylib
dyld: loaded: <769F4C16-2746-3182-85C1-45CC98D119C8> /usr/lib/system/libunwind.dylib
dyld: loaded: <AC9AD00D-BAA9-3ABC-B557-77E604CF9955> /usr/lib/system/libxpc.dylib
dyld: loaded: <17241F77-6A7A-39D7-8836-63E2725AA3C9> /usr/lib/libobjc.A.dylib
dyld: loaded: <BC1E5821-4540-3226-ABB0-BC35E4DDF0B9> /usr/lib/libc++abi.dylib
dyld: loaded: <6018A70E-5CD3-32AF-BA60-E7A0B7E7CEB2> /usr/lib/libc++.1.dylib
OpenSSL 1.1.1d  10 Sep 2019
built on: Thu Sep 19 13:36:19 2019 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(int) des(int) idea(int) blowfish(ptr) 
compiler: clang -fPIC -arch x86_64 -O2 -g -arch x86_64 -fno-common -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DNDEBUG -DNDEBUG -arch x86_64
OPENSSLDIR: "/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/ssl"
ENGINESDIR: "/Volumes/hd2/pb2/build/sb_0-36003742-1568900155.81/openssl-1.1.1d-macos10.14-x86-64bit/lib/engines-1.1"
Seeding source: os-specific
`

**Comment by puxlit** [comment] 2020-02-04 05:20
Thanks, we're getting somewhere. Could you please run `echo $DYLD_LIBRARY_PATH`? Also, do you remember which MySQL-related products you installed? Was it just the community server, or were there also additional connectors and utilities? Did you download the `.tar.gz` distributions and manually untar them, or did you download the `.dmg` distributions and run the contained `.pkg` installer?

**Comment by fbuibish** [comment] 2020-02-04 15:11
```
echo $DYLD_LIBRARY_PATH
/usr/local/mysql/lib:
```

I think I found the article I used to install, [here](https://www.lifewire.com/how-to-install-mysql-on-macos-4586389)

Which is just the community server and downloads as a `.dmg` package and then run installer.

**Comment by SMillerDev** [comment] 2020-02-04 16:22
Out of curiosity, why not use the homebrew version?

**Comment by fbuibish** [comment] 2020-02-05 04:15
Honestly because it was one of the first links I viewed when I search how to install mysql on mac into google.  So really no particular reason

**Comment by puxlit** [comment] 2020-02-05 05:20
I've had a quick look at the installer package, but couldn't find anything to suggest that it sets this envvar out-of-the-box.

Do you remember whether you set `DYLD_LIBRARY_PATH` explicitly in your shell profile? Searching through the docs, it seems like this hack is [suggested](https://dev.mysql.com/doc/connector-python/en/connector-python-cext-development.html) for getting the Connector/Python C extension working.

If you can find it in your shell profile, and don't remember having to/why you explicitly set it, then I'd suggest removing it. MySQL should still function, as the binaries are relatively linked.

**Comment by fbuibish** [comment] 2020-02-10 17:02
Oh it looks like I am setting it to:
```
MYSQL=/usr/local/mysql/bin
export PATH=$PATH:$MYSQL
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH
```

I did this though in an attempt to fix the problem.

When I remove those three lines, I still get the same `SSL: CERTIFICATE_VERIFY_FAILED` error

**Comment by puxlit** [comment] 2020-02-10 18:23
Are you sure you launched a fresh shell after you removed those exports? Could you double-check that `DYLD_LIBRARY_PATH` is unset prior to running your Python script? Did you reinstall OpenSSL from bottle? Can you confirm that `/usr/local/etc/openssl@1.1/cert.pem` was generated? And are you sure that the server you're trying to access is presenting a certificate signed by a trusted CA?
