### ISSUE TITLE
brew install swift-format

### ISSUE THREAD

**Issue by stephane-archer** [Homebrew/homebrew-core#198632] opened 2024-11-22 14:20 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew install swift-format                                                             (base)
==> Downloading https://ghcr.io/v2/homebrew/core/swift-format/manifests/600.0.0_1
Already downloaded: /Users/fractale/Library/Caches/Homebrew/downloads/fe2942d2b7c4a891d0ef5c3c642f74f9225debec94ecad975d5e2351826202fa--swift-format-600.0.0_1.bottle_manifest.json
==> Fetching swift-format
==> Downloading https://ghcr.io/v2/homebrew/core/swift-format/blobs/sha256:a99a19c9fc177a57b2577e3c1b30feb70f13388fc9c4e4ea7968f783058e09a0
########################################################################################################################################################################### 100.0%
==> Verifying attestation for swift-format
Warning: Failed to verify attestation. Retrying in 1s...
Warning: Failed to verify attestation. Retrying in 3s...
Warning: Failed to verify attestation. Retrying in 9s...
Warning: Failed to verify attestation. Retrying in 27s...
Warning: Failed to verify attestation. Retrying in 81s...
Error: The bottle for swift-format has an invalid build provenance attestation.

This may indicate that the bottle was not produced by the expected
tap, or was maliciously inserted into the expected tap's bottle
storage.

Additional context:

attestation verification failed: Failure while executing; `/usr/bin/env GH_TOKEN=****** GH_HOST=github.com /usr/local/bin/gh attestation verify /Users/fractale/Library/Caches/Homebrew/downloads/8da8d419e62049209889ef97fef8edda666d6d4c1ceb8d77fdf77d2df32480cf--swift-format--600.0.0_1.sonoma.bottle.tar.gz --repo Homebrew/homebrew-core --format json` exited with 1. Here's the output:
Failed to verify the artifact: failed to fetch attestations for subject: sha256:a99a19c9fc177a57b2577e3c1b30feb70f13388fc9c4e4ea7968f783058e09a0
```
```


### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

install swift-format

### What happened (include all command output)?

```
attestation verification failed: Failure while executing; `/usr/bin/env GH_TOKEN=****** GH_HOST=github.com /usr/local/bin/gh attestation verify /Users/fractale/Library/Caches/Homebrew/downloads/8da8d419e62049209889ef97fef8edda666d6d4c1ceb8d77fdf77d2df32480cf--swift-format--600.0.0_1.sonoma.bottle.tar.gz --repo Homebrew/homebrew-core --format json` exited with 1. Here's the output:
Failed to verify the artifact: failed to fetch attestations for subject: sha256:a99a19c9fc177a57b2577e3c1b30feb70f13388fc9c4e4ea7968f783058e09a0
```

### What did you expect to happen?

successful install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install swift-format`
```

**Comment by SMillerDev** [comment] 2024-11-22 17:08
Duplicate of the pinned https://github.com/Homebrew/homebrew-core/issues/177384

**Closed by SMillerDev** 2024-11-22 17:08 UTC
Labels: bug
