### ISSUE TITLE
SDL not configured with OpenGL/GLX support

### ISSUE THREAD

**Issue by Raffaello** [Homebrew/homebrew-core#163244] opened 2024-02-19 17:43 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.2.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: e5fefd73cd97cd36ae3af29551f529ae59b333d6
Last commit: 10 hours ago
Core tap JSON: 19 Feb 17:24 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 3.1.4 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: quad-core 64-bit zen
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 6.2.0-39-generic x86_64 GNU/Linux
OS: Ubuntu 22.04.4 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 13.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 13.2.0
xorg: N/A
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

open a SDL2 window, it fails at this statement level:
```
SDL_CreateWindow(SDL_WINDOW_OPENGL);
```

`SDL_GetError()` returns: `SDL not configured with OpenGL/GLX support`

### What happened (include all command output)?

on brew nothing, sdl2 is installed correctly. 

I think the formula is missing some dependency or, a define config is missing when building SDL2 (for linux at least)

### What did you expect to happen?

that SDL2 can create an OPEN_GL window.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew install sdl2
2. create a c/c++ simple project like: 

int main()
{
  SDL_Init(...);
  SDL_CreateWindow(SDL_WINDOW_OPENGL);
  SDL_Quit();

  return 0;
}


it might be a flag when compiling SDL2 from source
```

**Comment by SMillerDev** [comment] 2024-02-19 18:14
This is not a bug, so I'm closing it.

You can create a pull request to adjust the formula features though.

**Closed** 2024-02-19 18:13 UTC
Labels: bug

**Comment by Raffaello** [comment] 2024-02-19 18:58
> This is not a bug, so I'm closing it.
> 
> You can create a pull request to adjust the formula features though.

it might be not a bug, but it is a broken formula, like pouring an old rotten beer... not sure it should neither be available to be installed at that point as it is broken, it means doesn't work on linux at all. 

anyway.

**Comment by Raffaello** [comment] 2024-02-19 19:19
doing a `brew install --build-from-source sdl2` has fixed the issue. 
(in this case was a reinstall)

so the formula looks like ok, 
it might have been something on my end the first time compiling it.
