### ISSUE TITLE
Crystal fails to install correctly

### ISSUE THREAD

**Issue by mig-hub** [Homebrew/homebrew-core#102106] opened 2022-05-23 07:33 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4560b73bb3eeb57f1768bdfe6f02315ac5c5fcba
Core tap last commit: 14 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.3.1.0.1.1648687083
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install crystal.

### What happened (include all command output)?

I ran:

```
brew install crystal
```

It seemed to have succeeded. But when I try to use the `crystal` binary with any sub command (including `crystal --version`), it shows this error message:

```
Unhandled exception: Unable to get file info: '/usr/local/bin/pkg-config': Permission denied (File::AccessDeniedError)
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'raise<File::Error+>:NoReturn'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'Crystal::System::File::info?<String, Bool>:(Crystal::System::FileInfo | Nil)'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'Process::is_executable_file?<Path>:Bool'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'Process::find_executable<String>:(String | Nil)'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in '~Crystal::Program::PKG_CONFIG_PATH:init'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'Crystal::OnceState#once<Pointer(Bool), Pointer(Void)>:(Pointer(Bool) | Nil)'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in '__crystal_main'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'main'
Unhandled exception: Unable to get file info: '/usr/local/bin/pkg-config': Permission denied (File::AccessDeniedError)
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'raise<File::Error+>:NoReturn'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'Crystal::System::File::info?<String, Bool>:(Crystal::System::FileInfo | Nil)'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'Process::is_executable_file?<Path>:Bool'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'Process::find_executable<String>:(String | Nil)'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in '~Crystal::Program::PKG_CONFIG_PATH:init'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'Crystal::OnceState#once<Pointer(Bool), Pointer(Void)>:(Pointer(Bool) | Nil)'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in '__crystal_main'
  from /opt/homebrew/Cellar/crystal/1.4.1/libexec/crystal in 'main'
```

It looks like it's trying to use `pkg-config` from the wrong location. The message says "/usr/local/bin/pkg-config", but mine is installed by homebrew in "/opt/homebrew/bin/pkg-config". And this is the only location where I have a `pkg-config`. When I run `which -a pkg-config`, I only get this "/opt/homebrew" location, nothing else. 

### What did you expect to happen?

Just be able to use `crystal` in this case.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
brew install crystal
crystal --version
```
```

**Comment by SMillerDev** [comment] 2022-05-23 08:11
So the issue is "Crystal looks for pkg-config" in the wrong location then? That seems like a Crystal bug, not Homebrew since https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/crystal.rb does not define this location.

**Comment by carlocab** [comment] 2022-05-24 21:57
Closing as not reproducible.

**Closed by carlocab** 2022-05-24 21:57 UTC
Labels: bug

**Comment by mig-hub** [comment] 2022-05-25 04:49
@cho-m Thank you so much! You've put me on the right path. I checked and still had "/usr/local/bin" and "/usr/local/sbin" in my PATH, probably because I used to have homebrew installed in the legacy path with rosetta when many softs where not adapted to the M1 ship. I have reinstalled crystal after removing these from the PATH and it works fine.

Nevertheless, there is probably something not working correctly down the chain somewhere because my "/usr/local/bin" was completely empty and an empty directory in the PATH should not have such an impact.

@carlocab Thank you for you response as well. What do you think about the above point? Is it not reproducible when you add an empty "/usr/local/bin" directory? It sounds like somewhere down the chain the location of pkg-config is picked only because this directory exist and not because it's its official `which` path. i.e. it is not checking there is a `pkg-config` bin there.

**Comment by carlocab** [comment] 2022-05-25 05:10
This sounds like a bug that needs to be fixed in Crystal itself, rather than in the formula. That means you need to report it to the Crystal devs rather than here.

If they come back and tell you it's a problem with the formula you're welcome to open a new issue for this problem.
