### ISSUE TITLE
Python installation should not flood stdout

### ISSUE THREAD

**Issue by Dispader** [Homebrew/homebrew-core#58087] opened 2020-07-16 16:44 UTC
## What you were trying to do (and why)

Update Python.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
[...]
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/README
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/StripViewer.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/Switchboard.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/TextViewer.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/TypeinViewer.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/X/rgb.txt
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/X/xlicense.txt
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/__init__.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/html40colors.txt
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/namedcolors.txt
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/pyColorChooser.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/pynche
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/pynche.pyw
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/webcolors.txt
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/pynche/websafe.txt
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/2to3
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/README
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/abitype.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/analyze_dxp.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/byext.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/byteyears.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/checkpip.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/checkpyc.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/cleanfuture.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/combinerefs.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/copytime.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/crlf.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/db2pickle.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/diff.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/dutree.doc
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/dutree.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/eptags.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/find-uname.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/find_recursionlimit.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/finddiv.py
/usr/local/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/scripts/findlinksto.py
[...]
  </pre>
</details>

## What you expected to happen

Python to not fill the log buffer in screen (at least a thousand lines large), making it impossible to know what else was installed or updated by brew.

## Step-by-step reproduction instructions

brew upgrade, when python is installed.

**Comment by SMillerDev** [comment] 2020-07-16 16:58
This isn't displayed on standard installs. Are you building from source?

**Comment by muneebmahmed** [comment] 2020-07-18 03:48
I had the same issue, reproduced in both my Catalina and Mojave partitions, and also my work laptop. I have a standard install of `brew` in `/usr/local`, so I assume it pours from bottle instead of trying to build from source. In each case, I had python 3.8.3_2 installed, and `brew upgrade` resulted in the above 1000+ lines of output, followed by:
```
Warning: These files were overwritten during `brew link` step:
/usr/local/bin/2to3

They have been backed up in /Users/[USER]/Library/Caches/Homebrew/Backup
==> /usr/local/Cellar/python@3.8/3.8.4/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python@3.8/3.8.4/bin --install-lib=/usr/lo
==> /usr/local/Cellar/python@3.8/3.8.4/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python@3.8/3.8.4/bin --install-lib=/usr/lo
==> /usr/local/Cellar/python@3.8/3.8.4/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python@3.8/3.8.4/bin --install-lib=/usr/lo
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.8/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
```
This actually resulted in python3 being removed from my system, requiring a `brew reinstall python`. I'm sorry for not having a more detailed log before the output, as I didn't think to log my iTerm session beforehand.

**Comment by SMillerDev** [comment] 2020-07-18 07:45
`python` doesn't exist as a formula anymore. That's `python@3.8` now so that is correct.

**Comment by muneebmahmed** [comment] 2020-07-26 05:49
Hi @SMillerDev,

I'm unsure what you mean. Both `brew info python` and `brew info python@3.8` show Python 3.8 for me, so I assumed that although the `python` formula was deleted, the name was still being used to refer to 3.8. Are you saying the issue has to do with the upgrade that occurred from Python 3.7 to 3.8, when the formula was deleted?

Some more information that I think might be relevant: On another computer I upgraded from 3.7.8 -> 3.8.5, and I didn't get the flood of output as before. However, running `brew doctor` yielded this:
```
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.8
```
and a `brew link --dry-run python@3.8` yielded the 15000+ lines of output as described in the original post. Could the issue be homebrew was somehow not symlinking the installation properly during the upgrade?

Note that the above instance of the unlinked keg I just gave could be unrelated, or just a problem on my machine, since it's from a non-standard install in `~/homebrew` instead of `/usr/local/`. 
Also, since the original issue was a minor inconvenience that can be fixed with a `brew reinstall python@3.8` - and probably shouldn't be an issue on new installs - I understand if it's not a priority to figure out what went wrong.

**Comment by iMichka** [comment] 2020-07-27 06:41
> on-standard install in ~/homebrew instead of /usr/local/

We do not support this configuration. If you do not install in a standard prefix, you need to fix any encountered issues yourself.
Any superfluous output because you are building from source is also expected.

**Closed by iMichka** 2020-07-27 06:41 UTC

**Comment by muneebmahmed** [comment] 2020-07-27 08:12
> Any superfluous output because you are building from source is also expected.

Hi @iMichka,

To clarify my comment, the superfluous output **only appeared in a standard install** to /usr/local, and did **not** appear in a non-standard install.

**Comment by iMichka** [comment] 2020-07-27 08:16
I did not have all this output on my side; and most of people did not too.
Many things may have happened here.

If your setup is working correctly right now, everything is fine. The output is maybe a little bit ugly, and could surely be improved, but I think this is a very low-priority issue on our side. A pull request to improve things is welcome of course, but I do not think any maintainer will spend time debugging this.

**Comment by dave-kennedy** [comment] 2020-08-05 21:00
> Some more information that I think might be relevant: On another computer I upgraded from 3.7.8 -> 3.8.5, and I didn't get the flood of output as before. However, running `brew doctor` yielded this:
> 
> ```
> Warning: You have unlinked kegs in your Cellar.
> Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
> those kegs to fail to run properly once built. Run `brew link` on these:
>   python@3.8
> ```

I also saw this after a recent upgrade. When I tried to run a Python script, it was unable to import a pip dependency that was still installed in /usr/local/lib/python3.8/site-packages because for some reason python3 suddenly pointed to /usr/bin/python3 instead of /usr/local/bin/python3.
