### ISSUE TITLE
brew update failing (transfer closed with outstanding read data remaining)

### ISSUE THREAD

**Issue by Dids** [Homebrew/homebrew-core#61772] opened 2020-09-30 09:40 UTC
# Bug report

Ever since this morning, I noticed `brew update` failing repeatedly on my local machine.
Next I tried it on a second machine, where it was also failing.

Eventually I also saw this while running GitHub Actions CI jobs, where it was failing exactly like on my local machine, which sounds like it's a global problem, not a local problem.

Ultimately this was fixed by the following git configuration change:
```
git config --global http.postBuffer 524288000
```

UPDATE: Even after the above change, I'm still seeing occasional failures, unless this is entirely on GitHub's side and nothing to do with brew per se?

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run `brew update`.

## What happened (include command output)

```
> brew update
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
```

## What you expected to happen

Homebrew update should have succeeded.

## Step-by-step reproduction instructions (by running `brew install` commands)

> brew update

## Output from `brew config` and `brew doctor`

```
HOMEBREW_VERSION: 2.5.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c7e4a3d8b9835a94edb3a6744b6f66cac06cf064
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 97dbb4fc16488ad5ba63ee24d52ab3f8c92442c5
Core tap last commit: 12 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2, 13.0.2, 12.0.2, 11.0.8, 1.8.0_265, 1.7.0_272
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1599194153
Xcode: 11.7 => /Applications/Xcode_11.7.app/Contents/Developer
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a
```

**Comment by sebastianw** [comment] 2020-09-30 10:32
Yeah noticed the same problem this morning.

**Comment by miccal** [comment] 2020-09-30 12:27
Thank you @Dids and @sebastianw for the reports.

The maintainers of `brew` are aware of this issue and have lodged support tickets with GitHub, so it is being investigated.

**Comment by Francegala** [comment] 2020-09-30 15:15
<img width="1293" alt="Screenshot 2020-09-30 at 16 12 17" src="https://user-images.githubusercontent.com/7479492/94704412-cb127080-0337-11eb-8b31-ec54d741856e.png">

When installing homebrew I had the same issue then I realised it's not just the brew update, but any installation "brew cask install" returns the error
fatal: unable to access 'https://github.com/Homebrew/homebrew-cask/': transfer closed with outstanding read data remaining
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask` exited with 128.
(In case I need to raise another issue, just let me know)

**Comment by seanwang-okta** [comment] 2020-09-30 19:12
seeing this as well

**Comment by madebyamin** [comment] 2020-09-30 20:33
has there been a solution to this issue? 

fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining

**Comment by iMichka** [comment] 2020-09-30 20:45
It's a GitHub issue. The homebrew maintainers are also impacted by this right now.

We have reported the issue to Github and are waiting for feedback.

**Comment by minwook-shin** [comment] 2020-10-02 01:24
Same issue for me, but it works now.
try ```brew update && brew upgrade```.

**Comment by Rylan12** [comment] 2020-10-02 02:51
I believe the issue has been fixed. Several maintainers (including myself) have been able to push/pull successfully today and our CI system seems to be working again.

I haven't received an official response from GitHub indicating the issue's been fixed, though, so it's possible that they are still working on it in some capacity.

If you were having trouble previously, I would recommend giving it another try now.

**Comment by SMillerDev** [comment] 2020-10-02 05:23
Closing this since it seems to be resolved.

**Closed by SMillerDev** 2020-10-02 05:23 UTC

**Comment by Djadih** [comment] 2020-10-09 07:01
Unfortunately still happening for me. Here's my output:

> fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining
> Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!

**Comment by timolehto** [comment] 2020-10-09 07:11
I can confirm too, it's still happening.

**Comment by Dids** [comment] 2020-10-09 07:36
Indeed, this was fine for about a week, but largely just failing today.

**Comment by iMichka** [comment] 2020-10-09 07:38
As said above:

> It's a GitHub issue. Not a homebrew issue.

**Comment by tigertim08** [comment] 2020-10-09 07:48
I'm having the same Issue here, so not solved yet

**Comment by iMichka** [comment] 2020-10-09 07:54
I am locking this issue. The timeouts are a Github issue, so you all need to report it to Github.

Adding a "it's broken for me too" comment does not help moving things forward, and just pollutes the maintainer's notifications with useless messages.

Sorry but we as homebrew maintainers can't do anything about this bug.

**Comment by alebcay** [comment] 2020-10-09 19:57
Just to provide an update, we've reached out to GitHub again and their engineering team is looking at this once again. However, like previously mentioned, there's nothing we can do on our end to fix this issue, so please sit tight. We maintainers are crossing our fingers as hard as everyone else is at this time.
