### ISSUE TITLE
python@3.8 breaks python installation

### ISSUE THREAD

**Issue by oliverandrich** [Homebrew/homebrew-core#48368] opened 2019-12-29 16:31 UTC
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I wanted to install python and python@3.8 in parallel, cause the brews cookiecutter and httpie rely on python@3.8. 

## What happened (include command output)

/usr/local/bin/pip3 from python was replaced with /usr/local/bin/pip3 from python@3.8. For all packages installed with pip3 for global usage, are also using Python 3.8.

<details>
  <summary>Command output</summary>
  <pre>
❯ brew reinstall python
[...]
❯ pip3 --version
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
❯ brew install python@3.8
[...]
❯ pip3 --version
pip 19.3.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
  </pre>
</details>

## What you expected to happen

python@3.8 should be keg-only, so a pip3 that uses this version of python should be stored in /usr/local/Cellar/python@3.8/3.8.1/bin/ and not be referenced from /usr/local/bin.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install python
brew install python@3.8

https://gist.github.com/oliverandrich/bdf9caa4f2d33d10f3f071874b933804#file-python-3-8-2019-12-29_16-22-02-txt

**Comment by fxcoudert** [comment] 2019-12-29 16:59
poke @bayandin @iMichka

**Comment by fxcoudert** [comment] 2019-12-29 17:00
I’m not a Python expert but it looks like the versioned python@3.8 is installing stuff outside its keg: 
```
    # post_install happens after link
    %W[pip3 pip#{xy} easy_install-#{xy} wheel3].each do |e|
      (HOMEBREW_PREFIX/"bin").install_symlink bin/e
    end
```

That `postinstall` is doing a lot of things directly in `HOMEBREW_PREFIX`, to which it should not have any access. That looks like a Bad Idea, but maybe it is more subtle than that…

**Comment by fxcoudert** [comment] 2019-12-29 17:08
@oliverandrich running `brew postinstall python` should fix the issue for you, while we work on the root cause of the bug

**Comment by oliverandrich** [comment] 2019-12-29 17:15
@fxcoudert @bayandin @iMichka Side question: I am working on a new formula for poetry. Should I base this already on python@3.8? Or is it save for a new formula to rely on the "normal" python formula.

**Comment by fxcoudert** [comment] 2019-12-29 17:18
@oliverandrich right now if it depends only on python and nothing else, `python@3.8`. Otherwise, `python`

**Comment by fxcoudert** [comment] 2019-12-29 17:23
Two-stage strategy to fix this:
- python@3.8 postinstall fixed by https://github.com/Homebrew/homebrew-core/pull/48371
- python revision bump to get the correct python postinstall to run again for all users

Meanwhile, users affected should run `brew postinstall python` to fix the issue locally.

**Closed** 2019-12-31 09:32 UTC

**Comment by noamtamim** [comment] 2020-01-21 07:46
I might be missing something. I **want** Python 3.8 to be the default python3 in my system, instead of 3.7. 
Is there a reason not to do it (why is Python@3.8 keg-only)? Is there anything I can do locally to make `python3` and `pip3` use 3.8?
Please explain the situation, as I didn't find anything in https://docs.brew.sh/Homebrew-and-Python and https://formulae.brew.sh/formula/python@3.8.

**Comment by fxcoudert** [comment] 2020-01-21 07:56
We will be migrating everything to Python 3.8 as soon as we can, but migration and testing takes time. Also, not all packages are ready as of now.

**Comment by noamtamim** [comment] 2020-01-21 07:58
@fxcoudert thanks. In the meantime, what's the correct way to run my code against 3.8? Currently all of my scripts are shebanged with `/usr/bin/env python3`.

**Comment by fxcoudert** [comment] 2020-01-21 10:50
Add `/usr/local/opt/python@3.8/bin` to your `PATH`
