### ISSUE TITLE
octave 4.4.0 doc command does not work

### ISSUE THREAD

**Issue by sunilshah** [Homebrew/homebrew-core#29059] opened 2018-06-15 05:17 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Octave builds and runs.

doc command does not work and help command gives error. 
*********
octave:2>doc 
error: doc: unable to find the Octave info manual, Octave installation is incomplete

octave:3> help info
/var/folders/pw/jd_p87zn7n32z498p1c7091h0000gn/T/octave-help-lBWcqz:114: Unknown command `codequoteundirected'.
warning: help: Texinfo formatting filter exited abnormally; raw Texinfo source of help text follows...
'info' is a function from the file /usr/local/Cellar/octave/4.4.0/share/octave/4.4.0/m/miscellaneous/info.m 

******
See GNU Octave - Bugs: bug #53473

Points to old version of texinfo used by octave 

$ which makeinfo
/usr/bin/makeinfo
sunils-imac:Documents sugarcane$ makeinfo --version
makeinfo (GNU texinfo) 4.8

$brew info texinfo
texinfo: stable 6.5 (bottled) [keg-only]
Official documentation format of the GNU project
https://www.gnu.org/software/texinfo/
/usr/local/Cellar/texinfo/6.5 (408 files, 8.3MB)
  Poured from bottle on 2017-09-19 at 10:38:04
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/texinfo.rb
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because software that uses TeX, such as lilypond and octave, require a newer
version of these files.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/texinfo/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/texinfo/lib
*****************
 $brew gist-logs octave 
[https://gist.github.com/958dc364aa2d0e1b4e2ecbe9e33b257e](url)

**Comment by SMillerDev** [comment] 2018-06-15 07:16
The formula uses `"--disable-docs",` as one of the arguments. So I guess this is expected behaviour.

**Comment by apjanke** [comment] 2018-06-16 00:37
BTW, it looks like the "info" docs built under `--enable-docs` are only 3 MB. IMHO, we may as well include them. In Matlab, and thus I assume in Octave, using the documentation interactively from within the REPL is a common use case.

**Comment by apjanke** [comment] 2018-06-16 01:17
I looked around Octave's `--configure` stuff, and there doesn't seem to be a way to tell Octave to use a different `makeinfo` at run time. If you include `texinfo` as a dependency, than the the `info` docs get generated correctly at build time, but it still produces that error when doing a `help <whatever>` at run time. Might be something to ask upstream about.

**Comment by ilovezfs** [comment] 2018-06-16 01:47
CC @schoeps any thoughts?

**Comment by schoeps** [comment] 2018-06-16 06:56
The doc command won't work without gui (it's build on top of qt). The help command can be fixed with a more modern makeinfo. I did it in my fork of the formula https://github.com/dpo/homebrew-openblas. The main idea is:

    # make sure that Octave uses the modern texinfo
    rcfile = buildpath/"scripts/startup/site-rcfile"
    rcfile.append_lines "makeinfo_program(\"#{Formula["texinfo"].opt_bin}/makeinfo\");"

**Comment by ilovezfs** [comment] 2018-06-16 07:03
@schoeps nice!

**Comment by apjanke** [comment] 2018-06-16 07:03
You sure about `doc` not working without a gui? When I built octave with docs but without Qt, `doc` started working, displaying a curses-based help viewer in the terminal.

**Comment by sunilshah** [comment] 2018-06-16 07:14
@schoeps 

 In the brew installed octave 4.4.0, can I make help work correctly?  If yes, can you please elaborate?  

Thanks!

**Comment by sunilshah** [comment] 2018-06-16 07:48
@schoeps 

I just did and tested it.   Did not work - may be I made a mistake?
************************
/usr/local/opt/texinfo/bin/makeinfo --version
texi2any (GNU texinfo) 6.5

Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
*********************
octave:2> makeinfo_program="/usr/local/opt/texinfo/bin/makeinfo"
makeinfo_program = /usr/local/opt/texinfo/bin/makeinfo
octave:3> help mean
/var/folders/pw/jd_p87zn7n32z498p1c7091h0000gn/T/octave-help-oKTLgZ:114: Unknown command `codequoteundirected'.
warning: help: Texinfo formatting filter exited abnormally; raw Texinfo source of help text follows...
'mean' is a function from the file /usr/local/Cellar/octave/4.4.0/share/octave/4.4.0/m/statistics/mean.m

on

 -- mean (X)

******

**Comment by ilovezfs** [comment] 2018-06-16 07:59
```
makeinfo_program("/usr/local/opt/texinfo/bin/makeinfo")
```
not
```
makeinfo_program="/usr/local/opt/texinfo/bin/makeinfo"
```

**Comment by sunilshah** [comment] 2018-06-16 08:02
That worked!  Thanks @ilovezfs.

**Comment by apjanke** [comment] 2018-06-16 11:11
Here's a PR that fixes `doc` and `help` for all users: #29112.

It uses @schoeps's fix for locating texinfo. Thanks @schoeps!

**Comment by ilovezfs** [comment] 2018-06-16 11:49
This is now fixed if you `brew upgrade`. Thanks to @apjanke and @schoeps

**Closed** 2018-06-16 11:51 UTC

**Comment by apjanke** [comment] 2018-06-17 07:36
While we're on the subject: what do you all think about getting the Octave Qt GUI to build under Homebrew? (It's currently broken under 4.4.0, but with a fix already in upstream master.) I understand there are still some issues with Qt-based figures and Retina monitors, but it might be nice to have the full GUI; I'd use it myself.

**Comment by ilovezfs** [comment] 2018-06-17 07:38
Based on the discussion on https://github.com/Homebrew/homebrew-core/pull/28803 I doubt we'll be adding any GUIs anywhere any time soon.

**Comment by apjanke** [comment] 2018-06-17 07:44
Hmmm. Okay. I'll look in to the Octave .app situation and see how much that applies here. I'm not sure it does; the .app download for Octave is a semi-third-party project, and is quite old (4.0.3).

@schoeps, it looks like you're actually involved in the .app packaging for Octave project. What's the situation there?

**Comment by ilovezfs** [comment] 2018-06-17 07:47
Just to be explicit, given the problems it caused when we had it on the science formula, I don't intend to approve bringing back the option.

**Comment by apjanke** [comment] 2018-06-17 07:48
Okay, that makes more sense. I wasn't aware of the history. (Looked through PRs and commits on the new repo and didn't see anything about Qt.) I probably won't pursue it, then.

**Comment by ilovezfs** [comment] 2018-06-17 07:56
@schoeps did the crashing ever get fixed with the latest version of Qt?

**Comment by schoeps** [comment] 2018-06-17 08:02
After adding a few patches Octave’s GUI is doing fine (try for yourself my pullrequest at https://github.com/dpo/homebrew-openblas). Many people use it everyday. Additional changes are that we added tests and use openblas at @dpo’s repository. The octave community consists mainly of scientists and we are pushing for open source and reproducabilty of numerical experiments; this does not go well with closed source libraries (i.e. accelerate).

The app bundle is generated from my homebrew formula using https://github.com/schoeps/octave_installer.

**Comment by ilovezfs** [comment] 2018-06-17 08:04
Is there an app bundle for 4.4.0?

**Comment by schoeps** [comment] 2018-06-17 08:07
Yes but not yet officially.... http://octave.1599824.n4.nabble.com/Please-test-macOS-dmg-for-4-3-92-tp4687817p4687863.html

**Comment by ilovezfs** [comment] 2018-06-17 08:08
Where would it get posted once official?

**Comment by schoeps** [comment] 2018-06-17 08:33
I guess sourceforge

**Comment by ilovezfs** [comment] 2018-06-17 08:40
Is the app bundle fully self-contained or does it require things to be installed from that homebrew-openblas and/or homebrew-core?

**Comment by apjanke** [comment] 2018-06-17 09:35
If the Octave app-bundling project is going to be a going concern, maybe it could get its own little project web page? I've been reading through the Octave web pages the last couple days, and I'm confused as to how it fits in with the main Octave project, how official or supported it is, and where the binaries are coming from. (SourceForge is an all right place for hosting files, but not great as a project presentation page.)

Or maybe I'm just not the target audience, and y'all know just fine what's going on.

**Comment by sunilshah** [comment] 2018-06-17 16:02
@schoeps 

On Apple Accelerate, I was under the impression that BLAS and LAPACK codes (cblas) under Apple accelerate are essentially optimized versions (for Apple hardware) of open source packages. They have the same APIs as well.  So, numerical reproducibility should be similar to other versions of BLAS / LAPACK libraries.  In my experience, Accelerate CBLAS and BLAS codes, numerical behavior is not distinguishable from openblas.   Did you find any counterexamples?

**Comment by schoeps** [comment] 2018-06-17 16:13
@sunilshah no, accelerate is not based on free software (there is no source code available). Please give a reference if you have. However, most blas libraries have the same API (including the non free Intel blas) but that does not make them free. Actually, Accelerate has even issues with the API (single precision fortran interface as far as I recall) which is fixed by `veclibfort`. Sorry, I have no good example at hand of bugs in Accelerate but you should find some on the octave mailing list. My argument is less about bugginess than about openess and reproducibility (A linux user cannot reproduce my results if I use accelerate). Keep in mind that Octave is part of GNU, so the community cares about these issues.

**Comment by apjanke** [comment] 2018-06-18 04:38
@ilovezfs:

> Is the app bundle fully self-contained or does it require things to be installed from that homebrew-openblas and/or homebrew-core?

@schoeps is out on travel, so I'll try to answer this for him. (Correct me if I'm wrong please.)

The app bundle is fully self-contained, like a normal native Mac app. All the dependencies are included inside the Octave.app bundle. (Except AquaTerm. Oh well.) Based on this, I think it would be a good candidate for installation using Cask.

The bundler tool takes an interesting approach: its build process creates a whole new separate Homebrew installation under `/Applications/Octave.app` and uses that to install octave and all its dependencies there, with path references pointing to where the installed app will end up. It does not interact with the main Homebrew installation at all. Then it wraps that /Applications/Octave.app up in an app bundle, and wraps the app bundle up in a DMG for distribution.

I find this really clever, and an interesting use case for Homebrew prefixes in a non-default location.

**Comment by ilovezfs** [comment] 2018-06-18 04:42
@apjanke yeah although sounds like a hack to me if it causes the app to stop working when the app bundle is in any location other than /Applications or has any name other than Octave.app. It really should use e.g. `@loader_path` for relative paths for proper relocatability and native macOS standard macOS behavior.

**Comment by apjanke** [comment] 2018-06-18 05:04
Yep, it's a hack. I'm interested in this project, and maybe relocatability is something I'll be able to make happen.

**Comment by schoeps** [comment] 2018-06-18 05:15
I am aware, too. It used to be on my todo list but with low priority :) I guess a few lines of bash script would be enough to go through the files and fix the paths which start with "/Applications/Octave.app".

**Comment by apjanke** [comment] 2018-06-18 05:19
:)

> I guess a few lines of bash script would be enough to go through the files and fix the paths which start with "/Applications/Octave.app".

It might be more involved than that. That could handle libraries. But what about external commands called by Octave? I don't know how all its Python and other interop fits together. Is it just DLL paths that would need to be fixed?

**Comment by schoeps** [comment] 2018-06-18 05:33
Core Octave does not need python (only some thirdparty packages do and they look for the python binary themselves). I think that Python is a consequence of the QScintilla installation and could be avoided. Anyway, I always hoped that it's sufficient to fix the libraries :)

**Comment by ilovezfs** [comment] 2018-06-18 05:39
>http://octave.1599824.n4.nabble.com/Please-test-macOS-dmg-for-4-3-92-tp4687817p4687863.html

Any sense on the time frame until that becomes "official"?

>https://sourceforge.net/projects/octave/files/Octave%20MacOSX%20Binary/2016-07-11-binary-octave-4.0.3/

What is the status of this one?

**Comment by schoeps** [comment] 2018-06-18 07:31
It becomes official if I have enough trust in it :) The old one 4.0.x is considered outdated.

**Comment by ilovezfs** [comment] 2018-06-18 07:49
>Just  to be explicit, given the problems it caused when we had it on the  science formula, I don't intend to approve bringing back the option.

Changed my mind on this. Given @schoeps says that Qt 5.11.0 is actually working fine now and given how outdated 4.0.x is (nearly two years old now), I'm OK with bringing the Qt option back at least temporarily until there is a viable, current cask if you still want to work on adding that option back to the formula @apjanke. If not, we can just wait for http://octave.1599824.n4.nabble.com/Please-test-macOS-dmg-for-4-3-92-tp4687817p4687863.html to be schoepstrusted.

Once there is a cask, we can reassess the status of the GUI option.

**Comment by ilovezfs** [comment] 2018-06-18 08:43
👍 Thanks @apjanke

**Comment by apjanke** [comment] 2018-06-20 02:58
Homebrew formula whose `bottle` blocks lack `cellar :any` are themselves non-relocatable, right? I'm looking at `gcc`, `hdf5`, `imagemagick`, and `openssl` in particular here.

**Comment by ilovezfs** [comment] 2018-06-20 04:56
Right.
```
brew build --bottle foo
brew bottle -dv foo
```
to see why foo isn't relocatable.

**Comment by apjanke** [comment] 2018-06-20 05:28
Thanks! That gives me good output.

`brew build --bottle foo` doesn't work for me. You mean `brew install --build-bottle foo`?

```
$ brew build --bottle gcc                                                                                                                                                                                master
Error: Unknown command: build
```

**Comment by ilovezfs** [comment] 2018-06-20 05:30
>You mean brew install --build-bottle foo?

Yes. My brain is malfunctioning today.
