### ISSUE TITLE
Cannot install Txt2man by brew install txt2man

### ISSUE THREAD

**Issue by HapCoderWei** [Homebrew/homebrew-core#45964] opened 2019-10-30 01:37 UTC
I want to install txt2man on Mac osx. But brew said `Error: No available formula with the name "txt2man"`. What can i do to find it in brew repo and install this tool?
```
➜  ~ brew install txt2man
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).

Error: No available formula with the name "txt2man"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by SMillerDev** [comment] 2019-10-30 06:26
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request and https://docs.brew.sh/Acceptable-Formulae can help you get started adding software to homebrew.

**Comment by SMillerDev** [comment] 2019-10-30 06:27
Since this is expected behavior I'm closing the issue though.

**Closed by SMillerDev** 2019-10-30 06:27 UTC
