### ISSUE TITLE
Big Sur 11.4 update breaks OpenJDK (Apple Silcon)

### ISSUE THREAD

**Issue by georgemarshall** [Homebrew/homebrew-core#77954] opened 2021-05-25 01:12 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

https://gist.github.com/b6328cb4df3b7a3d4bd317f951d40722

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `maven` and `openapi-generator` after updating to latest macOS 11.4 release.

### What happened (include all command output)?

OpenJDK runtime panicked

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:531), pid=43092, tid=9731
#  Error: ShouldNotReachHere()
#
# JRE version: OpenJDK Runtime Environment (16.0+14) (build 16+14)
# Java VM: OpenJDK 64-Bit Server VM (16+14, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /private/tmp/openjdk-test-20210524-43077-c7nph8/hs_err_pid43092.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
```

### What did you expect to happen?

The application to run and exit successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openjdk
brew test openjdk
brew install -s openjdk
```

**Comment by georgemarshall** [comment] 2021-05-25 01:15
The following PRs may be able to remedy the issue #72535 and #76313. Formula is unable to built from source as the bootstrap builder is no longer available.

`Error: Failed to download resource "openjdk--boot-jdk"`

**Comment by Toberumono** [comment] 2021-05-25 01:23
Based on the panic message, it looks like the tests were running against OpenJDK 16, but Homebrew installs OpenJDK 15.
Did you previously attempt to install the JDK via a different source?
Either way, are you able to provide the log file mentioned in the panic message?

**Comment by georgemarshall** [comment] 2021-05-25 06:10
> Based on the panic message, it looks like the tests were running against OpenJDK 16, but Homebrew installs OpenJDK 15.

If you look at the OpenJDK formula, it does a special build that uses OpenJDK 16 for Apple Silcon.

**Comment by Toberumono** [comment] 2021-05-25 06:28
Then I'm the goat. I completely forgot that part of the formula.
Regardless, do you have the full log referenced in the panic message? Without that, it's rather difficult to debug (or even determine if the issue would be resolved via a JDK update).

**Comment by SMillerDev** [comment] 2021-05-25 06:57
11.4 is also a pre-release AFAIK so things are expected to break.

**Comment by carlocab** [comment] 2021-05-25 07:13
11.4 is not a pre-release: https://developer.apple.com/documentation/macos-release-notes (or, just check "Software Update" in "System Preferences").

**Comment by Czahrien** [comment] 2021-05-25 18:45
I am running into this too after updating to 11.4 this morning.

Narrowed it down as much as possible and discovered that merely running the "java" command without arguments from the commandline causes a crash so I do not even need to run an application or anything to reproduce it.

Crash dump: 

[hs_err_pid28308.log](https://github.com/Homebrew/homebrew-core/files/6541603/hs_err_pid28308.log)

For now I installed openjdk@11 which works as expected.

Please get back to me if you want more details.

**Comment by Czahrien** [comment] 2021-05-25 20:20
Did a bit more digging and found this issue on OpenJDK's issue tracker which is likely related https://bugs.openjdk.java.net/browse/JDK-8267235

**Comment by georgemarshall** [comment] 2021-05-25 21:46
@Czahrien thanks for the info, I was trying to track down their issue tracker. My curiosity still resolves around the PRs referenced in https://github.com/Homebrew/homebrew-core/issues/77954#issuecomment-847458629. I am hoping to find some time soon to try those formulas to see if a new build would fix the issue.

**Comment by wangliang1989** [comment] 2021-05-29 06:16
2 days ago, the bug has been resolved (https://bugs.openjdk.java.net/browse/JDK-8267235).

I need to run programs based java everyday.

Please, please update java in brew

**Comment by cho-m** [comment] 2021-05-30 19:45
Homebrew is planning to update `openjdk` formula to JDK 17 Early Access Build 24 for Apple Silicon devices in #72535, which will have the upstream JDK fix.

If everything goes well with CI run, we can hopefully have it ready later today or tomorrow (America timezone). Worst-case scenario would probably add a couple extra days (it takes ~1 day to run CI tests).

Based on readout from ARM CI node running macOS 11.4, I believe this build shouldn't hit the issue anymore.

A couple things to note:
1. This is again an Early Access (non-GA) build. OpenJDK 16 (General Audience) doesn't compile on Apple Silicon, so if you require JDK16, then you may want to explore alternative options.
2. Along similar lines, there is currently no GA build available with upstream fix. The fix was added to JDK17-ea Build 24 and backported to JDK 16.0.2 Build 6.

**Comment by carlocab** [comment] 2021-05-31 10:07
Fixed in https://github.com/Homebrew/homebrew-core/pull/72535.

**Closed by carlocab** 2021-05-31 10:07 UTC
Labels: bug
