### ISSUE TITLE
Relative symlinks to Cellar binaries breaks kpathsea in TexLive

### ISSUE THREAD

**Issue by ESultanik** [Homebrew/homebrew-core#176090] opened 2024-07-01 18:25 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: e5f776b3e23cae8f1b6c3d1194b8329bf701965f
Last commit: 12 hours ago
Core tap JSON: 01 Jul 17:28 UTC
Core cask tap JSON: 01 Jul 17:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to use the `pdflatex` command to compile LaTeX into a PDF using [the version of TeXLive installed through Homebrew](https://formulae.brew.sh/formula/texlive).

### What happened (include all command output)?

Running `pdflatex` by itself works fine, but running it on a simple `.tex` file results in an error:
```
lstat(/opt/homebrew/bin/Cellar) failed: /opt/homebrew/bin/Cellar: No such file or directory
kpathsea: Can't get directory of program name: /opt/homebrew/bin//pdflatex
```

### What did you expect to happen?

`pdflatex test.tex` should have resulted in `test.pdf` without an error.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install texlive
```

```
$ cat test.tex
\documentclass{article}

\begin{document}

Testing

\end{document}
```

```
$ pdflatex test.tex
lstat(/opt/homebrew/bin/Cellar) failed: /opt/homebrew/bin/Cellar: No such file or directory
kpathsea: Can't get directory of program name: /opt/homebrew/bin//pdflatex
```

`kpathsea` is TeXLive's utility for resolving paths that is called internally from `pdflatex`. It occasionally has to resolve the path to the `pdflatex` binary itself. It apparently is not resilient to being called from a relative symlink. If I run the following command to replace the relative symlink with an absolute path, it fixes my issue and causes `pdflatex test.tex` to behave as expected:
```
$ ln -F -s /opt/homebrew/Cellar/texlive/20240312/bin/pdflatex /opt/homebrew/bin/pdflatex
```

**Comment by woodruffw** [comment] 2024-07-01 18:58
Hmm, I was unable to reproduce this:

```console
arbet:tmp william$ pdflatex test.tex 
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024/Homebrew) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-02-20>

(/opt/homebrew/Cellar/texlive/20240312/share/texmf-dist/tex/latex/base/article.
cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class

(/opt/homebrew/Cellar/texlive/20240312/share/texmf-dist/tex/latex/base/size10.c
lo))
(/opt/homebrew/Cellar/texlive/20240312/share/texmf-dist/tex/latex/l3backend/l3b
ackend-pdftex.def)
No file test.aux.
[1{/opt/homebrew/Cellar/texlive/20240312/share/texmf-dist/fonts/map/pdftex/updm
ap/pdftex.map}] (./test.aux) )</opt/homebrew/Cellar/texlive/20240312/share/texm
f-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on test.pdf (1 page, 12687 bytes).
Transcript written on test.log.

arbet:tmp william$ file test.pdf 
test.pdf: PDF document, version 1.5
```

I also confirmed that I have the same symlink:

```console
arbet:tmp william$ ls -al /opt/homebrew/bin/pdflatex
lrwxr-xr-x  1 william  admin  39 Jul  1 14:51 /opt/homebrew/bin/pdflatex -> ../Cellar/texlive/20240312/bin/pdflatex
```

**Comment by ESultanik** [comment] 2024-07-01 19:20
It looks like the root cause may be my shell (fish) and/or my environment (PATH), because when I run this in bash I can't reproduce it 🤦‍♂️.

**Comment by carlocab** [comment] 2024-07-01 21:22
Closing as not reproducible. Feel free to continue discussion here, though.

**Closed by carlocab** 2024-07-01 21:22 UTC
Labels: bug

**Comment by ESultanik** [comment] 2025-05-19 15:42
This happened to me again. I noticed that the texlive symlinks in `/opt/homebrew/bin` all contained duplicates prefixed with a forward slash. You can see this hinted in my original post with the path `/opt/homebrew/bin//pdflatex` in the error message. It turns out there were two identical symlinks lin `/opt/homebrew/bin/`: `pdflatex` and `\/pdflatex`. Deleting the symlinks prefixed with `\/` solved my problem. I have no idea how, why, or by what they were created.
