### ISSUE TITLE
Cannot use zsh-builtin completion for git since f710a1395

### ISSUE THREAD

**Issue by agross** [Homebrew/homebrew-core#33275] opened 2018-10-22 21:00 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question.
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? 
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I prefer to use the git completion from zsh rather than the bundled completion that comes with the git package. Unfortunately, f710a1395 removes to option to omit the bundled completion files from the git package and places the completion function in a path that is preferred to what ships with zsh.

These are the directories in question:

```sh
$ zsh -c 'print -l $fpath'
/usr/local/share/zsh/site-functions
/usr/local/Cellar/zsh/5.6.2_1/share/zsh/functions
```

The first (preferred) directory is the location the completion file (`_git`) from the git package is installed to. The second one contains the more advanced completion shipped with zsh (also `_git`).

The commit message of f710a1395 does not explain why the `--without-completions` option was removed nor how to work around it.

The only workaround I found is to move the `zsh/<version>` element to the beginning of the array which is a rather nasty hack:

```zsh
fpath[$fpath[(i)/usr/local/Cellar/zsh/5.6.2_1/share/zsh/functions]]=()
fpath=(/usr/local/Cellar/zsh/5.6.2_1/share/zsh/functions $fpath)
```

While this works it makes is impossible to have selective overrides for zsh-bundled completions.

# Reproduction

```sh
$ cd "$(brew --repository)"
$ git checkout f710a1395 -- Formula/git.rb
$ brew install git --without-completions
==> Downloading https://homebrew.bintray.com/bottles/git-2.18.0.mojave.bottle.tar.gz
...
$ ls -la /usr/local/share/zsh/site-functions/_git
lrwxr-xr-x 1 agross admin 58 Oct 22 22:28 /usr/local/share/zsh/site-functions/_git -> ../../../Cellar/git/2.19.0_1/share/zsh/site-functions/_git

# => override installed
```

```sh
$ cd "$(brew --repository)"
$ git checkout f710a1395~ -- Formula/git.rb
$ brew reinstall git --without-completions
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.18.0.tar.xz
...
$ ls -la /usr/local/share/zsh/site-functions
ls: cannot access '/usr/local/share/zsh/site-functions/_git': No such file or directory

# => override not installed
```

**Comment by SMillerDev** [comment] 2018-10-23 06:49
Homebrew is removing options based on limited usage (as we see it in the analytics here: https://formulae.brew.sh/analytics/). These options provide a lot of reasons for builds to break and aren't tested. 

In your specific case the best option might be to improve zsh autocomplete for everyone by contributing it to git. If you prefer to keep the option you'll have to use `brew extract` to copy the git formula to a tap.

**Comment by agross** [comment] 2018-10-23 08:34
Another option is to hard-code the formula to install only the bash completion by default. Anyone using zsh will then automatically get the better completion provided by zsh itself. Anyone using bash will get the completion provided by git.

**Comment by gmcinalli** [comment] 2018-10-23 09:36
@agross Yes, but if we hard-code it we should do it every time the git formula is updated, correct?

**Comment by agross** [comment] 2018-10-23 10:15
Not sure what you mean by "everytime the formula is updated". If you mean installing the bash completion for the respective git version that is installed, then yes, do that. It's what the current formula does as well. But please omit the `_git` symlink.

**Comment by MikeMcQuaid** [comment] 2018-10-23 10:34
Which ZSH completion (the one provided by ZSH or the one provided by Git) is up for debate and as a result I think we should defer to installing both versions and require users to manually configure which one they wish to use. I personally use Git and ZSH pretty heavily and am happy with Git's ZSH completion.

**Comment by gmcinalli** [comment] 2018-10-23 10:39
@agross Sorry but I didn't understand, every time git updates what should I do to get the working zsh completions back?

**Comment by agross** [comment] 2018-10-23 10:54
@gmcinalli You as a brew package author or you as a zsh+git user?

**Comment by agross** [comment] 2018-10-23 10:59
@MikeMcQuaid zsh installs its version when you install zsh. There is no option to disable that.

The git package overrides it with an inferior version, that is what I'm trying to resolve here. We had an option to decide upon this which was taken away from me and others.

What I suggest is from my perspective what you suggest: You can decide whether you want to use the inferior version by adding git's packaged (inferior) completion to your zsh `fpath`.

**Comment by MikeMcQuaid** [comment] 2018-10-23 14:31
> The git package overrides it with an inferior version, that is what I'm trying to resolve here.

That is your opinion and it's not universally held. In general we defer to what upstream does.

**Comment by gmcinalli** [comment] 2018-10-23 14:36
@agross Sorry, me as a zsh+git user.

**Comment by agross** [comment] 2018-10-23 15:50
@gmcinalli I [remove `/usr/local/share/zsh/site-functions/_git`](https://github.com/agross/dotfiles/commit/4938bc8987a5b4ef0c7411a2c4b988d89a3ade11) on every invocation of the shell.

**Comment by agross** [comment] 2018-10-23 15:52
> In general we defer to what upstream does.

Who is upstream, zsh or git? What does the upstream "do" in this case? Both provide a file, git as a "contrib" file, zsh as a core file.

**Comment by fxcoudert** [comment] 2018-10-23 15:54
If git completion is not doing a good job, surely the better path, for all involved, is to contribute to them a better version?

**Comment by fxcoudert** [comment] 2018-11-09 09:41
Closing now. The issue with git's completion file should be reported to git and discussed with them. They can fix it, in which case everyone will benefit, or drop it, in which case the issue is also fixed.

**Closed by fxcoudert** 2018-11-09 09:41 UTC

**Comment by wjv** [comment] 2018-11-09 09:49
As explained, it’s not nearly as simple as that. _But_ I understand that this is not considered a problem here, so we’ll continue to work around this issue.

Thanks for your time.

**Comment by sometimesfood** [comment] 2018-11-15 16:57
@MikeMcQuaid: The problem with the ZSH completion provided via Git contrib is that it is not as actively maintained as the one bundled with ZSH. This results in less features and more bugs than the ZSH version.

Here's a bug I reported two years ago:
https://marc.info/?l=git&m=147265392409883&w=2

Here's the commit history of the ZSH completion provided by Git:
https://github.com/git/git/commits/master/contrib/completion/git-completion.zsh

Here's the commit history of the ZSH completion bundled with ZSH:
https://github.com/zsh-users/zsh/commits/master/Completion/Unix/Command/_git

@wjv's suggestion seems quite sensible:

> My preferred solution would be to just stop installing the git/contrib completion script from the recipe, and rely on the completion that ships with zsh.
