### ISSUE TITLE
brew install vim: Error: vim: Unsupported special dependency :python

### ISSUE THREAD

**Issue by ngtuna** [Homebrew/homebrew-core#44845] opened 2019-10-03 08:03 UTC
```
$ brew update
Already up-to-date.
$ brew install vim
Updating Homebrew...
Error: vim: Unsupported special dependency :python
$ brew uninstall vim
Error: No such keg: /usr/local/Cellar/vim
```

**Comment by fxcoudert** [comment] 2019-10-03 08:51
Duplicate of your other issue #44844

**Closed by fxcoudert** 2019-10-03 08:51 UTC
