### ISSUE TITLE
mpv pkgconfig file is unusable

### ISSUE THREAD

**Issue by tko** [Homebrew/homebrew-core#125973] opened 2023-03-17 19:01 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.0.6-137-gf09fcf4
ORIGIN: https://github.com/Homebrew/brew
HEAD: f09fcf45d41967b809fc3a6a3e3f645ac8383891
Last commit: 2 hours ago
Core tap JSON: 17 Mar 18:39 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0.0
HOMEBREW_EDITOR: nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false

❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Get compiler flags needed to locate header files for `mpv`

Because I'm trying to make an `mpv` plugin and need the include path for the headers.

### What happened (include all command output)?

❯ pkg-config --cflags --libs mpv
Package libarchive was not found in the pkg-config search path.
Perhaps you should add the directory containing `libarchive.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libarchive', required by 'mpv', not found

### What did you expect to happen?

To get compiler command line flags for mpv.
Similar to how I could get them for, for example `libass`, a dependency of mpv.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mpv
```

**Comment by ZhongRuoyu** [comment] 2023-03-17 19:34
`brew info libarchive` will give you the following caveats. It should have been shown when you installed it as `mpv`'s dependency.

```plaintext
libarchive is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have libarchive first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/libarchive/bin:$PATH"' >> ~/.zshrc

For compilers to find libarchive you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/libarchive/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/libarchive/include"

For pkg-config to find libarchive you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/libarchive/lib/pkgconfig"
```

Try `export PKG_CONFIG_PATH="/opt/homebrew/opt/libarchive/lib/pkgconfig"`, and see if it works. If `PKG_CONFIG_PATH` is already set, you may need `export PKG_CONFIG_PATH="/opt/homebrew/opt/libarchive/lib/pkgconfig:$PKG_CONFIG_PATH"` instead.

**Comment by tko** [comment] 2023-03-17 19:50
_I_ did not install `libarchive`, it came as baggage for `mpv` -- I'm only interacting directly with `mpv` and from my perspective mpv as installed is partially broken.

I understand the extra steps needed if I were to use `libarchive` and could deal with that, but I'm not using it.
I'm using `mpv` which didn't come with any caveats.
IMO either 1) mpv pkgconfig should work out of the box, 2) print appropriate caveats, or 3) not include the pkgconfig file.

**Comment by ZhongRuoyu** [comment] 2023-03-17 20:19
> I did not install libarchive, it came as baggage for mpv

Right, if `libarchive` is installed as a dependency, no caveats will be shown.

> IMO either 1) mpv pkgconfig should work out of the box, 2) print appropriate caveats, or 3) not include the pkgconfig file.

1. `libarchive`'s keg-only status on macOS is the only reason why this requires some tweaks, but that couldn't be changed.
2. `brew` does not print out dependencies' caveats by design. See https://github.com/Homebrew/brew/issues/13936. If you think this needs a re-evaluation due to pkg-config, please file an issue at https://github.com/Homebrew/brew.
3. That's not really an option because pkg-config will stop working.

I'm closing this issue as the problem has already been solved.

**Closed by ZhongRuoyu** 2023-03-17 20:19 UTC
Labels: bug

**Comment by carlocab** [comment] 2023-03-17 20:23
Actually we can probably modify mpv's `.pc` file so that it refers to `libarchive` via a path, like so:

https://github.com/Homebrew/homebrew-core/blob/ca493ded3c8c850c5159b58251448a9921c2423d/Formula/glib.rb#L90-L93

Happy to review a PR for this.

**Comment by tko** [comment] 2023-03-17 20:45
The comment in `glib.rb` seems to be exactly applicable to `mpv` as well, if you substitute
* `gobject-2.0` == `mpv`
* `libffi` == `libarchive`

```
# `pkg-config --print-requires-private gobject-2.0` includes libffi,
# but that package is keg-only so it needs to look for the pkgconfig file
# in libffi's opt path.
```

**Comment by carlocab** [comment] 2023-03-17 20:49
Yes, that's the point I was making.

**Comment by ZhongRuoyu** [comment] 2023-03-17 20:55
See #125983.
