### ISSUE TITLE
libsodium: Failed to download resource "libsodium"

### ISSUE THREAD

**Issue by liufuyang** [Homebrew/homebrew-core#104191] opened 2022-06-22 12:36 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: fba051f98f609634ae4392d0053ddfc627f8cdb3
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d1945aece64d3c5bbf47d6251311ebfa79f77c04
Core tap last commit: 85 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install `zmq`, which needs `libsodium`

```
brew install zmq
==> Downloading https://ghcr.io/v2/homebrew/core/libsodium/manifests/1.0.18_1
Already downloaded: /Users/fuyangl/Library/Caches/Homebrew/downloads/d14e811d4b4dc5be4758836da0008ea37879d7a8f7d353829decd14f70a20dec--libsodium-1.0.18_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libsodium/blobs/sha256:493ce4faacb1fba817e73213cde331a68f73531d89260200726cc17c1ca00797
curl: (22) The requested URL returned error: 401                              

Error: zeromq: Failed to download resource "libsodium"
Download failed: https://ghcr.io/v2/homebrew/core/libsodium/blobs/sha256:493ce4faacb1fba817e73213cde331a68f73531d89260200726cc17c1ca00797
```

### What happened (include all command output)?

```
brew install libsodium
==> Downloading https://ghcr.io/v2/homebrew/core/libsodium/manifests/1.0.18_1
Already downloaded: /Users/fuyangl/Library/Caches/Homebrew/downloads/d14e811d4b4dc5be4758836da0008ea37879d7a8f7d353829decd14f70a20dec--libsodium-1.0.18_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libsodium/blobs/sha256:493ce4faacb1fba817e73213cde331a68f73531d89260200726cc17c1ca00797
curl: (22) The requested URL returned error: 401                              

Error: libsodium: Failed to download resource "libsodium"
Download failed: https://ghcr.io/v2/homebrew/core/libsodium/blobs/sha256:493ce4faacb1fba817e73213cde331a68f73531d89260200726cc17c1ca00797
```

### What did you expect to happen?

libsodium get installed without 401 error code.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libsodium
```
```

**Comment by MikeMcQuaid** [comment] 2022-06-22 12:37
Duplicate of https://github.com/Homebrew/brew/issues/13460

**Closed by MikeMcQuaid** 2022-06-22 12:37 UTC
Labels: bug
