### ISSUE TITLE
homebrew's hledger gives corrupt output when pressing backspace

### ISSUE THREAD

**Issue by simonmichael** [Homebrew/homebrew-core#109922] opened 2022-09-07 22:56 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~/src/hledger$ brew gist-logs hledger
Error: No logs.
~/src/hledger$ brew config
HOMEBREW_VERSION: 3.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 93ea8cb2c40e1ef25f1489b0267526bd47bc8030
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f341d50049095213e1a2185cf9aef3800d2f318a
Core tap last commit: 35 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.NfFmsa72mS/org.macosforge.xquartz:0
HOMEBREW_EDITOR: emacsclient -a "" -s2 -nw
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
~/src/hledger$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  delta
  httping
  multitail

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/simon/.local/bin/propellor-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.10
  libomp
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Delete some tab-completed input at a `hledger add` prompt (to confirm user bug report https://github.com/simonmichael/hledger/issues/1928). 
I ran
```
/opt/homebrew/bin/hledger -f /dev/null add
```
and at the first date prompt, pressed TAB then pressed BACKSPACE three times.

### What happened (include all command output)?

Most times, the first two backspaces delete a character as expected but the third press deletes several lines of output including text which is normally undeletable. At this point the screen looks like:
```
$ /opt/homebrew/bin/hledger-1.26 -f/dev/null add
Adding transactions to journal file /dev/null
Any command line arguments will be used as defaults.
Use tab key to complete, readline keys to edit, enter to accept defaults.
An optional (CODE) may follow transaction dates.
An optional ; COMMENT may follow descriptions or amounts.
If you make a mistake, enter < at any prompt to go one step backward.
To end a transaction, enter . when prompted.
T
```

### What did you expect to happen?

Backspace should delete single characters until the input is gone, then stop. A non-brew hledger executable shows the correct output after three presses:
```
$ hledger-1.26 -f/dev/null add
Adding transactions to journal file /dev/null
Any command line arguments will be used as defaults.
Use tab key to complete, readline keys to edit, enter to accept defaults.
An optional (CODE) may follow transaction dates.
An optional ; COMMENT may follow descriptions or amounts.
If you make a mistake, enter < at any prompt to go one step backward.
To end a transaction, enter . when prompted.
To quit, enter . at a date prompt or press control-d or control-c.
Date [2022-09-07]: 2022-09
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install hledger
hledger -f /dev/null add
# press TAB, BACKSPACE, BACKSPACE, BACKSPACE
# if it works correctly, CTRL-c to quit and try again, alternating tab completion and backspace
# reproduced in iterm3 and apple Terminal
```

**Comment by cho-m** [comment] 2022-09-08 00:27
May be specific to Apple Silicon as I was only able to reproduce there and wasn't able to see issue on Intel macOS or Linux.

Were the non-brew tests done on a native ARM binary?

Also noticed a segfault when changing terminal size. Again, only with ARM binary.

Not sure of reason for issue though. Only noticeable difference is GHC builds would be done through LLVM backend on ARM.

**Comment by cho-m** [comment] 2022-09-08 01:26
Might be possible to fix by updating Haskell dependencies using a newer Stack resolver. Looks like Homebrew builds with `lts-17.5` which is from 2021-03-03:
https://github.com/Homebrew/homebrew-core/blob/1fd926c11b88cb56ceb975d67df03011e6783eb9/Formula/hledger.rb#L52-L53

---

At least segfaults go away with newer resolver. Not sure which package update is needed. `terminfo` package did get an Apple Silicon bug fix in 0.4.1.5.

**Comment by simonmichael** [comment] 2022-09-08 01:38
Yes I am using arm executables. The suggestion of using a newer resolver is very good, many bugs have probably been fixed. terminfo sounds likely, another relevant lib might be haskeline.

**Comment by cho-m** [comment] 2022-09-13 04:09
Should hopefully be fixed with 1.27. I didn't see above issues when trying locally, but would like confirmation before closing.

**Comment by simonmichael** [comment] 2022-09-13 04:33
I believe it is fixed. Testing again, I could somewhat reliably reproduce with 1.26, and could never reproduce with 1.27. Thanks!

**Closed** 2022-09-13 04:46 UTC
Labels: bug, 11-arm64, 12-arm64

**Comment by veikus** [comment] 2022-09-13 21:34
Checked on 1.27, works correctly. Thank you.
