### ISSUE TITLE
brew install lastpass-cli --with-pinentry fails

### ISSUE THREAD

**Issue by phoolish** [Homebrew/homebrew-core#9740] opened 2017-02-08 01:01 UTC
### Bug reports:
I am running brew v1.1.9 on OSX 10.12.3

I ran `brew install lastpass-cli --with-pinentry`

and received 
```bash
==> Using the sandbox
==> Downloading https://github.com/lastpass/lastpass-cli/archive/v1.1.2.tar.gz
Already downloaded: /Users/lphilbrook/Library/Caches/Homebrew/lastpass-cli-1.1.2.tar.gz
==> make PREFIX=/usr/local/Cellar/lastpass-cli/1.1.2 install
==> make MANDIR=/usr/local/Cellar/lastpass-cli/1.1.2/share/man install-doc
Last 15 lines from /Users/lphilbrook/Library/Logs/Homebrew/lastpass-cli/02.make:
to the PKG_CONFIG_PATH environment variable
No package 'bash-completion' found
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/lastpass-cli-20170207-12595-my48hu/lastpass-cli-1.1.2/build
/Library/Developer/CommandLineTools/usr/bin/make -C build install-doc
Scanning dependencies of target doc-man
[100%] Generating lpass.1
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/Cellar/asciidoc/8.6.9_1/etc/asciidoc/docbook-xsl/manpage.xsl" "/private/tmp/lastpass-cli-20170207-12595-my48hu/lastpass-cli-1.1.2/build/lpass.1.xml" returned non-zero exit status 5
make[4]: *** [lpass.1] Error 1
make[3]: *** [CMakeFiles/doc-man.dir/all] Error 2
make[2]: *** [CMakeFiles/install-doc.dir/rule] Error 2
make[1]: *** [install-doc] Error 2
make: *** [install-doc] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html
```

Running these commands first seemed to solve it.
```bash
brew reinstall asciidoc --with-docbook-xsl
export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
```

**Comment by ilovezfs** [comment] 2017-02-08 05:47
I was seeing this on one of our CI nodes the other day, and then it spontaneously resolved itself. It sounds like the dependency should be
```
depends_on "asciidoc" => [:build, "with-docbook-xsl"]
```
instead of just
```
depends_on "asciidoc" => :build
```
but I'm wondering why we have that as an option at all as opposed to always building with-docbook-xsl. CC @DomT4 do you know the reason it's only optional currently?

**Comment by DomT4** [comment] 2017-02-08 06:21
I'll double check later through my stash of old problems but off the top of my head I have no justification for the status quo.

**Comment by zmwangx** [comment] 2017-02-08 18:53
> I'm wondering why we have that as an option at all as opposed to always building with-docbook-xsl.

Because some people might be opposed to shelling out ~100MB for docbook-xsl?

**Comment by phoolish** [comment] 2017-02-08 20:02
It should also be noted that there use to be an option to build with docs ` --with-doc`. It is still referenced in the brew install documentation on the project repo. I am unclear why it was removed in the first place.

**Comment by ilovezfs** [comment] 2017-02-19 09:55
@phoolish that's a formula-by-formula option, not a global option like --verbose.

**Comment by ilovezfs** [comment] 2017-02-19 10:06
I cannot reproduce this issue in a clean installation of brew, so closing for now. Please let us know if it's still a problem.

**Comment by phoolish** [comment] 2017-02-19 16:24
I don't have a clean system to test on, but I will next week. I will reopen if necessary. Thanks!

**Comment by ilovezfs** [comment] 2017-02-19 16:26
Thanks @phoolish

**Comment by phoolish** [comment] 2017-03-15 14:08
@ilovezfs Finally, got around to testing this on a fresh system and it is definitely still an issue.

**Comment by peerster** [comment] 2017-09-01 07:31
Ran into the same problem on macOS Sierra 10.12.6 when uprading lastpass-cli. The workaround suggested by @phoolish solved it.

```
> brew --version
Homebrew 1.3.1
Homebrew/homebrew-core (git revision 61c13; last commit 2017-08-31)
```

**Comment by phoolish** [comment] 2017-09-05 16:24
@ilovezfs can you reopen the issue. folks are still experiencing the problem.

**Comment by ilovezfs** [comment] 2017-09-05 16:29
Sure.

**Comment by ilovezfs** [comment] 2017-09-26 17:02
stalebot, go take your medicine

**Comment by llimllib** [comment] 2017-09-28 14:58
I also just experienced this problem, and the workaround worked for me.

Mac 10.13, brew 1.3.4

**Comment by llimllib** [comment] 2017-10-19 17:07
This remains an issue, waiting on #19382 looks like

**Comment by ilovezfs** [comment] 2017-10-19 17:16
I've closed #19382 as this doesn't affect CI and I cannot reproduce the issue.

**Comment by ilovezfs** [comment] 2017-10-19 17:17
Can someone who is experiencing this please provide their `brew gist-logs lastpass-cli`

**Comment by DomT4** [comment] 2017-10-20 01:23
The only way I can persistently reproduce this is my denying the process access to the internet.
```
[100%] Generating lpass.1
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/Cellar/asciidoc/8.6.9_1/etc/asciidoc/docbook-xsl/manpage.xsl" "/private/tmp/lastpass-cli-20171020-76144-jqkrae/lastpass-cli-1.2.1/build/lpass.1.xml" returned non-zero exit status 5
make[4]: *** [lpass.1] Error 1
make[3]: *** [CMakeFiles/doc-man.dir/all] Error 2
make[2]: *** [CMakeFiles/install-doc.dir/rule] Error 2
make[1]: *** [install-doc] Error 2
make: *** [install-doc] Error 2
```
Otherwise 🤷‍♂️.

**Comment by ilovezfs** [comment] 2017-10-20 01:25
Ah OK. That makes sense since docbook-xsl just makes those available offline.

**Comment by llimllib** [comment] 2017-10-20 01:35
I definitely experienced it while connected to the internet, but I don't feel like uninstalling and reinstalling a bunch of stuff to maybe reproduce it 🤷‍♂️

**Comment by ilovezfs** [comment] 2017-10-20 04:25
This should be fixed now if you `brew update`.

**Closed** 2017-10-20 04:25 UTC
Labels: user configuration
