### ISSUE TITLE
gitk broken with git-gui 2.30.0

### ISSUE THREAD

**Issue by janusw** [Homebrew/homebrew-core#68798] opened 2021-01-11 16:26 UTC
# Bug report

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Running gitk on a git working directory to visualize history (as always).

## What happened (include command output)

gitk starts up alright and shows a GUI window, but it does not show any commits.

Selecting `File -> Update` shows the following error message:

<pre>
Error: can't read "mainheadid": no such variable

Details:
can't read "mainheadid": no such variable
can't read "mainheadid": no such variable
    while executing
"set oldmainhead $mainheadid"
    (procedure "rereadrefs" line 10)
    invoked from within
"rereadrefs"
    (procedure "updatecommits" line 11)
    invoked from within
"updatecommits"
    (menu invoke)
</pre>

Selecting `File -> Reload` shows a different error:

<pre>
Error: can't read "viewcomplete(0)": no such variable

Details:
can't read "viewcomplete(0)": no such variable
can't read "viewcomplete(0)": no such variable
    while executing
"if {!$viewcomplete($curview)} {
        stop_rev_list $curview
    }"
    (procedure "reloadcommits" line 11)
    invoked from within
"reloadcommits"
    (menu invoke)
</pre>

When closing the gitk window, I see the following output in the Terminal:

<pre>
Error in startup script: window "." was deleted before its visibility changed
    while executing
"tkwait visibility ."
    (file "/usr/local/bin/gitk" line 12661)
</pre>

## What you expected to happen

gitk shows the repository history with all commits, as it did with previous versions.

## Step-by-step reproduction instructions (by running `brew` commands)

<pre>
brew install git-gui
gitk
</pre>

## Output of `brew config` and `brew doctor` commands

<pre>
% brew config
HOMEBREW_VERSION: 2.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7d7b703696d6d01eda4d4716257ccb0dbe3ab5a
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 32e4bba929379ab3fdf82deef1d99414ea3b8ce5
Core tap last commit: 7 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Kt05rypui7/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.271.09, 1.8.0_131
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11

% brew doctor
Your system is ready to brew.
</pre>

**Comment by bronzeiii** [comment] 2021-01-12 03:15
Also encountered a gitk startup problem after upgraded to git-gui 2.23.0 version, though it's a different error output

```
✦ ➜ gitk &
[2] 43472
objc[43472]: autorelease pool page 0x7f863400f000 corrupted
  magic     0x00000000 0x00000000 0x00000000 0x00000000
  should be 0xa1a1a1a1 0x4f545541 0x454c4552 0x21455341
  pthread   0x113138dc0
  should be 0x113138dc0
```

```
✦2 ➜ brew config
HOMEBREW_VERSION: 2.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7d7b703696d6d01eda4d4716257ccb0dbe3ab5a
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8b09d773307b23a2894a0cbec9072fe84efa7547
Core tap last commit: 13 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_261
macOS: 10.15.7-x86_64
CLT: 12.0.32.28
Xcode: N/A

✦ ➜ brew doctor
Your system is ready to brew.
```

**Comment by SMillerDev** [comment] 2021-01-12 07:36
That sounds like an upstream bug that should be reported.

**Comment by janusw** [comment] 2021-01-12 07:44
> **UPDATE** - git-gui 2.30.0 works properly with tcl-tk 8.6.10 version, but not with 8.6.11

Thanks for the hint! Is there a simple way to downgrade tcl-tk via homebrew? Unfortunately I only see version 8.6.11:

```
% brew list --versions tcl-tk
tcl-tk 8.6.11
```

**Comment by leewillis77** [comment] 2021-01-12 09:37
Looks like it's already known upstream: https://github.com/git/git/pull/944

**Comment by SMillerDev** [comment] 2021-01-12 10:01
If anyone has time to make a pull request that applies the patch to the git-gui formula that would be appreciated, otherwise I'll make one in a couple of hours.

**Comment by bronzeiii** [comment] 2021-01-12 12:57
> > **UPDATE** - git-gui 2.30.0 works properly with tcl-tk 8.6.10 version, but not with 8.6.11
> 
> Thanks for the hint! Is there a simple way to downgrade tcl-tk via homebrew? Unfortunately I only see version 8.6.11:
> 
> ```
> % brew list --versions tcl-tk
> tcl-tk 8.6.11
> ```

Hey Janus - I manually installed tcl-tk 8.6.10 version, and edited gitk binary file to use the older version.  Below is the steps I took. 

1. brew tap bronzeiii/tcl-tk https://github.com/bronzeiii/tcl-tk   (bronzeiii/tcl-tk is my personal github repo)
2. brew extract --version 8.6.10 tcl-tk bronzeiii/tcl-tk
3. brew install tcl-tk@8.6.10 

Hope this helps
Jason

**Comment by carlocab** [comment] 2021-01-12 13:03
Opened a PR (#68865) to apply the fix. Should be merged soon-ish.

**Comment by janusw** [comment] 2021-01-12 13:06
> Hey Janus - I manually installed tcl-tk 8.6.10 version, and edited gitk binary file to use the older version. Below is the steps I took.
> 
>     1. brew tap bronzeiii/tcl-tk https://github.com/bronzeiii/tcl-tk   (bronzeiii/tcl-tk is my personal github repo)
> 
>     2. brew extract --version 8.6.10 tcl-tk bronzeiii/tcl-tk
> 
>     3. brew install tcl-tk@8.6.10

Thanks for the explanation, @bronzeiii! I have already figured out that part by myself, but I did not mess with the gitk binary yet.

It looks like we have a patch with the upstream fix already (thanks @carlocab), so I guess I'll just wait for that to be merged.

**Closed** 2021-01-12 14:02 UTC

**Comment by janusw** [comment] 2021-01-12 14:23
Just pulled the update and can confirm that it works like a charm. Thanks for the quick fix!

**Comment by bronzeiii** [comment] 2021-01-12 14:29
i just pulled the update as well, but continue to have the same problem.. Can someone please assist this case?

```
wish quit unexpectedly

➜ gitk
objc[99911]: autorelease pool page 0x7fcd53185000 corrupted
  magic     0x00000000 0x00000000 0x00000000 0x00000000
  should be 0xa1a1a1a1 0x4f545541 0x454c4552 0x21455341
  pthread   0x1126e4dc0
  should be 0x1126e4dc0

zsh: abort      gitk
```

**Comment by gromgit** [comment] 2021-01-12 15:00
@bronzeiii What's the output of:
```
brew reinstall tcl-tk
brew info tcl-tk
brew test -v tcl-tk
```
?

**Comment by bronzeiii** [comment] 2021-01-12 15:03
@gromgit - the problem is resolved after i deleted the gitk config file in my home dir.. not sure why though..maybe related to the layout??

**Comment by gromgit** [comment] 2021-01-12 15:34
I don't use gitk, so I really couldn't say, but as long as it works now, :+1:

**Comment by sylr** [comment] 2021-01-24 15:32
I had to remove `./.config/git/gitk` and `<gitdir>/.git/gitk.cache` to resolve this.

**Comment by aleksandrs-ledovskis** [comment] 2021-01-25 14:00
`set geometry(state) zoomed` in `gitk` config was manually bisected as culprit. Set to `set geometry(state) normal` to solve crash

**Comment by sebastienbarre** [comment] 2021-01-26 05:01
Thanks, this has been killing me all day since I accidentally upgraded Homebrew. 
For those of you landing here, what @sylr meant with `./.config/git/gitk` was actually `~/.config/git/gitk` :)
Removing that file did it for me, removing `<gitdir>/.git/gitk.cache` didn't, but you mileage may vary.

Thanks all.
