### ISSUE TITLE
LBDB does not install the abook module (m_abook)

### ISSUE THREAD

**Issue by djwf** [Homebrew/homebrew-core#775] opened 2016-05-02 13:19 UTC
When installing lbdb using `brew install lbdb` the file `/usr/local/Cellar/lbdb/0.41/libexec/m_abook` is not installed.  To check to see if it's a brew problem or an original source problem I downloaded the source tarball for lbdb 0.41, tried `./configure --prefix=/Users/dave/lbdb && make install`, and the abook module does install.

My solution (so far) is to change the formula to allow `configure` to use the `--with-abook` option, thus ensuring the module is installed.

However, before putting up a pull request I figured I'd see if anyone else is having the problem.  I've tried searching on a number of terms, but haven't found anyone else reporting this problem.

**Comment by ilovezfs** [comment] 2016-05-02 15:50
If you think it should be in the bottles,
```
depends_on "abook" => :recommended
```
otherwise
```
depends_on "abook" => :optional
```

No need to manually change the configure options.

**Comment by djwf** [comment] 2016-05-02 17:56
Sorry: I should have been more specific.  My current solution is to apply the attached patch.

[lbdb.txt](https://github.com/Homebrew/homebrew-core/files/245625/lbdb.txt)

The weirdness is that the current tarball does provide this module when I configure/make *without* requiring the `--with-abook` option, but something in the homebrew configure/make process is preventing the `m_abook` module from being made/installed.

**Comment by ilovezfs** [comment] 2016-05-02 22:37
@djwf no need to be any more specific than you were the first time. Before responding above, I both reproduced the behavior you described, and verified that the `depends_on` statements alone were sufficient to resolve it without further intervention in configure. All behavior described is normal, though it may be somewhat surprising if you haven't dealt with Homebrew's `superenv` before.

The reason you do *not* need to intervene with the configure is that `superenv` changes the environment to expose the dependency if and only if you declare it. When it's undeclared, even if the dependency is installed, it will be hidden from view during formula installation, and configure won't see it there.

**Comment by mikemcquaid** [comment] 2016-05-03 13:59
@djwf Your patch looks good. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by djwf** [comment] 2016-05-03 17:43
@ilovezfs thanks for the clarification

@mikemcquaid I'll put that in tonight

**Comment by ilovezfs** [comment] 2016-05-04 07:49
Closing in favor of #826

**Closed by ilovezfs** 2016-05-04 07:49 UTC
Labels: question
