### ISSUE TITLE
OpenSSL@1.1 repeatedly tries to upgrade, even though nothing has changed

### ISSUE THREAD

**Issue by alex** [Homebrew/homebrew-core#5126] opened 2016-09-22 20:42 UTC
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

No matter how many times I run `brew upgrade`, it tries to upgrade `openssl@1.1`:

```
~ $ brew upgrade
==> Upgrading 1 outdated package, with result:
openssl@1.1 1.1.0a
==> Upgrading openssl@1.1
==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.0a.sierra.bottle.tar.gz
Already downloaded: /Users/alex_gaynor/Library/Caches/Homebrew/openssl@1.1-1.1.0a.sierra.bottle.tar.gz
==> Pouring openssl@1.1-1.1.0a.sierra.bottle.tar.gz
==> Using the sandbox
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl@1.1/lib
    CPPFLAGS: -I/usr/local/opt/openssl@1.1/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.0a: 6,222 files, 15.3M
~ $ brew upgrade
==> Upgrading 1 outdated package, with result:
openssl@1.1 1.1.0a
==> Upgrading openssl@1.1
==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.0a.sierra.bottle.tar.gz
Already downloaded: /Users/alex_gaynor/Library/Caches/Homebrew/openssl@1.1-1.1.0a.sierra.bottle.tar.gz
==> Pouring openssl@1.1-1.1.0a.sierra.bottle.tar.gz
==> Using the sandbox
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl@1.1/lib
    CPPFLAGS: -I/usr/local/opt/openssl@1.1/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.0a: 6,222 files, 15.3M
~ $ brew upgrade
==> Upgrading 1 outdated package, with result:
openssl@1.1 1.1.0a
==> Upgrading openssl@1.1
==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.0a.sierra.bottle.tar.gz
Already downloaded: /Users/alex_gaynor/Library/Caches/Homebrew/openssl@1.1-1.1.0a.sierra.bottle.tar.gz
==> Pouring openssl@1.1-1.1.0a.sierra.bottle.tar.gz
==> Using the sandbox
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl@1.1/lib
    CPPFLAGS: -I/usr/local/opt/openssl@1.1/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.0a: 6,222 files, 15.3M
~ $
```

**Comment by DomT4** [comment] 2016-09-22 21:16
Oh, I can reproduce this one. What on earth.

**Comment by DomT4** [comment] 2016-09-22 21:37
Looks suspiciously like it doesn't record the `version_scheme` in the formula's `Tab` for the `@`-style formulae, which would cause a situation exactly like this one. Looking into it.

**Comment by DomT4** [comment] 2016-09-22 22:18
This broke on https://github.com/Homebrew/brew/commit/41e25209f7486676f633ae05d7fc61e05af07b90, apparently. At least it's a new issue & not something we introduced with `@` formula from the start, that's some small mercy.

**Comment by DomT4** [comment] 2016-09-23 02:49
This seems to be a bottle problem, perhaps, somehow. If I remove my preexisting `openssl@1.1` installation and then do `brew install openssl@1.1 -s` I can no longer reproduce the problem. It's only there if you pour the bottle.

**Comment by ilovezfs** [comment] 2016-09-23 06:41
@alex please try again now.

**Comment by Lukasa** [comment] 2016-09-23 07:13
@ilovezfs I just did a `brew update`, and I can continue to reproduce this bug.

**Comment by ilovezfs** [comment] 2016-09-23 09:47
@Lukasa did you first do an explicit `brew uninstall`?

**Comment by Lukasa** [comment] 2016-09-23 09:51
@ilovezfs Yup. Here's my most recent shell log where I did it again:

```
cory@heimdall:urllib3/ % brew uninstall openssl@1.1
Uninstalling /usr/local/Cellar/openssl@1.1/1.1.0a... (6,222 files, 15.3M)
openssl@1.1 1.1.0 is still installed.
Remove all versions with `brew uninstall --force openssl@1.1`.
cory@heimdall:urllib3/ % brew uninstall openssl@1.1
Uninstalling /usr/local/Cellar/openssl@1.1/1.1.0... (6,216 files, 15.3M)
cory@heimdall:urllib3/ % brew update
brew install openssl@1.1Updated 1 tap (caskroom/cask).
No changes to formulae.
cory@heimdall:urllib3/ % brew install openssl@1.1
==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.0a.sierra.b
Already downloaded: /Users/cory/Library/Caches/Homebrew/openssl@1.1-1.1.0a.sierra.bottle.tar.gz
==> Pouring openssl@1.1-1.1.0a.sierra.bottle.tar.gz
==> Using the sandbox
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl@1.1/lib
    CPPFLAGS: -I/usr/local/opt/openssl@1.1/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.0a: 6,222 files, 15.3M
cory@heimdall:urllib3/ % brew outdated
openssl@1.1 (1.1.0a) < 1.1.0a
```

Note that OpenSSL is still listed as outdated, and I can `brew upgrade openssl@1.1` without limitation.

**Comment by ilovezfs** [comment] 2016-09-23 10:30
sorry, missed that you were on 1.1. regular had same issue. let's rebuild these too ...

**Comment by DomT4** [comment] 2016-09-23 11:51
It seems to explicitly require a from-source build locally where `openssl@1.1` isn't already installed to get rid of the erroneous version_scheme is 0 & 1 at the same time issue. Not sure quite what that's about yet.

**Comment by DomT4** [comment] 2016-09-23 12:07
@alex @Lukasa Can someone confirm my local steps work?
```bash
brew rm openssl@1.1 && brew install openssl@1.1 -s
```
And then check `brew outdated` doesn't complain about `openssl@1.1` any more?

**Comment by Lukasa** [comment] 2016-09-23 12:17
Yup, that works on my machine.

**Comment by DomT4** [comment] 2016-09-23 12:20
Cool. We think we've managed to narrow this down to human error in fresh bottles not being pulled after the `version_scheme` was bumped yesterday, which would cause this. So much for the 4 hours I spent poking around Homebrew's core code last night trying to find a breakage point 😆.

Should be fixed from bottle once https://github.com/Homebrew/homebrew-core/pull/5149 is merged (with bottles this time 🙈).

**Comment by Lukasa** [comment] 2016-09-23 12:21
Heh, whoops!

**Comment by zmwangx** [comment] 2016-09-23 12:46
Affected users: come at me 😓

**Comment by DomT4** [comment] 2016-09-23 13:43
We've had maintainers break the entirety of Homebrew for thousands & thousands of users... You're practically a saint @zmwangx 😉. Better human error than some fundamental flaw in Homebrew's code.

**Comment by zmwangx** [comment] 2016-09-23 13:43
> You're practically a saint

Pretty sure I'm not 😉

**Comment by ilovezfs** [comment] 2016-09-23 13:44
Well technically don't saints have to no longer have a pulse?

**Comment by ilovezfs** [comment] 2016-09-23 15:43
Should now be fixed. https://github.com/Homebrew/homebrew-core/pull/5149

**Closed by ilovezfs** 2016-09-23 15:43 UTC
Labels: bug
