### ISSUE TITLE
Cannot install postgresql on fresh Ubuntu build for Windows (WSL2)

### ISSUE THREAD

**Issue by mike-usa** [Homebrew/homebrew-core#80543] opened 2021-07-04 05:43 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

$ brew config

```
HOMEBREW_VERSION: 3.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09f7bc27a99469cf947431df4754737dfbadb31d
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 4ccfbea4752d145c46c2bab305f5468ac36f3e0a
Core tap last commit: 8 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit zen
Clang: N/A
Git: 2.32.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 4.19.128-microsoft-standard x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: 5.5.0_7
xorg: N/A
```

$ brew doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  guile@2
  isl@0.18
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

```
brew install postgresql
```

### What happened (include all command output)?

```
Already downloaded: /home/meatloaf/.cache/Homebrew/downloads/c40797c508fca7740033177f2cf44d3cc5a87ee7ec649662ae2080046f648742--postgresql-13.3.tar.bz2
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/postgresql/13.3 --datadir=/home/linuxbrew/.linuxbrew/share/postgresql --libdir=/home/linuxbrew/.linuxbrew/lib --includedir=/home/linuxbrew/.linuxbrew/include --sysconfdir
Last 15 lines from /home/meatloaf/.cache/Homebrew/Logs/postgresql/01.configure:
checking for library containing gss_init_sec_context... -lgssapi_krb5
checking for CRYPTO_new_ex_data in -lcrypto... yes
checking for SSL_new in -lssl... yes
checking for X509_get_signature_nid... yes
checking for OPENSSL_init_ssl... yes
checking for BIO_get_data... yes
checking for BIO_meth_new... yes
checking for ASN1_STRING_get0_data... yes
checking for CRYPTO_lock... no
checking for pam_start in -lpam... yes
checking for xmlSaveToBuffer in -lxml2... yes
checking for xsltCleanupGlobals in -lxslt... yes
checking for ldap_bind in -lldap... yes
checking for ldap_simple_bind in -lldap_r... no
configure: error: library 'ldap_r' is required for LDAP

READ THIS: https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

I expected it to install postgres, but it seems to be hanging on LDAP.  I am not sure where to modify the configuration in order to disable it.  Likewise, this is Ubuntu for Windows (WSL).  If there's a way to enable LDAP, that might also be preferred, but postgresql is not installing either way.  I'm not unsure if this is a linuxbrew-specific issue or an issue with the postgres formula.  I haven't been able to locate much information either way, but please advise if this is better suited elsewhere.

### Other Info

**(No options listed)**
```
$ brew options postgresql
# (returns nothing)
```

**(Can't pass command line options)**
```
$ brew install postgresql --no-ldap
Usage: brew install [options] formula|cask [...]

Install a formula or cask. Additional options specific to a formula may be
appended to the command.

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will then be run for
the installed formulae or, every 30 days, for all formulae.

  -d, --debug                      If brewing fails, open an interactive
...
```

### Step-by-step reproduction instructions (by running `brew` commands)

With a clean install of Ubuntu20 on Windows, run `brew install postgresql`

**Comment by carlocab** [comment] 2021-07-04 05:46
CC @iMichka

**Comment by mike-usa** [comment] 2021-07-04 06:14
I believe I was able to edit and install with the following process:

1. Edit the formula:
    ```
    brew edit postgresql
    ```
1. Change the args line `--with-ldap` to `--without-ldap`
1. Install again (ensure make is installed; `brew install make`)
    ```
    brew install postgresql
    ```

Note: I would still like to know how I can install the ldap_r, if possible.

**Comment by cho-m** [comment] 2021-07-04 10:03
It may be that `postgresql` doesn't support `openldap 2.5.x`.
OpenLDAP 2.5 merged `libldap_r` and `libldap` libraries.

Most Linux distros are still on `openldap 2.4.x`, which may be due to compatibility 
https://repology.org/project/openldap/badges

**Comment by mike-usa** [comment] 2021-07-04 17:02
> It may be that `postgresql` doesn't support building with `openldap 2.5.x`.
> OpenLDAP 2.5 merged `libldap_r` and `libldap` libraries.
> 
> Most Linux distros are still on `openldap 2.4.x`, which may be due to compatibility
> https://repology.org/project/openldap/badges

Thank you for your reply, @cho-m.  It seems (to me) an odd thing to lack support given the maturity of these libraries.  

Worth mentioning, this is a fairly fresh/vanilla install of Ubuntu20 as WSL2 on Win10.  I don't believe I've configured an LDAP server at all and imagine I would need to in order to establish a Certificate Authority unless Windows/WSL/Ubuntu does any of that out of the box.  

- Does Windows/WSL/Ubuntu configure LDAP OTB?
- Would PostgreSQL be able to compile with LDAP despite lack of LDAP configuration or would it know to skip over? 
- What's the best way to check any of this?

LDAP might be overkill as an individual user/developer on a test box, but it might be something to consider configuring to have something that more closely resembles a production system and perhaps containerize for future machine instances.

**Comment by cho-m** [comment] 2021-07-04 19:14
> Thank you for your reply, @cho-m. It seems (to me) an odd thing to lack support given the maturity of these libraries.

Homebrew usually tracks the latest stable version for formulae, which is OpenLDAP 2.5. Older versions are added if they are useful and meet the requirements (https://docs.brew.sh/Versions#acceptable-versioned-formulae)

In this case, it may be necessary to add an `openldap@2.4` formula if it impacts the build for existing `postgresql` formulae (still supported versions: `9.6`, `10`, `11`, `12`, and `13`). 

@iMichka may know if any issues were seen from OpenLDAP update over in the linuxbrew repo.

On macOS Big Sur, the `uses_from_macos "openldap"` is OpenLDAP 2.4 and has `libldap` & `libldap_r`.

---

> * Does Windows/WSL/Ubuntu configure LDAP OTB?

I don't think any come with an LDAP server.
LDAP would also require some deployment-specific configs.

> * Would PostgreSQL be able to compile with LDAP despite lack of LDAP configuration or would it know to skip over?

PostgreSQL compilation just requires the `openldap` libraries to make the feature available. This is tied to the `--with-ldap` and `--without-ldap` flags.

A running/reachable LDAP server (with valid LDAP configuration) would only be needed when trying to configure the client authentication for starting up a PostgreSQL database.

**Comment by iMichka** [comment] 2021-07-05 09:16
`openldap` was updated to 2.5 in homebrew-core. There was no Linux CI there (it is being implemented now), and so the MacOS maintainers did not notice that `postgresql` was broken on Linux.

I confirm that the issue is due to the fact that `libldap_r` got removed from `openladp` and only `libldap` exists now.

The correct fix is to write a patch for `postgresql` that makes it compatible with `openladp` 2.5 and 2.4.

The quick and dirty hack would be to introduced a `openladp@2.4` formula.

Whatever way is chosen, I don't have time to work on this, so anyone can pick this task up and try to fix it given the above.

**Closed** 2021-07-07 23:16 UTC
Labels: bug
