### ISSUE TITLE
Bugs after upgrade to MacOSX11.1 `warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk'`

### ISSUE THREAD

**Issue by cxwx** [Homebrew/homebrew-core#67358] opened 2020-12-21 08:48 UTC
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  - https://gist.github.com/cxwx/82341bb9e9790735ad0d8b56ef3a9553
- [] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

using root which install by homebrew

## What happened (include command output)

bug with `no SDK 11.0` after upgrade to MacOS X 11.1

<details>
  <summary>Command output</summary>
  <pre>

  warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk'

 *** Break *** segmentation violation
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCore.so] TUnixSystem::DispatchSignals(ESignals) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCore.so] SigHandler(ESignals) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCore.so] sighandler(int) (no debug info)
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] (anonymous namespace)::RedirectingDirectoryEntry::classof((anonymous namespace)::Entry const*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] llvm::isa_impl<(anonymous namespace)::RedirectingDirectoryEntry, (anonymous namespace)::Entry, void>::doit((anonymous namespace)::Entry const&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] llvm::isa_impl_cl<(anonymous namespace)::RedirectingDirectoryEntry, (anonymous namespace)::Entry const*>::doit((anonymous namespace)::Entry const*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] llvm::isa_impl_wrap<(anonymous namespace)::RedirectingDirectoryEntry, (anonymous namespace)::Entry const*, (anonymous namespace)::Entry const*>::doit((anonymous namespace)::Entry const* const&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] llvm::isa_impl_wrap<(anonymous namespace)::RedirectingDirectoryEntry, (anonymous namespace)::Entry* const, (anonymous namespace)::Entry const*>::doit((anonymous namespace)::Entry* const&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] bool llvm::isa<(anonymous namespace)::RedirectingDirectoryEntry, (anonymous namespace)::Entry*>((anonymous namespace)::Entry* const&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] llvm::cast_retty<(anonymous namespace)::RedirectingDirectoryEntry, (anonymous namespace)::Entry*>::ret_type llvm::dyn_cast<(anonymous namespace)::RedirectingDirectoryEntry, (anonymous namespace)::Entry>((anonymous namespace)::Entry*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] (anonymous namespace)::RedirectingFileSystemParser::uniqueOverlayTree((anonymous namespace)::RedirectingFileSystem*, (anonymous namespace)::Entry*, (anonymous namespace)::Entry*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] (anonymous namespace)::RedirectingFileSystemParser::uniqueOverlayTree((anonymous namespace)::RedirectingFileSystem*, (anonymous namespace)::Entry*, (anonymous namespace)::Entry*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] (anonymous namespace)::RedirectingFileSystemParser::parse(llvm::yaml::Node*, (anonymous namespace)::RedirectingFileSystem*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] (anonymous namespace)::RedirectingFileSystem::create(std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >, void (*)(llvm::SMDiagnostic const&, void*), llvm::StringRef, void*, llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] clang::vfs::getVFSFromYAML(std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >, void (*)(llvm::SMDiagnostic const&, void*), llvm::StringRef, void*, llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] (anonymous namespace)::collectModuleMaps(clang::CompilerInstance&, llvm::SmallVectorImpl<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] (anonymous namespace)::setupCxxModules(clang::CompilerInstance&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] (anonymous namespace)::createCIImpl(std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >, cling::CompilerOptions const&, char const*, std::__1::unique_ptr<clang::ASTConsumer, std::__1::default_delete<clang::ASTConsumer> >, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > > const&, bool, bool) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] cling::CIFactory::createCI(llvm::StringRef, cling::InvocationOptions const&, char const*, std::__1::unique_ptr<clang::ASTConsumer, std::__1::default_delete<clang::ASTConsumer> >, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > > const&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] cling::IncrementalParser::IncrementalParser(cling::Interpreter*, char const*, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > > const&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] cling::IncrementalParser::IncrementalParser(cling::Interpreter*, char const*, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > > const&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] cling::Interpreter::Interpreter(int, char const* const*, char const*, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > > const&, bool, cling::Interpreter const*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] cling::Interpreter::Interpreter(int, char const* const*, char const*, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > > const&, bool, cling::Interpreter const*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] cling::Interpreter::Interpreter(int, char const* const*, char const*, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > > const&, bool) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] std::__1::enable_if<!(std::is_array<cling::Interpreter>::value), std::__1::unique_ptr<cling::Interpreter, std::__1::default_delete<cling::Interpreter> > >::type llvm::make_unique<cling::Interpreter, unsigned long, char const**, TString&, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > >&>(unsigned long&&, char const**&&, TString&, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > >&) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] TCling::TCling(char const*, char const*, char const* const*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] TCling::TCling(char const*, char const*, char const* const*) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCling.so] CreateInterpreter (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCore.so] TROOT::InitInterpreter() (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCore.so] ROOT::Internal::GetROOT2() (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCore.so] ROOT::GetROOT() (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libCore.so] TApplication::TApplication(char const*, int*, char**, void*, int) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libRint.so] TRint::TRint(char const*, int*, char**, void*, int, bool) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/lib/root/libRint.so] TRint::TRint(char const*, int*, char**, void*, int, bool) (no debug info)
[/usr/local/Cellar/root/6.22.06_1/bin/root.exe] main (no debug info)
[/usr/lib/system/libdyld.dylib] start (no debug info)

  </pre>
</details>

## What you expected to happen

How could I use /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk not MacOSX11.1.sdk nor MacOSX11.0.sdk when install this formula or others

**Comment by carlocab** [comment] 2020-12-21 09:21
This might be a duplicate of https://github.com/Homebrew/homebrew-core/issues/67075.

>How could I use /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk not MacOSX11.1.sdk nor MacOSX11.0.sdk

That's currently in progress at this PR: https://github.com/Homebrew/brew/pull/10072

Right now you could try creating a symlink `/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk` to `MacOSX11.1.sdk`. Caveat: this may not work as expected; I'm not certain.

I think the safest alternative is to rebuild `root` using `brew reinstall --build-from-source root`. Rebuilding from source might take a while.

You can also try another workaround I suggest in the issue linked above.

**Comment by fxcoudert** [comment] 2020-12-21 10:41
Yes, this is a duplicate. Thanks @cxwx for the report, we are working on fixing this.

**Closed by fxcoudert** 2020-12-21 10:41 UTC

**Comment by carlocab** [comment] 2020-12-24 08:50
@cxwx, the fix should be merged shortly: https://github.com/Homebrew/homebrew-core/pull/67411

Once that happens, could you please test `root` and let me know if it works for you? Thank you.

**Comment by cxwx** [comment] 2020-12-24 12:34
It works thanks @carlocab

**Comment by carlocab** [comment] 2020-12-24 15:35
Thanks. Please do let me know as soon as possible if you experience any problems related to this.
