### ISSUE TITLE
Gv

### ISSUE THREAD

**Issue by yannis1962** [Homebrew/homebrew-core#17094] opened 2017-08-22 09:54 UTC
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new

YES 

- [x] Ran `brew update` and retried your prior step?

**YES** 

- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

**YES**

- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

**phoebe:~ yannis$ brew gist-logs gv
Error: No logs.**

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**phoebe:~ yannis$ brew config
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 01b40c6161d835b1610d4324650e7d773cef8fab
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_51, 1.7.0_45, 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: N/A
X11: 2.7.112 => /opt/X11
phoebe:~ yannis$ brew doctor
Your system is ready to brew.**

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

Suddenly gv doesn't work anymore. I tried with Xquartz 2.7.2, 2.7.8 and with the latest 2.7.11, nothing works. Here is the error I get when running gv:

- What happened (include command output)

**phoebe:~ yannis$ gv &
[1] 60979
phoebe:~ yannis$ dyld: Library not loaded: /opt/X11/lib/libXinerama.1.dylib
  Referenced from: /usr/local/bin/gv
  Reason: no suitable image found.  Did find:
	/opt/X11/lib/libXinerama.1.dylib: code signature invalid for '/opt/X11/lib/libXinerama.1.dylib'

	/opt/X11/lib/libXinerama.1.dylib: code signature invalid for '/opt/X11/lib/libXinerama.1.dylib'

[1]+  Abort trap: 6           gv**

- What you expected to happen

I expected it to open a gv window as usual.

- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by fxcoudert** [comment] 2017-08-22 11:41
I cannot reproduce that on my macOS 10.12 with Xquartz 2.7.11 (latest).

One thing is that your config says `X11: 2.7.112` which I don't think is a valid version number. Can you clarify that?

**Comment by ilovezfs** [comment] 2017-08-22 11:57
Please try
```
brew cask zap xquartz
brew cask install xquartz
```

**Comment by fxcoudert** [comment] 2017-09-03 19:38
Closing this as a local configuration issue, having had no feedback on the issue.

**Closed by fxcoudert** 2017-09-03 19:38 UTC
Labels: user configuration
