### ISSUE TITLE
fontforge python module not properly installed with `fontforge` package

### ISSUE THREAD

**Issue by bendavis78** [Homebrew/homebrew-core#122471] opened 2023-02-06 21:00 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

Brew config and brew doctor output: https://gist.github.com/bendavis78/ad66fcde1884c621f59f353912f22523

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

> Note that I ignored brew doctor warnings that had to do with postgres/black/kubectl as I don't want it to break my current setup. They should not be affecting the current issue.

### What were you trying to do (and why)?

Trying to do:
```
$ python3
>>> import fontforge
```

### What happened (include all command output)?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fontforge'
```

### What did you expect to happen?

Successful import of fontforge python module

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install fontforge
$ python3
>>> import fontforge
```
```

**Comment by SMillerDev** [comment] 2023-02-06 21:05
What does `which python3` say? Because fontforge installs for python 3.11

**Comment by anajuliabit** [comment] 2023-02-12 23:22
Same issue here. Any updates? @bendavis78

**Comment by cho-m** [comment] 2023-02-13 01:10
Based on local test, this looks like a user config/usage issue, so closing.

Can't reproduce when using the Python that formula expects:
```console
$ python3.11 -c 'import fontforge; print(fontforge.version())'
20230101
```

As already mentioned, we build bindings for Python 3.11.

It is expected that bindings won't be available for any other Python. If you are using default `python3` from Homebrew (i.e. right now `python@3.10`), then it won't work.

The default `python3` won't change until #114154. And once it changes, any formulae that only builds bindings for `python@3.10` will then need to use `python3.10`.

Users need to check what version of Python a formula supports, e.g. `brew info fontforge`. There is no guarantee on what version of Python Homebrew's `python3` symlink is set to nor any guarantee that the version of Python used for a formula will remain. These are updated asynchronously as it is not possible to update all Python dependents in Homebrew at same time.

**Closed by cho-m** 2023-02-13 01:10 UTC
Labels: user configuration
