### ISSUE TITLE
error upgrade php@7.4

### ISSUE THREAD

**Issue by brianbrownton** [Homebrew/homebrew-core#75953] opened 2021-04-26 17:18 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
[~]$ brew gist-logs php@7.4
Error: No logs.
[~]$ brew gist-logs icu4c
Error: No logs.
```

```
==> Installing php@7.4 dependency: icu4c
Error: undefined method `bottle_tag?' for false:FalseClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `bottle_tag?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:136:in `pour_bottle?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:339:in `install'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:741:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:389:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:137:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:47:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:178:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

```
[~]$ brew config
HOMEBREW_VERSION: 3.1.3-105-gc5bcfe8
ORIGIN: https://github.com/Homebrew/brew
HEAD: c5bcfe8fac3321c6333e7248dc14e8314e8c5da1
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f1742bccb0b0d8e8e98dfcbc936c6d815d204963
Core tap last commit: 65 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

```
[~]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  qt
  kubernetes-cli
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew upgrade php@7.4`

why: it was outdated and needed upgrading...

### What happened (include all command output)?

```
[~]$ brew upgrade php@7.4 node@12
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 35942830f to c5bcfe8fa.
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/bundle).
==> Updated Formulae
Updated 22 formulae.
==> New Casks
fpc-laz                                              fpc-src-laz
==> Updated Casks
Updated 9 casks.
==> Deleted Casks
fpcsrc

==> Upgrading 2 outdated packages:
php@7.4 7.4.16 -> 7.4.16_1
node@12 12.22.1 -> 12.22.1_1
==> Upgrading php@7.4 7.4.16 -> 7.4.16_1
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/manifests/2.71
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:0aa64f171bac19ce6ac0c0ca697f30658d
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:0aa64f171bac19ce6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/manifests/1.4.9_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/blobs/sha256:eeb8825bb703294879b70a5018efecb08a4286
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:eeb8825bb70329487
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/unixodbc/manifests/2.3.9_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/unixodbc/blobs/sha256:7e85c6cae69a18bc572ac63a624d44f5e1
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:7e85c6cae69a18bc5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/freetds/manifests/1.2.21
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/freetds/blobs/sha256:5c9dfc5df86bae027e729b766b3454cf493
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:5c9dfc5df86bae027
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/manifests/4.3.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/blobs/sha256:09f08e1168780c12c8f1526038eb4f46926
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:09f08e1168780c12c
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.35.4
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:861dc044ea531c39a2105010107feb95cf10
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:861dc044ea531c39a
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/glib/manifests/2.68.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/glib/blobs/sha256:244628aa2804cc51993188636086a93d9f3557
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:244628aa2804cc519
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/manifests/69.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/blobs/sha256:d46b8ec5c3db629e7848e9fd31e5ec99ed952
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:d46b8ec5c3db629e7
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/oniguruma/manifests/6.9.7.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/oniguruma/blobs/sha256:8154799c44b09d3283fab1d9e5c2a59c8
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:8154799c44b09d328
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/php/7.4/manifests/7.4.16_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/php/7.4/blobs/sha256:825b512bf8880f9d3e667df30a66a49447b
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:825b512bf8880f9d3
######################################################################## 100.0%
==> Installing dependencies for php@7.4: autoconf, zstd, unixodbc, freetds, libtiff, sqlite, glib, icu4c and oniguruma
==> Installing php@7.4 dependency: autoconf
==> Pouring autoconf--2.71.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/autoconf/2.71: 71 files, 3.2MB
==> Installing php@7.4 dependency: zstd
==> Pouring zstd--1.4.9_1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/zstd/1.4.9_1: 31 files, 2.6MB
==> Installing php@7.4 dependency: unixodbc
==> Pouring unixodbc--2.3.9_1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/unixodbc/2.3.9_1: 46 files, 2.2MB
==> Installing php@7.4 dependency: freetds
==> Pouring freetds--1.2.21.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/freetds/1.2.21: 1,259 files, 13.8MB
==> Installing php@7.4 dependency: libtiff
==> Pouring libtiff--4.3.0.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.3.0: 249 files, 4.4MB
==> Installing php@7.4 dependency: sqlite
==> Pouring sqlite--3.35.4.big_sur.bottle.tar.gz
==> Caveats
sqlite is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have sqlite first in your PATH, run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.zshrc

For compilers to find sqlite you may need to set:
  export LDFLAGS="-L/usr/local/opt/sqlite/lib"
  export CPPFLAGS="-I/usr/local/opt/sqlite/include"

For pkg-config to find sqlite you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/sqlite/3.35.4: 11 files, 4.2MB
==> Installing php@7.4 dependency: glib
==> Pouring glib--2.68.1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.68.1: 442 files, 21MB
==> Installing php@7.4 dependency: icu4c
Error: undefined method `bottle_tag?' for false:FalseClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `bottle_tag?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:136:in `pour_bottle?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:339:in `install'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:741:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:389:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:137:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:47:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:178:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### What did you expect to happen?

It upgrades the formula w/o errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
see above
```

**Comment by MikeMcQuaid** [comment] 2021-04-26 18:21
@bo98 looks bottle tag related?

**Comment by Bo98** [comment] 2021-04-26 19:15
This doesn't make sense. `formula` appears to be a boolean for whatever reason? Despite being accessed one step prior in the backtrace?

**Comment by brianbrownton** [comment] 2021-04-27 15:18
FWIW I tried the upgrade again and it went through w/o issue, so if nobody else is having problems maybe it was just a transient issue?

**Comment by carlocab** [comment] 2021-04-27 15:19
Since the issue is gone, we can close this for now. It can be reopened if it happens again or someone else reproduces it.

**Closed by carlocab** 2021-04-27 15:19 UTC
Labels: bug
