### ISSUE TITLE
Unable to install apache-spark v2.0.2

### ISSUE THREAD

**Issue by aleksey-suprun** [Homebrew/homebrew-core#6970] opened 2016-11-16 10:14 UTC
When I try to install `apache-spark` formula, I get following error:
```bash
$ brew install apache-spark
==> Using the sandbox
==> Downloading https://www.apache.org/dyn/closer.lua?path=spark/spark-2.0.2/spark-2.0.2-bin-hadoop2.7.tgz
Already downloaded: /Users/asuprun/Library/Caches/Homebrew/apache-spark-2.0.2.tgz
Error: Interrupted system call - /Library/Ruby/Gems/2.0.0/specifications/default/bigdecimal-1.2.0.gemspec
```

**Comment by ilovezfs** [comment] 2016-11-16 10:18
This is likely a problem with your brew ruby installation but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

**Comment by aleksey-suprun** [comment] 2016-11-16 13:25
Thank you, @ilovezfs for your response. Actually I tried all things mentioned in that guide. I've even totally reinstalled my Homebrew. Moreover, other formulas forks fine. I really doubt that this issue related to my brew installation.

Please see output of `brew config` and `brew doctor` using following link: https://gist.github.com/aleksey-suprun/90135328ab294a3ca1511b9cb08d5cb2

**Comment by aleksey-suprun** [comment] 2016-11-16 13:49
I've also faced with issue when I tried to use cask after reinstallation:
```shell
$ brew cask list
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3530, done.
remote: Compressing objects: 100% (3515/3515), done.
remote: Total 3530 (delta 31), reused 166 (delta 11), pack-reused 0
Receiving objects: 100% (3530/3530), 1.14 MiB | 476.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/metagrowler.rb
undefined method `cask' for Formulary::FormulaNamespace0a3fc67eb7f20792f6a4ee633903a783:Module
Error: Cannot tap caskroom/cask: invalid syntax in tap!
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:226:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
I've also tried to troubleshoot this issue using link from logs, but it did not help me.

**Comment by MikeMcQuaid** [comment] 2016-11-16 14:20
@aleksey-suprun The cask issue is a duplicate of https://github.com/caskroom/homebrew-cask/issues/26815.

**Comment by aleksey-suprun** [comment] 2016-11-16 21:03
@MikeMcQuaid Thanks! But the original issue with Spark unfortunately is still actual.

**Comment by MikeMcQuaid** [comment] 2016-11-17 16:23
What does `/usr/bin/gem list` output?

**Comment by aleksey-suprun** [comment] 2016-11-18 13:13
```bash
$ /usr/bin/gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
CFPropertyList (2.2.8)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
minitest (4.3.2)
nokogiri (1.5.6)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
```

**Comment by MikeMcQuaid** [comment] 2016-11-20 12:33
What about `ls /Library/Ruby/Gems/2.0.0`?

**Comment by MikeMcQuaid** [comment] 2016-11-20 12:33
Also, I'm afraid this is an issue specific to you and your machine and I'm not sure how much else we're going to be able to do to help.

**Comment by aleksey-suprun** [comment] 2016-11-20 16:05
```
$ ls /Library/Ruby/Gems/2.0.0
build_info	cache		doc		gems		specifications
```

**Comment by MikeMcQuaid** [comment] 2016-11-20 16:08
Sorry, `ls /Library/Ruby/Gems/2.0.0/gems`

**Comment by aleksey-suprun** [comment] 2016-11-21 09:02
```
$ ls /Library/Ruby/Gems/2.0.0/gems
rake-0.9.6		rdoc-4.0.0		test-unit-2.0.0.0
```

**Comment by MikeMcQuaid** [comment] 2016-11-21 09:04
That looks correct. I'm not sure what else to suggest except trying to reinstall Homebrew. Sorry!

**Closed by MikeMcQuaid** 2016-11-21 09:04 UTC
