### ISSUE TITLE
curl: (22) The requested URL returned error: 401

### ISSUE THREAD

**Issue by Luca00711** [Homebrew/homebrew-core#104190] opened 2022-06-22 12:15 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 3.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: fba051f98f609634ae4392d0053ddfc627f8cdb3
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d1945aece64d3c5bbf47d6251311ebfa79f77c04
Core tap last commit: 66 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1

brew doctor:
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to install some packages as usual.

It don't matter which package I try to install I get:

`curl: (22) The requested URL returned error: 401`

### What happened (include all command output)?

```
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/manifests/70.1
Already downloaded: /Users/luca-miguel/Library/Caches/Homebrew/downloads/5f7334647a065541c9a05c73955ee0b51d20e9a23ab759cbede21626dac99198--icu4c-70.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/blobs/sha256:321592eb1aebb7c6edc7a
curl: (22) The requested URL returned error: 401

Error: dotnet: Failed to download resource "icu4c"
Download failed: https://ghcr.io/v2/homebrew/core/icu4c/blobs/sha256:321592eb1aebb7c6edc7a5e91393598725ebcc63362f059072b993c27f3bf979
```

### What did you expect to happen?

That the package get installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install dotnet or a other packages
```

**Comment by Simbaclaws** [comment] 2022-06-22 12:16
I'm having the same issue with any package right now for upgrading. I'm thinking something might be wrong with ghcr.io

**Comment by akien-mga** [comment] 2022-06-22 12:18
Duplicate of #104189.

**Comment by Luca00711** [comment] 2022-06-22 12:18
Yea I saw already in another issue report

**Comment by WeiQingPackage** [comment] 2022-06-22 12:19
Yes, I'm having this problem now too

**Comment by jeniceek** [comment] 2022-06-22 12:27
Looks like problem with GitHub Container Registry, doesn't work from Docker too.

**Comment by MikeMcQuaid** [comment] 2022-06-22 12:33
Duplicate of https://github.com/Homebrew/brew/issues/13460

**Closed by MikeMcQuaid** 2022-06-22 12:34 UTC
Labels: bug
