### ISSUE TITLE
GCC fails to install

### ISSUE THREAD

**Issue by gnzlbg** [Homebrew/homebrew-core#17405] opened 2017-08-30 15:28 UTC
# Please always follow these steps:
- [x] I must run `brew install gcc --HEAD` to run into this problem.
    - Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? Yes, I must run `brew install gcc --HEAD` to run into this problem.
    - If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new: No, it is not a general `brew` problem, just a `brew install` one.
    -  If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. No, it is not a `brew cask` problem, but a `brew install` one.
    - If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap. No, it is not a tap problem, but a `brew install` one.
- [x] Ran `brew update` and retried your prior step? Yes, I ran `brew update` and retried, but the problem persists.
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? Yes, brew doctor does not show any issues (only a couple of harmless warnings). I still retried the previous step, the problem persists.
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? `brew gist-logs` worked just fine

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

# This is what happens when I run `brew install gcc --HEAD`:

```
brew install gcc --HEAD
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/science).
==> Updated Formulae
homebrew/science/prodigal                homebrew/science/sga

==> Cloning svn://gcc.gnu.org/svn/gcc/trunk
Updating /Users/gnzlbg/Library/Caches/Homebrew/gcc--svn-HEAD
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e9e0e
Already downloaded: /Users/gnzlbg/Library/Caches/Homebrew/gcc--patch-863957f90a934ee8f89707980473769cff47ca0663c3906992da6afb242fb220.patch
==> Patching
==> Applying 6.1.0-jit.patch
patching file gcc/jit/Make-lang.in
==> ../configure --build=x86_64-apple-darwin16.7.0 --prefix=/usr/local/Cellar/gc
==> make
Last 15 lines from /Users/gnzlbg/Library/Logs/Homebrew/gcc/02.make:
clang++ -std=gnu++98 -fno-PIE -c   -g  -DIN_GCC    -fno-strict-aliasing -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace -I/usr/local/opt/isl/include  -o builtins.o -MT builtins.o -MMD -MP -MF ./.deps/builtins.TPo ../../gcc/builtins.c
clang++ -std=gnu++98 -fno-PIE -c   -g  -DIN_GCC    -fno-strict-aliasing -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace -I/usr/local/opt/isl/include  -o caller-save.o -MT caller-save.o -MMD -MP -MF ./.deps/caller-save.TPo ../../gcc/caller-save.c
../../gcc/builtins.c:4913:6: error: cannot pass object of non-POD type 'scalar_int_mode' through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                                 ptr_mode, bot, ptr_mode);
                                 ^
../../gcc/builtins.c:4913:21: error: cannot pass object of non-POD type 'scalar_int_mode' through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                                 ptr_mode, bot, ptr_mode);
                                                ^
2 errors generated.
make[3]: *** [builtins.o] Error 1
make[3]: *** Waiting for unfinished jobs....
rm fsf-funding.pod gcov.pod cpp.pod gfdl.pod gpl.pod gcc.pod gcov-dump.pod gcov-tool.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
gcc: Hack version_suffix to fix --HEAD builds https://github.com/Homebrew/homebrew-core/pull/7642
```

# This is my `brew doctor` output:

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/gnzlbg/pool/toolchain/llvm/bin/llvm-config
  /usr/local/opt/pkg-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gcc
```

# This is my `brew gist-logs gcc` output:

https://gist.github.com/a0925af0820a20c00bd9d0ba8ea6b9b8

**Comment by fxcoudert** [comment] 2017-08-30 15:56
I'll look at it, but GCC head is known to be frequently broken. This looks like an upstream issue, not a Homebrew issue.

**Comment by fxcoudert** [comment] 2017-09-08 18:18
I cannot reproduce this, so it was probably fixed in GCC head in-between.

**Closed by fxcoudert** 2017-09-08 18:18 UTC
