### ISSUE TITLE
Sha mismatch for guile patch

### ISSUE THREAD

**Issue by thomaspinckney3** [Homebrew/homebrew-core#92086] opened 2021-12-27 22:34 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config

HOMEBREW_VERSION: 3.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96137bc19e68398ebbb7033379df288cd8b9a3f9
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 386dbd8bf930f169dd43bac7c7719659ee99026d
Core tap last commit: 26 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /Users/tp/homebrew
HOMEBREW_REPOSITORY: /Users/tp/homebrew
HOMEBREW_CELLAR: /Users/tp/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

run brew upgrade

### What happened (include all command output)?

There is a sha256 mismatch when downloading one the guile patches.

==> Downloading https://git.savannah.gnu.org/cgit/guile.git/patch/?id=1f100a4f20
##O#-#                                                                        
Error: SHA256 mismatch
Expected: a5adf2586b30381cf24524c7fc0364115f7cb1f568d2b69a9f3fb49ad8355b55
  Actual: a857c5fde2eb1c05379a97ba88047404da1c5b1da0291903f036d0a8745d85b5
    File: /Users/tp/Library/Caches/Homebrew/downloads/ed0ab6d9aa9892d417f166b6aca3db95c5c2eab4a4e3c6f5a74a585c956debf6--9a62f7cacaf730fca07f6cfd400a1893c2c2acb6..1f100a4f20c3a6e57922fb26fce212997e2a03cb.patch

### What did you expect to happen?

brew upgrade to successfully upgrade guile

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade
```

**Comment by Jasstkn** [comment] 2021-12-28 08:26
Looks like change here is required https://github.com/Homebrew/homebrew-core/blob/master/Formula/guile.rb#L45

**Comment by Jasstkn** [comment] 2021-12-28 14:11
```
curl https://git.savannah.gnu.org/cgit/guile.git/patch/\?id\=1f100a4f20c3a6e57922fb26fce212997e2a03cb | gsha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   956    0   956    0     0   1800      0 --:--:-- --:--:-- --:--:--  1817
a857c5fde2eb1c05379a97ba88047404da1c5b1da0291903f036d0a8745d85b5  -
```

**Comment by SMillerDev** [comment] 2021-12-28 14:56
Duplicate of https://github.com/Homebrew/homebrew-core/issues/92080

**Closed by SMillerDev** 2021-12-28 14:56 UTC
Labels: bug
