### ISSUE TITLE
"fmt" should be promoted as required

### ISSUE THREAD

**Issue by thiagoauler** [Homebrew/homebrew-core#55840] opened 2020-06-05 12:30 UTC
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I recently installed mkvtoolnix so I could run mkvmerge tool.

## What happened (include command output)

After installing mkvtoolnix I tried to run mkvmerge, but it didn't work as expected.

<details>
  <summary>Command output</summary>
  <pre>

mkvmerge

dyld: Library not loaded: /usr/local/opt/fmt/lib/libfmt.6.dylib
  Referenced from: /usr/local/bin/mkvmerge
  Reason: image not found
zsh: abort      mkvmerge

  </pre>
</details>

## What you expected to happen

I expected mkvmerge to run properly after the installation.
The solution I found to work was to run manually

brew install fmt

So, I believe that "fmt" should be promoted as required and be auto installed with mkvtoolnix.

## Step-by-step reproduction instructions (by running `brew install` commands)

To reproduce to problem is pretty simple.
Install this formula and try to run it. It won't work.
VERY IMPORTANT: must be replicated in a clean install of brew.

**Comment by jonchang** [comment] 2020-06-05 12:44
Can you open a pull request to fix this? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help you get started. Thanks!

**Comment by thiagoauler** [comment] 2020-06-05 12:57
Thanks! I'll do it anytime soon.

**Comment by Bo98** [comment] 2020-06-05 13:42
Duplicate of #55686.

There was an open pull request at #55690 which I'll now merge.

**Closed by Bo98** 2020-06-05 13:42 UTC
