### ISSUE TITLE
boost 1.67.0 failures

### ISSUE THREAD

**Issue by commitay** [Homebrew/homebrew-core#26769] opened 2018-04-18 02:56 UTC
- [x] [dnsdist](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dnsdist.rb) https://gist.github.com/commitay/94ba19e96f2c3e94a82c58ea128284db 
Reported to upstream via IRC https://github.com/Homebrew/homebrew-core/pull/26812
- [x] [monotone](https://github.com/Homebrew/homebrew-core/blob/master/Formula/monotone.rb) https://gist.github.com/commitay/fee428aff09ea46c8f4fa63c3cb96b99 https://github.com/Homebrew/homebrew-core/pull/26778
- [x] [mpd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpd.rb) https://gist.github.com/commitay/fa067e60066dd9aac83223ca5b1f7c79 https://github.com/MusicPlayerDaemon/MPD/issues/265 https://github.com/Homebrew/homebrew-core/pull/26784
- [x] [libtorrent-rasterbar](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libtorrent-rasterbar.rb) https://gist.github.com/commitay/04ef78894b60b312b7b5e9e744c98e94 https://github.com/arvidn/libtorrent/issues/2947 https://github.com/Homebrew/homebrew-core/pull/26783
- [x] [pcb2gcode](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pcb2gcode.rb) https://gist.github.com/commitay/38a57752c533665ea4c6d7a908d2f88b https://github.com/Homebrew/homebrew-core/pull/26782
- [x] [pcl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pcl.rb) https://gist.github.com/commitay/b29d35ff45c429a42acd8f095b039eae https://github.com/PointCloudLibrary/pcl/issues/2284 https://github.com/boostorg/uuid/commit/a8a1ec3d826b https://reviews.freebsd.org/D15030 https://github.com/Homebrew/homebrew-core/pull/26824
- [ ] [osm2pgrouting](https://github.com/Homebrew/homebrew-core/blob/master/Formula/osm2pgrouting.rb) https://gist.github.com/commitay/353a36ac506ffa735936a01c2d747155
fails on high sierra only https://github.com/pgRouting/osm2pgrouting/issues/227
- [x] [monero](https://github.com/Homebrew/homebrew-core/blob/master/Formula/monero.rb) https://gist.github.com/ilovezfs/c9c30a8fc935f50afef945202915eb01 https://github.com/monero-project/monero/issues/3663 https://github.com/monero-project/monero/pull/3667 https://github.com/Homebrew/homebrew-core/pull/26813

**Comment by ilovezfs** [comment] 2018-04-18 10:41
monotone failure was actually caused by pcre 8.42 in https://github.com/Homebrew/homebrew-core/pull/25562

**Comment by ilovezfs** [comment] 2018-04-18 11:04
deleting monotone in https://github.com/Homebrew/homebrew-core/pull/26778

**Comment by ilovezfs** [comment] 2018-04-18 12:14
pcb2gcode is just missing a pkg-config dependency

**Comment by ilovezfs** [comment] 2018-04-19 06:30
@jbeich thanks! Patch for dnsdist applied in https://github.com/Homebrew/homebrew-core/pull/26812

**Comment by ilovezfs** [comment] 2018-04-22 09:32
Closing this out since the remaining failure is covered by
https://github.com/pgRouting/osm2pgrouting/issues/227
https://github.com/Homebrew/homebrew-core/pull/26825

and is specific to Xcode 9.3 not Boost 1.67.0

Thanks @commitay!

**Closed by ilovezfs** 2018-04-22 09:32 UTC
