### ISSUE TITLE
Rust won't upgrade

### ISSUE THREAD

**Issue by blogabe** [Homebrew/homebrew-core#29360] opened 2018-06-23 21:23 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade Rust which I haven't been able to do since https://github.com/Homebrew/homebrew-core/pull/28679

- What happened (include command output)
```
brew upgrade rust
==> Upgrading 1 outdated package, with result:
rust 1.26.1 -> 1.27.0
==> Upgrading rust
==> Downloading https://static.rust-lang.org/dist/rustc-1.27.0-src.tar.gz
Already downloaded: /Users/arajab/Library/Caches/Homebrew/rust-1.27.0.tar.gz
==> ./configure --prefix=/Users/arajab/local/Cellar/rust/1.27.0 --release-channel=stable
==> make
==> make install
==> Downloading https://static.rust-lang.org/dist/2018-05-10/cargo-0.27.0-x86_64-apple-darwin.tar.gz
Already downloaded: /Users/arajab/Library/Caches/Homebrew/rust--cargobootstrap-0.27.0.tar.gz
==> ./install.sh --prefix=/private/tmp/rust-20180623-28726-1odxdv0/rustc-1.27.0-src/cargobootstrap
==> Cloning https://github.com/rust-lang/cargo.git
Updating /Users/arajab/Library/Caches/Homebrew/rust--cargo--git
==> Checking out tag 0.27.0
==> cargo install --root /Users/arajab/local/Cellar/rust/1.27.0
Last 15 lines from /Users/arajab/Library/Logs/Homebrew/rust/05.cargo:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:121:72: error: expected ';' after top level declarator
typedef struct CF_BRIDGED_TYPE(id) SECTYPE(SecKeychain) *SecKeychainRef API_PROHIBITED(ios);
                                                                       ^
                                                                       ;
7 errors generated.
make[2]: *** [src/CMakeFiles/git2internal.dir/streams/stransport.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/git2internal.dir/all] Error 2
make: *** [all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /private/tmp/rust-20180623-28726-1odxdv0/rustc-1.27.0-src/.brew_home/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.31/src/lib.rs:643:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


READ THIS: https://docs.brew.sh/Troubleshooting
```

- What you expected to happen
Successful upgrade like usual

- Step-by-step reproduction instructions (by running `brew install` commands)
see above

**Comment by mistydemeo** [comment] 2018-06-25 19:19
I'm not able to reproduce. Can you please provide all of the debug output requested by https://docs.brew.sh/Troubleshooting?

**Comment by blogabe** [comment] 2018-06-25 19:28
This? https://gist.github.com/blogabe/4a4438e311da2a233a78ba7348650a96

**Comment by blogabe** [comment] 2018-06-25 19:55
Only additional thing to add is that my system is a 10.13 system, but I did install the 10.14 developer beta access utility on it.  I never did install the beta however.  Unsure if xCode or command-line-tolls got updated in the process or thereafter.  When I run `xcode-select --version`, the system replies with 2349.

**Comment by mistydemeo** [comment] 2018-06-25 20:13
It does look like you ended up with the Xcode 10 beta CLT installed, even though you're still on 10.13. Building with the 10.14 CLT SDK seems to be the source of the problem you're seeing. I'd recommend downgrading back to the stable version.

**Comment by mistydemeo** [comment] 2018-06-30 00:09
@blogabe Is this still an issue for you?

**Comment by blogabe** [comment] 2018-06-30 16:08
Hi @mistydemeo Haven't had a chance to downgrade and test.  I don't use rust, but have something that depends on it.  I'm fine waiting till this will be supported whenever Mojave is released (assume that's the plan).

**Comment by ilovezfs** [comment] 2018-06-30 16:10
>I don't use rust, but have something that depends on it.

```
brew install --force-bottle rust
```

**Comment by blogabe** [comment] 2018-06-30 16:12
Thanks, @ilovezfs... yep, that's what I did to force the install.  Just wanted to report the failure when trying to build from source.

**Comment by mistydemeo** [comment] 2018-06-30 18:33
> I'm fine waiting till this will be supported whenever Mojave is released (assume that's the plan).

That's the plan. :) Xcode 10/CLT 10 works fine on Mojave; the only issue is using the 10.14 SDK to build it on 10.13, which we may not be able to support.

Closing for now, but if this resurfaces after Xcode 10 is released we can look at it then. Thanks again for the report!

**Closed by mistydemeo** 2018-06-30 18:33 UTC
Labels: 10.14
