### ISSUE TITLE
wireguard doesn't start anymore

### ISSUE THREAD

**Issue by merkleID** [Homebrew/homebrew-core#71253] opened 2021-02-16 05:18 UTC
**`brew config` output**

HOMEBREW_VERSION: 3.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c951be8d3c7b339c7e759b7c40aec859e09a70a5
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bd29885841e708e187114686b614966962023d1d
Core tap last commit: 70 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.gQr5i7fMSd/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11

**`brew doctor` output**

luca@russell~😈 brew doctor
Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

starting one of my wireguard vpn

**What happened (include all command output)?**

this:
luca@russell~😈 wg-quick up h4
wg-quick must be run as root. Please enter the password for luca to continue: 
[#] wireguard-go utun
[+] Interface for h4 is utun7
[#] wg setconf utun7 /dev/fd/63

and it's forever stuck at the last line.

I can tell this happend after the last update as I have two macbooks, and it started not working on the update one while the one with the wireguard pre-version was starting and working perfectly.
As the second macbook got updated too, it happened to have the same problem.

Luckily it works with the AppStore version of wireguard.

Thanks,
Luca

**What did you expect to happen?**

to rise up the interface.

**Step-by-step reproduction instructions (by running `brew` commands)**

sudo wg-quick up $conf

**Comment by gheift** [comment] 2021-02-16 14:39
Installing the older version of wireguard-go works for me:
```
curl -L -O https://github.com/Homebrew/homebrew-core/raw/bf84868a06c77d8964f57e45b641e20748174ad1/Formula/wireguard-go.rb
brew remove --force wireguard-tools
brew remove --force wireguard-go
brew install wireguard-tools
brew unlink wireguard-go
brew install -s ./wireguard-go.rb
```

This is a dirty workaround, but since all `brew switch` was removed, this is the quickest way I found. See https://github.com/Homebrew/discussions/discussions/339

Since they removed switch, why is pin/unpin still available? /s

**Comment by jonchang** [comment] 2021-02-17 02:33
@gheift You agreed to follow the code of conduct when posting here, so please be more considerate in your communication. https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#considerate

@merkleID can you please provide a more detailed reproduction, which includes all the steps for someone who does not have wireguard already configured?

**Comment by merkleID** [comment] 2021-02-17 04:25
> @merkleID can you please provide a more detailed reproduction, which includes all the steps for someone who does not have wireguard already configured?

Sure, but... it's just a 'brew install wireguard-go wireguard-tools'.
I have config files under /usr/local/etc/wireguard and I fire up a vpn with 
wg-quick up $conf
it's just that.
it always worked and got broken with the last update.
I honestly don't how I could give a more detailed description of this.

All I can do is paste my redacted h4.conf file:

[Interface]
PrivateKey = [REDACTED]
Address = 172.20.0.50/24
MTU = 1420

[Peer]
Endpoint = [REDACTED]:[REDACTED]
PublicKey = [REDACTED]
AllowedIPs = 172.20.0.0/14, 172.50.0.0/16, 172.31.1.0/24
PersistentKeepalive = 5

Once again, I'd liek to restate once again that the same configuration perfectly works with the Apple AppStore version of wireguard.
It just suddenly stopped working in the brew version of wireguard.

Thanks.

**Comment by merkleID** [comment] 2021-02-17 06:50
@gheift 
It worked like a charm,
thank you.
Still don't understand why your comment was tagged as 'disruptive'.

**Comment by SMillerDev** [comment] 2021-02-17 06:55
It only provides a workaround instead of a fix and it's unnecessarily rude to brew maintainers.

---

Now as for your issue. Have you tried checking if the app store version is actually the same version number that brew ships?

**Comment by gheift** [comment] 2021-02-17 07:23
If my comment was rude, I will try to be more polite. Maybe I was just a little bit frustrated because there was no easy way to install the older version. All posts I found were about using `brew switch`, but this is not supported anymore.

I don't know if it's belongs here, but is there a new way to use an older version of a program in brew?

**Comment by merkleID** [comment] 2021-02-17 08:20
> It only provides a workaround instead of a fix and it's unnecessarily rude to brew maintainers.
> 

He definitely wasn't and I think you should reconsider your definition of rudeness, unless in unmasking his original now hidden post there's something I can't read.
Using the same logic, also posting that a new version fo $any-package doesn't work and is now broken could be seen as offensive to the maintainers and dismissive of their work, and I clearly do not intend to abide to those self-entitled ethical authorities.

Also, suggesting a workaround I still hadn't tried yet, helped me to be back on track with *absolutely necessary* vpns I need for work.
Fixes will come and will be applied, but until then every work-around is fully appreciated, and if he's not a maintainer, he's not even requested to write a fix.


> Now as for your issue. Have you tried checking if the app store version is actually the same version number that brew ships?

AppStore version says:
App version: 1.0.12 (22)
Go backend version: 0.0.20201119

from CLI:
feynman:tmp luca$ ls -l /usr/local/Cellar/wireguard-go/
total 0
drwxr-xr-x  7 luca  staff  224 Feb 17 07:47 0.0.20201118
drwxr-xr-x  7 luca  staff  224 Feb 17 07:47 0.0.20210212 (<--- the brew unlinked one)

feynman:tmp luca$ ls -l /usr/local/Cellar/wireguard-tools/
total 0
drwxr-xr-x  9 luca  staff  288 Feb 17 07:47 1.0.20200827

and also:
feynman:tmp luca$ sudo wg-quick up h4
[#] wireguard-go utun
INFO: (utun2) 2021/02/17 09:08:18 Starting wireguard-go version 0.0.20201118
[+] Interface for h4 is utun2
[#] wg setconf utun2 /dev/fd/63
[#] ifconfig utun2 inet 172.20.0.50/24 172.20.0.50 alias
[#] ifconfig utun2 up
[#] route -q -n add -inet 172.31.1.0/24 -interface utun2
[#] route -q -n add -inet 172.50.0.0/16 -interface utun2
[#] route -q -n add -inet 172.20.0.0/14 -interface utun2
[+] Backgrounding route monitor

 And now it's back to working thanks to the workaround provided.

**Comment by SMillerDev** [comment] 2021-02-17 08:34
> If my comment was rude, I will try to be more polite. Maybe I was just a little bit frustrated because there was no easy way to install the older version. All posts I found were about using brew switch, but this is not supported anymore.

Thanks

> I don't know if it's belongs here, but is there a new way to use an older version of a program in brew?

You can use `brew extract` to clone an older version as a separate versioned formula.

---

> AppStore version says:
Go backend version: 0.0.20201119

and
> drwxr-xr-x 7 luca staff 224 Feb 17 07:47 0.0.20201118
drwxr-xr-x 7 luca staff 224 Feb 17 07:47 0.0.20210212 (<--- the brew unlinked one)

This is probably the issue. There is likely an upstream bug in the `0.0.20210212` version that isn't present in the `0.0.20201119` version.

**Comment by gheift** [comment] 2021-02-17 10:11
So basically the better way to install the old version is the following:
```
brew tap-new $USER/local --no-git
brew extract --version=0.0.20201118 wireguard-go $USER/local
brew install wireguard-go@0.0.20201118
brew unlink wireguard-go
brew link wireguard-go@0.0.20201118
```
I found this page helpful: https://cmichel.io/how-to-install-an-old-package-version-with-brew/

**Comment by bbsixzz** [comment] 2021-02-18 10:13
Once this is officially fixed, what happens to the local tap when you run brew upgrade? Do you need to clean up anything?

**Comment by SMillerDev** [comment] 2021-02-18 10:40
> Once this is officially fixed, what happens to the local tap when you run brew upgrade? Do you need to clean up anything?

Nothing. You will still have your explicitly installed version installed. You'll need to uninstall that version and install the new one when this is fixed.

**Comment by smonv** [comment] 2021-02-18 12:47
After installed the old wireguard via local repo, I got git error whenever upgrade brew package, not sure because of local repo or something else.

```
❯ brew upgrade
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Updating Homebrew...
fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it
fatal: invalid upstream 'origin/master'
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 7 formulae.
==> Updated Casks
Updated 15 casks.
```

**Comment by AKarbas** [comment] 2021-02-18 16:53
Firstly thank you all for the fix. My wireguard is up and running again :)

---
@smonv
> After installed the old wireguard via local repo, I got git error whenever upgrade brew package, not sure because of local repo or something else.

The error on `brew update` is because it tries to do a git fetch on the newly created local tap which is a git repo. See [here](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) for more on taps.

If you want to remove the error (and not ignore it), you can create your own tap, or just publish the local tap to github. It should be at `/usr/local/Homebrew/Library/Taps/<user_name>/homebrew-local`.

**Comment by gromgit** [comment] 2021-02-19 01:25
> It should be at `/usr/local/Homebrew/Library/Taps/<user_name>/homebrew-local`.

For every `brew tap <username/tap>`, you can always get the underlying path with `brew --repo <username/tap>`.

**Comment by smonv** [comment] 2021-02-19 01:27
@AKarbas @gromgit thanks for the guidance, I'll try to resolve this issue later.

After this issue resolved by brew, do I need to unpin wireguard version before deleting the local tap?

**Comment by gromgit** [comment] 2021-02-19 01:54
> After this issue resolved by brew, do I need to unpin wireguard version before deleting the local tap?

`Pinning` in a Homebrew context means running `brew pin <formula>` to stop future `brew upgrades` from changing the installed version of `<formula>`. I assume you didn't do that.

You do need to uninstall your locally-extracted version before reinstalling the core formula (and untapping your local tap).

**Comment by smonv** [comment] 2021-02-19 02:02
> `Pinning` in a Homebrew context means running `brew pin <formula>` to stop future `brew upgrades` from changing the installed version of `<formula>`. I assume you didn't do that.

I did pin the older wireguard version in my local tap.

> You do need to uninstall your locally-extracted version before reinstalling the core formula (and untapping your local tap).
Thank you

**Comment by huwany** [comment] 2021-02-19 06:01
mark.

the same issue, Tony Stuck on 「wg setconf utun7 /dev/fd/63」

**Comment by jonchang** [comment] 2021-02-19 06:07
Someone who actually uses wireguard and can write reproduction steps needs to send a bug report to upstream, otherwise this will never get fixed. Saying "this affects me to" in the Homebrew issue tracker is not useful since Homebrew just packages the software; the maintainers are not the upstream developers. https://lists.zx2c4.com/pipermail/wireguard/

**Comment by merkleID** [comment] 2021-02-19 06:15
> Someone who actually uses wireguard and can write reproduction steps needs to send a bug report to upstream, otherwise this will never get fixed. Saying "this affects me too" in the Homebrew issue tracker is not useful since Homebrew just packages the software; the Homebrew maintainers are not the upstream developers. https://lists.zx2c4.com/pipermail/wireguard/

Hi,
I see you are asking this again after I answered you, and I also posted a redacted version of a conf of mine.
There is really nothing more than 
wg-quick up $conf 
and it gets stuck before applying ifconfig to the created utunX until you ctrl-C and exit.
This happens with the latest version of brew wireguard.
All I can really tell you is that I don't know if this bug is something specifically related to the brew version of wireguard or not.
The AppStore version of wireguard is no affected as it uses a previous version of wireguard, so a real comparison can't be made.
What exactly are you looking for?

**Comment by bbsixzz** [comment] 2021-02-22 00:04
Did someone send a bug report upstream? I will do it otherwise, never done before but I want this fixed asap.

**Comment by gluxon** [comment] 2021-02-22 01:45
I just sent the WireGuard email list a note about this after narrowing it down to https://github.com/WireGuard/wireguard-go/commit/18e47795e598973195887893e7d77baddec53ebb.

It should appear on the February 2021 archive page soon: https://lists.zx2c4.com/pipermail/wireguard/2021-February/thread.html

**Comment by gluxon** [comment] 2021-02-22 02:29
Dug a bit deeper and realized this is already fixed by commit https://github.com/WireGuard/wireguard-tools/commit/457f96b65e4f7241aceaa7cb9c7bbce7be1a2212 on January 25th, 2021. The homebrew version of `wireguard-tools` is from August 27th, 2020. I asked the mailing list whether a new release with this could be made.

So this issue should be resolved once a new `wireguard-tools` version is pushed and the homebrew formula is updated for it.

**Closed** 2021-02-24 09:23 UTC
Labels: upstream issue
