### ISSUE TITLE
uptime from coreutils return an incorrect uptime (18800 days)

### ISSUE THREAD

**Issue by dev-mansonthomas** [Homebrew/homebrew-core#79757] opened 2021-06-22 11:13 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09f7bc27a99469cf947431df4754737dfbadb31d
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d758f08e4d5dc1e37967f83ed6480fadbb159ca4
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-x86_64
CLT: 12.5.0.22.9
Xcode: N/A


 brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

get the uptime from my mac with the uptime command that is provided by coreutils

 13:09:35  ~ 
 $  brew info coreutils
coreutils: stable 8.32 (bottled), HEAD
GNU File, Shell, and Text utilities
https://www.gnu.org/software/coreutils
Conflicts with:
  aardvark_shell_utils (because both install `realpath` binaries)
  b2sum (because both install `b2sum` binaries)
  ganglia (because both install `gstat` binaries)
  gdu (because both install `gdu` binaries)
  gegl (because both install `gcut` binaries)
  idutils (because both install `gid` and `gid.1`)
  md5sha1sum (because both install `md5sum` and `sha1sum` binaries)
  truncate (because both install `truncate` binaries)
  uutils-coreutils (because coreutils and uutils-coreutils install the same binaries)
/usr/local/Cellar/coreutils/8.32 (476 files, 12.5MB) *
  Poured from bottle on 2021-03-29 at 23:52:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/coreutils.rb
License: GPL-3.0-or-later
==> Options
--HEAD
	Install HEAD version
==> Caveats
Commands also provided by macOS have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
==> Analytics
install: 63,222 (30 days), 196,714 (90 days), 612,498 (365 days)
install-on-request: 42,111 (30 days), 133,595 (90 days), 515,265 (365 days)
build-error: 0 (30 days)
 13:09:41  ~ 
 $  which uptime
/usr/local/opt/coreutils/libexec/gnubin/uptime
 13:09:48  ~ 

### What happened (include all command output)?

uptime value is incorrect as 18800 days

 $  uptime
 13:09:51  up 18800 days 10:26,  3 users,  load average: 3.28, 2.79, 2.41
 13:09:51  ~ 
 $  /usr/bin/uptime
13:09  up 36 days,  3:25, 3 users, load averages: 3.44 2.85 2.43
 13:09:59  ~ 
 $ 

### What did you expect to happen?

I would have expected that it returns 36 days just as the native uptime command

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install coreutils
uptime
/usr/bin/uptime
```

**Comment by carlocab** [comment] 2021-06-22 11:36
Can't reproduce.
```
❯ guptime
 12:34:19  up  12:28,  1 user,  load average: 2.62, 2.47, 2.37
❯ /usr/bin/uptime
12:34  up 12:28, 1 user, load averages: 2.44 2.43 2.36
```
Is this an issue just with Homebrew `coreutils`, or can you reproduce this with a Non-Homebrew `coreutils`? If it's the latter, this needs to be reported upstream, as it needs to be fixed there.

I suspect it's the latter. However, given that I'm unable to reproduce this even with the Homebrew `coreutils`, I'm unable to test whether a non-Homebrew `coreutils` is also affected.

**Comment by gromgit** [comment] 2021-06-22 13:06
@dev-mansonthomas , what does `which -a uptime` output?

**Comment by dev-mansonthomas** [comment] 2021-06-23 13:22
@gromgit here it is : 

 16:56:24  ~  projects  sdkperf-mqtt-8.4.3.70 
 $  uptime
 15:19:32  up 18801 days 12:35,  3 users,  load average: 2.46, 2.83, 2.72
 15:19:32  ~  projects  sdkperf-mqtt-8.4.3.70 
 $  which -a uptime
/usr/local/opt/coreutils/libexec/gnubin/uptime
/usr/bin/uptime
 15:19:34  ~  projects  sdkperf-mqtt-8.4.3.70 

@carlocab I understand, any idea on how to use coreutils outside of homebrew (I'm using brew to not bother about this lol) 

The number of days is increasing, at first I thought it was just displaying some kind of hard limit.

**Comment by carlocab** [comment] 2021-06-23 14:34
Try this:
```
cd /tmp
curl -L https://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.xz | tar -x
cd coreutils-8.32
./configure --prefix=/tmp/coreutils --without-gmp --without-selinux
make install
/tmp/coreutils/bin/uptime
```
You can probably make the compile quicker by compiling only `uptime` (maybe with `make uptime` instead of `make install` -- but that won't install `uptime` so you'll need to find where the build put it).

**Comment by gromgit** [comment] 2021-06-23 14:45
And while that build is running, also run the following:
```
type uptime
```
I should've asked for this instead of `which -a uptime`, as it tells us exactly what _your shell_ thinks `uptime` is.

**Comment by dev-mansonthomas** [comment] 2021-06-23 15:22
@gromgit  
$  type uptime
uptime is hashed (/usr/local/opt/coreutils/libexec/gnubin/uptime)

@carlocab 
![image](https://user-images.githubusercontent.com/5695269/123123875-7a075700-d447-11eb-8083-5e1819581762.png)

I guess I know what to do 😂

Thanks for the quick explanations !

**Comment by carlocab** [comment] 2021-06-23 15:23
No problem.

Closing as this is definitely a upstream issue, and not a problem that we can fix here.

**Closed by carlocab** 2021-06-23 15:23 UTC
Labels: bug

**Comment by dev-mansonthomas** [comment] 2021-06-23 15:24
so that would be an issue ticket for : https://github.com/coreutils/coreutils  ?

**Comment by carlocab** [comment] 2021-06-23 15:26
That's just a mirror. Bug reporting information can be found on the homepage: https://www.gnu.org/software/coreutils/
