### ISSUE TITLE
docutils not working: ImportError: No module named docutils.core

### ISSUE THREAD

**Issue by luangong** [Homebrew/homebrew-core#14474] opened 2017-06-11 11:31 UTC
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs docutils` and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## `brew config` output

```
HOMEBREW_VERSION: 1.2.2-55-gf3970b52
ORIGIN: https://github.com/Homebrew/brew
HEAD: f3970b52b6827176838cceead370a50e0cbb6cbf
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5b77ea420efb0a930b50fe489930912527fe19f7
Core tap last commit: 34 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_102
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

## `brew doctor` output

```
Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```

## What I was trying to do (and why)

I was trying to install `docutils` via Homebrew rather than `pip`:

```
$ brew install docutils
$ rst2html.py --version
```

## What happened (include command output)

```
Traceback (most recent call last):
  File "/usr/local/bin/rst2html.py", line 17, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named docutils.core
```

## What you expected to happen

It should print the version of `docutils`, like this:

```
rst2html.py (Docutils 0.13.1 [release], Python 2.7.13, on darwin)
```

## Analysis

The shebangs in `/usr/local/bin/rst2*.py` all use system Python (`/usr/bin/python`) rather than the homebrewed one, but the Python package for `docutils` is installed to homebrewed Python site package folder (`/usr/local/lib/python2.7/site-packages/docutils`) when I run `brew install docutils`.

So we need to add a patch to point the shebangs to Homebrewed Python (`/usr/local/bin/python`).

I believe this issue exists because homebrew/legacy-homebrew#44665 was not fixed.

**Comment by ilovezfs** [comment] 2017-06-11 12:05
We build `docutils` with system Python deliberately. Regardless, I cannot reproduce this issue with either brew python or system python, whether using the bottle or building from source. See log here: https://gist.github.com/ilovezfs/826ab04acf2eb30f5a6f81ccc76208f4

**Comment by ilovezfs** [comment] 2017-06-11 12:08
CC @tdsmith any idea what's going on here?

**Comment by luangong** [comment] 2017-06-11 12:16
I think I found the cause of this issue. In `docutils.rb`, line 14–16:

```
def install
    system "python", *Language::Python.setup_install_args(prefix)
end
```

I had installed Python 2.7.13 through `brew install python` before installing `docutils`, so it is actually installing the `docutils` package to homebrewed Python rather than system Python. We need to change line 15 to

```
system "/usr/bin/python", *Language::Python.setup_install_args(prefix)
```

**Comment by ilovezfs** [comment] 2017-06-11 12:18
Actually brew takes care of that automatically:
```
iMac-TMP:~ joe$ which python
/usr/local/bin/python
iMac-TMP:~ joe$ brew install -dvs docutils
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/docutils.rb
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170611-38401-1dy6p4f.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/docutils.rb --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/docutils.rb
==> Downloading https://downloads.sourceforge.net/project/docutils/docutils/0.13.1/docutils-0.13.1.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/docutils-0.13.1.tar.gz
==> Verifying docutils-0.13.1.tar.gz checksum
tar xzf /Users/joe/Library/Caches/Homebrew/docutils-0.13.1.tar.gz
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
RuntimeError: here
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
bash-3.2$ which python
/usr/bin/python
bash-3.2$
```

**Comment by ilovezfs** [comment] 2017-06-11 12:44
@luangong what's the output of
```
env | grep PY
```
and
```
echo $PATH
```

**Comment by luangong** [comment] 2017-06-11 12:46
```
$ env | grep PY
$ echo $PATH
/usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
```

**Comment by ilovezfs** [comment] 2017-06-11 12:49
And how about
```
python -c "import sys; print sys.path"
```
and
```
pip -V
```

**Comment by luangong** [comment] 2017-06-11 12:53
```
$ python -c 'import sys; print sys.path'
['', '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages']

$ pip -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by ilovezfs** [comment] 2017-06-11 13:02
Can you try
```
brew reinstall docutils
```

**Comment by ilovezfs** [comment] 2017-06-11 13:05
I can reproduce the issue by corrupting my installation:
```
iMac-TMP:~ joe$ mv /usr/local/lib/python2.7/site-packages ~/spp
iMac-TMP:~ joe$ brew postinstall python
==> Postinstalling python
==> Using the sandbox
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --
iMac-TMP:~ joe$ brew install docutils
Warning: docutils 0.13.1 is already installed
iMac-TMP:~ joe$ rst2html.py --version
Traceback (most recent call last):
  File "/usr/local/bin/rst2html.py", line 17, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named docutils.core
iMac-TMP:~ joe$ brew reinstall docutils
==> Reinstalling docutils 
==> Downloading https://homebrew.bintray.com/bottles/docutils-0.13.1.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/docutils-0.13.1.el_capitan.bottle.tar.gz
==> Pouring docutils-0.13.1.el_capitan.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/docutils/0.13.1: 205 files, 1.9MB
iMac-TMP:~ joe$ rst2html.py --version
rst2html.py (Docutils 0.13.1 [release], Python 2.7.10, on darwin)
iMac-TMP:~ joe$
```

**Comment by ilovezfs** [comment] 2017-06-11 13:29
@luangong any luck after `brew reinstall docutils`?

**Comment by luangong** [comment] 2017-06-11 21:41
@ilovezfs No luck.

**Comment by ilovezfs** [comment] 2017-06-13 10:47
Please try in an empty brew installation.

```
mkdir ~/homebrew-20170613
sudo mv /usr/local ~/homebrew-20170613/
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install docutils
rst2html.py --version
```

**Comment by luangong** [comment] 2017-06-15 10:48
I installed Homebrew and `docutils` on a clean macOS virtual machine:

```
$ brew install docutils
==> Downloading https://homebrew.bintray.com/bottles/docutils-0.13.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring docutils-0.13.1.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/luangong/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/luangong/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/docutils/0.13.1: 205 files, 1.9MB
```

But the issue still remained:

```
$ rst2html.py --version
Traceback (most recent call last):
  File "/usr/local/bin/rst2html.py", line 17, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named docutils.core
```

I then followed the instructions:

```
$ mkdir -p /Users/luangong/Library/Python/2.7/lib/python/site-packages
$ echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/luangong/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```

After that, the `docutils` package worked well:

```
$ rst2html.py --version
rst2html.py (Docutils 0.13.1 [release], Python 2.7.10, on darwin)
```

**Comment by ilovezfs** [comment] 2017-06-15 12:29
Yup.
```
iMac-TMP:~ joe$ cat /Users/joe/Library/Python/2.7/lib/python/site-packages/homebrew.pth
import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")
import sys, os; sys.path = (os.environ["PYTHONPATH"].split(os.pathsep) if "PYTHONPATH" in os.environ else []) + ["/usr/local/lib/python2.7/site-packages"] + sys.path
iMac-TMP:~ joe$ rst2html.py --version
-bash: rst2html.py: command not found
iMac-TMP:~ joe$ brew install docutils
==> Downloading https://homebrew.bintray.com/bottles/docutils-0.13.1.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/docutils-0.13.1.el_capitan.bottle.tar.gz
==> Pouring docutils-0.13.1.el_capitan.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/docutils/0.13.1: 205 files, 1.9MB
iMac-TMP:~ joe$ rst2html.py --version
rst2html.py (Docutils 0.13.1 [release], Python 2.7.10, on darwin)
iMac-TMP:~ joe$ mv /Users/joe/Library/Python/2.7/lib/python/site-packages/homebrew.pth .
iMac-TMP:~ joe$ rst2html.py --version
Traceback (most recent call last):
  File "/usr/local/bin/rst2html.py", line 17, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named docutils.core
```

CC @tdsmith

**Comment by tdsmith** [comment] 2017-06-15 14:33
I think the problem is just that this is installing to prefix and not writing wrappers?

**Comment by ilovezfs** [comment] 2017-06-15 14:34
Why do I randomly have that file though that "fixes" the issue?

**Comment by tdsmith** [comment] 2017-06-15 14:37
Dunno! Homebrew didn't write it, but the caveats tell you to do it when it detects that python modules were installed and your $PATH python won't see them.

**Comment by ilovezfs** [comment] 2017-06-15 14:38
Ah maybe I followed orders at one point. :see_no_evil:

**Comment by ilovezfs** [comment] 2017-06-15 14:46
Yeah I guess there's actually no bug here since the caveats tell you exactly what to do to make it work.

**Comment by ilovezfs** [comment] 2017-06-15 15:19
Thanks for reporting this @luangong! It should be fixed now.

**Closed** 2017-06-15 15:19 UTC
Labels: python

**Comment by luangong** [comment] 2017-06-16 00:06
Thank you @ilovezfs
