### ISSUE TITLE
diff-pdf bottles are missing (in revision 8)

### ISSUE THREAD

**Issue by thbar** [Homebrew/homebrew-core#67072] opened 2020-12-17 19:58 UTC
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem? (not 100% here)
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install diff-pdf`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew install diff-pdf
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
signal

==> Downloading https://homebrew.bintray.com/bottles/diff-pdf-0.4.1_8.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "diff-pdf"
Download failed: https://homebrew.bintray.com/bottles/diff-pdf-0.4.1_8.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/vslavik/diff-pdf/releases/download/v0.4.1/diff-pdf-0.4.1.tar.gz
Already downloaded: /Users/thbar/Library/Caches/Homebrew/downloads/ed587a20534d95120971bb9dd050b7bbf84210d189ebefda91a082f11512205e--diff-pdf-0.4.1.tar.gz
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

==> ./configure --prefix=/usr/local/Cellar/diff-pdf/0.4.1_8
Last 15 lines from /Users/thbar/Library/Logs/Homebrew/diff-pdf/01.configure:
checking for style of include used by make... GNU
checking dependency style of clang++... none
checking for pkg-config... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for POPPLER... no
configure: error: Package requirements (poppler-cairo >= 0.10 poppler-glib >= 0.10 cairo-pdf) were not met:

No package 'poppler-cairo' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables POPPLER_CFLAGS
and POPPLER_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
diff-pdf failing to build on macOS 10.15.7 https://github.com/Homebrew/homebrew-core/issues/66385

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
  </pre>
</details>

Output for `brew config` and `brew doctor` is available at https://gist.github.com/thbar/b5890cb0ab658bc3bed4dd170c45032d

## What you expected to happen

I expected the bottle at https://homebrew.bintray.com/bottles/diff-pdf-0.4.1_8.mojave.bottle.tar.gz to be available.

The previous revision is available at: https://homebrew.bintray.com/bottles/diff-pdf-0.4.1_7.mojave.bottle.tar.gz 

In https://github.com/Homebrew/homebrew-core/commit/6474b708f48902e5ab23885b22b0acd9328d8d83 the revision was updated from 7 to 8.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install diff-pdf`

**Comment by thbar** [comment] 2020-12-17 20:04
Just a guess: if the bottles are built via the "brew test bot" (as described here https://docs.brew.sh/Brew-Test-Bot) via PR, this issue could have been caused by a direct `master` commit, leading to no PR.

**Comment by thbar** [comment] 2020-12-17 20:18
There's an ongoing PR to update the formula at https://github.com/Homebrew/homebrew-core/pull/66369.

**Comment by fxcoudert** [comment] 2020-12-18 09:49
Duplicate of https://github.com/Homebrew/homebrew-core/issues/66385

**Closed by fxcoudert** 2020-12-18 09:49 UTC

**Comment by thbar** [comment] 2020-12-20 11:31
Fixed now. Thanks @fxcoudert!
