### ISSUE TITLE
qt@5.rb looks in a wrong place for gl.h on newer systems

### ISSUE THREAD

**Issue by arekm** [Homebrew/homebrew-core#201472] opened 2024-12-17 07:58 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
macos 15.2 no longer provides gl.h (not sure which macos version exactly dropped this header)

`
bash-3.2# find /System/Library/Frameworks/ -name gl.h
bash-3.2#
````

but /opt/homebrew/Cellar/qt@5/5.15.16/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake searches only in these old locations:

````
set(_GL_INCDIRS "/System/Library/Frameworks/OpenGL.framework/Headers" "/System/Library/Frameworks/AGL.framework/Headers")
````

On my system some package installed /opt/X11/include/GL/gl.h, so as workaround I used

````
set(_GL_INCDIRS "/System/Library/Frameworks/OpenGL.framework/Headers" "/System/Library/Frameworks/AGL.framework/Headers" "/opt/X11/include/GL")
````

to solve this problem. What's the correct way to fix this with homebrew philosophy - no idea.

My brew doctor doesn't say "Your system is ready to brew" but warnings it shows are unrelated.

````
% brew gist-logs qt@5
Error: No logs.
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ansible@8

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
% brew config
HOMEBREW_VERSION: 4.4.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3001afe88112c13b5aafdd92e097680897060881
Last commit: 2 days ago
Branch: stable
Core tap JSON: 17 Dec 07:27 UTC
Core cask tap JSON: 17 Dec 07:27 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 14
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 14-core 64-bit arm_palma
Clang: 16.0.0 build 1600
Git: 2.47.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.2-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: 16.2
Rosetta 2: false
````
```


### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

build app that uses qt5

### What happened (include all command output)?

CMake Error at /opt/homebrew/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
  Failed to find "gl.h" in

(and here were paths "/System/Library/Frameworks/OpenGL.framework/Headers" "/System/Library/Frameworks/AGL.framework/Headers"; sorry, don't have full copy of this error)


### What did you expect to happen?

gl.h to be located in places where it exists on macos 15.2 (with additional homebrew packages)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
No applicable
```

**Comment by SMillerDev** [comment] 2024-12-17 08:16
Does the upstream QT5 binary have the same issue? Because that seems more like an upstream bug then something Brew introduced.

**Comment by Bo98** [comment] 2024-12-20 00:03
Qt/Cmake should search the SDK for that path: https://github.com/qt/qtbase/commit/e9af987f2821112ec6b03af5e2527c37c5580c68. Perhaps worth checking whether the SDK is being detected correctly by CMake. You may be able to see from fuller output.

**Comment by arekm** [comment] 2024-12-20 00:19
Which SDK exactly? So I can check if gl.h exists there.

As recent macos dropped gl.h entirely (from "/System/Library/Frameworks/OpenGL.framework/Headers" "/System/Library/Frameworks/AGL.framework/Headers") - it was deprecated in favor of "metal".

I guess this bug is upstream qt if homebrew philosophy is "do not fix upstream bugs at all".

**Comment by Bo98** [comment] 2024-12-20 00:45
> As recent macos

It was moved from the OS to the SDK 6 years ago.

> Which SDK exactly? So I can check if gl.h exists there.

`/Library/Developer/CommandLineTools/SDKs/MacOSX15.2.sdk` _or_ the equivalent in Xcode.app (e.g. `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk`)

depending on what `xcode-select -print-path` is set to.

**Comment by cho-m** [comment] 2024-12-21 18:28
Closing for reasons already mentioned.

---

Also, I personally cannot reproduce behavior with brew's `cmake` and `qt@5` on macOS 15.2

Just running `cmake -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@5 --trace`, I see no issue. CMake has no errors and some expanded variables from trace show corresponding framework path (inside SDK)

* With CLT selected:
  ```
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake(227):  include(${CMAKE_CURRENT_LIST_DIR}/Qt5GuiConfigExtras.cmake )
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake(4):  set(_GL_INCDIRS /System/Library/Frameworks/OpenGL.framework/Headers /System/Library/Frameworks/AGL.framework/Headers )
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake(5):  find_path(_qt5gui_OPENGL_INCLUDE_DIR gl.h PATHS ${_GL_INCDIRS} )
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake(8):  if(NOT _qt5gui_OPENGL_INCLUDE_DIR )
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake(11):  unset(_GL_INCDIRS )
  ...
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake(13):  if(NOT EXISTS /Library/Developer/CommandLineTools/SDKs/MacOSX15.2.sdk/System/Library/Frameworks/OpenGL.framework )
  ```

* With Xcode selected:
  ```
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake(227):  include(${CMAKE_CURRENT_LIST_DIR}/Qt5GuiConfigExtras.cmake )
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake(4):  set(_GL_INCDIRS /System/Library/Frameworks/OpenGL.framework/Headers /System/Library/Frameworks/AGL.framework/Headers )
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake(5):  find_path(_qt5gui_OPENGL_INCLUDE_DIR gl.h PATHS ${_GL_INCDIRS} )
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake(8):  if(NOT _qt5gui_OPENGL_INCLUDE_DIR )
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake(11):  unset(_GL_INCDIRS )
  ...
  /opt/homebrew/opt/qt@5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake(13):  if(NOT EXISTS /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/System/Library/Frameworks/OpenGL.framework )
  ```

**Closed by cho-m** 2024-12-21 18:28 UTC
Labels: user configuration
