### ISSUE TITLE
`aiccu` sourceball is 402-ing

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew-core#7541] opened 2016-12-04 21:53 UTC
```
brew fetch --force-bottle aiccu
==> Downloading https://www.sixxs.net/archive/sixxs/aiccu/unix/aiccu_20070115.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.2-19-g88d0e8c2e (Macintosh; Intel macOS 10.12.1) curl/7.49.1 https://www.sixxs.net/archive/sixxs/aiccu/unix/aiccu_20070115.tar.gz -C 0 -o /stuff/brache/aiccu-20070115.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 402 Payment Required
Error: Failed to download resource "aiccu"
Download failed: https://www.sixxs.net/archive/sixxs/aiccu/unix/aiccu_20070115.tar.gz
```

**Comment by MikeMcQuaid** [comment] 2016-12-04 21:55
That's not the bottle, FYI.

**Comment by chdiza** [comment] 2016-12-04 22:00
I wonder why it isn't.  I asked for the bottle.  Huh.

**Comment by chdiza** [comment] 2016-12-04 22:01
It also fails to try the bottle (and then fails to get the source ball) if I unset HOMEBREW_BUILD_FROM_SOURCE and just do `brew fetch aiccu`.

**Comment by chdiza** [comment] 2016-12-04 22:27
Ah, I see that I am an idiot re the bottle.

But still, the sourceball shouldn't be 402-ing and asking for money.

**Comment by ilovezfs** [comment] 2016-12-04 22:50
It's caused by our invented user agent.

```
Josephs-MacBook-Pro:~ joe$ openssl dgst -sha256 <(curl -A "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0" -sL https://www.sixxs.net/archive/sixxs/aiccu/unix/aiccu_20070115.tar.gz)
SHA256(/dev/fd/63)= 2260f426c13471169ccff8cb4a3908dc5f79fda18ddb6a55363e7824e6c4c760
Josephs-MacBook-Pro:~ joe$ openssl dgst -sha256 <(curl -sL https://www.sixxs.net/archive/sixxs/aiccu/unix/aiccu_20070115.tar.gz)
SHA256(/dev/fd/63)= 88cffcaf0688507c1196a3ba186864a4a324f72197c81ca506460148a94bded7
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by MikeMcQuaid** [comment] 2016-12-08 10:04
> our invented user agent.

We set our user agent exactly for reasons like this: upstreams can prevent Homebrew from hammering their servers. The "fix" will be setting a mirror as the primary URL here or going imagemagick style and mirroring them ourselves.

**Comment by ilovezfs** [comment] 2016-12-25 17:30
Another casualty of `--online`

```
==> brew audit aiccu --online
==> FAILED
Error: 1 problem in 1 formula
aiccu:
  * The homepage https://www.sixxs.net/tools/aiccu/ is not reachable (HTTP status code 402)
```

This one is going to have permanent audit failure.

**Comment by ilovezfs** [comment] 2016-12-25 17:37
Closed via https://github.com/Homebrew/homebrew-core/pull/8218.

**Closed by ilovezfs** 2016-12-25 17:37 UTC
