### ISSUE TITLE
Redis formula doesn't create config file or db directory for background service.

### ISSUE THREAD

**Issue by jeffbr13** [Homebrew/homebrew-core#11175] opened 2017-03-16 16:46 UTC
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew?

### Bug reports:

While `redis-server` works fine for running Redis in the foreground, starting the service via `brew services (start|run) redis` results in a daemon with the following error in `/usr/local/var/log/redis.log`:

```
2090:C 16 Mar 14:11:39.058 # Fatal error, can't open config file '/usr/local/etc/redis.conf'
```

This is fixed by running `cp /usr/local/etc/redis.conf.default /usr/local/etc/redis.conf`, and then you run into another:

```
5058:C 16 Mar 14:45:02.353 # Can't chdir to '/usr/local/var/db/redis/': No such file or directory
```

This is fixed by running `mkdir -p /usr/local/var/db/redis`.

I haven't contributed before so it might be faster for someone else to fix this in the `redis` formula, but otherwise I can probably get to this in a few days!

**Comment by MikeMcQuaid** [comment] 2017-03-16 18:58
Duplicate of https://github.com/Homebrew/homebrew-core/issues/11175

**Closed by MikeMcQuaid** 2017-03-16 18:58 UTC

**Comment by joeyAghion** [comment] 2017-03-20 18:13
I'm also running into this. It's marked as a duplicate of itself, so maybe it should be re-opened?

**Comment by MikeMcQuaid** [comment] 2017-03-20 19:51
@joeyAghion Sorry, duplicate of #11134.
