### ISSUE TITLE
brew install wireshark is very unstable in GitHub CI (macos-12)

### ISSUE THREAD

**Issue by BewareMyPower** [Homebrew/homebrew-core#157142] opened 2023-12-13 03:27 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
<none> (it can only be reproduced in CI)
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Our project uses `brew install pkg-config wireshark protobuf` to install dependencies. See https://github.com/apache/pulsar-client-cpp/blob/7087a8ef730a1422980f5ee01399dc3528eebe10/.github/workflows/ci-pr-validation.yaml#L54

### What happened (include all command output)?

Recently the CI failed very frequently
- https://github.com/apache/pulsar-client-cpp/actions/runs/7190269569/job/19583126732?pr=371
- https://github.com/apache/pulsar-client-cpp/actions/runs/7178031999/job/19545501038
- https://github.com/apache/pulsar-client-cpp/actions/runs/7095899723/job/19313548306

All these workflows failed at:

```
==> colima
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

To start colima now and restart at login:
  brew services start colima
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/colima/bin/colima start -f
Error: Process completed with exit code 1.
```

### What did you expect to happen?

It should succeed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install pkg-config wireshark protobuf
```

**Comment by branchvincent** [comment] 2023-12-13 06:20
Thanks for the links, the cause of the error is logged a bit [further up](https://github.com/apache/pulsar-client-cpp/actions/runs/7190269569/job/19583126732?pr=371#step:4:498): 

```
==> Pouring node@18--18.19.0.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/node_modules/npm/docs/content/commands/npm-sbom.md
Target /usr/local/lib/node_modules/npm/docs/content/commands/npm-sbom.md
already exists. You may want to remove it:
  rm '/usr/local/lib/node_modules/npm/docs/content/commands/npm-sbom.md'

To force the link and overwrite all conflicting files:
  brew link --overwrite node@18

To list all files that would be deleted:
  brew link --overwrite --dry-run node@18
```

So brew is conflicting with the runner's pre-installed npm. You can workaround that by not upgrading formulae that GitHub pre-installs, either by skipping `brew update` or setting `HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1`

**Comment by Bo98** [comment] 2023-12-13 17:38
This is a bug on GitHub's side.

GitHub seems to have a mismatch in npm versions here, which is causing the conflict. node 18.19.0 shipped with npm 10 (https://github.com/nodejs/node/releases/tag/v18.19.0) and it seems like the GitHub image here has half npm 9, half npm 10 installed.

This issue does not happen on macos-13. If using macos-13 isn't desirable, I imagine it will be fixed with the next macos-12 image update which will universally update everything to Node 18.19.0 (and thus should be consistently npm 10). macos-12 20231211.1 is rolling out now: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20231211.1 - it may take a few days to reach you.

**Comment by X25guru** [comment] 2023-12-15 01:35
wireshark is available as an app in the app store. Save yourself some hair follicles.

**Comment by Bo98** [comment] 2023-12-21 01:50
This fix has been rolled out by GitHub.

**Closed by Bo98** 2023-12-21 01:50 UTC
Labels: bug, upstream issue
