### ISSUE TITLE
[Regression] libaom/aomenc segfaults when aq-mode is 2 and tiles are not square

### ISSUE THREAD

**Issue by ILOVEPIE** [Homebrew/homebrew-core#84771] opened 2021-09-06 22:37 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A this issue is to notify Homebrew project of a regression in 3.1.2 and some earlier versions of libaom/aomenc.
ArchLinux Bug Report: https://bugs.archlinux.org/task/71800

Potential Fixes:

git cherry-pick -n 31257f59a1df72cbbd1399efb780d13a0e433b16

Or the following patch can be applied to 3.1.2:

https://bugs.archlinux.org/task/71800?getfile=20619
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Encode a av1 video with aq-mode 2 and non-square tiles

### What happened (include all command output)?

libaom segfaults.

### What did you expect to happen?

The video should encode without the encoder crashing.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install aom

encode a video with non-square tiles and aq-mode set to 2.
```

**Comment by alebcay** [comment] 2021-09-07 23:55
I think I managed to reproduce the segfault in question via the steps mentioned at https://bugs.archlinux.org/task/71800 (without the fix, trying as a control since the actual segfault doesn't seem to be mentioned anywhere):
```
./crash.sh: line 4: 25895 Bus error: 10           ffmpeg -y -copyts -i "bad_apple.mp4" -pass 2 -slices 8 -ss 0.0 -t 219.22 -vf "scale=w=2566:h=1924:force_original_aspect_ratio=decrease:sws_flags=lanczos:sws_dither=none,crop=trunc(iw/2)*2:trunc(ih/2)*2:0:0" -strict -2 -quality best -row-mt 1 -frame-parallel 0 -deadline best -keyint_min 72 -g 72 -cpu-used 0 -sws_dither none -sws_flags lanczos -aq-mode 2 -deadline best -tile-columns 3 -tile-rows 2 -pix_fmt:v yuv420p -b:v 9790020 -auto-alt-ref 1 -lag-in-frames 25 -threads 32 -passlogfile 5d30cfc6-1532-4db6-b992-2a8406c76977_2566x1924-av1-9790020.0 -sn -an -speed 0 -c:v libaom-av1 -f webm -dash 1 "output.webm"
```

Trying now with the provided fix to verify that it fixes the segfault behavior.

**Comment by ILOVEPIE** [comment] 2021-09-08 03:35
Huh, that's odd, the patch fixes the problem on linux just fine, are you
sure you applied it correctly?
I'd double check to be certain The patch is specifically formatted for
archlinux's package build system layout so it may need to be tweaked, also
ffmpeg may be statically compiled by homebrew in which case you would need
to recompile ffmpeg too.
On Tuesday, September 7, 2021, Caleb Xu ***@***.***> wrote:
> I still see a segfault when I try again with an aom that has the patch:
>
> ./crash.sh: line 4: 29692 Segmentation fault: 11 ffmpeg -y -copyts -i
"bad_apple.mp4" -pass 2 -slices 8 -ss 0.0 -t 219.22 -vf
"scale=w=2566:h=1924:force_original_aspect_ratio=decrease:sws_flags=lanczos:sws_dither=none,crop=trunc(iw/2)*2:trunc(ih/2)*2:0:0"
-strict -2 -quality best -row-mt 1 -frame-parallel 0 -deadline best
-keyint_min 72 -g 72 -cpu-used 0 -sws_dither none -sws_flags lanczos
-aq-mode 2 -deadline best -tile-columns 3 -tile-rows 2 -pix_fmt:v yuv420p
-b:v 9790020 -auto-alt-ref 1 -lag-in-frames 25 -threads 32 -passlogfile
5d30cfc6-1532-4db6-b992-2a8406c76977_2566x1924-av1-9790020.0 -sn -an -speed
0 -c:v libaom-av1 -f webm -dash 1 "output.webm"
>
> It's different from the first one, but unclear to me if it's at all
related (caused by same issue as first one, or perhaps caused by the
patch?).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/HSdIWfGSFQHOL2hkWymEsgjBWBTUxX97LNpAxg24iHEU92rFJ6G9fFP-mJ0cUCBMPjCIFMZV6EyhHGOt6ueSghXTqX__-pka8BVwGYbjjmIAjQblHlBBoG-QncmzS0pfFu6fi9an07sttzFlJhejoEiY1PNkqXV58i_te3cBDaRSn5ufhae-Xr5lKAPRkLF-qpIy9JmBE6uJao_xy2ZDfZmu6JW0se5rjTdFeMBfoQ=s0-d-e1-ft#https://github.com/notifications/beacon/AACB45UYULD6YMNCRXDR2BLUA2YUXA5CNFSM5DRFDQHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOG2C7ILA.gif>

**Comment by alebcay** [comment] 2021-09-08 12:06
> I'd double check to be certain The patch is specifically formatted for
archlinux's package build system layout so it may need to be tweaked

I did tweak it, we apply with `patch -p2` since the source in Arch Linux lives under a `src` folder. The patch itself succeeds.

> ffmpeg may be statically compiled by homebrew in which case you would need
to recompile ffmpeg too.

```
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libcurl.4.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libobjc.A.dylib
  /usr/lib/libxml2.2.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/aom/lib/libaom.3.dylib (aom)
  [...]
```

Looks like `ffmpeg` links dynamically to `libaom`.

**Comment by ILOVEPIE** [comment] 2021-09-09 03:19
hmm, odd, ill double check again later, it could be there's another issue
that only comes into play on other archetectures (if you're using an ARM
mac) or i missed something. either way it needs addressing.

On Wednesday, September 8, 2021, Caleb Xu ***@***.***> wrote:
> I'd double check to be certain The patch is specifically formatted for
> archlinux's package build system layout so it may need to be tweaked
>
> I did tweak it, we apply with patch -p2 since the source in Arch Linux
lives under a src folder. The patch itself succeeds.
>
> ffmpeg may be statically compiled by homebrew in which case you would need
> to recompile ffmpeg too.
>
> System libraries:
> /usr/lib/libSystem.B.dylib
> /usr/lib/libbz2.1.0.dylib
> /usr/lib/libc++.1.dylib
> /usr/lib/libcurl.4.dylib
> /usr/lib/libiconv.2.dylib
> /usr/lib/libobjc.A.dylib
> /usr/lib/libxml2.2.dylib
> /usr/lib/libz.1.dylib
> Homebrew libraries:
> /usr/local/opt/aom/lib/libaom.3.dylib (aom)
> [...]
>
> Looks like ffmpeg links dynamically to libaom.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/_xTct6JsvD1Rh3Sg5fwwNBrilLcX8eqhHFGfKXtf4_0pzEWA5RjpUkUeBpoN7B-ylAtl5-2S2AzR1XkHEwtT6_mxIUxToIrmt6FDyonUHOv_cfXKH2Oxj8SYt9U0yb-l4F0JO0gLbs7WIYlmMpd2gBxHvSIeNr2MnoTqgGW3agXGIFwbXvlAlPTCWt-auwME5z-X6qV5BNCuhp308-5Lz2gdV-lXrK_G48mGjhreaw=s0-d-e1-ft#https://github.com/notifications/beacon/AACB45S3U2QB7BAJVEDF2O3UA5GTLA5CNFSM5DRFDQHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOG2GHS3Q.gif>

**Comment by alebcay** [comment] 2021-09-09 13:14
I agree that this should be addressed, I'm just wondering if maybe there's additional patches needed or something else amiss. I'm testing this on Intel, not Apple Silicon.

I wonder if the error could be something related to resource exhaustion, considering how intensive the second encoding pass is.

**Comment by ILOVEPIE** [comment] 2021-09-12 00:18
```
Bus Error (also known as SIGBUS and is usually signal 10) occur when a process is trying to access memory that the CPU cannot physically address.In other words the memory tried to access by the program is not a valid memory address.It caused due to alignment issues with the CPU
```
that sounds like the patch didn't apply... weird

**Comment by alebcay** [comment] 2021-09-12 02:15
To be clear, the bus error (10) I mentioned was without the patch. I posted that as verification that I was able to reproduce the issue. The subsequent error was not specifically a bus error, just a segfault (11). That happened with the patch applied.

**Comment by ILOVEPIE** [comment] 2021-09-13 03:37
Well the reason this bug causes a crash is an out-of-memory read or write which would cause a bus error (10) not a segfault. So the patch does work, it just seems like there might be some other issue.

**Comment by alebcay** [comment] 2021-09-13 05:14
Right, I reckon that might be the case. Unfortunately there's just no way to tell if the subsequent issue is related to/caused by the addition of this patch (at least on my local system; maybe I just need a beefier machine - the second pass was averaging 0.1-0.2 fps before it crashed).

As such I'm personally not confident in applying the patch from upstream, although I'm open to including it if someone else on our maintainer team can try running through the provided test case.

**Comment by ILOVEPIE** [comment] 2021-09-14 17:57
0.1-0.2 fps is normal, in fact thats on the high end, av1 encoding can be pretty slow.

**Comment by ILOVEPIE** [comment] 2021-09-17 17:36
Just tried this on archlinux, it looks like there's a second bug that happens with this specific video file. I tried with another one that didn't work before the patch and it works now, so it looks like this patch fixes one crash issue but that the bad_apple.mp4 triggers another crash issue too.

**Comment by alebcay** [comment] 2021-09-17 18:05
Could you provide another video to test with that behaves this way (broken before but fixed now)?

Given how fragile this seems right now, ideal scenario here would be that upstream cuts a release soon with any and all such fixes that should make it downstream.

**Comment by SMillerDev** [comment] 2022-05-30 13:27
There have been releases after this, closing

**Closed by SMillerDev** 2022-05-30 13:27 UTC
Labels: bug, help wanted, maintainer feedback
