### ISSUE TITLE
Upgrade: ImageMagick 7.0.x-y

### ISSUE THREAD

**Issue by rakkesh** [Homebrew/homebrew-core#1828] opened 2016-06-08 21:22 UTC
Formulae dependent on imagemagick (in official Homebrew taps)

❌ - Build failed
⚠️ - Formula needs a revision update
✅ - Formula works as is, without a revision update

---

   Formula     => Dependency ( Formula revision )

---
- [x] asciinema2gif            => required (⚠️)
- [x] autotrace                => recommended (⚠️)
- [x] [blockhash](https://github.com/commonsmachinery/blockhash)                => required (❌ [build failed](https://gist.github.com/02477d5bcbbbf2b4697991d18cd48add), failure related to change in path of `wand/MagickWand.h`)
- [x] [dmtx-utils](https://sourceforge.net/p/libdmtx/bugs/)               => required (❌ [build failed](https://gist.github.com/eeccc370b67b5f10c7bd3585cd434067))
- [x] gifify                   => required (✅, shell-script)
- [x] negfix8                  => required (✅, shell-script)
- [x] neofetch                 => required (✅, shell-script)
- [x] nuxeo                    => required (✅, shell-script)
- [x] pdf-redact-tools         => required (✅)
- [x] plowshare                => required (✅, shell-script)
- [x] pstoedit                 => required (⚠️)
- [x] spaceman-diff            => required (✅, shell-script)
- [x] synfig                   => required (❌ [build failed](https://gist.github.com/b69b505e494bd876d6e0ec3fedfaabf1))
- [x] vcs                      => required (✅, shell-script)
- [x]  xplanetfx                => required (✅)
- [x] [zbar](https://sourceforge.net/p/zbar/support-requests/)                     => required (❌[build failed](https://gist.github.com/f51997dc48699f868b17bd77404c873a), failure related to change in path of `wand/MagickWand.h`)
- [x] homebrew/games/mgba      => recommended (❌[build failed](https://gist.github.com/337dfe1700c929c4ba77679334d670a8), failure related to change in path of `wand/MagickWand.h`)
- [x] homebrew/gui/geeqie      => recommended (✅)
- [ ] homebrew/science/ogdraw  => required (too much of a hassle to install Perl dependencies)
- [x] homebrew/science/therion => required (⚠️)
- [x] homebrew/science/weblogo => required (✅, perl-script)
- [x] [homebrew/x11/pyxplot](https://sourceforge.net/p/pyxplot/bugs/)     => required (❌[build failed](https://github.com/Homebrew/homebrew-x11/issues/156), [boneyard candidate](https://github.com/Homebrew/homebrew-x11/issues/156))

**Comment by rakkesh** [comment] 2016-06-21 04:28
`blockhash` => https://github.com/commonsmachinery/blockhash/issues/19

**Comment by rakkesh** [comment] 2016-06-21 04:47
`dmdx-utils` => [libdmtx/bugs#58](https://sourceforge.net/p/libdmtx/bugs/58/)

**Comment by rakkesh** [comment] 2016-06-21 04:51
`zbar` => [zbar/support-requests#156](https://sourceforge.net/p/zbar/support-requests/156/)

**Comment by rakkesh** [comment] 2016-06-21 04:53
`synfig` errors out on a weird check,

```
checking for synfig >= 1.0.2 ETL >= 0.04.19 sigc++-2.0... configure: error:  ** Unable to set up dependent libraries (synfig >= 1.0.2, ETL >= 0.04.19
        )
```

**Comment by MikeMcQuaid** [comment] 2016-09-03 14:44
@rakkesh Given your list above I think we can ship this?

**Comment by ilovezfs** [comment] 2016-11-10 08:31
@zmwangx any thoughts on whether we should still stick with the 6.9.x-y series?

**Comment by zmwangx** [comment] 2016-11-10 15:56
@ilovezfs 

I'd say it's better to stick with IMv6.

IM is one of those old, boring, yet reliable tools that many users probably stick into a pipeline (whether that's a wrapper script for batch processing photos, or a server php program handling user submissions, or whatever) and forget about. IMv7 has made some backward-incompatible changes to the command line interface (see https://www.imagemagick.org/script/porting.php), and users probably don't want to deal with those. (No one wants to revisit five or ten-year-old wrapper scripts. Oh and before dismissing my argument as resisting changes, please read to the end, especially the paragraph starting with "IMv6".) What I found most terrifying on https://www.imagemagick.org/script/porting.php about CLI changes was this:

> However the strict order means that you can no longer give operations before providing an image for the operations to work on. To do so will now produce an error.

which implies something as simple as

```
convert -resize 50% in.png out.png
```

would error out. (The order has been considered legacy since the inception of IMv6, see [this explanation](https://www.imagemagick.org/Usage/basics/#why). But still, you can't tell without digging into docs, because there's no warning on the command line.) Fortunately, I just tried 7.0.3-6 and the syntax above still works, so I guess the developers changed their mind (here's an [`imagemagick7.rb`](https://gist.githubusercontent.com/zmwangx/a40b41fe2feb61b6a59aad6a3bc99218/raw/dcd915f230f28d0dc4d31d335c963e6279f2f452/imagemagick7.rb) which you can install alongside `imagemagick` for testing). Still, there are definitely subtle changes — ones that do not lead to errors outright, but those are the scariest, because you'll get something, just not what you wanted.

IMv6 has been out for 12 years; IMv7, less than a year. https://www.imagemagick.org/Usage/ is still on v6, and I'm not sure if http://www.fmwconcepts.com/imagemagick/ is entirely v7 compatible yet. That is to say, v7 resources are still scarce. If a user is to pick IM today, they may be better off starting with v7. But for the vast existing user base, v6 is still the safer choice, and the dev team is still updating v6 diligently.

A middle ground might be to provide a `imagemagick7` formula, if there's enough interest.

**Comment by pkieltyka** [comment] 2016-11-10 20:52
+1 for imagemagick7 formula

**Comment by MikeMcQuaid** [comment] 2016-11-10 20:55
If imagemagick 7 works for all our reverse dependencies: we should upgrade it.

**Comment by ilovezfs** [comment] 2016-11-10 22:15
We may want to provide imagemagick6 in homebrew/versions in anticipation of the need @zmwangx described above.

**Comment by jmagnusson** [comment] 2017-01-11 08:19
Guys, I just posted a [$100 bounty on Bountysource](https://www.bountysource.com/issues/34990763-upgrade-imagemagick-7-0-x-y), receivable by anyone who resolves this issue. Would be forever thankful for IM 7.0 being available through Homebrew.

**Comment by zmwangx** [comment] 2017-01-11 08:25
@jmagnusson I already posted an `imagemagick7.rb` in this thread a long time ago: https://gist.githubusercontent.com/zmwangx/a40b41fe2feb61b6a59aad6a3bc99218/raw/dcd915f230f28d0dc4d31d335c963e6279f2f452/imagemagick7.rb. You can use that.

But would you please elaborate on your use case? What do you need from IMv7? Scripting? Some revdep that works with IMv7 only (not that I know of)?

It seems to me that anyone can open a PR with a slightly modified `imagemagick7.rb` and get it merged (you can do it yourself and save yourself $100), and I won't complain if someone decides to do it. But as I pointed out above, I'm concerned about issues it may cause, so I don't want to be that guy.

**Comment by jmagnusson** [comment] 2017-01-11 16:30
@zmwangx I have a very specific use case where unnecessary color information is not removed from 16-bit/channel images in ImageMagick 6 but it is in IM7. This new feature generally reduces the file size about 70-75% for the images I'm using, and for 100-150 MB images it's quite a lot. Currently I have to use Photoshop to get the same file size on my Mac, and as you all know Photoshop has no integration with the shell, and is not FOSS (far from!).

Considering how common Imagemagick is, perhaps Imagemagick 7 could be installed to the system in a similar manner to how Python 3 is? And only link in the magick command to the path to avoid collisions (so that we finally can get rid of all the generic command names...)

**Comment by ilovezfs** [comment] 2017-01-11 16:36
blockhash => required (:x: build failed, failure related to change in path of wand/MagickWand.h)
dmtx-utils => required (:x: build failed) zbar => required (:x:build failed, failure related to change in path of wand/MagickWand.h)

The likely path forward here is probably boneyarding blockhash, dmtx-utils, and zbar, upgrading imagemagick to 7, and adding imagemagick@6 for the legacy version.

**Comment by jmagnusson** [comment] 2017-01-11 16:38
@ilovezfs I would also prefer making imagemagick 6 the legacy version and replacing with v7. But if I can't have that I'd be almost as happy with a `imagemagick7` package...

**Comment by ilovezfs** [comment] 2017-01-11 16:43
I don't want to see us adding versioned formulae for new versions to escape issues with reverse dependencies.

**Comment by wickles** [comment] 2017-01-11 16:45
@ilovezfs too late? see: python, python3

**Comment by ilovezfs** [comment] 2017-01-11 16:49
@wickles python is another conversation altogether.

**Comment by wickles** [comment] 2017-01-11 16:55
@ilovezfs According to the homebrew/versions repo, the repo itself will be deprecated because [homebrew-core now supports versions](http://docs.brew.sh/Versions.html). Does that not apply here?

**Comment by ilovezfs** [comment] 2017-01-11 16:57
That's exactly what applies here. If we were keeping the tap, I'd be talking homebrew/versions/imagemagick6 (as I mentioned here https://github.com/Homebrew/homebrew-core/issues/1828#issuecomment-259823775) instead of the possibility of a homebrew/core/imagemagick@6 if there's sufficient need for the old one.

**Comment by ilovezfs** [comment] 2017-01-11 18:56
I've opened https://github.com/Homebrew/homebrew-core/pull/8746.

**Comment by ilovezfs** [comment] 2017-01-12 00:43
Closed via https://github.com/Homebrew/homebrew-core/pull/8746.

**Closed by ilovezfs** 2017-01-12 00:43 UTC
Labels: in progress

**Comment by crazymykl** [comment] 2017-01-12 05:21
Chiming in real quick here: imagemagick@7 straight up breaks `rmagick`. Imagemagick@6 will be the savior of many a Rails developer.

**Comment by zmwangx** [comment] 2017-01-12 05:22
What I feared about, at least vaguely 😂

**Comment by zmwangx** [comment] 2017-01-12 05:26
Since we don't really do downgrades here, I guess now we need to figure out a way to include an IMv6 (I can keep bumping/maintaining it). Keep in mind that the AT_VERSION syntax was designed for libraries (which should be handled transparently), not for users to type, so `imagemagick@6` is not ideal.

**Comment by ilovezfs** [comment] 2017-01-12 05:34
What is the status of progress on ImageMagick 7 support in rmagick?

>Keep in mind that the AT_VERSION syntax was designed for libraries (which should be handled transparently), not for users to type, so imagemagick@6 is not ideal.

It's not a forgone conclusion that even will accept an ImageMagick 6 formula, so there may be nothing for you to worry about in terms of the naming.

**Comment by zmwangx** [comment] 2017-01-12 06:00
Naming is an argument *against* including an IMv6 formula.

**Comment by ilovezfs** [comment] 2017-01-12 06:07
@zmwangx I see. I think any attempt to change the @ naming scheme will fall in the spitting-in-the-wind category.

**Comment by ilovezfs** [comment] 2017-01-12 06:17
@zmwangx fyi: https://github.com/Homebrew/homebrew-core/pull/8756

**Comment by jmagnusson** [comment] 2017-01-12 15:19
Thanks @ilovezfs!!! Don't forget to [claim your bounty](https://www.bountysource.com/issues/34990763-upgrade-imagemagick-7-0-x-y) :-)

**Comment by ilovezfs** [comment] 2017-01-12 15:40
@jmagnusson can I convince you to donate it to the project instead? https://github.com/Homebrew/brew#donations

**Comment by jmagnusson** [comment] 2017-01-12 16:21
@ilovezfs I don't see any way to refund the money. Perhaps you can claim it and donate yourself?

**Comment by ilovezfs** [comment] 2017-01-13 00:30
@jmagnusson will do

**Comment by ilovezfs** [comment] 2017-01-17 10:27
Just a heads up that we've now merged ImageMagick 6 as "imagemagick@6"
