### ISSUE TITLE
openjdk8 crashes on MacOS Monterey

### ISSUE THREAD

**Issue by JasonMing** [Homebrew/homebrew-core#88605] opened 2021-11-02 06:54 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9daf5e2d28396c7a4379605e89e029d9fccb41e6
Last commit: 2 days ago
Core tap ORIGIN: https://mirrors.aliyun.com/homebrew/homebrew-core.git
Core tap HEAD: 8429e2f5ad28fd8f76b2b7530372eec48948e941
Core tap last commit: 6 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.aliyun.com/homebrew/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-x86_64
CLT: 13.1.0.0.1.1633545042
Xcode: N/A
```

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.aliyun.com/homebrew/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Running my project.

### What happened (include all command output)?

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010bbcdce8, pid=40265, tid=0x0000000000006307
#
# JRE version: OpenJDK Runtime Environment (8.0_312) (build 1.8.0_312-bre_2021_10_20_23_15-b00)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b00 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x545ce8]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# *********************************/hs_err_pid40265.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/Homebrew/homebrew-core/issues
#
```

### What did you expect to happen?

No SIGSEGV

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
There are too many dependencies, I don't know which dependency will trigger this SIGSEGV.
```

**Comment by SMillerDev** [comment] 2021-11-02 07:13
This is missing the brew doctor output and a way to reproduce it. "Running my project" is a terrible reproduction instruction, we need to know when it fails otherwise I'm just going to assume it's your code that breaks Java.

**Comment by carlocab** [comment] 2021-11-02 07:13
Can you try to reproduce this with the `temurin8` cask? `brew install --cask homebrew/cask-versions/temurin8`

**Comment by JasonMing** [comment] 2021-11-02 07:42
Hi @SMillerDev  I found it seems not relate to project
try:
```bash
 brew reinstall --build-from-source openjdk@8
```
console output:

```
==> Installing openjdk@8
==> common/autoconf/autogen.sh
==> ./configure --with-boot-jdk-jvmargs=-Duser.home=*********/Library/Caches/Homebrew/java_cache --with-boot-jdk=/private/tmp/openjdkA8
==> make bootcycle-images CONF=release
Last 15 lines from *********/Library/Logs/Homebrew/openjdk@8/03.make:
2021-11-02 07:20:33 +0000

make
bootcycle-images
CONF=release

No configurations found for /private/tmp/openjdkA8-20211102-44546-1ht5syf/jdk8u312-ga/! Please run configure to create a configuration.
Makefile:55: *** Cannot continue.  Stop.

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
openjdk 17.0.1 https://github.com/Homebrew/homebrew-core/pull/87643
openjdk@11 11.0.13 https://github.com/Homebrew/homebrew-core/pull/87638
openjdk: try to reproduce java.lang.UnsatisfiedLinkError https://github.com/Homebrew/homebrew-core/pull/84886
OpenJDK is somewhat broken on newer MacOS instances, console is flooded with errors when using JMeter, AdoptOpenJDK has no issues https://github.com/Homebrew/homebrew-core/issues/66953
```

**Comment by SMillerDev** [comment] 2021-11-02 07:44
That's a very different issue than your first post.

**Comment by JasonMing** [comment] 2021-11-02 07:53
Because before upgrading my MacOS to Monterey, there is no problem in all cases, no matter openjdk@8 or adoptopenjdk8.
I really don't known what is triggering this SIGSEGV.
Then I found this bottle is only support to Big Sur. So I try to reinstall it with building from sources, the result is what you see failed.
Is it the binary compatibility issue on Monterey?

**Comment by JasonMing** [comment] 2021-11-02 08:03
> Can you try to reproduce this with the `temurin8` cask? `brew install --cask homebrew/cask-versions/temurin8`

@carlocab I tried the adoptopenjdk8 is ok.

**Comment by carlocab** [comment] 2021-11-07 12:23
Great; you should do that. At the moment, there's nothing actionable here, because we have no way of reproducing your crash, so I'm closing this issue.

If you'd like it reopened please provide a minimal example that allows us to reproduce your crash.

**Closed by carlocab** 2021-11-07 12:23 UTC
Labels: bug

**Comment by JasonMing** [comment] 2021-11-09 06:24
@carlocab Is there any plan to push a new bottle for [openjdk@8](https://formulae.brew.sh/formula/openjdk@8) that rebuild on Monterey? That may fix the problem.

**Comment by carlocab** [comment] 2021-11-09 06:27
If it builds on Monterey, sure. My understanding is that it doesn't.

**Comment by JasonMing** [comment] 2021-11-09 07:47
Thanks, I'll try to reproduce this issue.

**Comment by ontzuevanhussen** [comment] 2021-11-21 14:07
I have same problem.

```
No configurations found for /private/tmp/openjdkA8-20211121-13674-852fzh/jdk8u312-ga/! Please run configure to create a configuration.
Makefile:55: *** Cannot continue.  Stop.

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
openjdk@11 11.0.13 https://github.com/Homebrew/homebrew-core/pull/87638
openjdk: bump revision for gcc, fixes RPATH issue https://github.com/Homebrew/homebrew-core/pull/89642
OpenJDK is somewhat broken on newer MacOS instances, console is flooded with errors when using JMeter, AdoptOpenJDK has no issues https://github.com/Homebrew/homebrew-core/issues/66953
```

**Comment by carlocab** [comment] 2021-11-21 14:26
That's not the same problem at all. You're encountering an error building `openjdk@8`. This issue is about a crash while using `openjdk@8`.
