### ISSUE TITLE
weechat failed to build on 10.11.6

### ISSUE THREAD

**Issue by lparsons** [Homebrew/homebrew-core#8452] opened 2017-01-03 21:02 UTC
`brew gist-logs weechat`: https://gist.github.com/995b82718c70369eb2bf60dbe6806fe2

**Comment by ilovezfs** [comment] 2017-01-05 09:51
Yup.

**Comment by marmot1123** [comment] 2017-01-05 09:52
I had the same situation.
I solved the situation by removing `anaconda` from my `$PATH`.
Concretely, I search in `~/.zshrc`, `~/.bashrc`, and `~/.bash_profile`.
Anaconda may add an export sentence to `~/.bash_profile` when it was installed.
Then, I executed `brew upgrade weechat` and I could upgrade weechat.

**Comment by ilovezfs** [comment] 2017-01-05 09:52
nope, no anaconda in sight here.

**Comment by ilovezfs** [comment] 2017-01-05 09:53
Appears to be caused by `--with-ruby `

**Comment by ilovezfs** [comment] 2017-01-05 10:51
Should be fixed if you brew update.

**Closed** 2017-01-05 10:51 UTC
Labels: bug

**Comment by sprig** [comment] 2017-01-07 12:45
Not for me: https://gist.github.com/anonymous/15ef53e0311437d7bc6f60f604556d0d

**Comment by kejadlen** [comment] 2017-01-08 20:46
I still have this issue as well. Is this because I only use Ruby through `chruby` and don't `brew install ruby`?

**Comment by ilovezfs** [comment] 2017-01-09 02:05
@kejadlen probably.

**Comment by kejadlen** [comment] 2017-01-09 03:13
Oof. Is there a way to coax weechat into looking at the right include path?

**Comment by sprig** [comment] 2017-01-09 09:22
P.S.
{{{brew update && brew upgrade && brew cleanup}}} fixed the problems in my case. Mysterious problem...
