### ISSUE TITLE
packer 1.8.6 requests acccess to Calendar/Photos/etc.

### ISSUE THREAD

**Issue by kevemueller** [Homebrew/homebrew-core#125635] opened 2023-03-14 16:18 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0c1031f2fd71016f0f5df699caaed384487bfb16
Last commit: 4 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9827c70dc93eaaa4fd79e59b824accdbdaf3855c
Core tap last commit: 4 weeks ago
Core tap branch: master
Core tap JSON: 14 Mar 16:08 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

```
Your system is ready to brew.
```
```


### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

```brew install packer ``` to use packer.io


### What happened (include all command output)?

When launching the ```packer``` binary from Terminal MacOS asked for permissions to access Calendar, Photos etc.


### What did you expect to happen?

I don't expect this program to access my Calendar, Photos etc. and consider this a security/privacy threat.

I have removed the community version and installed the software from HashiCorp's site: ```brew install hashicorp/tap/packer``` 

The binary instaled from this site does not request any of the special folder permissions.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install packer
```

**Comment by SMillerDev** [comment] 2023-03-14 16:20
What happens if you build the software from source. Will it still request the permissions?

**Comment by chenrui333** [comment] 2023-04-08 19:20
I did not observe any access requests when launched in my local?

```
$ brew install packer
==> Fetching packer
==> Downloading https://ghcr.io/v2/homebrew/core/packer/manifests/1.8.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:03609bacb2a233f609b222d7420854d731765b9d2b1f6421a4494a784eecfb00
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:03609bacb2a233f609b222d7420854d731765b9d2b1f6421a4494a784eecfb00?se=2023-04-08T19%3A25
######################################################################## 100.0%
==> Pouring packer--1.8.6.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/packer/1.8.6: 8 files, 163.7MB

$ packer
Usage: packer [--version] [--help] <command> [<args>]

Available commands are:
    build           build image(s) from template
    console         creates a console for testing variable interpolation
    fix             fixes templates from old versions of packer
    fmt             Rewrites HCL2 config files to canonical format
    hcl2_upgrade    transform a JSON template into an HCL2 configuration
    init            Install missing plugins or upgrade plugins
    inspect         see components of a template
    plugins         Interact with Packer plugins and catalog
    validate        check that a template is valid
    version         Prints the Packer version
    
$ packer fmt
Usage: packer fmt [options] [TEMPLATE]

  Rewrites all Packer configuration files to a canonical format. Both
  configuration files (.pkr.hcl) and variable files (.pkrvars.hcl) are updated.
  JSON files (.json) are not modified.

  If TEMPLATE is "." the current directory will be used.
  If TEMPLATE is "-" then content will be read from STDIN.

  The given content must be in Packer's HCL2 configuration language; JSON is
  not supported.

Options:
  -check        Check if the input is formatted. Exit status will be 0 if all
                 input is properly formatted and non-zero otherwise.

  -diff         Display diffs of formatting change

  -write=false  Don't write to source files
                (always disabled if using -check)

  -recursive     Also process files in subdirectories. By default, only the
                 given directory (or current directory) is processed.

$ packer version
Packer v1.8.6    
```

Did I miss anything?

**Comment by carlocab** [comment] 2023-04-08 19:40
Closing because this is not reproducible.

**Closed by carlocab** 2023-04-08 19:40 UTC
Labels: bug
