### ISSUE TITLE
vim is broken with non-standard brew prefix after the last update

### ISSUE THREAD

**Issue by xeron** [Homebrew/homebrew-core#35236] opened 2018-12-18 23:32 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`vim` is broken for me after the last update: https://github.com/Homebrew/homebrew-core/pull/35157. Example:
```
$ vim .vimrc
Error detected while processing /Users/ilarionov/.vimrc:
line  216:
E484: Can't open file /usr/local/share/vim/syntax/syntax.vim
Press ENTER or type command to continue
```
line  216:
```
syntax on
```
real syntax file location:
```
/opt/brew/share/vim/vim81/syntax/syntax.vim
```

I didn't test with the standard brew prefix but looks like it shouldn't be installed using bottle if prefix is non-standard.

- Step-by-step reproduction instructions:
* install brew into non-standard prefix
* `brew install vim`
* `echo 'syntax on' > ~/.vimrc`
* try to use it

```
$ brew config
HOMEBREW_VERSION: 1.8.6-14-ga2b4d4a
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a2b4d4aac294ec0872cd84d44f65bd5bd507e166
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 24e0c2fce4f2226c77ffb7b7c7d8764200556c58
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /opt/brew
HOMEBREW_REPOSITORY: /opt/brew
HOMEBREW_CELLAR: /opt/brew/Cellar
HOMEBREW_AWS_ACCESS_KEY_ID: set
HOMEBREW_AWS_SECRET_ACCESS_KEY: set
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /opt/brew/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_192, 1.8.0_144, 1.7.0_80
macOS: 10.14.2-x86_64
CLT: N/A
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
```

**Comment by xeron** [comment] 2018-12-18 23:46
Probably related to the fact that `vim` is a bottle now and not to the update.

`brew install vim --build-from-source` fixes the issue.

**Comment by SMillerDev** [comment] 2018-12-19 07:21
Vim has been a bottle for a very long time already. If you want to run software in a non-standard location you'll always have to compile from source though since homebrew really isn't made for that.

**Comment by xeron** [comment] 2018-12-19 21:17
I'm pretty sure homebrew has a way to determine if bottle is going to work or no. `vim` was always compiling from source for me (without me specifying `--build-from-source`) and always worked with my setup in `/opt/brew` and only stopped working after this commit – https://github.com/Homebrew/homebrew-core/commit/7de8bd0af7d34ef91b2a660de3649928c8315d96.

**Comment by MikeMcQuaid** [comment] 2018-12-20 08:22
Can you reproduce this in a prefix that's not under `/opt`? I strongly suspect that's your issue here. Closing this out until we have something reproducible.

**Comment by xeron** [comment] 2018-12-20 10:08
I really don't care, I don't mind compiling it from the source, just wanted to report a regression.

This worked before with homebrew prefix under `/opt/brew` and I pointed to the commit which broke it. It's up to you if you want to change that formula to enforce compiling if prefix is not standard.

**Comment by Forcer78** [comment] 2018-12-27 23:59
> Can you reproduce this in a prefix that's not under `/opt`? I strongly suspect that's your issue here. Closing this out until we have something reproducible.

My prefix is `~/homebrew`. I reproduce this issue.

**Comment by Forcer78** [comment] 2018-12-29 18:39
Issue persists with today's 8.1.0650 release.

Commenting out the `cellar :any` line as mentioned in https://github.com/Homebrew/homebrew-core/issues/35236#issuecomment-448746949 builds correctly from source.

**Comment by jkulesza** [comment] 2019-01-04 21:51
> Issue persists with today's 8.1.0650 release.
> 
> Commenting out the `cellar :any` line as mentioned in [#35236 (comment)](https://github.com/Homebrew/homebrew-core/issues/35236#issuecomment-448746949) builds correctly from source.

I can reproduce both the problem and the workaround.

**Comment by igas** [comment] 2019-01-05 09:36
to be clear, you don't need to edit it to build from source, you can use flag `--build-from-source` or `-s`

**Comment by Forcer78** [comment] 2019-01-06 00:59
> to be clear, you don't need to edit it to build from source, you can use flag `--build-from-source` or `-s`

I used that flag to install the 8.1.0600_2 release. My (hazy) recollection is that the 8.1.0650 release then clobbered the working install with the broken bottle, after which I edited the formula.

**Comment by igas** [comment] 2019-01-06 02:07
When you build from source bottle is not involved.

**Comment by MikeMcQuaid** [comment] 2019-01-21 19:55
Could someone more familiar with `vim` than me output the `VIM` and `VIMRUNTIME` variables for your install? I believe `:!echo $VIM` and `:!echo $VIMRUNTIME` are how you do this.

**Comment by MikeMcQuaid** [comment] 2019-01-21 20:20
Never mind: I think I've found the issue. Once https://github.com/Homebrew/brew/pull/5577 is merged and we rebottle `vim` I believe this should be fixed.

**Comment by MikeMcQuaid** [comment] 2019-01-21 20:51
> From what I see: my understanding is that I'll need to develop my own "tap" for this? Ultimately, all I want in `vim` is the aforementioned flag. Is that so, or have I misunderstood something?

@jkulesza Yes, sorry. We cannot enable that option by default as it requires X11 which hasn't been shipped by default with macOS for many years.

**Comment by jkulesza** [comment] 2019-01-21 20:53
> > From what I see: my understanding is that I'll need to develop my own "tap" for this? Ultimately, all I want in `vim` is the aforementioned flag. Is that so, or have I misunderstood something?
> 
> @jkulesza Yes, sorry. We cannot enable that option by default as it requires X11 which hasn't been shipped by default with macOS for many years.

Understood.  I'll pursue building my own tap for this.  Thanks.

**Closed** 2019-01-22 08:19 UTC
