### ISSUE TITLE
R 4.2.2 Segmentation Fault (Linux)

### ISSUE THREAD

**Issue by jwhite007** [Homebrew/homebrew-core#114845] opened 2022-11-05 16:37 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.8-46-g9b318a5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9b318a54d0026f9b1dcb836702c1f58e75b57c6b
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1b38a3b5d80b90f4cff3507eefe1863096d3685e
Core tap last commit: 26 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/env vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /home/linuxbrew/.logs/Homebrew
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_TEMP: /home/linuxbrew/.temp
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit skylake
Clang: N/A
Git: 2.38.1 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.61.1 => /bin/curl
Kernel: Linux 4.18.0-372.26.1.el8_6.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux release 8.6 (Ootpa) (Ootpa)
Host glibc: 2.28
/usr/bin/gcc: 8.5.0
/usr/bin/ruby: N/A
glibc: 2.35_1
gcc@11: 11.3.0
gcc: 12.2.0
xorg: N/A

$ brew dr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  elinks
  gcc@5
  isl@0.18

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /toolbox/bioinformatics/.pyenv/shims/python3-config
  /toolbox/bioinformatics/.pyenv/shims/icu-config
  /toolbox/bioinformatics/.pyenv/shims/ncurses6-config
  /toolbox/bioinformatics/.pyenv/shims/python-config
  /toolbox/bioinformatics/.pyenv/shims/ncursesw6-config
  /toolbox/bioinformatics/.pyenv/shims/python3.9-config

Warning: Formulae which link to GCC through a versioned path were found. These formulae
are prone to breaking when GCC is updated. You should `brew reinstall` these formulae:
  gcc@11

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo bioinformatics_group/local-pyenv) checkout
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Upgrade R (4.2.1_4 -> 4.2.2), because I want the latest version.

Two R dependencies were also upgraded, libxext (1.3.4 -> 1.3.5) and openssl@1.1 (1.1.1q > 1.1.1s).

R and two dependencies above were all poured from bottles.

I did not resolve all of the warnings from ```brew dr``` as most of the warnings were there when a functional R (4.2.1) was installed.

I did continue to resolve the following.
> Warning: Formulae which link to GCC through a versioned path were found. These formulae
are prone to breaking when GCC is updated. You should `brew reinstall` these formulae:
  gcc@11

I proceeded to reinstall gcc@11 and received the following.
> Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall gcc@11

I conducted ```brew postinstall gcc@11``` and received the same warning.

After reinstallation of gcc@11, I did the following.
```brew reinstall libxext openssl@1.1 r```

Executing R still results in segmentation fault

### What happened (include all command output)?

```
$ R
Segmentation fault
```

### What did you expect to happen?

No segmentation fault.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
This is an issue with an application poured from bottle not a direct brew issue.
```

**Comment by jwhite007** [comment] 2022-11-12 16:36
Of course installing with ```--build-from-source```, fixes it; however, the bottle build is still broken at least on my system.

**Comment by jwhite007** [comment] 2022-11-26 19:03
I had to do a fresh installation of Linuxbrew for other reasons and am still getting a segmentation fault with the bottle for R. In addition, now when I ```brew install r --build-from-source```, I get the following.

```
$ brew install r --build-from-source
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

==> Downloading https://cran.r-project.org/src/base/R-4/R-4.2.2.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/2cc35deb74316557f5bf075f5d775cd8214dbd01e31595613b6c366b27fec93f--R-4.2.2.tar.gz
Error: An exception occurred within a child process:
  CompilerSelectionError: r cannot be built with any available compilers.
Install Clang or run `brew install gcc`.
```
but look:
```
$ brew info gcc
==> gcc: stable 12.2.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0 (1,623 files, 306.5MB) *
  Poured from bottle on 2022-11-26 at 12:33:32
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb
License: GPL-3.0-or-later with GCC-exception-3.1
==> Dependencies
Required: gmp ✔, isl ✔, libmpc ✔, mpfr ✔, zstd ✔, zlib ✔, binutils ✔, glibc ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 98,233 (30 days), 381,536 (90 days), 1,502,575 (365 days)
install-on-request: 49,356 (30 days), 189,110 (90 days), 709,788 (365 days)
build-error: 514 (30 days)
```

**Comment by cho-m** [comment] 2022-12-09 02:45
I think this should be same root cause as your other issue (#116841)? If so, we should close this issue since there is more discussion/traction in other issue.

**Closed** 2022-12-09 17:25 UTC
Labels: bug, linux
