### ISSUE TITLE
brew install sip error

### ISSUE THREAD

**Issue by weather319** [Homebrew/homebrew-core#9715] opened 2017-02-07 07:24 UTC
READ THIS: http://docs.brew.sh/Troubleshooting.html

**And this is the log from /user/xxx/Library/Logs/Homebrew/sip/01.python:**

2017-02-07 15:14:43 +0800

python
configure.py
--deployment-target=10.10
--destdir=/usr/local/Cellar/sip/4.19/lib/python/site-packages
--bindir=/usr/local/Cellar/sip/4.19/bin
--incdir=/usr/local/Cellar/sip/4.19/include
--sipdir=/usr/local/share/sip

HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: 70f53358683dce182fc8fc1f8d08c9c9e510f0e7
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.5.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: N/A
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_65
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python3/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.10
PKG_CONFIG_PATH: /usr/local/opt/python3/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/python3/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/bin

How could I install the sip? I had tried to install by myself use the code in sip file:

python3 configure.py --deployment-target=10.10 --destdir=/usr/local/Cellar/sip/4.19/lib/python/site-packages --bindir=/usr/local/Cellar/sip/4.19/bin --incdir=/usr/local/Cellar/sip/4.19/include --sipdir=/usr/local/share/sip

I got:

This is SIP 4.19 for Python 3.6.0 on darwin.
The SIP code generator will be installed in /usr/local/Cellar/sip/4.19/bin.
The sip module will be installed in
/usr/local/Cellar/sip/4.19/lib/python/site-packages.
The sip.pyi stub file will be installed in
/usr/local/Cellar/sip/4.19/lib/python/site-packages.
The sip.h header file will be installed in /usr/local/Cellar/sip/4.19/include.
The default directory to install .sip files in is /usr/local/share/sip.
MacOS/X deployment target is 10.10.
Creating siplib/sip.h...
Creating siplib/siplib.c...
Creating siplib/siplib.sbf...
Creating sipconfig.py...
Creating top level Makefile...
Creating sip code generator Makefile...
Creating sip module Makefile...

THEN I FOUND THERE WAS NOTHING NEW IN THOSE FILES!!!

**Comment by weather319** [comment] 2017-02-07 07:31
After commit this issue , I realized that I forgot to run 'make &&make install'.

So I run the code and 'brew link sip' 

Now I continue to install my octave, but I still not understand why the problem happened.

**Comment by weather319** [comment] 2017-02-07 07:41
Now the problem comes out again when I run 'brew install pyqt5'

It seems that brew install the sip again.

==> Installing dependencies for pyqt5: sip
==> Installing pyqt5 dependency: sip
==> Using the sandbox
==> Downloading

python configure.py --deployment-target=10.10 --destdir=/usr/local/Cellar/si
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/sip/01.python:
2017-02-07 15:35:46 +0800

python
configure.py
--deployment-target=10.10
--destdir=/usr/local/Cellar/sip/4.19/lib/python/site-packages
--bindir=/usr/local/Cellar/sip/4.19/bin
--incdir=/usr/local/Cellar/sip/4.19/include
--sipdir=/usr/local/share/sip


READ THIS: http://docs.brew.sh/Troubleshooting.html

'brew info sip' and I got:

sip: stable 4.19 (bottled), HEAD
Tool to create Python bindings for C and C++ libraries
https://www.riverbankcomputing.com/software/sip/intro
/usr/local/Cellar/sip/4.19 (68B) *
  Built from source
/usr/local/Cellar/sip/4.19.tmp (6 files, 608.7K)
  Built from source
==> Requirements
Optional: python3 ✔
==> Options
--with-python3
	Build with python3 support
--without-python
	Build without python2 support
--HEAD
	Install HEAD version
==> Caveats
The sip-dir for Python is /usr/local/share/sip.


Is there anyone may help me ?

**Comment by ilovezfs** [comment] 2017-02-07 07:58
```
mkdir ~/Documents/brew-2017-02-06
sudo mv /usr/local ~/Documents/brew-2017-02-06
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install octave
```

**Comment by ilovezfs** [comment] 2017-02-07 11:27
I'm assuming that fixed it?

**Comment by weather319** [comment] 2017-02-08 04:19
@ilovezfs 

Finally, I fixed this problem.
First, I tried to reinstall homebrew but it didn't work. So I force on the sip install error.

I found that homebrew will reinstall the sip every time even I have installed the sip by myself. There is something wrong in sip installing. 

After I entry the 'brew install sip --with-python3' and 'brew install pyqt5' but error again.
Homebrew will rename the sip file to sip.tmp and reinstall it but not successful.

/usr/local/Cellar/sip/4.19 (68B) *
Built from source
/usr/local/Cellar/sip/4.19.tmp (6 files, 608.7K)

'brew install sip --without-python --with-python3' and 'brew install pyqt5', everything was ok!

/usr/local/Cellar/sip/4.19 (12 files, 940.7K) *
  Built from source on 2017-02-07 at 16:15:52 with: --without-python --with-python3


Maybe anyone else could test this problem, I doubt if it is wrong with homebrew.

**Comment by ilovezfs** [comment] 2017-02-08 05:42
```
iMac-TMP:~ joe$ brew install --with-python3 sip
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/pyqt/sip/sip-4.19/sip-4.19.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/sip-4.19.tar.gz
==> python configure.py --deployment-target=10.11 --destdir=/usr/local/Cellar/sip/4.19/lib/python2.7/
==> make
==> make install
==> make clean
==> python3 configure.py --deployment-target=10.11 --destdir=/usr/local/Cellar/sip/4.19/lib/python3.6
==> make
==> make install
==> make clean
==> Caveats
The sip-dir for Python is /usr/local/share/sip.
==> Summary
🍺  /usr/local/Cellar/sip/4.19: 16 files, 1.1M, built in 5 seconds
iMac-TMP:~ joe$ brew install pyqt5
==> Installing dependencies for pyqt5: qt@5.7
==> Installing pyqt5 dependency: qt@5.7
==> Downloading https://homebrew.bintray.com/bottles/qt@5.7-5.7.1.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/qt@5.7-5.7.1.el_capitan.bottle.tar.gz
==> Pouring qt@5.7-5.7.1.el_capitan.bottle.tar.gz
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local.

Older version of qt5

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt@5.7/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/qt@5.7/lib
    CPPFLAGS: -I/usr/local/opt/qt@5.7/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/qt@5.7/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/qt@5.7/5.7.1: 8,273 files, 242.6M
==> Installing pyqt5 
==> Downloading https://homebrew.bintray.com/bottles/pyqt5-5.7.1_1.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/pyqt5-5.7.1_1.el_capitan.bottle.tar.gz
==> Pouring pyqt5-5.7.1_1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/pyqt5/5.7.1_1: 830 files, 26M
iMac-TMP:~ joe$
```

Closing this since I cannot reproduce the issue.

**Closed by ilovezfs** 2017-02-08 05:42 UTC
