### ISSUE TITLE
cvs fails with 'cannot get working directory' on Catalina

### ISSUE THREAD

**Issue by martinproulx** [Homebrew/homebrew-core#46066] opened 2019-11-01 14:02 UTC
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Martins-2017-MacBook-Pro:PDT proulxm$ brew update
Already up-to-date.
Martins-2017-MacBook-Pro:PDT proulxm$ brew doctor
Your system is ready to brew.
Martins-2017-MacBook-Pro:PDT proulxm$ brew gist-logs cvs
Error: No logs.
Martins-2017-MacBook-Pro:PDT proulxm$ 

## What you were trying to do (and why)

Just trying to perform updates using CVS.

## What happened (include command output)

Martins-2017-MacBook-Pro:PDT proulxm$ cvs -q update
cvs [update aborted]: cannot get working directory: No such file or directory
Martins-2017-MacBook-Pro:PDT proulxm$ 

<details>
  <summary>Command output</summary>
  <pre>

  cvs [update aborted]: cannot get working directory: No such file or directory

  </pre>
</details>

## What you expected to happen

CVS to work as expected.

## Step-by-step reproduction instructions (by running `brew install` commands)

Information about the problem and fix can be found here: https://stackoverflow.com/questions/58329787/cvs-broken-on-macos-catalina-cannot-get-working-directory
and here: https://discourse.brew.sh/t/catalina-released-any-major-issues/5822/16

**Comment by alebcay** [comment] 2019-11-14 17:31
This should have been fixed in #45779. Please shout here or open a new issue if the issue is still present.

**Closed by alebcay** 2019-11-14 17:31 UTC
