### ISSUE TITLE
How to set Go version in formula?

### ISSUE THREAD

**Issue by bep** [Homebrew/homebrew-core#17978] opened 2017-09-12 08:27 UTC
We have an issue in Hugo related to Go 1.9, so I want to cut a new release on Go 1.8.3, but I have no control of the Homebrew formula:

https://github.com/Homebrew/homebrew-core/blob/b6a6d50ee2b69721647069e7db435d634a858213/Formula/hugo.rb

Not sure how to set Go version to use to build.

/cc @ilovezfs

**Comment by ilovezfs** [comment] 2017-09-12 09:04
@bep how can we test whether the issue is/is not present?

**Comment by bep** [comment] 2017-09-12 09:56
We need to control which Go version is in use in any case. It makes it very hard to support all of these builds without knowing that. 

So to conclude: 

I'm going to release Hugo 0.27.1, but I have to know that this is built on Go 1.8.3 on all "known" builds (snap, brew, binaries on GitHub).

**Comment by ilovezfs** [comment] 2017-09-12 10:02
@bep currently there are zero formulae (out of the 222 that use Go) that build with a versioned Go formula, and I'd really like to keep it that way. Is there a timetable for when the Go 1.9 issue is going to be fixed?

**Comment by bep** [comment] 2017-09-12 10:10
When I say that we need to know which Go version is in use, I'm not only talking about this issue. It is a general concern about knowing exactly what we release, and being able to change that if needed. The Go 1.9 issue will maybe be fixed in Go 1.9.1 if someone is willing to spend time on it. All of which is weeks/months (I don't know) in the future.

As I see it there are a couple of options:

1) Set go version in formula
2) Build brew from the binary on the Hugo repo.
3) Remove Hugo from homebrew-core and set up a brew-tap on the Gohugo GitHub org.

The last would be very sad (Brew is the main install method for Hugo), but at least that will give us the controll we need.

**Comment by ilovezfs** [comment] 2017-09-12 10:17
I appreciate that you may see it as a general concern, but as a rule we do not let formulae pin specific versions of anything. As a temporary measure, we will sometime use a versioned formula until the specific issue is fixed upstream. For Go I'm particularly reluctant to open up that Pandora's box, since it has not been necessary so far. I'm willing to make an exception for Hugo as long as it's understood that this is only temporary and as long as there's a concrete plan for how the issue is going to be fixed with the current version of Go.


(1) is possible subject to what I described above.
(2) is a non-option as we don't allow CLI tools to install binaries in Homebrew. Everything must build from source.
(3) is a non-option as we have too many people using the formula to remove it (over 8,100 installs in the 30 days alone).

**Comment by bep** [comment] 2017-09-12 11:27
Thanks for your input. Let us let this linger for a little. I have not gotten many complaints about this, and I may find a solution on the Hugo side once I understand it. 

Hugo strives to always release with the latest Go version, so this is not the normal case.

8100 installs are impressive. Are these stats available online somewhere?

**Comment by ilovezfs** [comment] 2017-09-12 11:31
>Thanks for your input. Let us let this linger for a little. I have not gotten many complaints about this, and I may find a solution on the Hugo side once I understand it.

Sounds good to me :)

>Hugo strives to always release with the latest Go version, so this is not the normal case.

:+1:

>8100 installs are impressive. Are these stats available online somewhere?

Currently we've published https://brew.sh/analytics/ and we may be able to add more on http://formulae.brew.sh/ in the near-ish future.

**Comment by bep** [comment] 2017-09-13 11:38
I have fixed it here:

https://github.com/gohugoio/hugo/releases/tag/v0.27.1

**Comment by ilovezfs** [comment] 2017-09-13 11:40
Awesome! Thanks, @bep. Here's a PR for 0.27.1: https://github.com/Homebrew/homebrew-core/pull/18032.

**Comment by ilovezfs** [comment] 2017-09-13 11:49
I've now shipped 0.27.1 :)

Thanks for reporting this @bep.

**Closed by ilovezfs** 2017-09-13 11:49 UTC
Labels: go, upstream issue
