### ISSUE TITLE
"imagemagick --with-perl" fails when trying to install Perlmagick through cpanm (fails in testing step)

### ISSUE THREAD

**Issue by openmedi** [Homebrew/homebrew-core#1620] opened 2016-06-01 12:51 UTC
I am using OSX 10.11.4. I try to get perlmagick working within the brew universe. I installed `perl` (version perl-5.24.0) and `imagemagick --with-perl` (version imagemagick-6.9.4-5) after updating/upgrading my brew install. The install went down fine, but when using cpanm to install Image::Magick, I get an error. [Here's the build.log as a gist.](https://gist.github.com/openmedi/96b386d8cc9238b7219b4919dea19bdf)

One suspicion  I have is that, since I use [pkgsrc](http://pkgsrc.joyent.com/) to stay up to date with one package brew doesn't offer, that this might be interfering somehow (not the package itself, but that the two package managers don't like each other).

I checked also `which perl`, which gave me: `/usr/local/bin/perl`, so it should use the brewed perl.

What else should I check? Thanks in advance!

**Comment by DomT4** [comment] 2016-06-01 14:55
I'm not sure that particular error is directly related to us. I removed Homebrew's Perl from my system and still ran right into it.

When I looked into this before I came to the conclusion building from `cpanm install Image::Magick` isn't actually supported anymore because it's considerably behind the latest release upstream and the [website](https://www.imagemagick.org/script/perl-magick.php) no longer mentions how to install it outside of the tarball at all.

I'm a bit confused why you're trying to do `brew install imagemagick --with-perl` and then reinstall `Image::Magick` directly afterwards? Can you elaborate on that a bit?

I wonder if this is the confusion: Because Perl enjoys being a bit frustrating it often installs modules into specifically versioned directories, for example `brew install imagemagick --with-perl` on OS X 10.11 will result in the Perl module `Image::Magick` being installed in:

```
/usr/local/lib/perl5/site_perl/5.18.2/darwin-thread-multi-2level
```

Which works, if you're running the system Perl & presuming the system Perl is never updated beyond 5.18.2:

```bash
export PERL5LIB="/usr/local/lib/perl5/site_perl":$PERL5LIB

/usr/bin/perl -e "use Image::Magick; print Image::Magick->QuantumDepth"
16
```

That doesn't work if you're running Homebrew's Perl because `5.24.0` doesn't check and may not be compatible with prior versions installed in `5.18.2`, for example. I'll try and tweak our Perl & Imagemagick formula to behave a bit less frustratingly when they co-exist.

**Comment by openmedi** [comment] 2016-06-02 16:58
To be honest, I don't understand completely what I'm doing either. ;) I'll tell you what I thought I was doing:

I want to use a brewed perl because then it gets updates and stuff, same goes for imagemagick. My reason for wanting perl + imagemagick on my system in the first place is so I can use it with [ikiwiki](http://ikiwiki.info/), a particularly full featured wiki compiler. One of it's features is the [img directive](http://ikiwiki.info/ikiwiki/directive/img/) which can display pictures on the wiki pages I write. But it can also show pages from a PDF file inline without me having to do the conversion, renaming, etc. by hand. For this to work imagemagick had to be installed. So I installed perl and imagemagick through brew, as I said. But it didn't work. So I poked around a bit and saw that there was the `imagemagick --with-perl` option, which I used then. Still, it didn't work. So I though, maybe, I need to "build/install" imagemagick within the perl ecosystem through cpanm. This last part I inferred from the comment in the brew formula of `imagemagick` which I will quote here:

```
option "with-perl", "enable build/install of PerlMagick"
```

**Comment by DomT4** [comment] 2016-06-04 04:01
https://github.com/Homebrew/homebrew-core/pull/1704 should make life easier, once merged.

**Comment by DomT4** [comment] 2016-06-04 14:34
> So I poked around a bit and saw that there was the imagemagick --with-perl option, which I used then. Still, it didn't work.

I suspect this is because the `INC` path didn't include where the Perl module from ImageMagick/PerlMagick was actually placed. I couldn't reproduce any other failure locally.

> This last part I inferred from the comment in the brew formula of imagemagick which I will quote here:

I cleaned up the option wording here to make it less ambiguous. That option builds and installs `PerlMagick`, no further steps required except a little environmental tweaking in some cases.

I've made some fairly major changes to our Perl system, and just merged 'em. If you do `brew update && brew upgrade perl && brew reinstall imagemagick` followed by:

```
perl "use Image::Magick; print Image::Magick->QuantumDepth"
```
It should "just work" now ©️.

**Comment by openmedi** [comment] 2016-06-06 11:39
Hm. What now?

```
martin@Macbook-openmedi:~$ perl "use Image::Magick; print Image::Magick->QuantumDepth"
Can't open perl script "use Image::Magick; print Image::Magick->QuantumDepth": No such file or directory
martin@Macbook-openmedi:~$ which perl
/usr/local/bin/perl
```

**Comment by DomT4** [comment] 2016-06-06 11:40
Oops, that's my fault, sorry. You want:

```
perl -e "use Image::Magick; print Image::Magick->QuantumDepth"
```

**Comment by openmedi** [comment] 2016-06-07 11:11
Thanks! It works.

**Comment by DomT4** [comment] 2016-06-07 11:28
Great! Thank you for reporting this.

**Closed by DomT4** 2016-06-07 11:28 UTC
