### ISSUE TITLE
Irssi broken build on ARM mac

### ISSUE THREAD

**Issue by 676339784** [Homebrew/homebrew-core#68856] opened 2021-01-12 08:05 UTC
# Irssi broken build on ARM mac

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
  - [`brew config`](https://gist.github.com/676339784/bcce4f455d5f1761fd92dd0b04551866)
  - `brew doctor`: Your system is ready to brew.

## What you were trying to do (and why)

Install irssi on ARM mac

## What happened (include command output)

Installation is functional but there's something wrong with the build process: see [related issue for irssi](https://github.com/irssi/irssi/issues/1238). To summarize, there's something wrong with the brew formula that causes irssi output to [look janky](https://user-images.githubusercontent.com/24735903/101548190-585eea80-39a3-11eb-94fd-1ac6dd8d3f83.png), perhaps due to terminfo.

## What you expected to happen

Functional irssi

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install irssi
irssi
```

Results in broken irssi

**Comment by carlocab** [comment] 2021-01-12 12:23
`irssi` works just fine for me. At the very least, I can't seem to reproduce the problem you're having.

>ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Please don't check the boxes without actually doing what they list.

**Comment by MikeMcQuaid** [comment] 2021-01-12 16:49
Closing until reproducible or at least providing logs.

**Comment by MikeMcQuaid** [comment] 2021-01-12 16:49
Reopening after reading edit 😅

**Comment by 676339784** [comment] 2021-01-12 19:01
> ~`irssi` works just fine for me. At the very least, I can't seem to reproduce the problem you're having.~ Missed the subject line saying that this is on an ARM Mac.

Right. `irssi` builds fine on my Intel Mac, not on the ARM one.

> > ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
> > if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
> 
> Please don't check the boxes without actually doing what they list.

Sorry for not including this. The output of `brew gist-logs` is empty. Added `brew config` output in original post.

**Comment by carlocab** [comment] 2021-01-12 19:27
FYI, you still haven't done `brew doctor`. Please read the template more carefully.

That said, I think I already understand your problem (but please share `brew doctor` anyway in case I'm wrong):

Your core repo is broken. Same issue as https://github.com/Homebrew/brew/issues/10275. Please do
```
brew uninstall irssi glib openssl@1.1
brew update
brew instal irssi
```
and try again. If you have Homebrew `git` installed, do `brew uninstall git pcre2 gettext` before doing `brew update`. You can do `brew install git` again after.

**Comment by 676339784** [comment] 2021-01-12 19:32
> FYI, you still haven't done brew doctor. Please read the template more carefully.

Cool, updated, thank you. Hopefully that helps a lot!

> That said, I think I already understand your problem (but please share `brew doctor` anyway in case I'm wrong):
> 
> Your core repo is broken. Same issue as [Homebrew/brew#10275](https://github.com/Homebrew/brew/issues/10275). Please do
> 
> ```
> brew uninstall irssi glib openssl@1.1
> brew update
> brew instal irssi
> ```
> 
> and try again. If you have Homebrew `git` installed, do `brew uninstall git pcre2 gettext` before doing `brew update`. You can do `brew install git` again after.

I ran into this issue earlier so thanks for filing that issue. I followed the steps you attached again in any case. Unfortunately they do not fix the irssi misalignment problem.

**Comment by carlocab** [comment] 2021-01-12 19:33
What does `brew config` say now after doing `brew update`?

**Comment by 676339784** [comment] 2021-01-12 19:33
> What does `brew config` say now after doing `brew update`?

```
HOMEBREW_VERSION: 2.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7d7b703696d6d01eda4d4716257ccb0dbe3ab5a
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 551a468fe99d598df80b386d511a9ff9470555b9
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
Rosetta 2: false
```

**Comment by carlocab** [comment] 2021-01-12 19:35
Very strange. Ok. Try
```
brew uninstall irssi glib openssl@1.1
brew install -s irssi
```
This will install `irssi` from source, so may take a few minutes.

**Comment by 676339784** [comment] 2021-01-12 19:45
> Very strange. Ok. Try
> 
> ```
> brew uninstall irssi glib openssl@1.1
> brew install -s irssi
> ```
> 
> This will install `irssi` from source, so may take a few minutes. Let me know if that helps.

No luck unfortunately, really not sure why.

Separate from this, I tried compiling by source manually ([steps here](https://github.com/irssi/irssi/issues/1238#issuecomment-751283057)) but it wouldn't compile successfully, saying "configure: error: The OpenSSL library was not found."

**Comment by carlocab** [comment] 2021-01-12 19:50
Can you uninstall `irssi` again, then do
```
brew install -sv irssi
```
and put the full output of that into a gist to link back here.

**Comment by 676339784** [comment] 2021-01-12 19:53
> Can you uninstall `irssi` again, then do
> 
> ```
> brew install -sv irssi
> ```
> 
> and put the full output of that into a gist to link back here.

Yes, [gist available here](https://gist.github.com/676339784/4cb597a4e7803f1193d7ffd611e96b10)

**Comment by carlocab** [comment] 2021-01-12 20:11
Try setting
```
export CPPFLAGS=-I$(brew --prefix openssl)/include
export LDFLAGS=-L$(brew --prefix openssl)/lib
```
before compiling manually so the `configure` script can find `openssl`. Please also put the output of compiling from source manually in a gist and link it here so I can compare it with the output from Homebrew.

**Comment by 676339784** [comment] 2021-01-12 21:03
[Output of `./configure`](https://gist.github.com/676339784/5088accccfd35030cc500fdbd77dab63)
[Output of `make`](https://gist.github.com/676339784/df892bb88c130caa2af502f339412ca4)
[Output of `sudo make install`](https://gist.github.com/676339784/22fba462c09e26b8fa097a4b732589a9)

So this compiled but it still results in a misaligned irssi build, making it similar to the Homebrew build. But there's still a disparity between the end results of irssi builds on Intel vs Arm.

**Comment by carlocab** [comment] 2021-01-12 21:05
>So this compiled but it still results in a misaligned irssi build, making it similar to the Homebrew build.

Sounds like it's not a Homebrew issue then. You'll need to report this back at https://github.com/irssi/irssi/issues/1238.

**Comment by 676339784** [comment] 2021-01-12 21:05
Sounds good, will do. Thanks for your help!

**Comment by carlocab** [comment] 2021-01-12 21:14
However, I do have one final suggestion. Do

    brew edit irssi

and change the `uses_from_macos "ncurses"` to `depends_on "ncurses"`. Then, do

    HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall -s irssi

and let me know if that helps at all. (You'll want to do `cd $(brew --repo homebrew/core) && git restore .` to undo your changes after this, to restore your core repo back to its original state.)

**Comment by lewisrobbins** [comment] 2021-01-12 21:22
On a semi-related note why are we doing only one tests by shelling out? Irssi has unit tests?

See here:

```ruby
test do
   IO.popen("#{bin}/irssi --connect=irc.freenode.net", "w") do |pipe|
     pipe.puts "/quit\n"
     pipe.close_write
   end
```

**Comment by 676339784** [comment] 2021-01-12 21:23
> However, I do have one final suggestion. Do
> 
> ```
> brew edit irssi
> ```
> 
> and change the `uses_from_macos "ncurses"` to `depends_on "ncurses"`. Then, do
> 
> ```
> HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall -s irssi
> ```
> 
> and let me know if that helps at all. (You'll want to do `cd $(brew --repo homebrew/core) && git restore .` to undo your changes after this, to restore your core repo back to its original state.)

Thanks again for your help! However, doing `brew edit irssi` and then doing `HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall -s irssi` did not change anything on my side.

**Comment by carlocab** [comment] 2021-01-12 21:25
>did not change anything on my side.

Hmm, ok. I was thinking maybe the built-in `ncurses` was just too old and not behaving properly. However, this test at least rules this out. I'm more confident now that there's something wrong with the `irssi` source code.

>Irssi has unit tests?

We usually prefer simple functionality tests, rather than complete unit tests, just to catch build errors that weren't caught at build time.

**Comment by SMillerDev** [comment] 2021-01-12 22:11
> Irssi has unit tests?

Unit tests are to verify the software works as expected. Homebrew tests are to verify we build it succesfully.

**Comment by carlocab** [comment] 2021-01-13 23:09
Given:
1. this isn't an issue with Homebrew's packaging of `irssi`;
2. we don't have any local workarounds that might fix the problem; and,
3. the upstream issue seems to be underway,

there doesn't appear to be much need to keep this issue open. Closing it now, but let me know if circumstances change that necessitate reopening.

**Closed by carlocab** 2021-01-13 23:09 UTC
Labels: upstream issue
