### ISSUE TITLE
Qt's macdeployqt does not pull in plugins

### ISSUE THREAD

**Issue by minorsecond** [Homebrew/homebrew-core#74946] opened 2021-04-11 10:50 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 3.0.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8e11f03fa93b148e26044a331654241a2c307039
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a6d75c0c35ff5a8e1b4b9250c80ba44c3adf52b2
Core tap last commit: 14 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4

---------
Brew doctor:
Your system is ready to brew.
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I am attempting to package a C++ app with macdeployqt so that it runs on computers without Qt library installed.

### What happened (include all command output)?

The macdeployqt command successfully finishes without error, but does not copy anything from the plugins directory, which is necessary for the app to run. (When running from an installation installed from the Qt installer, it works as expected, but I'd rather use the homebrew installation).

### What did you expect to happen?

I expected the Contents/plugins directory to be created and populated with contents from /usr/local/Cellar/qt/share/qt/plugins

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Install qt by running `brew install qt`. Run `macdeployqt MYAPPPATH -always-overwrite -appstore-compliant` and then try to run the app. An error message stating that Qt plugins cannot be found appears.
```

**Comment by carlocab** [comment] 2021-04-11 13:37
Duplicate of #73019

**Closed** 2021-04-11 13:41 UTC
Labels: bug
