### ISSUE TITLE
virt-manager crashes without `--no-fork`

### ISSUE THREAD

**Issue by agowa** [Homebrew/homebrew-core#171604] opened 2024-05-13 21:16 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.2.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: 82c2e743a5bcea725f9ca1429e3e21c3088ff904
Last commit: 8 days ago
Core tap JSON: 13 May 19:22 UTC
Core cask tap JSON: 13 May 19:22 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.JwJcBb3uNG/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false

% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

start virt-manager without arguments.

### What happened (include all command output)?

Macos software crash report screen appears "Python quit unexpectedly."

The full crash dump is here: https://gist.github.com/agowa/41eda1ad3b07406269b583c7c010a2f5

### What did you expect to happen?

virt-manager opening

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install virt-manager`
2. `virt-manager`
```

**Comment by cho-m** [comment] 2024-05-15 18:13
> * [x]  I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

Closing as duplicate of #158497. As mentioned there, this needs to be analyzed upstream: https://github.com/virt-manager/virt-manager/issues/620

**Closed by cho-m** 2024-05-15 18:13 UTC
Labels: bug
