### ISSUE TITLE
Python quit unexpectedly: segmentation fault on macOS 13.0.1 Ventura

### ISSUE THREAD

**Issue by EugeneTorap** [Homebrew/homebrew-core#116415] opened 2022-11-22 10:24 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7391069d48805c786b1e9fe88edf795960321dc
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9cb074f14daee8ee043c7b0c8f1ab638ca27d7e9
Core tap last commit: 7 days ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I did't have problems on macOS 12 Monterey but after updating to macos 13.0.1 on M1 the crash issue appears.
When I run any python command without debug in console I have the next `Problem Report for Python`:

### What happened (include all command output)?

I've also created the issue on [developer.apple.com](https://developer.apple.com/forums/thread/719949) and there's ability to download the full logs there.

![image](https://user-images.githubusercontent.com/29536522/203288201-776d7ec9-71aa-401f-87c9-e24b62654b71.png)

### What did you expect to happen?

In https://github.com/python/cpython/issues/99663 CPython core developers said that:

> The crash happens in a 3th-party library after a call to exit(3), which makes it likely that this is not a problem with CPython itself.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) brew install python@3.10
2) run any large python command with DB or big unit test
```

**Comment by SMillerDev** [comment] 2022-11-22 12:55
I just ran `python3.10 -c "print('test')"` on an M1 Mac Mini and it worked fine. It also seems from your log that libarrow is failing.

**Comment by EugeneTorap** [comment] 2022-11-22 13:02
Can we update `libarrow` for python?

**Comment by EugeneTorap** [comment] 2022-11-22 13:09
In order to reproduce it on 100% need to run a large command with DB query execution or big unit test

**Comment by EugeneTorap** [comment] 2022-11-22 13:11
I've installed the python from official site and all works good!

**Comment by SMillerDev** [comment] 2022-11-22 14:03
Without a way to reproduce this I think I'll have to close this issue.

**Closed** 2022-11-22 14:17 UTC
Labels: bug

**Comment by dave4jr** [comment] 2022-12-02 06:03
Hey guys, I'm also getting that error on Homebrew Python 3.10.8. It's happening on the fastAPI uvicorn auto-reload. So to reproduce, I just hit save on my code and it pops up everytime.

**Comment by EugeneTorap** [comment] 2022-12-02 06:35
@dave4jr Hi, please install python 3.10 from official site and you will not have the such issue!

**Comment by dave4jr** [comment] 2022-12-02 08:27
@EugeneTorap Really wanted to keep it in homebrew since that's how I have the rest of my workflow. I updated to 3.11 and the error is gone!

**Comment by SMillerDev** [comment] 2022-12-02 08:39
Whiteout any minimal commands to reproduce this there's not much maintainers can do. Glad an update fixed it for you though.

**Comment by EugeneTorap** [comment] 2022-12-02 08:43
@SMillerDev Because it's very hard to reproduce it from the scratch
