### ISSUE TITLE
Byobu: Half-broken state out of the box e.g. F1 does not work

### ISSUE THREAD

**Issue by timothybasanov** [Homebrew/homebrew-core#39855] opened 2019-05-14 20:29 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

> Note: This is probably a duplicate for https://github.com/Homebrew/homebrew-core/issues/35291 and https://github.com/Homebrew/homebrew-core/issues/15987 or https://github.com/Homebrew/homebrew-core/pull/37479

Issue: After installing Byobu via HomeBrew some functionality e.g. help (F1) does not work.

Steps to reproduce:
1. `brew install byobu`
1. `byobu`
1. <kbd>F1</kbd>

Expected: Shows a help screen
Actual: Closes a current pane in tmux

Additional info:
```bash
> byobu-config
ERROR: Could not import the python snack module
```

This workaround no longer works due to snack issues:
1. Install Xcode from AppStore, run it once
1. `brew reinstall python@2 newt byobu`

> Note: This is an issue that is open for the past two years. It would be really nice to fix it.

Output before workaround is applied:
```bash
> brew gist-logs byobu
Error: No logs.

> brew config
HOMEBREW_VERSION: 2.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4f73e61649fcfc5aaa779c311e2514619ce01e7
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8c1f1304c3f0d6b419e54511b173ba7ed152e511
Core tap last commit: 3 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.hTgjBIieu8/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/tbasanov/Library/Logs/Homebrew
HOMEBREW_VISUAL: subl -w
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_202
macOS: 10.14.4-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: N/A
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11

> brew doctor
Your system is ready to brew.
```

**Comment by Moisan** [comment] 2019-06-20 14:43
It doesn't seem to be brew related but more [Mac related](https://unix.stackexchange.com/questions/490922/byobu-configuration-menu-escape-exit-always-closes-the-tab).

**Comment by timothybasanov** [comment] 2019-07-09 21:19
@Moisan Issue you mentioned is a different issue, this one is about `byobu-config` itself being broken. More specifically `byobu-config` causes python snack errors as mentioned in several tickets linked.

**Comment by iMichka** [comment] 2019-11-25 18:17
As @timothybasanov said above, this is a duplicate of  #35291 and #15987 or #37479, which has not been solved in 2 years. This issue here has been open since May. Nobody is working on this.
I am not sure this is a homebrew issue: we ship thousand of different formulae and most of the things just work out of the box. Maybe something non-standard is happening here, and I would like upstream to fix their build to make this work. But we as homebrew team don't have much more time to invest in this issue. Sorry.

**Closed by iMichka** 2019-11-25 18:17 UTC
