### ISSUE TITLE
brew install subversion --with-java failed to build . Mac eclipse 

### ISSUE THREAD

**Issue by lixhbs** [Homebrew/homebrew-core#33908] opened 2018-11-08 02:32 UTC
- [X] ran brew update and can still reproduce the problem?
- [X] ran brew doctor, fixed all issues and can still reproduce the problem?
- [X] ran brew gist-logs <formula> (where <formula> is the name of the formula that failed) and included the output link?
- [X] if brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

- What you were trying to do 
Build subversion 1.9.x in order to obtain the JavaHL libraries for Subclipse plug-in for Eclipse.
- What happened 
The build failed.

Log: https://gist.github.com/lixhbs/829938c4485a7c5316502a654d66f0d1    

Output:    
```
Lix:~ li$ brew install subversion --with-java
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion
Already downloaded: /Users/li/Library/Caches/Homebrew/downloads/891bd5f606e2553db3534719644e0fee38f62a2e8f0d048d11bbb3092e982904--subversion-1.10.2.tar.bz2
==> Patching
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Downloading https://www.apache.org/dyn/closer.cgi?path=serf/serf-1.3.9.tar.b
Already downloaded: /Users/li/Library/Caches/Homebrew/downloads/3f4e2cb0f268fb9db7a761edccb60bdbdacb9923f8b2140e8c0a30b6792958a6--serf-1.3.9.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.10.2/li
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion/1.10.2 --enable-optimize -
==> make
==> make install
==> make tools
==> make install-tools
==> make swig-py
==> make install-swig-py
==> make swig-pl
==> make install-swig-pl
==> make javahl
==> make install-javahl
==> make swig-rb EXTRA_SWIG_LDFLAGS=-L/usr/lib
Last 15 lines from /Users/li/Library/Logs/Homebrew/subversion/14.make:
2018-11-08 10:17:49 +0800

make
swig-rb
EXTRA_SWIG_LDFLAGS=-L/usr/lib

/bin/sh "/private/tmp/subversion-20181108-9780-1w9wurd/subversion-1.10.2/libtool" --tag=CC --silent --mode=compile none  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10  -I/private/tmp/subversion-20181108-9780-1w9wurd/subversion-1.10.2/subversion/bindings/swig/ruby/libsvn_swig_ruby -prefer-pic -c -o subversion/bindings/swig/ruby/svn_client.lo subversion/bindings/swig/ruby/svn_client.c
/private/tmp/subversion-20181108-9780-1w9wurd/subversion-1.10.2/libtool: line 1760: none: command not found
make: *** [subversion/bindings/swig/ruby/svn_client.lo] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Subversion 1.11.0 https://github.com/Homebrew/homebrew-core/pull/33530
subversion: enable i18n support https://github.com/Homebrew/homebrew-core/pull/33162
brew install subversion --with-java failed to build on 10.12.6 https://github.com/Homebrew/homebrew-core/issues/33856
```
- What you expected to happen
A successful build of subversion.

- Step-by-step reproduction instructions 
brew install subversion --with-java

**Comment by fxcoudert** [comment] 2018-11-08 07:59
Possibly a duplicate of https://github.com/Homebrew/homebrew-core/issues/33250
Can you run `clang --version` and report the output? It is possibly that you need to accept the Xcode licence with `sudo xcodebuild -license`.

**Comment by fxcoudert** [comment] 2018-11-08 08:00
Also a duplicate of #33856

**Closed by fxcoudert** 2018-11-08 08:00 UTC

**Comment by lixhbs** [comment] 2018-11-08 11:10
@fxcoudert 
```
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
