### ISSUE TITLE
gnm (binutils) fails on Mojave (and breaks gcc-8)

### ISSUE THREAD

**Issue by ggouaillardet** [Homebrew/homebrew-core#32516] opened 2018-09-28 01:00 UTC
When the `binutils` formula is not installed, `gcc-8` works just fine

```
KA15-002: gilles$ cat conftest.c 
int main(int argc, char *argv[]) {
    return 0;
}
KA15-002:ompi-master-gcc8 gilles$ gcc-8 conftest.c 
KA15-002:ompi-master-gcc8 gilles$ gnm a.out 
-bash: gnm: command not found
```

now, after installing `binutils`, the same command fails

```
KA15-002: gilles$ brew install binutils
==> Downloading https://homebrew.bintray.com/bottles/binutils-2.31.1.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring binutils-2.31.1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/binutils/2.31.1: 114 files, 170.8MB
KA15-002: gilles$ gcc-8 conftest.c 
collect2: fatal error: /usr/local/bin/gnm returned 1 exit status
compilation terminated
```

Here is the error generated by manually invoking `gnm`

```
KA15-002: gilles$ /usr/local/bin/gnm a.out 
/usr/local/bin/gnm: a.out: unknown load command 0x32
/usr/local/bin/gnm: a.out: unknown load command 0x32
/usr/local/bin/gnm: a.out: unknown load command 0x32
/usr/local/bin/gnm: a.out: file format not recognized
```

Unsurprisingly, removing the `binutils` formula solves the issue.

```
KA15-002: gilles$ brew uninstall binutils
Uninstalling /usr/local/Cellar/binutils/2.31.1... (114 files, 170.8MB)
KA15-002:ompi-master-gcc8 gilles$ gcc-8 conftest.c 
```

I initially thought something was wrong with my system (I recently upgraded OS X from High Sierra to Mojave) so uninstalled `brew` and made a fresh install with just a few packages, and am still able to reproduce the very same issue.

**Comment by fxcoudert** [comment] 2018-09-28 08:33
Indeed, it appears that binutils' gnm cannot read MachO files:

```
bli /tmp $ cat a.c
int main (void) { return 0; }
bli /tmp $ clang -c a.c 
bli /tmp $ file a.o    
a.o: Mach-O 64-bit object x86_64
bli /tmp $ gnm a.o
gnm: a.o: unknown load command 0x32
gnm: a.o: unknown load command 0x32
gnm: a.o: unknown load command 0x32
gnm: a.o: file format not recognized
bli /tmp $ gnm --version
GNU nm (GNU Binutils) 2.31.1
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

Could you report this bug to the binutils project? It does not appear to be specific to Homebrew.

**Comment by ggouaillardet** [comment] 2018-09-30 10:38
done

the bug report is available at https://sourceware.org/bugzilla/show_bug.cgi?id=23728

Meanwhile, should something been done for Mojave (such as __not__ installing /usr/local/bin/gnm) in order not to break `gcc-8` ?

**Comment by dmarinescu** [comment] 2018-10-01 02:16
there is even a better idea. stop using that shit from apple

**Comment by dmarinescu** [comment] 2018-10-01 02:18
stop using their hardware and software
you can install linux (even windows) on their actual pc(s) and go from there
this battle is endless, they will do whatever it takes to stop you from using real development tools
they will do that till they run belly up, which will happen faster than you/they think

**Comment by ggouaillardet** [comment] 2018-10-01 04:30
@dmarinescu your trolling is very unwelcome here, good speed.

**Comment by wukefe** [comment] 2018-10-01 05:53
Hi @ggouaillardet, I have the same problem with Xcode 10, the latest version. (I don't think it is caused by the new OS Mojave because gcc works nicely with old Xcode 7.)

A temporary solution is to set nm to gnm as follows

```sh
mv /usr/local/bin/gnm /usr/local/bin/gnm-backup
ln -s /usr/bin/nm /usr/local/bin/gnm
```

**Comment by fxcoudert** [comment] 2018-10-02 15:36
We could introduce a conflict between the two packages, but in general that's not true. It's a case of bug in `binutils`, so I would suggest to simply uninstall the binutils until it is fixed in a new version.

**Closed by fxcoudert** 2018-10-02 15:36 UTC
Labels: upstream issue

**Comment by zbeekman** [comment] 2018-10-26 15:04
I'm going to open a PR to make binutils keg_only since it's so incredibly broken/janky on macOS.

**Comment by roolebo** [comment] 2018-11-06 14:22
Patch series to address the issue has been sent upstream: https://sourceware.org/ml/binutils/2018-11/msg00031.html

**Comment by mistydemeo** [comment] 2018-11-07 00:34
This now-upstreamed patch fixes it: https://sourceware.org/bugzilla/show_bug.cgi?id=23728

I've added it in https://github.com/Homebrew/formula-patches/pull/256
