### ISSUE TITLE
JVM crash when starting JFR recording with openjdk 1.8 installed with brew

### ISSUE THREAD

**Issue by Godagen** [Homebrew/homebrew-core#106195] opened 2022-07-20 05:59 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.5.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: f041a59af9daddc7c7afe8537e3858103f8f9ab9
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 040eff831be5ed38d6fd0b6f3a4ef04b01aa7a24
Core tap last commit: 25 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.37.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Start a JFR (Java Flight Recorder) recording to collect diagnostic data of a java application.

### What happened (include all command output)?

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010d125539, pid=3917, tid=0x0000000000009e03
#
# JRE version: OpenJDK Runtime Environment (8.0_322) (build 1.8.0_322-bre_2022_02_28_15_01-b00)
# Java VM: OpenJDK 64-Bit Server VM (25.322-b00 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x549539]  Unsafe_SetBoolean+0x61
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /var/folders/97/j_7v7gr50ts400jr00rvvjmh0000gn/T//hs_err_pid3917.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/Homebrew/homebrew-core/issues
#
zsh: abort      /usr/local/opt/tomcat@7/bin/catalina run
```

[hs_err_pid3917.log](https://github.com/Homebrew/homebrew-core/files/9146860/hs_err_pid3917.log)

### What did you expect to happen?

JVM doesn't crash and the JFR recording collects diagnostic data.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openjdk@8
brew install tomcat@7
/usr/local/opt/tomcat@7/bin/catalina run 
jcmd <pid_of_tomcat> JFR.start name=default settings=default
```

**Comment by carlocab** [comment] 2022-07-20 06:08
Does it crash if you use a JRE that wasn't built by Homebrew? A JRE provided by a Cask is fine.

**Comment by Godagen** [comment] 2022-07-20 06:08
The issue reproduces only with OpenJDK 1.8 installed by brew and does not reproduce with either Temurin, Zulu or Amazon builds.

I found a similar issue reported [https://github.com/DataDog/dd-trace-java/issues/2997](https://github.com/DataDog/dd-trace-java/issues/2997) - also occurs only with OpenJDK brew builds.

**Comment by adapasuresh** [comment] 2022-08-10 14:11
==> Installing openjdk@8
==> common/autoconf/autogen.sh
==> ./configure --with-boot-jdk-jvmargs=-Duser.home=/Users/sureshadapa/Library/Caches/Homebrew/java_cache --with-boot-jdk=/private/tmp/openjdkA8-20220810-59359-1ode0ke/jdk8u345-b01/boot-jdk --with-debug-l
==> make bootcycle-images CONF=release
Last 15 lines from /Users/sureshadapa/Library/Logs/Homebrew/openjdk@8/03.make:
2022-08-10 14:06:36 +0000

make
bootcycle-images
CONF=release

No configurations found for /private/tmp/openjdkA8-20220810-59359-1ode0ke/jdk8u345-b01/! Please run configure to create a configuration.
Makefile:55: *** Cannot continue.  Stop.

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
JVM crash when starting JFR recording with openjdk 1.8 installed with brew https://github.com/Homebrew/homebrew-core/issues/106195
sureshadapa@localhost Kafdrop % brew install --build-from-source openjdk@8
==> Downloading https://cdn.azul.com/zulu/bin/zulu7.56.0.11-ca-jdk7.0.352-macosx_x64.tar.gz
Already downloaded: /Users/sureshadapa/Library/Caches/Homebrew/downloads/5ae724877cd80f4710cfb7b50aad8626308bf3343dddfbf07250c40caa80f25e--zulu7.56.0.11-ca-jdk7.0.352-macosx_x64.tar.gz
==> Downloading https://openjdk-sources.osci.io/openjdk8/openjdk8u345-ga.tar.xz
Already downloaded: /Users/sureshadapa/Library/Caches/Homebrew/downloads/16cf5f467b62fca342106593ed7f12f002efbd0ef062bde6fc9f9b54e6010b08--openjdk8u345-ga.tar.xz
==> common/autoconf/autogen.sh
==> ./configure --with-boot-jdk-jvmargs=-Duser.home=/Users/sureshadapa/Library/Caches/Homebrew/java_cache --with-boot-jdk=/private/tmp/openjdkA8-20220810-60843-1duugpo/jdk8u345-b01/boot-jdk --with-debug-l
==> make bootcycle-images CONF=release
Last 15 lines from /Users/sureshadapa/Library/Logs/Homebrew/openjdk@8/03.make:
2022-08-10 14:07:57 +0000

make
bootcycle-images
CONF=release

No configurations found for /private/tmp/openjdkA8-20220810-60843-1duugpo/jdk8u345-b01/! Please run configure to create a configuration.
Makefile:55: *** Cannot continue.  Stop.

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
JVM crash when starting JFR recording with openjdk 1.8 installed with brew https://github.com/Homebrew/homebrew-core/issues/106195

**Comment by adapasuresh** [comment] 2022-08-10 14:12
sureshadapa@localhost Kafdrop % uname -a
Darwin PINEMAC0072.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

**Comment by adapasuresh** [comment] 2022-08-10 14:14
sureshadapa@localhost Kafdrop % brew update
Already up-to-date.
sureshadapa@localhost Kafdrop % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  kubernetes-cli

**Comment by adapasuresh** [comment] 2022-08-10 14:48
sureshadapa@localhost Kafdrop % vi /Users/sureshadapa/Library/Logs/Homebrew/openjdk@8/02.configure 

configure: error: Failed to determine Xcode version.
/private/tmp/openjdkA8-20220810-63860-103nuhj/jdk8u345-b01/common/autoconf/generated-configure.sh: line 84: 5: Bad file descriptor

====
sureshadapa@localhost jdk8u345-b01 % pwd
/Users/sureshadapa/Library/Caches/Homebrew/downloads/jdk8u345-b01

sureshadapa@localhost jdk8u345-b01 % grep -ir 'Failed to determine Xcode version' *
common/autoconf/toolchain.m4:      AC_MSG_ERROR([Failed to determine Xcode version.])
common/autoconf/generated-configure.sh:      as_fn_error $? "Failed to determine Xcode version." "$LINENO" 5
====
sureshadapa@localhost jdk8u345-b01 % brew install Xcode
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

You have 28 outdated formulae and 1 outdated cask installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Warning: No available formula with the name "xcode". Did you mean xcodegen?
==> Searching for similarly named formulae...
These similarly named formulae were found:
xcode-kotlin                                                                                           xcodegen
To install one of them, run (for example):
  brew install xcode-kotlin
Xcode can be installed from the App Store.

Installing Xcode from AppStore

====
Will keep you posted...

**Comment by SMillerDev** [comment] 2022-08-10 14:51
Please don't keep us posted, the first message already mentions:

> Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by archzi** [comment] 2022-11-18 10:57
same error:
```bash
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010d1fa027, pid=27024, tid=0x000000000000af03
#
# JRE version: OpenJDK Runtime Environment (8.0_352) (build 1.8.0_352-bre_2022_11_08_21_10-b00)
# Java VM: OpenJDK 64-Bit Server VM (25.352-b00 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x53d027]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumpi
[hs_err_pid27024.log](https://github.com/Homebrew/homebrew-core/files/10040622/hs_err_pid27024.log)
ng, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/Homebrew/homebrew-core/issues
#
```

**Comment by man-chi** [comment] 2022-12-12 07:42
I am currently running Mac OS 10.15.7,  Catalina and facing the same error "JVM crash when starting JFR recording with openjdk 1.8", any one has good idea on the solution? please help.

command * error log listed below:
➜  ~ brew install gradle
Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Downloading https://download.java.net/java/GA/jdk16.0.2/d4a915d82b4c4fbb9bde534da945d746/7/GPL/openjdk-16.0.2_osx-x64_bin.tar.gz
Already downloaded: /Users/mac/Library/Caches/Homebrew/downloads/16f25ef4e48ec3ac2436dabb9930e1434e4769c203b7e58316a8e48c95e8f30d--openjdk-16.0.2_osx-x64_bin.tar.gz
==> Downloading https://github.com/openjdk/jdk17u/archive/jdk-17.0.5-ga.tar.gz
Already downloaded: /Users/mac/Library/Caches/Homebrew/downloads/ad96db40ae0b8819f44488ad76f31ba6d25f548cd3c0a88b13942ca097e65a3e--jdk17u-jdk-17.0.5-ga.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/gradle/manifests/7.6
Already downloaded: /Users/mac/Library/Caches/Homebrew/downloads/0509f87600ba467189b75e426cda1627f2eafa07f4d887d82f1b2a342767f095--gradle-7.6.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gradle/blobs/sha256:4be64b296fb7a3b5c16d7807dd278dbcb2fbc21a6209e65786e0548f48cffc4
Already downloaded: /Users/mac/Library/Caches/Homebrew/downloads/6ba52de56bdc3731bab234cd0683a15396981eaf7fdf9e30cd16088b7a4ff3b5--gradle--7.6.catalina.bottle.tar.gz
==> Installing dependencies for gradle: openjdk@17
==> Installing gradle dependency: openjdk@17
==> bash configure --disable-warnings-as-errors --with-boot-jdk-jvmargs=-Duser.home=/Users/mac/Library/Caches/Homebrew/java_cache --
Last 15 lines from /Users/mac/Library/Logs/Homebrew/openjdk@17/01.bash:
checking whether the compiler supports GNU C++... yes
checking whether /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ accepts -g... yes
checking for /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ option to enable C++11 features... none needed
checking how to run the C preprocessor... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -E
checking how to run the C++ preprocessor... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -E
configure: Using clang linker version 609.8 [@(#)PROGRAM:ld  PROJECT:ld64-609.8]
checking for ar... /usr/bin/ar
checking for lipo... /usr/bin/lipo
checking for otool... /usr/bin/otool
checking for install_name_tool... /usr/bin/install_name_tool
checking for metal... [not found]
checking if metal can be run using xcrun... no
configure: error: XCode tool 'metal' neither found in path nor with xcrun
/private/tmp/openjdkA17-20221212-62433-hibk0r/jdk17u-jdk-17.0.5-ga/build/.configure-support/generated-configure.sh: line 84: 5: Bad file descriptor
configure exiting with result code 1

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
JVM crash when starting JFR recording with openjdk 1.8 installed with brew https://github.com/Homebrew/homebrew-core/issues/106195

Error: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

**Comment by man-chi** [comment] 2022-12-12 08:10
I have got my comment marked as off-topic. yes, I do refer to this ticket. may I know what can I do to resolve the issue?
I could not find any information on the action for resolution on this page. please help!

**Comment by man-chi** [comment] 2022-12-15 07:19
I have solved my problem by re-installing the Xcode 12.4 for catalina and move (important) to application folder correctly.
sorry to trouble. all good now!

**Comment by iMichka** [comment] 2023-09-25 20:12
I tested this with opendjk@8, tomcat@8 (tomcat 7 is now EOL), on macOS Ventura.

This worked without issue:
```
➜  ~ /usr/local/Cellar/openjdk@8/1.8.0-382_1/bin/jcmd 88264 JFR.start name=default settings=default
88264:
Started recording 1. No limit specified, using maxsize=250MB as default.

Use jcmd 88264 JFR.dump name=default filename=FILEPATH to copy recording data to file.
```

**Comment by iMichka** [comment] 2023-09-27 19:24
Here is what I did:

```
➜  ~ JRE_HOME=/usr/local/opt/openjdk@8 /usr/local/opt/tomcat@8/bin/catalina run
Using CATALINA_BASE:   /usr/local/Cellar/tomcat@8/8.5.93/libexec
Using CATALINA_HOME:   /usr/local/Cellar/tomcat@8/8.5.93/libexec
Using CATALINA_TMPDIR: /usr/local/Cellar/tomcat@8/8.5.93/libexec/temp
Using JRE_HOME:        /usr/local/opt/openjdk@8
Using CLASSPATH:       /usr/local/Cellar/tomcat@8/8.5.93/libexec/bin/bootstrap.jar:/usr/local/Cellar/tomcat@8/8.5.93/libexec/bin/tomcat-juli.jar
Using CATALINA_OPTS:
27-Sep-2023 21:19:08.498 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.93
27-Sep-2023 21:19:08.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 23 2023 22:43:14 UTC
27-Sep-2023 21:19:08.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.93.0
27-Sep-2023 21:19:08.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Mac OS X
27-Sep-2023 21:19:08.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            13.5.1
27-Sep-2023 21:19:08.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          x86_64
27-Sep-2023 21:19:08.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/Cellar/openjdk@8/1.8.0-382_1/libexec/openjdk.jdk/Contents/Home/jre
27-Sep-2023 21:19:08.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_382-bre_2023_09_05_21_07-b00
27-Sep-2023 21:19:08.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Homebrew
27-Sep-2023 21:19:08.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/Cellar/tomcat@8/8.5.93/libexec
27-Sep-2023 21:19:08.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/Cellar/tomcat@8/8.5.93/libexec
27-Sep-2023 21:19:08.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/Cellar/tomcat@8/8.5.93/libexec/conf/logging.properties
27-Sep-2023 21:19:08.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
27-Sep-2023 21:19:08.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
27-Sep-2023 21:19:08.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
27-Sep-2023 21:19:08.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
27-Sep-2023 21:19:08.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
27-Sep-2023 21:19:08.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/Cellar/tomcat@8/8.5.93/libexec
27-Sep-2023 21:19:08.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/Cellar/tomcat@8/8.5.93/libexec
27-Sep-2023 21:19:08.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/Cellar/tomcat@8/8.5.93/libexec/temp
27-Sep-2023 21:19:08.505 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/Users/michkapopoff/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
27-Sep-2023 21:19:08.594 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
27-Sep-2023 21:19:08.620 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 422 ms
27-Sep-2023 21:19:08.723 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
27-Sep-2023 21:19:08.723 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/8.5.93]
27-Sep-2023 21:19:08.732 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/docs]
27-Sep-2023 21:19:08.957 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/docs] has finished in [223] ms
27-Sep-2023 21:19:08.957 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/manager]
27-Sep-2023 21:19:08.982 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/manager] has finished in [25] ms
27-Sep-2023 21:19:08.982 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/examples]
27-Sep-2023 21:19:09.192 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/examples] has finished in [210] ms
27-Sep-2023 21:19:09.192 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/ROOT]
27-Sep-2023 21:19:09.202 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/ROOT] has finished in [10] ms
27-Sep-2023 21:19:09.203 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/host-manager]
27-Sep-2023 21:19:09.215 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat@8/8.5.93/libexec/webapps/host-manager] has finished in [12] ms
27-Sep-2023 21:19:09.217 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
27-Sep-2023 21:19:09.229 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 609 ms
```

```
/usr/local/opt/openjdk@8/bin/jcmd 6627 JFR.start name=default settings=default
6627:
Started recording 1. No limit specified, using maxsize=250MB as default.

Use jcmd 6627 JFR.dump name=default filename=FILEPATH to copy recording data to file.
```

On macOS Ventura (Intel), with all the latest versions of brew, openjdk@8 and tomcat@8

**Comment by iMichka** [comment] 2024-02-12 21:48
@Godagen @archzi still having this issue? I could not reproduce this locally.

**Comment by iMichka** [comment] 2024-02-17 13:46
Closing. The initial report dates from July 2022 … if we were not able to fix this since that time, no-one will probably do it. Sorry

**Closed by iMichka** 2024-02-17 13:46 UTC
Labels: bug, help wanted
