### ISSUE TITLE
Issue with zig formula? brew install --HEAD zig fails on macOS arm64

### ISSUE THREAD

**Issue by lordnoriyuki** [Homebrew/homebrew-core#113650] opened 2022-10-21 01:58 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew doctor
Your system is ready to brew.
% brew config
HOMEBREW_VERSION: 3.6.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 978a452ea7ccdff1ed7377f88add3ff0513ba2b7
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fbfc91f3d4a1d603135ba5688221387cf5a18fe2
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 20-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: 13.4.1
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install zig master via homebrew via ```brew install --HEAD zig```

### What happened (include all command output)?

Failed due to not finding libzstd because it doesn't look in /opt/homebrew/lib for libzstd.
```
warning(link): library not found for '-lzstd'
warning(link): Library search paths:
warning(link):   /opt/homebrew/Cellar/llvm/15.0.3/lib
warning(link):   /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
error(link): undefined reference to symbol '_ZSTD_compress'
error(link):   first referenced in '/opt/homebrew/Cellar/llvm/15.0.3/lib/libLLVMSupport.a(Compression.cpp.o)'
```

If I change the zig.rb formula locally so this line:
```
system "cmake", "-S", ".", "-B", "build", "-DZIG_STATIC_LLVM=ON", *std_cmake_args
```
becomes
```
system "cmake", "-S", ".", "-B", "build", "-DZIG_STATIC_LLVM=ON", "-DCMAKE_PREFIX_PATH=/opt/homebrew/opt/llvm;/opt/homebrew", *std_cmake_args
```
then it gets past this error. Note however that it still fails to install due to https://github.com/ziglang/zig/issues/9764, but that's expected until that issue is resolved.

Tail of full command output is (maybe?) interesting because ```CMAKE_PREFIX_PATH``` seems to include ```/opt/homebrew``` in addition to ``` /opt/homebrew/opt/llvm```, but it is colon separated and the zig build expects semi-colon separated according to https://github.com/ziglang/zig/pull/13108.

```
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j20
CMAKE_PREFIX_PATH: /opt/homebrew/opt/llvm:/opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/12
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/cmake/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

### What did you expect to happen?

Expected install to complete successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --HEAD zig
```

**Comment by carlocab** [comment] 2022-10-21 02:12
The problem is that CMake has two different `CMAKE_PREFIX_PATH`s: one is a cache variable, which is [semi-colon-separated](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html), and another is an [environment variable](https://cmake.org/cmake/help/latest/envvar/CMAKE_PREFIX_PATH.html), which is colon-separated on Unix.

Zig should not be treating the two identically.

**Comment by lordnoriyuki** [comment] 2022-10-21 02:23
Thanks @carlocab, I filed a zig issue for this one.

**Comment by carlocab** [comment] 2022-10-21 02:32
Yes, I think this is a regression somewhere in Zig. While trying to fix ziglang/zig#12943 and ziglang/zig#12923, I tested `brew install --HEAD zig` on an M1 Mac but then ran into ziglang/zig#9764. See https://github.com/ziglang/zig/issues/12943#issuecomment-1265670790.

**Comment by carlocab** [comment] 2022-10-21 02:36
A workaround in the formula would be to do something like this:
```diff
diff --git a/Formula/zig.rb b/Formula/zig.rb
index 93475dfb6e4..c2fc534028d 100644
--- a/Formula/zig.rb
+++ b/Formula/zig.rb
@@ -31,7 +31,10 @@ class Zig < Formula
   fails_with gcc: "5" # LLVM is built with GCC
 
   def install
-    system "cmake", "-S", ".", "-B", "build", "-DZIG_STATIC_LLVM=ON", *std_cmake_args
+    system "cmake", "-S", ".", "-B", "build",
+                    "-DZIG_STATIC_LLVM=ON",
+                    "-DCMAKE_PREFIX_PATH=#{ENV["CMAKE_PREFIX_PATH"].tr(":", ";")}",
+                    *std_cmake_args
     system "cmake", "--build", "build"
     system "cmake", "--install", "build"
   end
```

However, given that Zig won't build yet anyway, it seems a little pointless to do this. Also, if my diagnosis is correct (it may not be!), then ideally this will be fixed upstream. Presumably `brew` isn't the only one that uses the environment variable `CMAKE_PREFIX_PATH` as documented.

**Comment by andrewrk** [comment] 2022-10-21 03:16
> Zig should not be treating the two identically. This is safe only on Windows, where the environment variable is semi-colon-separated.

Sorry, what are the two? I'm only aware of `${CMAKE_PREFIX_PATH}`. I'm confused.

**Comment by gromgit** [comment] 2022-10-21 04:03
As @carlocab wrote in the comment you quoted:

> The problem is that CMake has two different `CMAKE_PREFIX_PATH`s: one is a [cache variable](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html), which is semi-colon-separated, and the other is an [environment variable](https://cmake.org/cmake/help/latest/envvar/CMAKE_PREFIX_PATH.html), which is colon-separated on Unix.

**Comment by andrewrk** [comment] 2022-10-22 17:55
@carlocab do you have a suggestion for an upstream change? That diff you posted does not make sense to me, why wouldn't cmake automatically do that transformation? Are you saying that `${CMAKE_PREFIX_PATH}` inside CMakeLists.txt is a cache variable or an environment variable?

> Zig should not be treating the two identically. This is safe only on Windows, where the environment variable is semi-colon-separated.

No idea what you're talking about, can you please elaborate on this?

**Comment by Bo98** [comment] 2022-10-22 19:21
Here's the missing bit of info here: setting `CMAKE_PREFIX_PATH` as env does not set `CMAKE_PREFIX_PATH` as a CMake variable, so the substitution in `ZIG_CMAKE_PREFIX_PATH` ends up being blank if the env is used.

When fixing that to correctly take in the ENV, then you may need to deal with path separator differences (though that could be fixed on the CMake side before substitution).

**Comment by andrewrk** [comment] 2022-10-23 00:20
Thank you for the explanation, @Bo98.

**Comment by andrewrk** [comment] 2022-10-23 18:25
Both upstream issues are now solved in master branch.

**Comment by Bo98** [comment] 2022-10-23 18:28
Thanks!

**Closed by Bo98** 2022-10-23 18:28 UTC
Labels: upstream issue
