### ISSUE TITLE
fatal: repository 'https://github.com/Homebrew/homebrew-core/' not found

### ISSUE THREAD

**Issue by sebastientaggart** [Homebrew/homebrew-core#1031] opened 2016-05-10 03:48 UTC
- [x]  Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Gist with errors: https://gist.github.com/sebastientaggart/23db9f525b55faf4cf9870372a79abf7

TL;DR: ''brew doctor'' fails complaining about a repository not found, however the repository appears to be set correctly, and all other troubleshooting steps seem fine (see gist).

I've [looked](http://stackoverflow.com/questions/14113427/brew-update-failed?rq=1) [at](http://stackoverflow.com/questions/21267220/homebrew-cannot-update-and-i-cannot-add-a-git-repository) [a](https://github.com/Homebrew/legacy-homebrew/issues/5128) [few](https://github.com/neovim/neovim/issues/107) similar-looking problems, but none of the suggested steps did the trick (even reinstalling from scratch).

Weirdly, repository not found errors show up for lots of commands:
```
/usr/local (master)$ brew services
==> Tapping homebrew/services
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-services'...
fatal: repository 'https://github.com/Homebrew/homebrew-services/' not found
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-services /usr/local/Library/Taps/homebrew/homebrew-services --config core.autocrlf=false --depth=1
Error: Failure while executing: /usr/local/bin/brew tap homebrew/services
```

Even completely removing /usr/local, starting with fresh directory, and running the install script fails:
```
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown sebastien /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
fatal: repository 'https://github.com/Homebrew/brew/' not found
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1
```

**Comment by ilovezfs** [comment] 2016-05-10 05:01
Can you please open a duplicate of this issue in https://github.com/Homebrew/brew and then close this one?

**Closed** 2016-05-10 06:21 UTC

**Comment by sebastientaggart** [comment] 2016-05-10 11:31
Done, reposted to [/Homebrew/brew](https://github.com/Homebrew/brew/issues/230)

**Comment by ilovezfs** [comment] 2016-05-10 12:51
Thanks @sebastientaggart
