### ISSUE TITLE
fuego: boost incompatibility?

### ISSUE THREAD

**Issue by tunesmith** [Homebrew/homebrew-core#24950] opened 2018-03-07 06:58 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

fuego works by issuing gtp commands against it, often from other client applications. When using sabaki (a gtp client) against fuego, I regularly get this kind of output, which breaks the gtp connection.

```
GoGtpEngine: Using move from opening book
dyld: lazy symbol binding failed: Symbol not found: __ZN5boost11this_thread6hidden11sleep_untilERK8timespec
  Referenced from: /usr/local/bin/fuego
  Expected in: /usr/local/opt/boost/lib/libboost_thread-mt.dylib
dyld: Symbol not found: __ZN5boost11this_thread6hidden11sleep_untilERK8timespec
  Referenced from: /usr/local/bin/fuego
  Expected in: /usr/local/opt/boost/lib/libboost_thread-mt.dylib
```

I confirmed this by also using GoGui and Goban, so it looks specific to fuego. Perhaps it is linked to the wrong version of boost?

I have no output in `brew gist-logs`, and `brew doctor` is fine.

```
HOMEBREW_VERSION: 1.5.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 08f7e8c5887d1c654a1a5d5bc851a9c9d5a00371
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1da7c6fd1aacee2a175c29c28342f670dbd6b1ce
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /Users/curt/.rvm/rubies/ruby-2.1.2/bin/ruby
Java: 1.8.0_31, 1.7.0_51, 1.6.0_65-b14-468
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

**Comment by equal-l2** [comment] 2018-03-07 08:28
Have you tried `brew reinstall`?

**Comment by tunesmith** [comment] 2018-03-07 08:30
Yes, when I did so it actually installed a newer (I believe) version of boost, but the same error occurred.

**Comment by equal-l2** [comment] 2018-03-07 09:00
The problem doesn't occur when I install `fuego` from source (via `--build-from-source`.)
I guess the bottle is corrupted.

Can you try with one built from source?

**Comment by tunesmith** [comment] 2018-03-07 09:18
Thanks for the tip, I hadn't done `--build-from-source` before. That works for me, too - fuego is now operating normally for me.

**Comment by fxcoudert** [comment] 2018-03-07 09:21
Possibly we need to rebuild the bottles for fuego when boost is revision bumped. This is not caught because we do not have a valid test for `fuego`. @tunesmith could you suggest a simple test that we could run that would catch the issue next time?

**Comment by ilovezfs** [comment] 2018-03-07 09:22
https://github.com/Homebrew/homebrew-core/pull/24952

**Comment by ilovezfs** [comment] 2018-03-07 09:25
@fxcoudert fyi just running the binary reproduces the problem.

**Comment by tunesmith** [comment] 2018-03-07 09:28
Hmm. For me it didn't trigger after just one move; it required a sequence of moves, and unfortunately it wasn't consistent - sometimes it was after four moves (two on each side, where each side was a bot), sometimes two or six. A short transcript of 4-6 "genmove" commands might do it. I can put some more thought into it tomorrow if you have identified another test by then.

**Comment by ilovezfs** [comment] 2018-03-07 09:49
@tunesmith try `fuego --help` with the bad bottle. It should segfault.

**Comment by fxcoudert** [comment] 2018-03-07 10:51
`fuego --help` didn't serrault for me, but I ended up finding something that does:

`echo 'genmove white\ngenmove black' | fuego`

**Comment by ilovezfs** [comment] 2018-03-07 12:40
Closed via https://github.com/Homebrew/homebrew-core/pull/24952.

**Comment by ilovezfs** [comment] 2018-03-07 12:40
This is now fixed if you `brew upgrade`

**Closed by ilovezfs** 2018-03-07 12:40 UTC
Labels: in progress
