### ISSUE TITLE
fpc not installing on macOS 10.12

### ISSUE THREAD

**Issue by antonshiryaev** [Homebrew/homebrew-core#5732] opened 2016-10-09 14:26 UTC
### Bug reports:

FreePascal (formula is "fpc") does not compile on macOS 10.12, reporting 10.12 as an invalid build target parameter.

Gist-log: https://gist.github.com/4de22f53767976bcbdde4a328c500df5
<img width="1178" alt="2016-10-09 17 06 19" src="https://cloud.githubusercontent.com/assets/5638404/19221119/8c1d3c72-8e45-11e6-8aa4-8d3e24c5518d.png">

**Comment by zmwangx** [comment] 2016-10-09 15:02
Reproducible, see #5488. I believe it's an upstream issue. They need to acknowledge 10.12 as a valid target.

**Comment by zmwangx** [comment] 2016-10-09 15:03
Edited title so that people don't go `brew info freepascal`.

**Comment by zmwangx** [comment] 2016-10-09 15:05
I think we should put a `MaximumMacOSRequirement` on `fpc` at the moment, and wait for an upstream release.

@antonshiryaev I would appreciate it if you can contact the upstream about the 10.12 situation. Please drop a link here if you open an issue on a public issue tracker or post to a mailing list with an archive.

**Comment by antonshiryaev** [comment] 2016-10-09 15:08
I just checked and fpc installed from the official image works flawlessly on 10.12. No update to the actual code is necessary.

By upstream do you mean fpc? Because that's almost certainly abandonware.

**Comment by zmwangx** [comment] 2016-10-09 15:11
> fpc installed from the official image works flawlessly on 10.12

The dmg was built on an earlier macOS release. The build products could certainly work on 10.12; it's compiling on 10.12 that's a problem.

But I'll see if it's easy to patch. Give me some time.

> Because that's almost certainly abandonware.

Last (major) release in November 2015; why are you convinced it's abandonware?

**Comment by antonshiryaev** [comment] 2016-10-09 15:18
I see. 
Actually, I now believe I was wrong about the project's abandonment. I re-checked, and the latest snapshot release is dated 20.09.16. I'm trying to register at their bug tracker and will post a link here once I report the bug.

**Comment by zmwangx** [comment] 2016-10-09 15:20
Okay, I looked into it, it's the bootstrap binary that's causing the trouble. Unless there's another way to build it that doesn't involve the bootstrap (I bet there is), I doubt we can rescue it without upstream involvement.

> I'm trying to register at their bug tracker and will post a link here once I report the bug.

Cool, thanks.

**Comment by antonshiryaev** [comment] 2016-10-09 15:25
Reported [here](http://bugs.freepascal.org/view.php?id=30711). But even if somebody notices and fixes this, they might not release an update anytime soon, going by their track record with 3.1.

**Comment by zmwangx** [comment] 2016-10-09 15:28
You might be able to convince @ilovezfs to port the El Cap bottle to Sierra (I ran `brew test` on it and it worked without problem; I would be more confident if there's a test suite). Not my favorite practice though.

**Comment by antonshiryaev** [comment] 2016-10-09 15:33
Considering the fact that fpc's bug tracker reports version 3.1.1 as being released 2015-11-26, and the version downloadable from brew and their official website is 3.0, I doubt there's much point to relying on upstream for fixes.
I would have contacted @ilovezfs, but they have not provided an email address, so unless they see this issue, I doubt they can help either.

**Comment by zmwangx** [comment] 2016-10-09 15:33
No, @ilovezfs is a fellow Homebrew maintainer.

**Comment by antonshiryaev** [comment] 2016-10-09 15:35
Yes, I got that. What I meant is that there is little chance of a fix for the issue I opened [here](http://bugs.freepascal.org/view.php?id=30711) reaching anyone.

**Comment by zmwangx** [comment] 2016-10-09 15:35
Let me make it clear:

> port the El Cap bottle to Sierra

That's something we can easily do on our side. Just need a decision.

**Comment by antonshiryaev** [comment] 2016-10-09 15:38
That's really not something I'm qualified to decide.
Like I said, there is something odd going on with the project: [here](http://bugs.freepascal.org/changelog_page.php?version_id=342) the reported latest version is 3.1.1, and [here](http://www.freepascal.org/download.var) it's 3.0.0, so a hypothetical fix might not reach anyone. Thus, I'm personally in favour of porting it.

**Comment by zmwangx** [comment] 2016-10-09 15:39
> That's really not something I'm qualified to decide.

That's our decision.

> there is something odd going on with the project

Yeah I'm looking for a 3.1.1 download but can't find it.

**Comment by zmwangx** [comment] 2016-10-09 15:40
Anyway, the problem isn't so much the 3.1.1 release, but rather the 2.6.4 bootstrap binary which doesn't work on 10.12. I'm look into whether we can bypass that after lunch.

**Comment by antonshiryaev** [comment] 2016-10-09 15:41
Source code and some builds of 3.1.1 can be downloaded [here](http://www.freepascal.org/develop.var), but I'm not sure if that's the release or also has all changes since.

**Comment by antonshiryaev** [comment] 2016-10-09 16:07
The [issue](http://bugs.freepascal.org/view.php?id=30711#c95060) has been updated and a workaround has been provided. I'm not sure whether it can be integrated into Homebrew, though.

**Comment by zmwangx** [comment] 2016-10-09 16:36
I can't comment on that closed issue. If you could, please let them know the bootstrap binary doesn't work on 10.12 due to certain libraries moved from `/usr/lib` to within the SDK:

```
$ /Volumes/Brew/HomebrewTemp/fpc-20161009-65188-134xd4r/fpc-3.0.0/bootstrap/ppcuniversal -Ur -Xs -O2 -n -Fux86_64 -Fusystems -Fu/Volumes/Brew/HomebrewTemp/fpc-20161009-65188-134xd4r/fpc-3.0.0/rtl/units/x86_64-darwin -Fix86_64 -FE. -FUx86_64/units/x86_64-darwin -dRELEASE    -dx86_64 -dGDB -dBROWSERLOG -Fux86 -Sew pp.pas
ld: file not found: /usr/lib/crt1.10.6.o
```

Someone else documented the issue in http://www.pilotlogic.com/sitejoom/index.php/forum/macos-development/3669-cannot-build-fpc-or-ide-on-macos-sierra.

**Comment by antonshiryaev** [comment] 2016-10-09 16:43
I repeated your comment more or less verbatim. The fact that someone is responding to the issues at all is somewhat reassuring.

**Comment by zmwangx** [comment] 2016-10-09 16:46
Interestingly, after you commented, I can comment too now.

**Comment by ilovezfs** [comment] 2016-10-09 17:00
@antonshiryaev https://github.com/Homebrew/homebrew-core/pull/5741

**Comment by antonshiryaev** [comment] 2016-10-09 17:43
@zmwangx FreePascal bug tracker has a new commentary the maintainer. I've checked and the library that's missing is indeed present in /usr/lib on my machine, although it may have had FreePascal installed on it at some point in the past, though.

**Comment by zmwangx** [comment] 2016-10-09 18:01
@ilovezfs Actually I have `/usr/lib/crt1.10.6.o` too, and setting `ENV["MACOSX_DEPLOYMENT_TARGET"] = "10.9"` is enough. Have you installed CLT on your VM?

**Comment by antonshiryaev** [comment] 2016-10-09 18:15
Yes, I do. I'm pretty sure I wouldn't be able to even run Homebrew otherwise. I think you need to respond to FreePascal's bug tracker about this, since the maintainer misunderstood the underlying issue.

**Comment by zmwangx** [comment] 2016-10-09 18:19
> Yes, I do.

Well I'm asking @ilovezfs because it was him who got the `ld: file not found` error on his testing VM...

I'm pretty sure this is misunderstanding, and we can set `ENV["MACOSX_DEPLOYMENT_TARGET"] = "10.9"` and be done with it. @antonshiryaev You can use this patch

```diff
diff --git a/Formula/fpc.rb b/Formula/fpc.rb
index 6f0791f..326d885 100644
--- a/Formula/fpc.rb
+++ b/Formula/fpc.rb
@@ -22,6 +22,7 @@ class Fpc < Formula
     resource("bootstrap").stage { fpc_bootstrap.install Dir["*"] }
 
     fpc_compiler = fpc_bootstrap/"ppcuniversal"
+    ENV["MACOSX_DEPLOYMENT_TARGET"] = "10.9"
     system "make", "build", "PP=#{fpc_compiler}"
     system "make", "install", "PP=#{fpc_compiler}", "PREFIX=#{prefix}"
 
```

and verify it works.

By the way, I can't comment on the issue because it has been marked as resolved again.

**Comment by antonshiryaev** [comment] 2016-10-09 18:43
I'm afraid I'm not entirely certain how to apply your patch, could you please elaborate? 
I'll reopen it.

**Comment by antonshiryaev** [comment] 2016-10-09 18:45
I've reopened the issue.

**Comment by zmwangx** [comment] 2016-10-09 18:54
```sh
curl -L https://github.com/Homebrew/homebrew-core/pull/5745.diff | git -C "$(brew --repo homebrew/core)" apply
HOMEBREW_NO_AUTOUPDATE=1 brew install -s fpc
git -C "$(brew --repo homebrew/core)" .
```

**Comment by antonshiryaev** [comment] 2016-10-09 20:47
I pasted the whole workaround into a shell script and ran it, and it appears to be compiling. I'll report how it goes.

**Comment by antonshiryaev** [comment] 2016-10-09 20:50
It worked!
<img width="762" alt="2016-10-09 23 49 37" src="https://cloud.githubusercontent.com/assets/5638404/19223548/10e35204-8e7b-11e6-8535-58922138eb42.png">

I guess there is no need for porting the bottle, then. I'll comment on that issue.

**Closed** 2016-10-09 20:52 UTC
Labels: 10.12, upstream issue

**Comment by ilovezfs** [comment] 2016-10-09 21:08
There is no Homebrew DSL for requiring the CLT. Things need to be able to build with Xcode alone ;)

**Comment by antonshiryaev** [comment] 2016-10-09 21:19
This is not unique to Homebrew, if it's installed from the disk image it still requires the CLT.

There are a lot of oddities to the project. For instance, [here](http://bugs.freepascal.org/changelog_page.php?version_id=342) the reported latest version is 3.1.1, and [here](http://www.freepascal.org/download.var) it's 3.0.0, which is what's installed by Homebrew. I doubt I'll be able to encourage them to do much, but I'll try.

**Comment by cielavenir** [comment] 2016-10-12 10:15
Hi, I installed fpc using your-like method: http://qiita.com/cielavenir/items/069101b97cf22b889bb5#fpc

By the way, I do have `/usr/lib/crt1.10.6.o`. Actually the original version on my MacBookAir is 10.8 (4 times upgrade!), so I don't know what package installed the file... Xcode CommandLine? or other?

**Comment by cielavenir** [comment] 2016-10-12 10:21
(Googling does find `xcode-select --install` fixes the crt1.10.6.o error...)

**Comment by zmwangx** [comment] 2016-10-12 21:43
> There is no Homebrew DSL for requiring the CLT. Things need to be able to build with Xcode alone ;)

Upstream says building and *using* `fpc` requires CLT. However unreasonable that may sound, it's a legit requirement, just like requiring GCC (or worse, a specific, non-latest version of GCC) on macOS.

We should either throw without CLT, or if there's enough demand or a consensus, add a DSL for requiring CLT. That's 10–100 more lightweight than the Xcode requirement.

**Comment by MikeMcQuaid** [comment] 2016-10-13 07:23
> Upstream says building and using fpc requires CLT.

Can you/they elaborate a bit more on why? We had a DSL previously but a CLT requirement is almost always a sign of an upstream buildsystem bug.

**Comment by ilovezfs** [comment] 2016-10-13 07:26
That just need to look for the relevant files in #{sdk}/usr/lib instead of /usr/lib. The requirement is goofy. It was fixable by simply using our el cap bottle as bootstrapper instead of their outdated one. Since Jenkins has CLT installed, we opted for this lighter weight solution but you can see https://github.com/Homebrew/homebrew-core/pull/5741 for a complete fix that renders the CLT unnecessary.
