### ISSUE TITLE
Formula php@5.6 not working on macOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by jzgoda** [Homebrew/homebrew-core#32497] opened 2018-09-27 13:55 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh

Yes, it is reproducible. In particular, on a fresh install of Mojave...I can't test on an upgrade to Mojave, because I did a fresh install.

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

The problem is not with brew itself (I have several other formulas running great), it's just related to `php@5.6` on macOS 10.14.

- [x] ran `brew update` and can still reproduce the problem?

It was a fresh install of brew using the command from https://brew.sh. 
```
$ brew update
Already up-to-date.
```

- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

```
$ brew doctor
Your system is ready to brew.
```

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/77a1f19af7a12120e577ac1386d6f5d7

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

It worked, see above.

To help us debug your issue please explain:
- What you were trying to do (and why)

Run `php@5.6` because I have an older application to support. 
In particular, I'm using php-fpm because I'm using nginx instead of Apache.
I attempted to both use the default networking port 127.0.0.1:9000, and a unix socket. Both were the same. I tried starting PHP with both my standard user, and sudo; there was no difference in the result.

- What happened (include command output)

Nothing from php itself, and I did set the `error_log` variable in the `php.ini`.

Nginx would say:
```
2018/09/26 21:15:15 [error] 19990#0: *6 kevent() reported about an closed connection (54: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /test.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
```

PHP-FPM would say:
```
[26-Sep-2018 21:15:15] WARNING: [pool www] child 20479 exited on signal 11 (SIGSEGV) after 4.343179 seconds from start
[26-Sep-2018 21:15:15] NOTICE: [pool www] child 20481 started
```

- What you expected to happen

I expected PHP to run, or at a minimum, produce an error.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install nginx
brew install php@5.6
```

Edit path to include php before /usr/local/sbin, something like: 
`export PATH="/usr/local/opt/php@5.6/bin:/usr/local/opt/php@5.6/sbin:/usr/local/sbin:$PATH"`

Uncomment the default proxy config in nginx.conf, and fix `SCRIPT_FILENAME` param:

```
location ~ \.php$ {
            root           html;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
```

Start/restart PHP & nginx (using `sudo` on nginx because on port 80):
```
sudo brew services start nginx
brew services start php
```

This SHOULD work, but doesn't.

All I had to do to get it to work is:

- Stop php@5.6
`brew services stop php`

- Install 7.2:
`brew install php`

- Update PATH:
`export PATH="/usr/local/opt/php@7.2/bin:/usr/local/opt/php@7.2/sbin:/usr/local/sbin:$PATH"`

- Start php:
`brew services start php`

Working on php 7.2!

Please let me know if there is any other info you need.

**Comment by fxcoudert** [comment] 2018-09-27 15:34
@jzgoda thanks for the detailed report. Is there any indication from the PHP project that 5.6 is supported on macOS Mojave? Do you know if the same issue is seen with a PHP from another distribution than Homebrew?

**Comment by jzgoda** [comment] 2018-09-27 16:38
I was able to get 5.6 working by using the distribution from https://php-osx.liip.ch/

I notice they have a warning that the plugin won't work with Apache, but using php-fpm through nginx worked for me.

I installed via:
`curl -s https://php-osx.liip.ch/install.sh | bash -s force 5.6`

And then just ran php-fpm from the command line, it was able to process just fine.

Here is a gist with the output from `php -i`: https://gist.github.com/jzgoda/1cc07f6c9bc0bc469cadfa6c1102b392

**Comment by jzgoda** [comment] 2018-09-29 14:29
I was able to track the issue down to the packaged OPcache extension.

If I change the `opcache.so` file that is being loaded to the one that is packaged with the above mentioned distribution, this formula works fine.

`/usr/local/etc/php/5.6/conf.d/ext-opcache.ini`
```
[opcache]
;zend_extension=/usr/local/opt/php@5.6/lib/php/20131226/opcache.so
zend_extension=/usr/local/php5/lib/php/extensions/no-debug-non-zts-20131226/opcache.so
```

**Comment by Myrkotyn** [comment] 2018-10-03 08:59
Have similar problem too.
Just changing opcache config or not load it, like @jzgoda sad, does not help for me.

**Comment by SMillerDev** [comment] 2018-10-03 10:13
I'd check disabling all plugins and re enabling them one by one to find the offending plugin.

**Comment by javian** [comment] 2018-10-04 19:30
Could you provide the output from `brew linkage php@5.6` ?

**Comment by alok108** [comment] 2018-10-06 16:39
> I was able to track the issue down to the packaged OPcache extension.
> 
> If I change the `opcache.so` file that is being loaded to the one that is packaged with the above mentioned distribution, this formula works fine.
> 
> `/usr/local/etc/php/5.6/conf.d/ext-opcache.ini`
> 
> ```
> [opcache]
> ;zend_extension=/usr/local/opt/php@5.6/lib/php/20131226/opcache.so
> zend_extension=/usr/local/php5/lib/php/extensions/no-debug-non-zts-20131226/opcache.so
> ```
> (Just not loading OPcache also works.)

Yes this works for me

**Comment by jzgoda** [comment] 2018-10-06 16:59
@javian, not sure if you wanted me to run the command, or @Myrkotyn, but this is what I have:

```
$ brew linkage php@5.6
System libraries:
  /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libcurl.4.dylib
  /usr/lib/libedit.3.dylib
  /usr/lib/libexpat.1.dylib
  /usr/lib/libexslt.0.dylib
  /usr/lib/libicucore.A.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libresolv.9.dylib
  /usr/lib/libxml2.2.dylib
  /usr/lib/libxslt.1.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/apr/libexec/lib/libapr-1.0.dylib (apr)
  /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib (apr-util)
  /usr/local/opt/aspell/lib/libaspell.15.dylib (aspell)
  /usr/local/opt/aspell/lib/libpspell.15.dylib (aspell)
  /usr/local/opt/freetds/lib/libsybdb.5.dylib (freetds)
  /usr/local/opt/freetype/lib/libfreetype.6.dylib (freetype)
  /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
  /usr/local/opt/gmp/lib/libgmp.10.dylib (gmp)
  /usr/local/opt/icu4c/lib/libicudata.62.1.dylib (icu4c)
  /usr/local/opt/icu4c/lib/libicui18n.62.dylib (icu4c)
  /usr/local/opt/icu4c/lib/libicuio.62.dylib (icu4c)
  /usr/local/opt/icu4c/lib/libicuuc.62.dylib (icu4c)
  /usr/local/opt/jpeg/lib/libjpeg.9.dylib (jpeg)
  /usr/local/opt/libiconv/lib/libiconv.2.dylib (libiconv)
  /usr/local/opt/libpng/lib/libpng16.16.dylib (libpng)
  /usr/local/opt/libpq/lib/libpq.5.dylib (libpq)
  /usr/local/opt/libtool/lib/libltdl.7.dylib (libtool)
  /usr/local/opt/libzip/lib/libzip.5.dylib (libzip)
  /usr/local/opt/mcrypt/lib/libmcrypt.4.dylib (mcrypt)
  /usr/local/opt/openldap/lib/liblber-2.4.2.dylib (openldap)
  /usr/local/opt/openldap/lib/libldap-2.4.2.dylib (openldap)
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
  /usr/local/opt/unixodbc/lib/libodbc.2.dylib (unixodbc)
Indirect dependencies with linkage:
  libtool
```

**Comment by fxcoudert** [comment] 2018-10-19 16:46
Duplicate of #32434

**Closed by fxcoudert** 2018-10-19 16:46 UTC
Labels: 10.14, php

**Comment by mertasan** [comment] 2018-10-31 01:09
@jzgoda You saved me from this problem. I am thankful to you.

**Comment by wuestkamp** [comment] 2018-11-05 17:37
Same issue, commenting out everything in `/usr/local/etc/php/5.6/conf.d/ext-opcache.ini` solved this.

**Comment by freedomfee** [comment] 2018-11-26 07:21
> Same issue, commenting out everything in `/usr/local/etc/php/5.6/conf.d/ext-opcache.ini` solved this.

solved as well
