### ISSUE TITLE
ncurses terminfo should be available at /usr/local/share/terminfo

### ISSUE THREAD

**Issue by z0rc** [Homebrew/homebrew-core#39477] opened 2019-05-02 16:04 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

Right now ncurses terminfo database is installed under its prefix (`/usr/local/Cellar/ncurses/6.1/share/terminfo`). What I'm looking for is making it available under `/usr/local/share/terminfo` so other applications and libraries that aren't using ncurses directly can find terminfo database. This is especially relevant to `slang` library, which is alternative to `ncurses`. `slang` has its own terminfo parser, but doesn't use `ncurses` libraries at all.

**Comment by z0rc** [comment] 2019-05-03 15:34
I looked into modifying ncurses formula to create /usr/local/share/terminfo symlink, but the brew documentation doesn't cover this case (creation of a symlink in /usr/local/share) at all, assistance needed.

**Comment by alebcay** [comment] 2019-07-10 04:46
I took a look at this, trying
```
(HOMEBREW_PREFIX/"share").install_symlink share/"terminfo"
```

The issue is that `HOMEBREW_PREFIX/"share"` (which is `/usr/local/share`) is protected (not writable) so we can't place things there on our own.

**Comment by geoff-codes** [comment] 2019-07-19 11:04
I've spent quite a lot of time hacking on ncurses and and the terminfo databases, and I really need to speak out on this one: its a very bad idea. In fact having a dupe of ncurses in Homebrew is a really bad idea.

The terminfo database(s) are what keep non-interoperable control sequences from fritzing your terminal (and more). Go ahead and try: `cat /usr/share/terminfo/78/xterm-256color`. Yeah.

(Imagine if that file were world-writable.)

I'm not actually away of any formulae with strictly _depend_ on an updated version of ncurses. If the formula needs an updated ncurses-based terminfo database (which appears like it may be the case for s-lang? although it includes its own in the `src` dir?), it would probably be best just to roll the database **only** into the s-lang package's install, and point to it by patching MISC_TERMINFO_DIRS in the m4 file.

For your pleasure, some light reading on the history of the s-lang/ncurses "saga":

https://invisible-island.net/ncurses/ncurses-slang.html

**Comment by z0rc** [comment] 2019-07-22 09:43
Rolling terminfo DB into s-lang install sounds good to me. I wasn't able to find other libraries that access terminfo files directly, it's only ncurses and s-lang.


> although it includes its own in the src dir?

Actually no, check `src/terminfo/README`

> The include files in this directory define the binary layout of the terminfo file.

Anyway proposal looks okay to me. This would probably make s-lang at least build depend on ncurses, but I'm okay with this if this makes things right.

**Comment by geoff-codes** [comment] 2019-07-22 22:54
> This would probably make s-lang at least build depend on ncurses...

Its been some time since I've hacked on a formula like... is a build-time dep preferable to a `resource` block? (The terminfo sources are made available as a standalone package.)

**Comment by SMillerDev** [comment] 2019-07-23 05:09
Referring to formula instead of resources is definitely preferred

**Comment by fxcoudert** [comment] 2019-09-16 11:58
Closing this issue, I think @geoff-nixon's comment above is clear as to why we want to keep the Homebrew ncurses terminfo database separate.

**Closed by fxcoudert** 2019-09-16 11:58 UTC
