### ISSUE TITLE
Fastd HEAD url broken

### ISSUE THREAD

**Issue by MoritzFago** [Homebrew/homebrew-core#26] opened 2016-04-03 21:01 UTC
### Bug reports:

This [Commit](https://github.com/Homebrew/homebrew-core/commit/fe574a4d33d6df90065cd21d85036f219f2c6e6d) broke the --HEAD Build of Fastd. Would it be okay to change the head url back to the old value?

~~`brew gist-logs <formula>`~~
`brew install fastd --HEAD`
`==> Cloning https://git.universe-factory.net/fastd/
Updating /Library/Caches/Homebrew/fastd--git
fatal: dumb http transport does not support --depth
Error: Failed to download resource "fastd"
Failure while executing: git fetch -q origin --unshallow`

**Comment by tdsmith** [comment] 2016-04-03 21:13
Please try again after running `rm -rf /Library/Caches/Homebrew/fastd--git`.

**Comment by tdsmith** [comment] 2016-04-03 21:13
(this should only happen once)

**Comment by apjanke** [comment] 2016-04-03 21:15
If that was the issue, this might be considered a `brew` bug, too, since it can't handle the download type of a git repo resource changing over time.

**Comment by mikemcquaid** [comment] 2016-04-04 09:53
> If that was the issue, this might be considered a brew bug, too, since it can't handle the download type of a git repo resource changing over time.

Agreed 👍

**Comment by MoritzFago** [comment] 2016-04-04 20:37
The solution provided by @tdsmith worked for me, thank you! If it's not a `brew` bug it can be closed. To determine if it is a bug maybe someone could test it on their machine?

**Comment by mikemcquaid** [comment] 2016-04-05 07:57
I think this is a `brew` bug, thanks @MoritzFago.

**Comment by apjanke** [comment] 2016-04-12 03:15
I can reproduce under a fresh Homebrew install on 10.9.5.

```
[/usr/local/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ gco 4f01edd92cff700e95eac5362583e76c003615c2 2>/dev/null
[/usr/local/Library/Taps/homebrew/homebrew-core on ⇄ 4f01edd]
$ brew fetch --HEAD fastd
==> Cloning git://git.universe-factory.net/fastd/
Cloning into '/Library/Caches/Homebrew/fastd--git'...
remote: Counting objects: 214, done.
remote: Compressing objects: 100% (208/208), done.
remote: Total 214 (delta 48), reused 61 (delta 1)
Receiving objects: 100% (214/214), 267.95 KiB | 164.00 KiB/s, done.
Resolving deltas: 100% (48/48), done.
Checking connectivity... done.
==> Checking out branch master
[/usr/local/Library/Taps/homebrew/homebrew-core on ⇄ 4f01edd]
$ gco master
Previous HEAD position was 4f01edd... googler 2.1 (new formula)
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
[/usr/local/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ brew fetch --HEAD fastd
==> Cloning https://git.universe-factory.net/fastd/
Updating /Library/Caches/Homebrew/fastd--git
fatal: dumb http transport does not support --depth
Error: Failed to download resource "fastd"
Failure while executing: git fetch -q origin --unshallow
[✘ /usr/local/Library/Taps/homebrew/homebrew-core on ⇄ master]
$
```

That should not happen. Gonna say this is indeed a `brew` bug.

I opened a `homebrew/brew` bug for this general pattern at https://github.com/Homebrew/brew/issues/73.

Closing this issue out because OP has a resolution to this particular failure, and they probably don't want notifications on whatever we do with the internals to fix this in the future. (If you actually do care about the internals on this, feel free to subscribe to the new bug.)

**Closed by apjanke** 2016-04-12 03:15 UTC
Labels: bug
