### ISSUE TITLE
Boost 1.71 

### ISSUE THREAD

**Issue by m8mble** [Homebrew/homebrew-core#44093] opened 2019-09-10 08:29 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

The build of the `boost` formula is suspicious to me.

- What you were trying to do (and why)

    Configure your `cmake`-project using the following `CMakeLists` stub:
    ```
    set(Boost_USE_MULTITHREADED ON)
    find_package(Boost 1.71 COMPONENTS date_time REQUIRED)
    ```

- What happened (include command output)
    `cmake` output:
    ```
    -- Found Boost 1.71.0 at /usr/local/lib/cmake/Boost-1.71.0
    --   Requested configuration: QUIET REQUIRED COMPONENTS date_time
    -- BoostConfig: find_package(boost_headers 1.71.0 EXACT CONFIG REQUIRED QUIET HINTS /usr/local/lib/cmake)
    -- Found boost_headers 1.71.0 at /usr/local/lib/cmake/boost_headers-1.71.0
    -- BoostConfig: find_package(boost_date_time 1.71.0 EXACT CONFIG REQUIRED QUIET HINTS /usr/local/lib/cmake)
    -- Found boost_date_time 1.71.0 at /usr/local/lib/cmake/boost_date_time-1.71.0
    -- Boost toolset is clang11 (Clang 11.0.0.11000032)
    -- Scanning /usr/local/lib/cmake/boost_date_time-1.71.0/libboost_date_time-variant*.cmake
    --   Including /usr/local/lib/cmake/boost_date_time-1.71.0/libboost_date_time-variant-mt-shared.cmake
    --   [x] libboost_date_time-mt.dylib
    --   Including /usr/local/lib/cmake/boost_date_time-1.71.0/libboost_date_time-variant-mt-static.cmake
    --   [ ] libboost_date_time-mt.a
    --   Including /usr/local/lib/cmake/boost_date_time-1.71.0/libboost_date_time-variant-shared.cmake
    --   [x] libboost_date_time.dylib
    CMake Warning at /usr/local/lib/cmake/boost_date_time-1.71.0/libboost_date_time-variant-shared.cmake:59 (message):
      Target Boost::date_time already has an imported location
      '/usr/local/lib/libboost_date_time-mt.dylib', which will be overwritten
      with '/usr/local/lib/libboost_date_time.dylib'
    Call Stack (most recent call first):
      /usr/local/lib/cmake/boost_date_time-1.71.0/boost_date_time-config.cmake:43 (include)
      /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
      /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
      /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindBoost.cmake:443 (find_package)
      CMakeLists.txt:6 (find_package)
    ```

- What you expected to happen
    Configuration should complete without warnings. In the described scenario I expect the `*variant-mt-*` to be the only viable `cmake` config file; the non-`mt`-variant should not be considered. In `boost`, this needs to be specified at build time. I verified that a manually compiled vanilla `boost` version 1.71 on linux does not have these issues.

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install boost` is sufficient to upgrade to the problematic version 1.71.

## Further Notes

After looking into `libboost_date_time-variant-*.cmake`s, I noticed there is no variable to switch between `mt` and non-`mt` variants. Presumably the `Boost_USE_MULTITHREADED` is intended for this purpose, but is not respected / read. Furthermore, there are the following comments indicating that some configuration likely went wrong:
```
# threading=multi

# variant=release
[...]
```
ie no special code is executed for multi-/single-mode boost builds.

### Config
```
$$ brew config
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ec49f31752308f2dbb5725f7009483b5b6a87c50
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.0 => /Applications/Xcode-beta.app/Contents/Developer
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```

### Doctor

```
$$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.7m/greenlet/greenlet.h
```

**Comment by scpeters** [comment] 2019-09-10 18:17
The `--no-cmake-config` boost flags were changed with the recent 1.71.0 pull request in #43661. Is this an upstream problem with boost, or are we not setting the cmake flags properly when building boost?

**Comment by m8mble** [comment] 2019-09-10 19:01
I haven't found time yet to fully understand the consequences of the `--no-cmake-config` flag. IMHO is seems likely, that this issue is actually an upstream boost problem. But this shouldn't motivate brew to break peoples builds, in particular when a workaround is known.

**Comment by fxcoudert** [comment] 2019-09-11 09:29
> I don't see why brew actually removed it

`--no-cmake-config` is not the default shipping for Boost, and we only used it as a temporary work-around due to a) serious breakage in Boost 1.70.0 in the cmake files, b) giving time to some projects to adapt their cmake files to changes in boost.

> this issue is actually an upstream boost problem

This should be reported to them, so it can be fixed for everyone, not just brew users.

> this shouldn't motivate brew to break other projects, in particular when a workaround is known

The workaround has a cost, which is that it breaks other things 😢 (which have come to depend on boost cmake files). Not shipping with the default settings from upstreams generates, in most cases, more work for us.

**Comment by fxcoudert** [comment] 2019-09-11 09:32
poke @henryiii whose opinion I would welcome on this

**Comment by henryiii** [comment] 2019-09-11 16:31
I'm about to travel for a couple of days, but can comment quickly. For now, you can set `Boost_NO_BOOST_CMAKE`, which will keep the FindPackage from calling the Config file and will provide the old behavior. I *think* this is a problem in upstream Boost; I (or someone else if they beat me to it) can ask.

This flag was added because there wasn't a good way to disable the lookup (or to have CMake prefer a Config file; there's now a way). CMake 3.15 and Boost 1.71 have improved the situation so it is now possible to avoid the `--no-cmake-config` flag, that's why it was dropped in Brew.

Do you know what is different when you build locally? Also we need to look into the Boost.Python, which seems to not be included in the produced Config files because it is built separately. That might be a Brew-caused issue.

**Comment by henryiii** [comment] 2019-09-11 16:32
(That is, does the manually compiled Boost 1.71 produce a CMake Config file that does include MT and non-MT paths?)

**Comment by drjasonharrison-vp-eio** [comment] 2019-09-18 19:13
I reported this issue separately to Kitware/cmake support and they agree that this is an issue with Boost 1.17.0:

`Since Boost 1.70, Boost itself provides a BoostConfig.cmake package configuration file and FindBoost defers to that.  In the broken log one can see that /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake is loaded.` https://gitlab.kitware.com/cmake/cmake/issues/19714#note_627731

Has this been reported to boost?

**Comment by drjasonharrison-vp-eio** [comment] 2019-09-19 17:06
For reference: https://github.com/boostorg/boost_install/issues/13

**Comment by henryiii** [comment] 2019-09-19 17:56
The problem is that Boost installs mt and single thread versions, and the boost-install authors were assuming no-one was still using the single threaded version. Does it make sense to build and install both versions?

**Comment by pnrhub** [comment] 2019-09-21 23:51
It would seem that there is a related issue as well relating to *boost-python3*, which I encountered when building prjtrellis. This stopped working with the update to boost-1.71. Using the Boost_NO_BOOST_CMAKE work-around fixes the issue.

The problem with the normal build appears to be that *brew install boost-python3* does not add an entry for python3 to the /usr/local/lib/cmake directory. This is where the Boost provided cmake routines look (and many other boost packages are listed in that directory from the the base *brew install boost* command).

**Comment by henryiii** [comment] 2019-09-22 03:17
Yes, this was seen with `boost-python` as well. This one may or may not be an upstream issue; Homebrew is handling these packages separately. Though, I have looked in the build products for the Python build and have not seen a CMake Config file being produced (in the boost-python recipe build dir).

**Comment by pnrhub** [comment] 2019-09-22 04:48
Maybe this is related to the split `boost` and `boost-python` build? I think the python cmake files would get build in the main boost package if it did not specify `--without-libraries=python,mpi` on line 38 of `boost.rb`, right?

**Comment by pnrhub** [comment] 2019-09-22 06:08
Just did a test, building boot.rb with the `without-libraries` commented out. Then boost builds the cmake file for python. It would seem to be a brew issue more than an upstream issue.

**Comment by henryiii** [comment] 2019-10-07 15:29
> It would seem to be a brew issue more than an upstream issue.

But then why does building only one library not produce a CMake file? The only difference I see is only the main Boost does an install, while the others copy from the staging directory; so possibly the install step is where the CMake file is produced?

**Comment by pnrhub** [comment] 2019-10-07 18:36
I'm not a boost expert, but looking at this:
https://github.com/boostorg/boost_install
makes me think your hypothesis is correct. The comment at the top of the *BoostConfig.cmake* file is in line with it, and from a quick glance *boost-install.jam* seems to contain code to write out CMake files.

Maybe the solution is to do an install to the staging area and then copy from there?

**Comment by henryiii** [comment] 2019-10-08 03:44
Looks like we have a problem: Boost-Python and Boost-Python3 produce many of the same names for cmake files.

**Comment by pnrhub** [comment] 2019-10-09 08:32
Not sure I understand. I think */usr/local/lib/cmake/* contains symlinks to directories with the cmake files themselves. The symlinks themselves would have different names, and link to different Cellar trees, if I'm not mistaken.

Where does the name conflict arise?

**Comment by henryiii** [comment] 2019-10-09 20:55
The link to files, made recursively, I believe. Both of them create the same directory (/usr/loca/lib/cmake/boost_python_1.71.0), which contains 2 identical files and otherwise different files. Not sure until I rebuild, though.

**Comment by fxcoudert** [comment] 2019-12-27 22:45
Boost 1.72.0 is about to be merged: we can revisit if the issue still exists after that

**Closed by fxcoudert** 2019-12-27 22:45 UTC
Labels: upstream issue
