### ISSUE TITLE
Qt 5.11.0 build failures

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#28455] opened 2018-05-30 07:06 UTC
Follow-up to [the Qt 5.11.0 PR](https://github.com/Homebrew/homebrew-core/pull/27882)

The following builds are now broken:

- [x] cockatrice https://gist.github.com/ilovezfs/6b4e9012c3c417fc82cd10679cbdce0e https://github.com/Homebrew/homebrew-core/pull/28190#issuecomment-391735606 https://github.com/Homebrew/homebrew-core/pull/29149
- [x] codequery https://gist.github.com/ilovezfs/4623ac2b5a033ffe4825c562e2758b8d https://github.com/Homebrew/homebrew-core/pull/32109
- [x] inspectrum https://gist.github.com/ilovezfs/b0955c7da0cbb43f553ae58ff03eba85 https://github.com/Homebrew/homebrew-core/pull/28734
- [x] liblastfm https://gist.github.com/ilovezfs/072ed66c40762df1963ec8eed51b5779
- [x] mgba https://gist.github.com/ilovezfs/4af273051592a00eb4384103976d1ca2 https://github.com/Homebrew/homebrew-core/pull/29056
- [x] qmmp https://gist.github.com/ilovezfs/c15ffcb9d28bf63c6f1966cfde0a9e4d https://github.com/Homebrew/homebrew-core/pull/28536
- [x] tarsnap-gui https://gist.github.com/ilovezfs/7147dbc4d3ff9661b44ec8a972296524 https://github.com/Homebrew/homebrew-core/pull/28631

CC @fxcoudert @commitay @DomT4

**Comment by DomT4** [comment] 2018-05-31 01:31
`tarsnap-gui` even fails from `HEAD`, so that's a bad start. Haven't checked the rest yet for upstream fixes.

**Comment by apjanke** [comment] 2018-05-31 01:39
* mgba: https://github.com/mgba-emu/mgba/pull/1095
* qmmp: upstream: https://sourceforge.net/p/qmmp-dev/tickets/955/
  * they describe it as fixed in qmmp 1.2.1, but 1.2.1 is still breaking for me with the same error
* tarsnap-gui: upstream report and PR: https://github.com/Tarsnap/tarsnap-gui/pull/180

**Comment by apjanke** [comment] 2018-05-31 01:42
liblastfm: it's not just an include error like the others.

```
-- Found Qt5! Please keep in mind, this is highly experimental and not our main development target..
CMake Error at src/CMakeLists.txt:91 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".


-- Configuring incomplete, errors occurred!
See also "/tmp/liblastfm-20180523-40180-qiak4e/liblastfm-1.0.9/build/CMakeFiles/CMakeOutput.log".

```

There's an upstream PR for it: https://github.com/lastfm/liblastfm/pull/36

But no upstream releases since 2014, no [commits](https://github.com/lastfm/liblastfm/commits/master) since 2015. Might be time to remove it, unless someone wants to hop in as a maintainer.

**Comment by apjanke** [comment] 2018-05-31 01:56
* codequery: upstream bug report: https://github.com/ruben2020/codequery/issues/68
* inspectrum: upstream bug report: https://github.com/miek/inspectrum/issues/146

**Comment by RandomDSdevel** [comment] 2018-06-14 19:50
@ilovezfs:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;While everybody's reporting Qt build failures in one issue, here are my belated* two cents for whatever they're worth:  `brew upgrade --build-from-source qt` is failing for me when it was originally `brew install`ed using, among other options, `--with-docs` upon getting to this:  

```
⋮
cd corelib/ && ( test -e Makefile || /private/tmp/qt-20180612-61556-1yvc9cp/qt-everywhere-src-5.11.0/qtbase/bin/qmake -o Makefile /private/tmp/qt-20180612-61556-1yvc9cp/qt-everywhere-src-5.11.0/qtbase/src/corelib/corelib.pro ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile prepare_docs
/usr/local/Cellar/qt/5.11.0/bin/qtattributionsscanner /private/tmp/qt-20180612-61556-1yvc9cp/qt-everywhere-src-5.11.0/qtbase --filter QDocModule=qtcore -o /private/tmp/qt-20180612-61556-1yvc9cp/qt-everywhere-src-5.11.0/qtbase/src/corelib/codeattributions.qdoc
/private/tmp/qt-20180612-61556-1yvc9cp/qt-everywhere-src-5.11.0/qtbase/src/corelib/qdoc_wrapper.sh -outputdir /private/tmp/qt-20180612-61556-1yvc9cp/qt-everywhere-src-5.11.0/qtbase/doc/qtcore -installdir /usr/local/Cellar/qt/5.11.0/doc /private/tmp/qt-20180612-61556-1yvc9cp/qt-everywhere-src-5.11.0/qtbase/src/corelib/doc/qtcore.qdocconf -prepare -no-link-errors -I. -Iglobal -I../3rdparty/harfbuzz/src -I../3rdparty/md5 -I../3rdparty/md4 -I../3rdparty/sha3 -I../3rdparty/double-conversion/include -I../3rdparty/double-conversion/include/double-conversion -I../3rdparty/forkfd -I../../include -I../../include/QtCore -I../../include/QtCore/5.11.0 -I../../include/QtCore/5.11.0/QtCore -I.moc -I.tracegen -I../3rdparty/pcre2/src -I../../mkspecs/macx-clang
/private/tmp/qt-20180612-61556-1yvc9cp/qt-everywhere-src-5.11.0/qtbase/src/corelib/qdoc_wrapper.sh: line 12: /usr/local/Cellar/qt/5.11.0/bin/qdoc: No such file or directory
/private/tmp/qt-20180612-61556-1yvc9cp/qt-everywhere-src-5.11.0/qtbase/src/corelib/qdoc_wrapper.sh: line 12: exec: /usr/local/Cellar/qt/5.11.0/bin/qdoc: cannot execute: No such file or directory
make[5]: *** [prepare_docs] Error 126
make[4]: *** [sub-corelib-prepare_docs] Error 2
make[3]: *** [sub-src-prepare_docs] Error 2
make[2]: *** [module-qtbase-prepare_docs] Error 2
make[1]: *** [html_docs] Error 2
make: *** [docs] Error 2
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make docs
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
⋮
```

Let me know if you want me to file a separate issue about this, complete with full logs (as I haven't collected them yet since this would entail capturing the usual additional output separate from what `brew` itself logs.)  

*&thinsp;I _would_ have caught this _much_ sooner, but I've been having issues with this dinosaur of a setup's power supply temperature sensor cable and GPU (to the effect that the system can't take _nearly_ as much simultaneous load of any non-trivial amount as I'm anywhere _near_ used to putting on it&thinsp;—&thinsp;though, admittedly, that _might_ have been too much to _begin_ with…) and only recently had the thought to try running builds with the display put to sleep, which seems to be helping matters significantly.

**Comment by apjanke** [comment] 2018-06-25 17:22
Yeah, that should be a separate issue: this issue is about things that break when built against Qt 5.11.0; your issue is that Qt itself is broken.

I'm able to reproduce. Here it is: https://github.com/Homebrew/homebrew-core/issues/29415

**Comment by z3ntu** [comment] 2018-07-16 09:02
liblastfm is probably fixed by https://git.archlinux.org/svntogit/packages.git/tree/trunk/liblastfm-qt5.11.patch?h=packages/liblastfm

**Comment by cbertelli** [comment] 2018-08-18 15:55
building qt fails on 10.9.5. From what I can see on this gist
https://gist.github.com/be5a7cc96fbfb0e24137b4cc3b94f816
there is a configuration issue. It tries to build for 10.10 deliberately excluding 10.9, but this doesn't seem the reason.

**Comment by DomT4** [comment] 2018-08-18 17:52
@cbertelli Qt haven't [supported 10.9](https://doc.qt.io/qt-5/supported-platforms.html) for a while and have very likely stopped testing against it upstream. I don't think there's much chance of it being fixed, to be honest. It's likely the `qt@5.5` formula still compiles on 10.9, for what it's worth.

**Comment by fxcoudert** [comment] 2018-10-06 09:14
Indeed, it is building now… and that was the last to be fixed. At long last, closing this issue!

**Closed by fxcoudert** 2018-10-06 09:14 UTC
Labels: help wanted
