### ISSUE TITLE
Homebrew Failing to Validate Host Certificate When Attempting to Download Core Formula Package Source Tarballs Hosted on SourceForge and `HOMEBREW_FORCE_BREWED_CURL=1`

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#23979] opened 2018-02-10 21:15 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

   (Not _exactly_, since this issue applies to multiple Core formulas' associated packages' source tarballs, but close enough since it only crops up for formulas from within the Core tap.)  

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] ~~Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~~  (N/A; this issue arises before a stage when `brew` would generate any logs for `gist-logs` to pick up and applies to multiple formulas anyway, though I could pipe output to a file if necessary.)  
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?  

   ```
   $ brew config
   HOMEBREW_VERSION: 1.5.3
   ORIGIN: https://github.com/Homebrew/brew.git
   HEAD: af8f8f11e32fe78677fc1d4cd62c07a29dc6d326
   Last commit: 5 days ago
   Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
   Core tap HEAD: 5638de870ce7f07beee609753e3ead3e7e97d877
   Core tap last commit: 2 hours ago
   HOMEBREW_PREFIX: /usr/local
   HOMEBREW_CASK_OPTS: --appdir=/Applications --prefpanedir=/Library/PreferencePanes --colorpickerdir=/Library/ColorPickers --dictionarydir=/Library/Dictionaries --servicedir=/Library/Services --qlplugindir=/Library/QuickLook --fontdir=/Library/Fonts --input_methoddir=/Library/Input\ Methods --screen_saverdir=/Library/Screen\ Savers --internet_plugindir=/Library/Internet\ Plug\-Ins
   HOMEBREW_DEV_CMD_RUN: 1
   HOMEBREW_FORCE_BREWED_CURL: 1
   HOMEBREW_GITHUB_API_TOKEN: set
   HOMEBREW_NO_AUTO_UPDATE: 1
   HOMEBREW_UPDATE_TO_TAG: 1
   CPU: dual-core 64-bit core2
   Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
   Clang: 8.0 build 800
   Git: 2.16.1 => /usr/local/bin/git
   Curl: 7.58.0 => /usr/local/opt/curl/bin/curl
   Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
   Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7
   Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0/bin/ruby
   Java: 9.0.4
   macOS: 10.11.6-x86_64
   Xcode: 8.2.1
   CLT: 8.2.0.0.1.1480973914
   X11: 2.7.11 => /opt/X11
   ```

   ```
   $ brew doctor
   Your system is ready to brew.
   ```

To help us debug your issue please explain:  
- What you were trying to do (and why:)  

   Fetching some formulas' associated packages (namely those associated with the `expect` formula as documented in https://github.com/Homebrew/homebrew-core/pull/23665#issuecomment-363619563 and `e2fsprogs` as hinted at in https://github.com/Homebrew/homebrew-core/pull/23665#issuecomment-364686658) prior to building them from source and upgrading them as part of my daily routine of getting everything on my system up to date over multiple days.  

- What happened (include command output:)  

   Both Expect and e2fsprogs failed to download successfully.  
   
   With `expect` (as copied from [the aforementioned issue comment](https://github.com/Homebrew/homebrew-core/pull/23665#issuecomment-363619563):)  

   ```
   $ brew fetch -vd --force --retry --build-from-source expect
   /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/expect.rb
   ==> Downloading https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
   /usr/local/opt/curl/bin/curl --show-error --user-agent Homebrew/1.5.3 (Macintosh; Intel Mac OS X 10.11.6) curl/7.58.0 --fail --location --remote-time --continue-at - --output /Users/zadmin/Library/Caches/Homebrew/expect-5.45.4.tar.gz.incomplete https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   curl: (60) SSL certificate problem: unable to get local issuer certificate
   More details here: https://curl.haxx.se/docs/sslcerts.html
   
   curl failed to verify the legitimacy of the server and therefore could not
   establish a secure connection to it. To learn more about this situation and
   how to fix it, please visit the web page mentioned above.
   ==> Retrying download
   ==> Downloading https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
   /usr/local/opt/curl/bin/curl --show-error --user-agent Homebrew/1.5.3 (Macintosh; Intel Mac OS X 10.11.6) curl/7.58.0 --fail --location --remote-time --continue-at - --output /Users/zadmin/Library/Caches/Homebrew/expect-5.45.4.tar.gz.incomplete https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   curl: (60) SSL certificate problem: unable to get local issuer certificate
   More details here: https://curl.haxx.se/docs/sslcerts.html
   
   curl failed to verify the legitimacy of the server and therefore could not
   establish a secure connection to it. To learn more about this situation and
   how to fix it, please visit the web page mentioned above.
   Error: Failed to download resource "expect"
   Download failed: https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz
   /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:329:in `rescue in fetch'
   /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:326:in `fetch'
   /usr/local/Homebrew/Library/Homebrew/resource.rb:137:in `fetch'
   /usr/local/Homebrew/Library/Homebrew/formula.rb:1603:in `fetch'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:124:in `fetch_fetchable'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:93:in `fetch_formula'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:65:in `block in fetch'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:45:in `each'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:45:in `fetch'
   /usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
   ```
   
   With `e2fsprogs`:  
   
   ```
   $ brew outdated | grep -E -v -f <(brew list --pinned) | xargs -I "{}" brew fetch -vd --build-from-source {}
   /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/e2fsprogs.rb
   ==> Downloading https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.43.9/e2fsprogs-1.43.9.tar.gz
   /usr/local/opt/curl/bin/curl --show-error --user-agent Homebrew/1.5.3 (Macintosh; Intel Mac OS X 10.11.6) curl/7.58.0 --fail --location --remote-time --continue-at - --output /Users/zadmin/Library/Caches/Homebrew/e2fsprogs-1.43.9.tar.gz.incomplete https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.43.9/e2fsprogs-1.43.9.tar.gz
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   curl: (60) SSL certificate problem: unable to get local issuer certificate
   More details here: https://curl.haxx.se/docs/sslcerts.html
   
   curl failed to verify the legitimacy of the server and therefore could not
   establish a secure connection to it. To learn more about this situation and
   how to fix it, please visit the web page mentioned above.
   Error: Failed to download resource "e2fsprogs"
   Download failed: https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.43.9/e2fsprogs-1.43.9.tar.gz
   /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:329:in `rescue in fetch'
   /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:326:in `fetch'
   /usr/local/Homebrew/Library/Homebrew/resource.rb:137:in `fetch'
   /usr/local/Homebrew/Library/Homebrew/formula.rb:1603:in `fetch'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:124:in `fetch_fetchable'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:93:in `fetch_formula'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:65:in `block in fetch'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:45:in `each'
   /usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:45:in `fetch'
   /usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
   ⋮
   ```

- What you expected to happen:  

   For Expect's and e2fsprogs's source tarballs to download successfully.  

- Step-by-step reproduction instructions (by running `brew` commands:)  

   ```
   export HOMEBREW_FORCE_BREWED_CURL=1 # Or set it in your `.bash_profile`.  
   brew fetch -vd --build-from-source expect e2fsprogs
   ```
   
   I also assume this same certificate error more than likely occurs when downloading source tarballs whose associated packages are associated with other formulas whose associated packages' source code is also hosted on SourceForge.  

- Additional notes:  
   - This issue does not occur when you `unset HOMEBREW_FORCE_BREWED_CURL` and use your system's bundled version of cURL regardless of whether you reset that environment variable later.  
   - This issue may depend on having cURL installed as follows, per the output of `brew info curl` on my machine:  (The relevant dependency is likely the `curl` formula's `--with-openssl` option, with which I installed my brewed cURL.)  
   
      ```
      $ brew info curl
      curl: stable 7.58.0 (bottled), HEAD [keg-only]
      Get a file from an HTTP, HTTPS or FTP server
      https://curl.haxx.se/
      /usr/local/Cellar/curl/7.58.0 (415 files, 3.2MB)
        Built from source on 2018-02-06 at 18:45:23 with: --with-rtmpdump --with-libssh2 --with-c-ares --with-gssapi --with-libmetalink --with-nghttp2
      From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/curl.rb
      ==> Dependencies
      Build: pkg-config ✔
      Optional: openssl ✔, rtmpdump ✔, libssh2 ✔, c-ares ✔, libmetalink ✔, nghttp2 ✔
      ==> Options
      --with-c-ares
      	Build with C-Ares async DNS support
      --with-gssapi
      	Build with GSSAPI/Kerberos authentication support.
      --with-libmetalink
      	Build with libmetalink support.
      --with-libssh2
      	Build with scp and sftp support
      --with-nghttp2
      	Build with HTTP/2 support (requires OpenSSL)
      --with-openssl
      	Build with OpenSSL instead of Secure Transport
      --with-rtmpdump
      	Build with RTMP support
      --HEAD
      	Install HEAD version
      ==> Caveats
      This formula is keg-only, which means it was not symlinked into /usr/local,
      because macOS already provides this software and installing another version in
      parallel can cause all kinds of trouble.
      
      If you need to have this software first in your PATH run:
        echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.bash_profile
      
      For compilers to find this software you may need to set:
          LDFLAGS:  -L/usr/local/opt/curl/lib
          CPPFLAGS: -I/usr/local/opt/curl/include
      For pkg-config to find this software you may need to set:
          PKG_CONFIG_PATH: /usr/local/opt/curl/lib/pkgconfig
      ```

   - I'm not exactly _positive_ that this is _exactly_ an issue with my brewed cURL or an issue with SourceForge's certificate signing that my brewed cURL detects but my system cURL does not.

**Comment by RandomDSdevel** [comment] 2018-03-03 22:44
Begone, ye accursed bucket of bits!  I banish thee!  (Seriously, though, did anyone ever reproduce this, or was I just seeing something odd, perhaps something to do with my local configuration…?)

**Comment by fxcoudert** [comment] 2018-03-12 09:54
We haven't seen anyone reproduce this or report it, and I can't reproduce it myself. Let's close it for now…

**Closed by fxcoudert** 2018-03-12 09:54 UTC

**Comment by RandomDSdevel** [comment] 2018-03-12 16:02
@fxcoudert:  Fine with me; perhaps my computer just didn't like me then (it wouldn't be the _first_ time…)
