### ISSUE TITLE
opam failed to build on 10.12 (breaks on extlib)

### ISSUE THREAD

**Issue by niieani** [Homebrew/homebrew-core#4483] opened 2016-09-03 15:38 UTC
The build fails while compiling the dependency ocaml-extlib 1.5.3. 
Not sure if this is 10.12 specific, I didn't try to install it on 10.11.

<details>
<summary>

Error</summary>

```
File "extlib/extString.ml", line 1:
Error: The implementation extlib/extString.ml
       does not match the interface extlib/extString.cmi:
       ...
       In module String:
       Values do not match:
         external unsafe_set : bytes -> int -> char -> unit
           = "%bytes_unsafe_set"
       is not included in
         external unsafe_set : string -> int -> char -> unit
           = "%string_unsafe_set"
make[4]: *** [extlib/extString.cmo] Error 2
make[3]: *** [byte-code-library] Error 2
make[2]: *** [subproj_extlib] Error 2
make[1]: *** [build] Error 2
make: *** [lib-ext] Error 2
```

</details>

gist-logs: https://gist.github.com/niieani/c621bed7f19851ce8f7822d66f238453

**Comment by dunn** [comment] 2016-09-03 19:30
```
Warning: Your Xcode (7.3) is outdated
Please update to Xcode 8.0.
Xcode can be updated from
https://developer.apple.com/xcode/downloads/
```

That's the most likely cause.  Try upgrading Xcode and installing again.

**Comment by niieani** [comment] 2016-09-03 20:13
@dunn Nope, I have both Xcode 7.3 and 8.0 and tested using both toolings, the error is the same.

**Comment by dunn** [comment] 2016-09-03 20:21
Oh, gotcha.  I can't replicate it on 10.11, though, so this is probably a Sierra issue.  Could you report it to the developers?

**Comment by niieani** [comment] 2016-09-03 20:24
Report it to developers of opam or ocaml-extlib? Cause ocaml-extlib is already on 1.7.0.

**Comment by niieani** [comment] 2016-09-03 20:32
Submitted upstream as https://github.com/ocaml/opam/issues/2654

**Comment by DomT4** [comment] 2016-09-03 21:33
I'm unable to reproduce on 10.12.

```
==> Summary
🍺  /usr/local/Cellar/opam/1.2.2_2: 30 files, 14.9M, built in 55 seconds
```
https://gist.github.com/anonymous/009a06d991ebcc3245422a59dd7a4171

**Comment by freebroccolo** [comment] 2016-09-03 21:56
I'm guessing it's because of this:

```
OCaml library path is /usr/local/lib/node_modules/bs-platform/lib/ocaml
checking for ocamlopt... ocamlopt
Fatal error: unknown C primitive `caml_add_debug_info'
versions differs from ocamlc  != 4.02.3+dev1-2016-05-24; ocamlopt discarded.
```

Looks like it's picking up the BuckleScript ocaml installation which probably isn't what you want. If you have node stuff in your path, that may be the cause of it.

**Comment by niieani** [comment] 2016-09-03 22:10
@freebroccolo yep! That was it! 
Could we somehow ensure that the homebrew compilation don't pick up the ocaml compilation from `node_modules` so that others won't face the same problem in the future?

**Comment by mistydemeo** [comment] 2016-09-06 03:53
Do you have `OCAMLC` or `OCAMLLIB` set in your environment?

**Comment by niieani** [comment] 2016-09-06 08:14
@mistydemeo no, I didn't set anything aside from globally npm installing bs-platform, which I don't think would alter the environment globally. The issue has been resolved for me, we only need to ensure that other people don't encounter this problem in the future - i.e. trying to brew opam **after** installing bs-platform.

**Comment by ilovezfs** [comment] 2016-11-05 14:34
Closing since the OP's issue has been resolved and no one is actively working on follow-up. PRs welcome.

**Closed by ilovezfs** 2016-11-05 14:34 UTC
