### ISSUE TITLE
cdiff is broken

### ISSUE THREAD

**Issue by adius** [Homebrew/homebrew-core#555] opened 2016-04-23 09:05 UTC
When I install it with pip everything works fine.
When I install it with homebrew, I get following error:

```
$ cdiff
Traceback (most recent call last):
  File "/usr/local/Cellar/cdiff/0.9.8/libexec/bin/cdiff", line 7, in <module>
    sys.exit(cdiff.main())
  File "/usr/local/Cellar/cdiff/0.9.8/libexec/lib/python2.7/site-packages/cdiff.py", line 770, in main
    diff_hdl = revision_control_diff(args)
  File "/usr/local/Cellar/cdiff/0.9.8/libexec/lib/python2.7/site-packages/cdiff.py", line 668, in revision_control_diff
    if check_command_status(ops['probe']):
  File "/usr/local/Cellar/cdiff/0.9.8/libexec/lib/python2.7/site-packages/cdiff.py", line 660, in check_command_status
    arguments, stdout=subprocess.PIPE, stderr=subprocess.PIPE) == 0
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

**Comment by ilovezfs** [comment] 2016-04-23 11:51
I can't reproduce this on OS X 10.8 or 10.11, with or without Homebrew's Python. 

Please follow the requested steps on the Troubleshooting page: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md

After completing all of these steps, post the information here so we can help you with your problem.

Thanks

**Comment by DomT4** [comment] 2016-07-31 03:58
Closing as dead, but please shout if we can offer any assistance here still. Thanks!

**Closed by DomT4** 2016-07-31 03:58 UTC
Labels: needs response, user configuration
