### ISSUE TITLE
go_resource deprecation

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#21801] opened 2017-12-16 13:41 UTC
This will serve as a tracking issue for the removal of the `go_resource` blocks from formulae.

- [ ] [acmetool](https://github.com/Homebrew/homebrew-core/blob/master/Formula/acmetool.rb)
- [ ] [aurora](https://github.com/Homebrew/homebrew-core/blob/master/Formula/aurora.rb)
- [x] [boot2docker](https://github.com/Homebrew/homebrew-core/blob/master/Formula/boot2docker.rb) https://github.com/Homebrew/homebrew-core/pull/30349
- [ ] [borg](https://github.com/Homebrew/homebrew-core/blob/master/Formula/borg.rb)
- [ ] [charm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/charm.rb)
- [ ] [cig](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cig.rb)
- [ ] [cosi](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cosi.rb)
- [x] [devd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/devd.rb) #22543
- [x] [dockviz](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dockviz.rb) https://github.com/justone/dockviz/issues/41 https://github.com/Homebrew/homebrew-core/pull/26862
- [ ] [dockward](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dockward.rb)
- [ ] [gdm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gdm.rb)
- [ ] [ghq](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ghq.rb)
- [x] [gitlab-runner](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gitlab-runner.rb) #24835 
- [x] [goad](https://github.com/Homebrew/homebrew-core/blob/master/Formula/goad.rb) #24835 
- [ ] [gobuster](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gobuster.rb)
- [ ] [goofys](https://github.com/Homebrew/homebrew-core/blob/master/Formula/goofys.rb)
- [ ] [gost](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gost.rb)
- [ ] [gron](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gron.rb)
- [ ] [gx-go](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gx-go.rb)
- [ ] [gx](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gx.rb)
- [ ] [jid](https://github.com/Homebrew/homebrew-core/blob/master/Formula/jid.rb)
- [ ] [jvgrep](https://github.com/Homebrew/homebrew-core/blob/master/Formula/jvgrep.rb)
- [x] [karn](https://github.com/Homebrew/homebrew-core/blob/master/Formula/karn.rb) #22167
- [x] [lego](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lego.rb) #28492
- [ ] [mailhog](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mailhog.rb)
- [x] [megacmd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/megacmd.rb) #21843 
- [ ] [mmark](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mmark.rb)
- [x] [modd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/modd.rb) #22025
- [x] [mongodb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongodb.rb) #23214
- [ ] [mongodb@3.0](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongodb@3.0.rb)
- [ ] [mongodb@3.2](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongodb@3.2.rb)
- [x] [mongodb@3.4](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongodb@3.4.rb) #22593
- [ ] [mpdviz](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpdviz.rb)
- [x] [otto](https://github.com/Homebrew/homebrew-core/blob/master/Formula/otto.rb) #22567
- [x] [packer](https://github.com/Homebrew/homebrew-core/blob/master/Formula/packer.rb) https://github.com/Homebrew/homebrew-core/pull/22017
- [x] [percona-server-mongodb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/percona-server-mongodb.rb) #23215
- [x] [pilosa](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pilosa.rb) #22528
- [x] [pond](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pond.rb) #22568
- [x] [pup](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pup.rb) https://github.com/Homebrew/homebrew-core/pull/22020
- [x] [qpm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qpm.rb) #28023
- [ ] [s-search](https://github.com/Homebrew/homebrew-core/blob/master/Formula/s-search.rb)
- [x] [serf](https://github.com/Homebrew/homebrew-core/blob/master/Formula/serf.rb) #22019
- [ ] [sift](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sift.rb)
- [x] [slackcat](https://github.com/Homebrew/homebrew-core/blob/master/Formula/slackcat.rb) #22026
- [ ] [spaceinvaders-go](https://github.com/Homebrew/homebrew-core/blob/master/Formula/spaceinvaders-go.rb)
- [x] [srclib](https://github.com/Homebrew/homebrew-core/blob/master/Formula/srclib.rb) #22158
- [ ] [teleconsole](https://github.com/Homebrew/homebrew-core/blob/master/Formula/teleconsole.rb)
- [ ] [termshare](https://github.com/Homebrew/homebrew-core/blob/master/Formula/termshare.rb)
- [x] [terraform-docs](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform-docs.rb) https://github.com/Homebrew/homebrew-core/pull/32799
- [ ] [terraform-inventory](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform-inventory.rb)
- [ ] [terraform-provisioner-ansible](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform-provisioner-ansible.rb)
- [x] [terraform](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform.rb)
- [x] [textql](https://github.com/Homebrew/homebrew-core/blob/master/Formula/textql.rb) #22156
- [x] [traefik](https://github.com/Homebrew/homebrew-core/blob/master/Formula/traefik.rb) #24835 
- [x] [vault](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vault.rb) #22003
- [x] [vaulted](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vaulted.rb) #34526
- [x] [vegeta](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vegeta.rb) #28024
- [x] [vultr](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vultr.rb) #22027
- [ ] [websocketd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/websocketd.rb)
- [ ] [wego](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wego.rb)
- [ ] [wellington](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wellington.rb)
- [ ] [wiki](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wiki.rb)

**Comment by vitorgalvao** [comment] 2017-12-18 15:21
Clickable list. @ilovezfs feel free to copy paste this one into the top post and delete this one, if you’d like.

- [ ] [acmetool](https://github.com/Homebrew/homebrew-core/blob/master/Formula/acmetool.rb)
- [ ] [aurora](https://github.com/Homebrew/homebrew-core/blob/master/Formula/aurora.rb)
- [ ] [boot2docker](https://github.com/Homebrew/homebrew-core/blob/master/Formula/boot2docker.rb)
- [ ] [borg](https://github.com/Homebrew/homebrew-core/blob/master/Formula/borg.rb)
- [ ] [charm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/charm.rb)
- [ ] [cig](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cig.rb)
- [ ] [cosi](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cosi.rb)
- [ ] [devd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/devd.rb)
- [ ] [dockviz](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dockviz.rb)
- [ ] [dockward](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dockward.rb)
- [ ] [gdm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gdm.rb)
- [ ] [ghq](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ghq.rb)
- [ ] [gitlab-runner](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gitlab-runner.rb)
- [ ] [goad](https://github.com/Homebrew/homebrew-core/blob/master/Formula/goad.rb)
- [ ] [gobuster](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gobuster.rb)
- [ ] [goofys](https://github.com/Homebrew/homebrew-core/blob/master/Formula/goofys.rb)
- [ ] [gost](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gost.rb)
- [ ] [gron](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gron.rb)
- [ ] [gx-go](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gx-go.rb)
- [ ] [gx](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gx.rb)
- [ ] [jid](https://github.com/Homebrew/homebrew-core/blob/master/Formula/jid.rb)
- [ ] [jvgrep](https://github.com/Homebrew/homebrew-core/blob/master/Formula/jvgrep.rb)
- [ ] [karn](https://github.com/Homebrew/homebrew-core/blob/master/Formula/karn.rb)
- [ ] [lego](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lego.rb)
- [ ] [mailhog](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mailhog.rb)
- [x] [megacmd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/megacmd.rb) #21843 
- [ ] [mmark](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mmark.rb)
- [ ] [modd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/modd.rb)
- [ ] [mongodb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongodb.rb)
- [ ] [mongodb@3.0](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongodb@3.0.rb)
- [ ] [mongodb@3.2](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongodb@3.2.rb)
- [ ] [mongodb@3.4](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongodb@3.4.rb)
- [ ] [mpdviz](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpdviz.rb)
- [ ] [otto](https://github.com/Homebrew/homebrew-core/blob/master/Formula/otto.rb)
- [ ] [packer](https://github.com/Homebrew/homebrew-core/blob/master/Formula/packer.rb)
- [ ] [percona-server-mongodb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/percona-server-mongodb.rb)
- [ ] [pilosa](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pilosa.rb)
- [ ] [pond](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pond.rb)
- [ ] [pup](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pup.rb)
- [ ] [qpm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qpm.rb)
- [ ] [s-search](https://github.com/Homebrew/homebrew-core/blob/master/Formula/s-search.rb)
- [ ] [serf](https://github.com/Homebrew/homebrew-core/blob/master/Formula/serf.rb)
- [ ] [sift](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sift.rb)
- [ ] [slackcat](https://github.com/Homebrew/homebrew-core/blob/master/Formula/slackcat.rb)
- [ ] [spaceinvaders-go](https://github.com/Homebrew/homebrew-core/blob/master/Formula/spaceinvaders-go.rb)
- [ ] [srclib](https://github.com/Homebrew/homebrew-core/blob/master/Formula/srclib.rb)
- [ ] [teleconsole](https://github.com/Homebrew/homebrew-core/blob/master/Formula/teleconsole.rb)
- [ ] [termshare](https://github.com/Homebrew/homebrew-core/blob/master/Formula/termshare.rb)
- [ ] [terraform-docs](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform-docs.rb)
- [ ] [terraform-inventory](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform-inventory.rb)
- [ ] [terraform-provisioner-ansible](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform-provisioner-ansible.rb)
- [ ] [terraform](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform.rb)
- [ ] [textql](https://github.com/Homebrew/homebrew-core/blob/master/Formula/textql.rb)
- [ ] [traefik](https://github.com/Homebrew/homebrew-core/blob/master/Formula/traefik.rb)
- [ ] [vault](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vault.rb)
- [ ] [vaulted](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vaulted.rb)
- [ ] [vegeta](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vegeta.rb)
- [ ] [vultr](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vultr.rb)
- [ ] [websocketd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/websocketd.rb)
- [ ] [wego](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wego.rb)
- [ ] [wellington](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wellington.rb)
- [ ] [wiki](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wiki.rb)

**Comment by ilovezfs** [comment] 2017-12-18 15:44
@vitorgalvao done!

**Comment by commitay** [comment] 2017-12-22 23:11
Couple of updates on this.

`otto` and `pond` are unmaintained

`devd`, `mailhog` and `qpm` have vendoring, just not in a tagged release.

`pilosa`: the go_resource was added by their upstream in https://github.com/Homebrew/homebrew-core/pull/16688

**Comment by commitay** [comment] 2017-12-26 08:45
@ilovezfs Should I submit a `go-bindata` formula that builds from the most recent commit to take care of `goad`, `gitlab-runner` and `traefik`?

**Comment by ilovezfs** [comment] 2017-12-26 08:45
We'll need to get them to tag it.

**Comment by commitay** [comment] 2017-12-26 08:52
Upstream hasn't been active for two years. https://github.com/jteeuwen/go-bindata/issues/134

**Comment by ilovezfs** [comment] 2017-12-26 08:56
I think he changed user names. You can CC @grobie in your issue ;)

**Comment by ilovezfs** [comment] 2017-12-26 09:02
There's also https://github.com/jteeuwen/go-bindata/issues/134

So we may want to request a tag on https://github.com/tmthrgd/go-bindata too

**Comment by ilovezfs** [comment] 2017-12-26 09:07
Note also
https://github.com/jteeuwen/go-bindata/issues/165
https://github.com/Dr-Terrible/go-overlay/issues/76

So we should probably bring goad, gitlab-runner and traefik into those discussions too and figure out what to actually do here :)

**Comment by ilovezfs** [comment] 2017-12-26 09:16
@matteeyah @tmaczukin @To1ne Do you have any thoughts on the situation with jteeuwen/go-bindata development seeming to have stopped and the various forks such as tmthrgd/go-bindata? We're hoping not to have to vendor the gobindata resource in formulae (such as gitlab-runner) in perpetuity, and instead to have a formula for it, but that's going to require an active gobindata upstream (and a tag).

**Comment by commitay** [comment] 2017-12-29 06:19
@ilovezfs `rakyll/statik` (`pilosa`) looks to be similar to `go-bindata`, do you want a formula for `rakyll-statik` (conflicts with `statik`) or is that another that needs to be referred upstream?

**Comment by ilovezfs** [comment] 2017-12-30 14:46
@commitay the project looks like it would meet the notability requirements for a new formula so that should be fine. Not sure about the name though.

**Comment by ilovezfs** [comment] 2018-01-07 07:34
>`devd`, `mailhog` and `qpm` have vendoring, just not in a tagged release.

@commitay do you mind requesting a new tag for those?

**Comment by commitay** [comment] 2018-01-07 07:45
👍  I'll ask for new tags and start asking for vendoring with the others.

> Not sure about the name though.

Any thoughts on this?

**Comment by ilovezfs** [comment] 2018-01-07 08:02
I guess `go-statik` or `golang-statik`
See https://packages.debian.org/sid/golang-statik

**Comment by ilovezfs** [comment] 2018-01-07 08:04
Probably `go-statik` since our Go package is `go` and Debian's is `golang`.

**Comment by commitay** [comment] 2018-01-08 01:34
Not sure how good this is but it works for `mongodb@3.4` and should also work with `mongodb` and `percona-server-mongodb`. The older versions don't include `mongo-tools` in the tarball.

```diff
diff --git a/Formula/mongodb@3.4.rb b/Formula/mongodb@3.4.rb
index 9fa80398d2..f1cab74e84 100644
--- a/Formula/mongodb@3.4.rb
+++ b/Formula/mongodb@3.4.rb
@@ -1,5 +1,3 @@
-require "language/go"
-
 class MongodbAT34 < Formula
   desc "High-performance, schema-free, document-oriented database"
   homepage "https://www.mongodb.org/"
@@ -24,13 +22,6 @@ class MongodbAT34 < Formula
   depends_on "scons" => :build
   depends_on "openssl" => :recommended

-  go_resource "github.com/mongodb/mongo-tools" do
-    url "https://github.com/mongodb/mongo-tools.git",
-        :tag => "r3.4.10",
-        :revision => "4f093ae71cdb4c6a6e9de7cd1dc67ea4405f0013",
-        :shallow => false
-  end
-
   needs :cxx11

   def install
@@ -42,9 +33,13 @@ class MongodbAT34 < Formula

     # New Go tools have their own build script but the server scons "install" target is still
     # responsible for installing them.
-    Language::Go.stage_deps resources, buildpath/"src"

-    cd "src/github.com/mongodb/mongo-tools" do
+    cd "src/mongo/gotools" do
+      inreplace "build.sh" do |s|
+        s.gsub! "\$(git describe)", version.to_s
+        s.gsub! "\$(git rev-parse HEAD)", "homebrew"
+      end
+
       args = %w[]

       if build.with? "openssl"
@@ -59,7 +54,7 @@ class MongodbAT34 < Formula
     end

     mkdir "src/mongo-tools"
-    cp Dir["src/github.com/mongodb/mongo-tools/bin/*"], "src/mongo-tools/"
+    cp Dir["src/mongo/gotools/bin/*"], "src/mongo-tools/"

     args = %W[
       --prefix=#{prefix}
```

**Comment by ayufan** [comment] 2018-01-08 08:50
As for `gitlab-runner` goes we are in process of moving away from go-bindata to have these resources stored as files alongside the binary. It seems to be a pain to maintain prebuilts this way, given that these images only grow.

cc @nolith 

(GitLab Runner Maintainer)

**Comment by nolith** [comment] 2018-01-08 11:35
I can confirm, we are planning to remove `go-bindata` from `gitlab-runner`.

**Comment by ilovezfs** [comment] 2018-01-08 11:41
Thanks @ayufan and @nolith!

@commitay so we'll need to raise this with `goad`, `otto` and `traefik` upstreams to see how they want to handle it.

**Comment by commitay** [comment] 2018-01-08 11:51
Not much more we can do with `otto`

https://github.com/hashicorp/otto#otto
> Otto is no longer actively developed or maintained.

**Comment by ilovezfs** [comment] 2018-01-08 12:03
Time for `otto` to go to the glue factory https://github.com/Homebrew/homebrew-core/pull/22567

**Comment by commitay** [comment] 2018-01-08 12:07
Two others you might want to 💀 

`boot2docker`  Latest commit 8a39996  on 21 Jan 2016

> This project is officially deprecated in favor of Docker Machine. The code and documentation here only exist as a reference for users who have not yet switched over (but please do soon).

`pond` Latest commit 675020c  on 25 May 2016

> Pond is in stasis, and has been for several years. I hope that some of the ideas prove useful in the future, but people should use something better polished and reviewed. I've no plans to shutdown down the default server, but new users should look elsewhere.

**Comment by ilovezfs** [comment] 2018-01-08 12:26
`pond` had 3 installs in the last 30 days, so that can be removed: https://github.com/Homebrew/homebrew-core/pull/22568

Unfortunately, `boot2docker` had 824 installs in the last 30 days (746 install on request), so it seems upstream is having trouble getting everyone to move to Docker Machine. `docker-machine` does have an order of magnitude more installs, 9,317 (2,207 install on request), so it may be a matter of time before the rest switch over.

**Comment by yumitsu** [comment] 2018-01-10 15:29
Just a message for someone else who decided to write a formula for Go app.

Many formulas (especially for apps written in Go) try to install package like this:
```ruby
(buildpath/"src/github.com/xxxx/yyyy").install buildpath.children
```
Guess what happens if package repo contains `src` dir 😆 
So, if your package does, slightly modify your formula:
```ruby
tempdir = buildpath/"gopath"
tempdir.mkpath
(tempdir/"src/github.com/odeke-em/drive").install buildpath.children - [tempdir]

ENV["GOPATH"] = tempdir
```

**Comment by ylluminarious** [comment] 2018-02-05 04:41
I stumbled across this ticket while searching for this error from `brew audit`:

```
`go_resource`s are deprecated. Please ask upstream to implement Go vendoring
```

 Why are `go_resource`s deprecated? It doesn't say anything about it in the documentation. What are we supposed to use instead? What is Go "vendoring?"

**Comment by yumitsu** [comment] 2018-02-05 19:30
@ylluminarious Go "vendoring" is similar to any other "vendoring" and based on same principles: dependences are collected and stored within 'vendor' folder in package root. On build, Go will use vendored sources instead of fetching them.

**Comment by sentoukat** [comment] 2018-03-29 14:23
I would like to help to this issue, but since I am a newbie, is there any tutorial or how-to for me to get started?

**Comment by nolith** [comment] 2018-06-27 15:09
It took a long time, but we finally merged the `go-bindata` removal from `gitlab-runner`

https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/831

gitlab-runner 11.1.0,  will be the first release without go-bindata

**Comment by ilovezfs** [comment] 2018-07-27 14:34
@nolith @ayufan excellent. Can someone from upstream open a PR for the new version now that gitlab-runner 11.1.0 is out? The formula needs to be adjusted since it currently assumes go-bindata use and I'm not sure what that entails.

**Comment by metmajer** [comment] 2018-10-09 19:37
This pull request seems to be managed by the BrewTestBot. Nevertheless, let me give you the update that `terraform-docs` has just been freed from `go_resource`, see [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform-docs.rb).

**Comment by MikeMcQuaid** [comment] 2018-12-22 11:48
Closing as @ilovezfs isn't around to maintain the list any more.

**Closed by MikeMcQuaid** 2018-12-22 11:48 UTC
Labels: go, help wanted
